### ISSUE TITLE
Lookup for Invoices

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#1002]
Add an ability to do specific search on the invoices via either a payment hash or payment request.
- Create a new tab on the transactions page, called Lookup Invoices
- Provide an ability for the user to specify either the payment hash or payment request of both and then search

API: https://api.lightning.community/?shell#v2-invoices-lookup

**Comment by ShahanaFarooqui** [comment]
Payment lookup reference issue: https://github.com/lightningnetwork/lnd/issues/6460

**Comment by ShahanaFarooqui** [comment]
This PR has transactions lookup tab and will load the dashboard faster than before. Closing this issue with PR #1010.
