### ISSUE TITLE
Change the server message in the log after successful server start

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#1013]
The message prompted in the log, after a successful server start should be changed to:
`Server is up and running, please open the UI at http://localhost:3000 or your proxy configured url`

**Comment by ShahanaFarooqui** [comment]
Closing with commit [9bb484d3fe49c39acb408986658a29f0823b3587](https://github.com/Ride-The-Lightning/RTL/commit/9bb484d3fe49c39acb408986658a29f0823b3587).
