### ISSUE TITLE
Liquidity Ads - Configuration

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#1020]
Relevant APIs:
- `/channel/funderupdate`
- `/utility/listConfigs`

Functional features:
- Show the option to configure liquidity ads based on the `experimental-dual-fund` flag in the listconfig response
- Show the liquidity ad params, based on the funderupdate response
- Enable the user to change the liquidity ads param. The API to update the params is also funderupdate

**Comment by ShahanaFarooqui** [comment]
Closing with PR #1022
