### ISSUE TITLE
Wrong unit displayed when fee bumping

### ISSUE THREAD

**Issue by elsirion** [Ride-The-Lightning/RTL#1028]
I was trying to fee-bump an opening channel and set the fee to 50 sat/vbyte (or so I thought). After submitting the CPFP transaction had a fee of ~1sat/vbyte. When digging into core lightning I found it uses sat/kweight internally. So I unreserved the UTXO and tried to fee bump again, this time with 50000 "sat/vbyte" (assuming it might be sat/kweight or something funny). It turns out the resulting transaction had a fee of 50sat/vbyte. So I assume either the label is wrong and should say "msat/vbyte" or you need to multiply with 1000 internally.

1. Go to Lightning -> Peers/Channels -> Pending/Inactive
2. Select a channel that's waiting for lockin
3. Actions -> Bump Fee
4. Enter fee and confirm

![Screenshot 2022-05-19 at 09-10-19 RTL](https://user-images.githubusercontent.com/84478054/169316003-0e01b71b-86bf-49ff-b806-fc486d1f4c26.png)

**Your environment**
* Version of `RTL`: 0.12.2-beta
* Version of `core lightning`: v0.11.1
* Version of `bitcoind`: v23.0.0
* Browser & browser version: Firefox 99.0.1 (64-bit)
* Operating system: Linux (NixOS)

**Comment by ShahanaFarooqui** [comment]
@elsirion Thank you for raising the issue. It has been fixed with PR #1065. Closing the issue now.
