### ISSUE TITLE
Links to external lightning node explorers for user research

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#1034]
Provide links to lightning node explorer like Amboss or LNrouter from the Actions menu of liquidity ads, so that user can research nodes before deciding to buy liquidity from them.
E.g. for the node with pubkey - 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f
- Amboss URL is: https://amboss.space/node/03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f
- Lnrouter URL is: https://lnrouter.app/node/03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f

<img width="780" alt="image" src="https://user-images.githubusercontent.com/39208279/170542768-f7a12acc-94ac-4895-a17e-bc3b57d37e4e.png">

**Comment by ShahanaFarooqui** [comment]
Closing with commit b8477e3613fdb0f7021279ed205f6aad7abc95b4.
