### ISSUE TITLE
Is there a chance to get "total_rebalance_fee" onto dashboard of C-Lightning RTL?

### ISSUE THREAD

**Issue by RemoRitzmann** [Ride-The-Lightning/RTL#1038]
I see total_rebalance_fee in lightning-cli rebalancereport, but it would be great to switch "lightning-cli rebalanceall" on or off by the menu or from C-Lightning RTL. I can start it in command line, but I have not yet found out how to enable it in a way that it is restarting when raspiblitz restarts.

**Comment by saubyk** [comment]
Hi @RemoRitzmann, I am assuming this `rebalanceall` function is enabled by a core lightning plugin.
Please note that we do not have support yet for add-on plugin functionality in RTL.

To enable plugins on the RTL interface would require a bit of engineering work. Once we have that ready, we can add features like this. Thanks.
