### ISSUE TITLE
The Logout in the Firefox after closing/opening does Login itself

### ISSUE THREAD

**Issue by Perlover** [Ride-The-Lightning/RTL#1042]
**Describe the bug**
After the Logout procedure, do not close the tab with the panel, if you close and open Firefox again (in session recovery mode), Firefox restores the tab and automatic Login occurs without requesting a password and OTP (I checked only with 2FA enabled)!

**To Reproduce**
1. Firefox should be in the mode of saving tabs and restoring them after starting again.
2. Open the RTL panel, go and Login there (I use 2FA method too), for example, to Dashboard. Then we do Logout
3. We see a message asking for a password - everything seems to be fine
4. Close Firefox and then run it again
5. We had an RTL panel tab open, where there was a password request to log in. But after launching Firefox, this page appears for a moment, then a panel appears and we are inside where we should have logged in with a password + OTP.
6. You can repeat from point 2 again and it will be the same again.
7. At some point in time, I clicked on the lock icon, selected "Delete cookies and this site", as it seemed to me - I deleted it. Then I restarted the browser and tried again and got inside. But I couldn't do it again. I may have clicked Cancel by mistake, but I thought I had deleted the cookies and site data. But it's better if you check it out too.

**Your environment**
* Version of `RTL` - 0.12.3-beta
* Browser & browser version - Firefox 101.0.1
* Operating system (`uname -a` on *Nix) - Linux Mint

**Comment by Perlover** [comment]
> 7\. At some point in time, I clicked on the lock icon, selected "Delete cookies and this site", as it seemed to me - I deleted it. Then I restarted the browser and tried again and got inside. But I couldn't do it again. I may have clicked Cancel by mistake, but I thought I had deleted the cookies and site data. But it's better if you check it out too.

I was able to repeat it! If you delete "Delete cookies and data from this site" between the 3rd and 4th point, the 5th point works (that is, we automatically get inside the panel without a login)

**Comment by Perlover** [comment]
At the same time, when "I delete cookies and site data", I check through the Firefox inspector (Ctrl + Shift + C) - I see that the storage (cookies) is empty. But after 1-2 seconds, the **_csrf & connect.sid** cookies appear there. It feels like the RTL panel periodically inserts cookies, even on the Logout page...

**Comment by Perlover** [comment]
It turns out that this bug also manifests itself if you do Logout, then close the tab and then do Ctrl + Shift +T (restore last-closed tab) - you also get back inside the logged-in page

**Comment by saubyk** [comment]
Hi @Perlover I tried replicating this issue on Mac, Ubuntu and Windows devices. I was able to successfully replicate only for windows. Other platforms just loaded the login page but didn't progress further.

We will investigate the issue for Windows.

Another thing to note is that, I tested on the latest version of Firefox v103.+
Can you please update your Firefox version and try if that fixes the issue on your device?

Thanks

**Comment by ShahanaFarooqui** [comment]
@Perlover, @saubyk I tested it on Fedora and it is stopping at login page on that too.

However, as you already tested and confirmed that Firefox is recovering previous session even after logging out from the application. At the application level, we can only delete session when logged out but stopping the browser from recovering the session is out of our control.

It is a bug in Firefox and should be raised with their team. Till they fix this critical bug, we would highly recommend to use Firefox on Windows with unchecked `open previous windows and tabs` option. It can be found under `Settings => General => Startup`. 

![image](https://user-images.githubusercontent.com/23240721/183236001-c847b5e2-ecac-4405-aa14-58690c7341e8.png)

**Comment by ShahanaFarooqui** [comment]
@Perlover Thank you for bringing it to our attention, @saubyk can we please inform users about this bug on twitter? Closing the issue now as it cannot be fixed by our team.

**Comment by Perlover** [comment]
I'm not at the computer right now. But if my memory serves me right, I even observed this bug in Chrome (Linux). And I use Linux not Windows

**Comment by Perlover** [comment]
But i saw the cookie manipulation. I don't think that it's Firefox bug. But I will check new version.

**Comment by ShahanaFarooqui** [comment]
@Perlover

**Comment by ShahanaFarooqui** [comment]
Reopened the issue to ensure that we are not setting any cookie or session after logout.

**Comment by ShahanaFarooqui** [comment]
@Perlover I retested the issue and it cannot be fixed by RTL. These _csrf and connect.sid cookies are auto generated by browsers. Another set will be generated even if the application deletes them on logout. I still added the logic to remove `connect.sid` through RTL but you can confirm that they will be regenerated.

Another point to note here is that, this issue occurs in 2 situations:

1: If the browser has been closed without logging out from RTL: even after reopening the browser and logging out from RTL, the logged in state persists somewhere in the browser and it keeps logging in on every browser load.

2: Same browser instance is used for multiple logins: If the user keeps logging in and out of the application without closing the browser, after 3-4 attempts, state starts persisting in the browser.   

Browser history cleaning doesn't resolve this issue. Restarting RTL server or multiple browser refresh and login/logouts are the solution.

So the best practice to use the browser is to:
1: Deselect `open previous windows and tabs`
2: Logout from the application once you are done using it.
3: Close the browser window after every logout.

**Comment by Perlover** [comment]
> So the best practice to use the browser is to: 1: Deselect `open previous windows and tabs` 2: Logout from the application once you are done using it. 3: Close the browser window after every logout.

I did  this but the bug exists!

Now I have:

1. RTL 0.13.1-beta
2. Firefox 104.0.2
3. Linux Mint 20.3 (Ubuntu 20.4)
4. Deselect open previous windows and tabs and after this restarted the Firefox
5. I have 2FA enabled

The same bug:

1. I open RTL and login
2. Go to Lightning / Peers section for example
3. I click Logout and I see login page
4. I close Tab (Ctrl + W)
5. I do Ctrl + Shift + T (open previous tab)
6. I see RTL panel - left navifation panel from RTL and in main window of RTL I see login page and after 1-2 seconds the main page to be reloaded and the panel inside admin area

I used web tools of Firefox (Ctrl + Alt + Shift + I) for sniffing and I see that when I do Logout the browser get 304 HTTP response (the problem of ETag middleware at server side?). It's because you use E-Tag control for logout URL (client sends `If-None-Match` for `/rtl/api/authenticate/logout` with ETag and got from server 304 response and don't remove cookie - but I see there set-cookie of `connect.sid=` only is in the response). So when I do close / restore Tab the browser open the `/rtl/login` URI and send cookie `_csrf` (as I understand it's cookie of closed session).

I use the [RaspiBolt config for RTL with Nginx](https://raspibolt.org/guide/lightning/web-app.html) but I think it's problem of RTL because the nginx config it's only [upstream config](https://raspibolt.org/guide/lightning/web-app.html#firewall--reverse-proxy) and doesn't manage ETag caching...

**Comment by Perlover** [comment]
> These _csrf and connect.sid cookies are auto generated by browsers

No, I tested by webtools and I see that this cookie goes from server when I do `/rtl/login` request:

The request:

```
GET /rtl/login HTTP/1.1
Host: *******:4001
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: *********
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Pragma: no-cache
Cache-Control: no-cache
```
And the response: 

```
HTTP/1.1 200 OK
X-Powered-By: Express
Cache-Control: no-cache
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, filePath
Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS
Set-Cookie: _csrf=NbK6************OYx; Path=/
Set-Cookie: XSRF-TOKEN=Kjs3*********haQrAyiw; Path=/
Set-Cookie: connect.sid=s%3AECC_zch*******************R%2BZYbnq7%2Bps; Path=/; Expires=Wed, 14 Sep 2022 16:13:16 GMT; HttpOnly
XSRF-TOKEN: Kjs**************rAyiw
Accept-Ranges: bytes
Last-Modified: Tue, 13 Sep 2022 15:39:46 GMT
ETag: W/"e*******534"
Content-Type: text/html; charset=UTF-8
Content-Length: 3794
Date: Tue, 13 Sep 2022 16:13:16 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

**Comment by Perlover** [comment]
After diving into the problem, how did I find out that the problem is not related to the fact that ETag is used, but to the fact that the logout page does not delete the cookie `XSRF-TOKEN`. Then this cookie is received by the page `/rtl/api/conf/updateSelNode/1/-1` which in response exposes a session cookie `connect.sid`

```
GET /rtl/api/conf/updateSelNode/1/-1 HTTP/1.1

Host: HOST:4001
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0
Accept: application/json, text/plain, */*
Accept-Language: ***********
Accept-Encoding: gzip, deflate, br
Authorization: Bearer eyJhbGciOi*****************jI5fQ.pRxhnDHzGX0XzOmbxHM-2T5HbrlKJO026Y4ZoGmIQFw
Connection: keep-alive
Referer: https://HOST:4001/rtl/login
Cookie: _csrf=NbK******a_Dx8rhOYx; XSRF-TOKEN=Kjs3***************_R73XYyuKnhaQrAyiw
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
If-None-Match: W/"32-4JDC+76Totmp+iiD5hW/xpzEeqY"

HTTP/1.1 304 Not Modified
X-Powered-By: Express
Cache-Control: no-cache
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, filePath
Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS
ETag: W/"32-4JDC+76Totmp+iiD5hW/xpzEeqY"
Set-Cookie: connect.sid=s************************XPg4tkYQc; Path=/; Expires=Wed, 14 Sep 2022 16:24:20 GMT; HttpOnly
Date: Tue, 13 Sep 2022 16:24:20 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

**Comment by ShahanaFarooqui** [comment]
Reopening the issue to investigate further.

**Comment by ShahanaFarooqui** [comment]
@Perlover After investigating it further I found that, Firefox by design, for restore session feature, does not clear its session cookies on tab closing. User has to close the whole browser window in order to clear its session cookies. Please feel free to check below links for further details:

https://stackoverflow.com/questions/22214426/how-to-log-out-when-i-close-the-firefox
https://stackoverflow.com/questions/777767/firefox-session-cookies
https://bugzilla.mozilla.org/show_bug.cgi?id=443354

> Cookies generated by browsers - there is no such thing. I have not seen any cookies that the browser generates for the site.

Thank you for the correction. By auto generated, I meant they are NOT generated by the code written in the RTL server's code base. These cookies are generated by express and sent to the browser without RTL's involvement, although `_csrf` and `XSRF_TOKEN` cookies are used for CSRF protection.
