### ISSUE TITLE
Option to turn off routing history download for Dashboard count?

### ISSUE THREAD

**Issue by wtogami** [Ride-The-Lightning/RTL#1045]
![dashboard-routing-fee-animation](https://user-images.githubusercontent.com/93665/177504036-8aa450d9-6fe1-425b-80d7-134c82a35c7d.png)

When you login to RTL the dashboard animates for a while as it downloads the entire routing history. It does this so it is able to display the quantity of transactions on the dashboard.

Could we please have an option or something to turn off this download? In that case it would download the routing history only if you load the Routing page. That way loading RTL would be fast and data efficient while on metered data. This matters over slow mobile to be able to get to the Transaction and Invoice page more quickly.

Maybe not an option ... how about click on that area to load the count? The count really isn't very important IMO relative to the amount of data transferred and the slowdown. Yes I am aware CLN will later have the ability to filter the data to make it a faster/smaller download. I still don't see it is important to update the count if it slows down mobile use?

**Comment by ShahanaFarooqui** [comment]
Removed number of transactions from Dashboard and initial listForwards call. Settled listForwards will only be called on fee report and forwarding history pages now. Dashboard will show total number of transactions if the user has already been visited to one of these pages and the data is available. 

Closing with PR #1061.
