### ISSUE TITLE
Peer Latency - unit of measurement

### ISSUE THREAD

**Issue by andrew-weber** [Ride-The-Lightning/RTL#1048]
**Describe the bug**
What is the peer's `ping_time` unit of measure? 

**To Reproduce**
- Look at the `Peer` table in the Lightning section of RTL.  
- There is a `Ping` column
- What is that measured in? (milliseconds, microseconds, nanoseconds, seconds)?

**Additional context**
I just think adding a little indicator here would be enough to help me identify the latency of my node.
https://github.com/Ride-The-Lightning/RTL/blob/master/src/app/lnd/peers-channels/peers/peers.component.html#L36-L40

**Comment by andrew-weber** [comment]
I've tried looking through the code to find an answer to this question so I could submit a PR myself, but I do not know. If I can get an answer, I can try to make a PR.

**Comment by saubyk** [comment]
Hi @andrew-weber unfortunately, the LND API documentation for this field is inadequate, see below:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/39208279/178575698-1efea1d7-633e-447a-91bc-1c8593535ff1.png">

We can assume it to be seconds or if you'd like, you can verify with LND team on one of their slack channels.

**Comment by ShahanaFarooqui** [comment]
Answered here: https://github.com/lightningnetwork/lnd/discussions/6307
