### ISSUE TITLE
Loop out failed, I was charged 30,000 sats 

### ISSUE THREAD

**Issue by DLux76198** [Ride-The-Lightning/RTL#1058]
Hi, I initiated a loop out on RTL and was charged 30,000 sats. The transaction failed but I was still charged 30k sats as a prepayment. Will I get this back? 

Thanks.

**Comment by DLux76198** [comment]
![image](https://user-images.githubusercontent.com/101473823/183357050-ca706555-d77d-453c-9d21-4fe86c9897b3.png)

**Comment by saubyk** [comment]
being tracked on the loop repo:
https://github.com/lightninglabs/loop/issues/518

**Comment by howTOdoIT2** [comment]
I have the same issue, 
Umbrel node that work without any issue

Initiation Time: 06/Aug/2022 15:16 
Server Cost (Sats): 30,000
ID: Qqa0AfBlFBQws9hVDj7Ce7EjnCRyZLwWu0LbQXuYZFA=
HTLC Address:  bc1q92y6nxxt5frfyx9n53hx8l58r3yffyarf92dxmv8ujvtte4j3ftq325aun

I wanna know who receive those 30k sats
