### ISSUE TITLE
Please add in/out pending htlcs to both the open, and pending/inactive channels tabs

### ISSUE THREAD

**Issue by devastgh** [Ride-The-Lightning/RTL#1086]
**Is your feature request related to a problem? Please describe.**
Should be nice to see how much pending htlcs i have on specific channels.

**Additional context**
In c-lightning pending htlcs are listed in `listpeers` so it just needs to be counted for in and out.

**Comment by jacobburrell** [comment]
Ran into the need for this. 

Funds seem to be missing, missing completely from the tx history while pending.

**Comment by ShahanaFarooqui** [comment]
Closing with PR #1235
