### ISSUE TITLE
[eclair]  private channels are shown as public in RTL

### ISSUE THREAD

**Issue by viaj3ro** [Ride-The-Lightning/RTL#1092]
for some reason RTL ignores the `announceChannel` flag and marks channels as public, even if the flag is set to `false`

**Comment by ShahanaFarooqui** [comment]
Closing with PR #1094

**Comment by ShahanaFarooqui** [comment]
@viaj3ro Thank you for opening the issue. Root cause for the bug was change in channel's response signature from Eclair.
