### ISSUE TITLE
Peerswap: Unable to View Info for swap-in/out

### ISSUE THREAD

**Issue by nlflint** [Ride-The-Lightning/RTL#1097]
**Describe the bug**
Clicking `View Info` on swap-in/out/canceled does nothing

**To Reproduce**
0. Ensure you have some swap-in/out/canceled
1. Go to 'Serivces->Peerswap'
2. Click on 'Swap Out' tab
3. Click on 'View Info' button

Expected Result: A dialog opens with info about the swap
Actual Result: Nothing happens. An error is recorded in the Firefix debug console: 

**Screenshots**
Firefox console error: ![image](https://user-images.githubusercontent.com/1383530/190538630-60f83203-75a7-47c5-bf08-4c1976dd1efb.png)

**Your environment**
RTL Version: branch `cln-peer-swap` commit: `781974b8e7580dcf87ebe8790241902f36701db8`
CLN version: 0.11.1
Bitcoind version: 23.0
Browser: Firefix v104.0.1 (from Ubuntu 22.04 snap store)
OS: Ubuntu 22.04.1 LTS

**Additional context**
`View Info` button also doesn't work on swap-in and swap cancelled tabs. It does the same thing as on the swap-out tab.

**Comment by nlflint** [comment]
Update: I am UNABLE to repro this with Chrome on the same PC with same web instance. Only seems to repro with Firefox.

**Comment by ShahanaFarooqui** [comment]
Issue fixed with commit 62acf36497be281eee3e24e48651330b7d78e7b5 and merged in `cln-peer-swap` branch.
