### ISSUE TITLE
RTL Outdated on Umbrel

### ISSUE THREAD

**Issue by Redinpais** [Ride-The-Lightning/RTL#1109]
Greetings.
Do  you have intention update RTL to Umbrel?
Now it is on 0.12.1-beta
TKS

**Comment by saubyk** [comment]
@Redinpais yes we do. Thanks for the reminder

**Comment by Redinpais** [comment]
You welcome

**Comment by ShahanaFarooqui** [comment]
Submitted the PR https://github.com/getumbrel/umbrel-apps/pull/170. Keeping this issue open till that is merged. Thank you.

**Comment by saubyk** [comment]
PR's merged on Umbrel. Closing this issue now.
