### ISSUE TITLE
Expired GPG key

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#1114]
**Describe the bug**
The GPG key is expired so it's no longer (easily) possible to verify the releases.

**To Reproduce**
1. Attempt to verify RTL signature using key 3E9BD4436C288039CA827A9200C9E2BC2E45666F
2. See expiration error

**Comment by saubyk** [comment]
Hi @Kixunil thanks for raising this. I renewed my gpg key on the mit server and keybase.
You should be able to verify the RTL releases again. Thanks.
