### ISSUE TITLE
Add warning message to UI if node is not `synced_to_chain`

### ISSUE THREAD

**Issue by milhousevanhouten11** [Ride-The-Lightning/RTL#1126]
**Is your feature request related to a problem? Please describe.**
This week there was a bug in LND, and LND nodes couldn't process new bitcoin blocks. 
There was no information about this in RTL. 

**Describe the solution you'd like**
Add warning message to UI if node is not `synced_to_chain`. 
Maybe we can add a red banner message if something like this happens again.

**Comment by saubyk** [comment]
Thanks for raising this. @ShahanaFarooqui and I discussed this when the last incident occurred

**Comment by ShahanaFarooqui** [comment]
I already fixed it on my local. I will merge it as soon as my current issue is done.

**Comment by ShahanaFarooqui** [comment]
Closing with PR #1128.
