### ISSUE TITLE
UI for choosing your own route when making a payment

### ISSUE THREAD

**Issue by obarat** [Ride-The-Lightning/RTL#113]
I would really like a UI where I can choose the route a payment should go through.  Maybe the UI can offer suggestions of routes that can be taken and the user can choose.

This will help with rebalancing channels.  I have 2 nodes and I want to rebalance by sending and receiving through specific routes.

**Comment by saubyk** [comment]
This requirement will be covered with the below ticket:
https://github.com/Ride-The-Lightning/RTL/issues/244
