### ISSUE TITLE
Add action to connect to a node in the node lookup page

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#1134]
User should be able to connect to a node on the node lookup page, eliminating the need to copy the Node URI Info all over to the peer page to initiate connection with the peer

Add the `Connect` action on the `Addresses` grid along with the `Copy Node URI` action

**Comment by harshit0verma** [comment]
Can I work on this issue ?

**Comment by ShahanaFarooqui** [comment]
@harshit0verma Sure, please go ahead.

**Comment by royalpinto007** [comment]
I have addressed this issue, kindly request your evaluation of my work- https://github.com/Ride-The-Lightning/RTL/pull/1186

**Comment by ShahanaFarooqui** [comment]
Closing with PR #1222.
