### ISSUE TITLE
Config click on CLN for BTCPay prompts for password

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#1144]
When user clicks navigates to `Node Config` > `Core Lightning Config` tab on BTCPayserver, the application prompts for a password, which the user cannot provide since BTCPay is single sign on authentication.
This check needs to be by-passed for BTCPay/SSO integration

![image](https://user-images.githubusercontent.com/39208279/207482518-77cacf98-31f7-43f9-9a1d-1176e38e0c42.png)

**Comment by ShahanaFarooqui** [comment]
Closing with commit 0e48676c5cf6838a10ad31e6182927321cde0e47.
