### ISSUE TITLE
Inconsistent color code for inactive channels

### ISSUE THREAD

**Issue by abhiShandy** [Ride-The-Lightning/RTL#1154]
**Describe the bug**
Pending and Inactive channels have inconsistent color coding.

Inactive should be yellow, pending should be gray.

**To Reproduce**
1. have one inactive and one pending channel
2. pending channel color on the home page (operator layout) is different from channels page

**Screenshots**
![Screenshot 2022-12-21 at 2 53 26 PM](https://user-images.githubusercontent.com/6998593/208991749-d0726298-8679-4a25-a205-db14a4e3b64e.png)
![Screenshot 2022-12-21 at 2 53 35 PM](https://user-images.githubusercontent.com/6998593/208991753-786cf855-29a3-4fc4-a695-dd9b007921d4.png)

**Your environment**
* Version of `RTL` 0.13.2
* Version of `lnd`/`core lightning`/`eclair` LND 
* Version of `btcd`, `bitcoind`, or other backend Neutrino
* Browser & browser version Chrome
* Operating system (`uname -a` on *Nix) MacOS
* any other relevant environment details

**Additional context**

**Comment by ShahanaFarooqui** [comment]
Closing with PR #1155 by @abhiShandy.
