### ISSUE TITLE
Config for default invoice expiry on dashboard

### ISSUE THREAD

**Issue by neocogent** [Ride-The-Lightning/RTL#1159]
Maybe this exists but I couldn't find. On dashboard when you create an invoice the default expiry is 3600 secs. I got bit the other day by this as it's far too short for many uses. I know on the transactions page the expiry can be set in advanced mode. 

I think it would be very useful to be able to define the expiry default when it's not settable, eg. on dashboard. Or even just allow it to be set manually rather than hidden.

I think invoices are supposed to be default 24 hours now anyway, so I find it odd that a 1 hour default exists on the simplified invoice widget.

**Comment by ShahanaFarooqui** [comment]
@neocogent Thank you for raising the issue. We increased default invoice expiry from an hour to seven days now. Closing it with PR @1201.
