### ISSUE TITLE
RTL server does not start - npm install generates several warnings

### ISSUE THREAD

**Issue by prassidicePM** [Ride-The-Lightning/RTL#1163]
**Describe the bug**
when running node rtl I got:
file:///home/clnuser/Downloads/RTL-0.13.3/backend/utils/common.js:204
            array?.unshift(newlyAddedRecord[0]);
            ----^

SyntaxError: Unexpected token '.'

the server is not running

**To Reproduce**
1. $ node rtl
2. 
3. 

**Screenshots**

**Your environment**
* Version of RTL: 0.13.3
* Version of core lightning: v22.11rc2
* Version of btcd: v22.0.0
* Browser & browser version: firefox 102.6.0esr
* Operating system: Linux debian 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
* any other relevant environment details: running bitcoin-qt, lightningd, lightning-qt, c-lightning-REST-0.9.0

**Additional context**

c-lightning-REST server is working:
$ node cl-rest.js
Reading config file
warn: --- Starting the cl-rest server ---
warn: --- cl-rest api server is ready and listening on port: 3001 ---
warn: --- cl-rest doc server is ready and listening on port: 4001 ---

RTL-Config.json:
{
  "multiPass": "",
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "Node 1",
      "lnImplementation": "CLN",
      "Authentication": {
        "macaroonPath": "",
        "configPath": "",
      },
      "Settings": {
	"userPersona": "OPERATOR",
        "themeMode": "DAY",
        "themeColor": "PURPLE",
        "bitcoindConfigPath": "",
        "logLevel": "INFO",
        "fiatConversion": false,
        "unannouncedChannels": false,
        "lnServerUrl": ""
      }
    }
  ]
}

$ node --version
v12.22.12

$ npm --version
7.5.2

$ npm audit
# npm audit report

d3-color  <3.1.0
Severity: high
d3-color vulnerable to ReDoS - https://github.com/advisories/GHSA-36jr-mh4h-2g58
fix available via `npm audit fix --force`
Will install @swimlane/ngx-charts@6.1.0, which is a breaking change
node_modules/d3-interpolate/node_modules/d3-color
node_modules/d3-transition/node_modules/d3-color
  d3-interpolate  0.1.3 - 2.0.1
  Depends on vulnerable versions of d3-color
  node_modules/d3-interpolate
    @swimlane/ngx-charts  >=7.0.0
    Depends on vulnerable versions of d3-interpolate
    Depends on vulnerable versions of d3-transition
    node_modules/@swimlane/ngx-charts
    d3-brush  0.1.0 - 2.1.0
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-brush
    d3-scale  0.1.5 - 3.3.0
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-scale
    d3-transition  0.0.7 - 2.0.0
    Depends on vulnerable versions of d3-color
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-transition

6 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

**Comment by ShahanaFarooqui** [comment]
Angular 15 needs NodeJS version '>=14.20.0 OR >=16.13.0 OR  >=18.10.0'.

**Comment by prassidicePM** [comment]
I've installed node 18.12.1 and npm 8.19.2
$ node --version
v18.12.1
$ npm --version
8.19.2

then I re untar'd v0.13.3.tar.gz
and run npm install --omit=dev --legacy-peer-deps

got worning, the npm audit is:

$ npm audit
# npm audit report

d3-color  <3.1.0
Severity: high
d3-color vulnerable to ReDoS - https://github.com/advisories/GHSA-36jr-mh4h-2g58
fix available via `npm audit fix --force`
Will install @swimlane/ngx-charts@12.1.0, which is a breaking change
node_modules/d3-interpolate/node_modules/d3-color
node_modules/d3-transition/node_modules/d3-color
  d3-interpolate  0.1.3 - 2.0.1
  Depends on vulnerable versions of d3-color
  node_modules/d3-interpolate
    @swimlane/ngx-charts  >=7.0.0
    Depends on vulnerable versions of d3-brush
    Depends on vulnerable versions of d3-interpolate
    Depends on vulnerable versions of d3-scale
    Depends on vulnerable versions of d3-transition
    node_modules/@swimlane/ngx-charts
    d3-scale  0.1.5 - 3.3.0
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-scale
    d3-transition  0.0.7 - 2.0.0
    Depends on vulnerable versions of d3-color
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-transition
      d3-brush  0.1.0 - 2.1.0
      Depends on vulnerable versions of d3-interpolate
      Depends on vulnerable versions of d3-transition
      node_modules/d3-brush

json5  <2.2.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
fix available via `npm audit fix`
node_modules/json5

jsonwebtoken  <=8.5.1
Severity: high
jsonwebtoken unrestricted key type could lead to legacy keys usage  - https://github.com/advisories/GHSA-8cf7-32gw-wr33
jsonwebtoken has insecure input validation in jwt.verify function - https://github.com/advisories/GHSA-27h2-hvpr-p74q
jsonwebtoken's insecure implementation of key retrieval function could lead to Forgeable Public/Private Tokens from RSA to HMAC - https://github.com/advisories/GHSA-hjrf-2m68-5959
jsonwebtoken vulnerable to signature validation bypass due to insecure default algorithm in jwt.verify() - https://github.com/advisories/GHSA-qwph-4952-7xr6
fix available via `npm audit fix --force`
Will install jsonwebtoken@9.0.0, which is a breaking change
node_modules/jsonwebtoken

8 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force





launching "node rtl" I got:
$ node rtl
[1/3/2023, 11:20:46 AM] ERROR: Config => Something went wrong while configuring the node server: 
SyntaxError: Unexpected token } in JSON at position 433.

file:///home/clnuser/Downloads/RTL-0.13.3/backend/utils/config.js:347
                throw new Error(err);
                      ^

Error: SyntaxError: Unexpected token } in JSON at position 433
    at ConfigService.setServerConfiguration (file:///home/clnuser/Downloads/RTL-0.13.3/backend/utils/config.js:347:23)
    at ExpressApplication.loadConfiguration (file:///home/clnuser/Downloads/RTL-0.13.3/backend/utils/app.js:32:25)
    at new ExpressApplication (file:///home/clnuser/Downloads/RTL-0.13.3/backend/utils/app.js:84:14)
    at file:///home/clnuser/Downloads/RTL-0.13.3/rtl.js:10:13
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.12.1

**Comment by prassidicePM** [comment]
fixed with rel. [v0.13.4-beta](https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.13.4)
