### ISSUE TITLE
2FA QR Code/Secret Code not generating

### ISSUE THREAD

**Issue by apemithrandir** [Ride-The-Lightning/RTL#1164]
**Describe the bug**
Fresh install of RTL on my server on top of LND node.

**To Reproduce**
1. Go to Settings/Authentication/
2. Click on Setup Two Factor Authentication
3. Scroll down to Enter Password
4. No QR code or secret displaying

**Screenshots**
![image](https://user-images.githubusercontent.com/99969638/210385030-ce6324bf-404a-41e0-89de-d8f6391cef1a.png)

**Your environment**
* `RTL`: 0.13.3-beta
* Browser & browser version: chrome/firefox
* NPM version 9.2.0
* Node version 19.3.0

**Additional context**
Not sure why this might be happening.

**Comment by ShahanaFarooqui** [comment]
This is fixed in release branch 0.13.4 but it will require NodeJS version 16.13.0.  Hopefully we will release it today.

**Comment by ShahanaFarooqui** [comment]
Closing with Final PR #1165 merge into master.

**Comment by apemithrandir** [comment]
Thanks this works now!
