### ISSUE TITLE
password mask

### ISSUE THREAD

**Issue by prassidicePM** [Ride-The-Lightning/RTL#1166]
**Is your feature request related to a problem? Please describe.**
inserting the new password the first time or changhing password is not so easy since you have to insert the passwords and then press "enter" and it is not clear if pressing the "2FA" button implies accepting the new password as well

![screen4](https://user-images.githubusercontent.com/109905397/210591318-37d2212d-b1ca-46c7-8bb9-99db0075141a.png)

**Describe the solution you'd like**

should be better to add a login button

# by the way, you have done a great job!

**Comment by ShahanaFarooqui** [comment]
We do have `change password` & `reset` buttons on the change password section but they somehow hide under the 2FA section in the last release. 

So I fixed the bug and it will be released in v0.13.5.

Thank you for raising the issue and for the appreciation :).
