### ISSUE TITLE
Circular Rebalancing - Receive from Peer, No Drop Down

### ISSUE THREAD

**Issue by Ripley81** [Ride-The-Lightning/RTL#1179]
I have 10 active channels with >900,000 sats in each, all as local balance. When I pick a channel and go to Action/Circular Rebalance, I am unable to select a Receive from Peer as that field does not contain a drop down to select from my other 9 active peers.

I can see drop down fields on other pages e.g. the Peer dashboard, i.e. I doubt it's a browser issue.

Screenshots attached.

Is there something else I need to do before being able to rebalance? I have yet to make any payment/invoice using any of these 10 channels.

RTL version:  0.13.4 beta
LND ver 0.15.5-beta
Bitcoind v24.0.1
Firefox 107  (I have tried on Chrome as well, same result)
MacOS 12.6.2

<img width="926" alt="RTL 2023-01-24 05-55-21" src="https://user-images.githubusercontent.com/28821403/214216135-23807d23-8ec2-41e5-804f-f43453563ca9.png">

<img width="537" alt="RTL 2023-01-24 06-07-57" src="https://user-images.githubusercontent.com/28821403/214216439-b007c878-b0ce-4a2f-95de-95e42ae8ac25.png">

**Comment by ShahanaFarooqui** [comment]
@Ripley81 Amount needs to be selected before peer selection because peers are filtered based upon amount.

**Comment by Ripley81** [comment]
Thanks for the quick response. I'm afraid I already tried that.

<img width="789" alt="RTL 2023-01-24 06-19-54" src="https://user-images.githubusercontent.com/28821403/214217628-1412a235-b8d1-4d90-b2c8-8fa02941e017.png">

**Comment by Ripley81** [comment]
Here is an example of the drop down working on e.g. Open Channel.
<img width="949" alt="RTL 2023-01-24 06-22-55" src="https://user-images.githubusercontent.com/28821403/214218164-588fc1eb-7fb5-4e7c-acbe-bddc18dbd171.png">

**Comment by ShahanaFarooqui** [comment]
@Ripley81 did you try with lower amount? Can you please check browser console if it shows any error.

**Comment by Ripley81** [comment]
Same, irrespective of amount, I've tried from 10,000 sats upwards.

Do I need to Open Channel before I can Rebalance?

**Comment by saubyk** [comment]
Hi @Ripley81 unless you have channels with inbound liquidity (or remote balance), you'll not be able to perform local rebalance action.

You're not able to select any peer to receive from, because none of your peers can route any funds to you.

**Comment by saubyk** [comment]
You need to get the funds on the remote side first, which can be done by any of the following actions:

1. Making a payment
2. Getting a peer to open a channel to you
3. Perform Loop-out swap to move funds to remote side
4. Buy a channel from any of the existing liquidity service providers

Once you have the funds on the remote side, you'll be able to do local rebalance

**Comment by Ripley81** [comment]
Gotcha. It seems like a chicken/egg situation. It sounds like I have to spend sats (fees) to properly get my channel to work, which is unfortunate. I will try paying myself through 1), or 2) if I can Open Channel among my own Peers, or 3) although I don't know what that is.
Thanks though for your help!
