### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by erikarvstedt** [Ride-The-Lightning/RTL#1182]
### Reproduce
```bash
npm install --omit=dev
```
Result:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @angular/flex-layout@14.0.0-beta.41
npm ERR! Found: @angular/cdk@15.0.3
npm ERR! node_modules/@angular/cdk
npm ERR!   dev @angular/cdk@"^15.0.1" from the root project
npm ERR!   peer @angular/cdk@"15.0.3" from @angular/material@15.0.3
npm ERR!   node_modules/@angular/material
npm ERR!     dev @angular/material@"^15.0.1" from the root project
npm ERR!   1 more (@swimlane/ngx-charts)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^14.0.0" from @angular/flex-layout@14.0.0-beta.41
npm ERR! node_modules/@angular/flex-layout
npm ERR!   dev @angular/flex-layout@"^14.0.0-beta.41" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/cdk@14.2.7
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@"^14.0.0" from @angular/flex-layout@14.0.0-beta.41
npm ERR!   node_modules/@angular/flex-layout
npm ERR!     dev @angular/flex-layout@"^14.0.0-beta.41" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

First bad commit: b4e65e209847310caa29fd7c99b2c3e8421a2f40

**Comment by erikarvstedt** [comment]
This should be mentioned in the readme.

**Comment by erikarvstedt** [comment]
Whether `--legacy-peer-deps` is required is completely deterministic (on all platforms), so the actual command in section `First time setup` should be fixed.

**Comment by ShahanaFarooqui** [comment]
We do not encourage to install dependencies with `--legacy-peer-deps` in the first instance. We update out library version with every release and 95% times, installation doesn't require --legacy-peer-deps option. So adding it in case of `npm error` was an intentional decision.

**Comment by erikarvstedt** [comment]
Would it be possible to add the flag to the recommended install command in the 5% of cases when it is broken?
This greatly improves robustness and user experience. Install commands should never fail deterministically.
It also allows you to remove section `Error on npm install` from the README.

**Comment by ShahanaFarooqui** [comment]
In ideal situation, it should always be updated before each release.

However, with limited time & resources, we found it more acceptable to add another section for 5% cases rather than unintentionally instructing the user to install with `legacy-peer-deps` option.
