### ISSUE TITLE
SyntaxError: Unexpected token '.'     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)

### ISSUE THREAD

**Issue by SebiCreator** [Ride-The-Lightning/RTL#1185]
**Describe the bug**
if i run node rtl i get the following error:

file:///home/sebi/RTL-0.13.4/backend/utils/webSocketServer.js:41
                const protocols = !request.headers['sec-websocket-protocol'] ? [] : request.headers['sec-websocket-protocol'].split(',')?.map((s) => s.trim());
                                                                                                                                         ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)

**To Reproduce**
1. followed your installation steps
2. loaded relase v0.13.4
3. run npm install --omit=dev --legacy-peer-deps
4. rename and modified RTL-Config.json (see screenshot below)
5. run node rtl
6. get the error i showed above

**Screenshots**
<img width="520" alt="Bildschirm­foto 2023-01-29 um 10 43 31" src="https://user-images.githubusercontent.com/63467522/215319289-a68a2e26-9ba0-4664-95cc-34f142797d2e.png">
<img width="714" alt="Bildschirm­foto 2023-01-29 um 11 07 12" src="https://user-images.githubusercontent.com/63467522/215319294-487d2608-b84d-4d6c-9001-aac3dd75c695.png">

**Your environment**
* Version=0.13.4
* Version of lnd: lnd version 0.11.0-beta.rc3 commit=v0.11.0-beta.rc3
* Version of bitcoind: Bitcoin Core version v22.0.0
* Operating system: Linux coreserver 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux

**Comment by ShahanaFarooqui** [comment]
What is your NodeJS version?

**Comment by SebiCreator** [comment]
v12.22.12
