### ISSUE TITLE
Dashboard Lightning Balance varying over time without events or payments being processed.

### ISSUE THREAD

**Issue by cadayton** [Ride-The-Lightning/RTL#1187]
**Describe the bug**
In the RTL Dashboard version 0.13.2-beta in the Balances dialog, the Lightning balance varying over time without any routing or payments being processed.

At one point in a 12 hour period the balance reported 2,072,587 sats and then 979,806 sats and then back to 2,071,587 sats.
During this period there were no payments and no routing events.

**To Reproduce**
1.  Just refresh the GUI overtime.

**Screenshots**

**Your environment**
* Version of `RTL`   0.13.2-beta
* Version of `lnd`/`core lightning`/`eclair` BTCPay Server v1.7.3.0+09d5f5a0 lnd 
* Version of `btcd`, `bitcoind`, or other backend  bitcoind 24.0
* Browser & browser version; Chrome 108.0.5359.124
* Operating system (`uname -a` on *Nix) Pop!_OS 22.04 LTS"
* any other relevant environment details

**Additional context**

**Comment by Kali-Decoder** [comment]
Is there any social group to communicate on issues and how to start with this project please add me or provide a link @cadayton

**Comment by cadayton** [comment]
> Is there any social group to communicate on issues and how to start with this project please add me or provide a link @cadayton

A bunch of references can be found here.  https://github.com/bcongdon/awesome-lightning-network#irc

**Comment by ShahanaFarooqui** [comment]
I am currently working with marcom team to schedule a live coding session and will share more details in upcoming weeks. But you can join their waitlist in the meanwhile.

**Comment by ShahanaFarooqui** [comment]
We also use Github discussions for communication/discussions and Github issues for bugs/enhancement suggestions.

**Comment by saubyk** [comment]
Hi @cadayton This has nothing to do with RTL. This can possibly happen if a part of your channel liquidity is locked up with an active HTLC on that channel. It can end up in two possibilities:
- The HTLC resolves, you see a forwarding event/payment and your channel balance shifts accordingly
- The HTLC fails to resolves (likely happened in the case above) and your channel balance goes back to the previous state

Next time you observe this, you should also check the `Active HTLCs` tab on the `Channels` page.
Hope this clarifies.

Closing this issue now. Thanks.

**Comment by cadayton** [comment]
Ok. I'll check the ```Active HTLCs``` tab.   BTW as indicated this behavior happens in the absents of any forwarding events occurring on two different nodes running a pruned bitcoind.   On a node that is running a full bitcoind, this behavior is not happening.
