### ISSUE TITLE
installation issues...

### ISSUE THREAD

**Issue by TopherBrowne** [Ride-The-Lightning/RTL#1203]
After installing node.js and RTL, execution of "node rtl" results in...

bitcoin@xxx:~/Downloads/RTL-0.13.5$ node rtl
file:///home/bitcoin/Downloads/RTL-0.13.5/backend/utils/common.js:205
            array?.unshift(newlyAddedRecord[0]);
                  ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
bitcoin@topherDEV:~/Downloads/RTL-0.13.5$ 

Steps:
- install node.js via snap
bitcoin@xxx:~/Downloads$ tar -xvf v0.13.5.tar.gz
cd RTL-0.13.5
npm install --omit=dev --legacy-peer-deps

tail of output from NPM ...

npm WARN deprecated csurf@1.11.0: Please use another csrf package
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 384 packages, and audited 385 packages in 4s

25 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

modified RTL-Config.json...
{
  "multiPass": "xyzzy>",
  "port": "3000",
  "SSO": {
    "rtlSSO": 0,
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "xxx",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "/home/bitcoin/.lnd/data/chain/bitcoin/mainnet",
        "swapMacaroonPath": "/home/bitcoin/.lnd/data/chain/bitcoin/mainnet",
        "boltzMacaroonPath": "/home/bitcoin/.lnd/data/chain/bitcoin/mainnet",
        "configPath": "/home/bitcoin/.lnd",
      },
      "Settings": {
        "userPersona": "OPERATOR",
        "themeMode": "DAY",
        "themeColor": "PURPLE",
        "bitcoindConfigPath": "/home/bitcoin/.bitcoin",
        "logLevel": "DEBUG",
        "fiatConversion": true,
        "currencyUnit": "USD",
        "lnServerUrl": "https://127.0.0.1:8080",
      }
    }
  ]
}

environment...
lnd 0.15.5
bitcoind 22.0
ubuntu 22.0.4

**Comment by ShahanaFarooqui** [comment]
@TopherBrowne what is the NodeJS version?

**Comment by TopherBrowne** [comment]
bitcoin@topherDEV:~/Downloads/RTL-0.13.5$ npm version
{
  rtl: '0.13.5-beta',
  npm: '8.5.1',
  node: '12.22.9',
  v8: '7.8.279.23-node.56',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '72',
  nghttp2: '1.43.0',
  napi: '8',
  llhttp: '2.1.4',
  http_parser: '2.9.4',
  openssl: '1.1.1m',
  cldr: '40.0',
  icu: '70.1',
  tz: '2022g',
  unicode: '14.0'
}

**Comment by ShahanaFarooqui** [comment]
RTL is not compatible with NodeJS < 16

**Comment by TopherBrowne** [comment]
egads - 12.22 was included with distribution and is "most recent".

snap install of 18 stable didn't "overwrite"

in process of purging and will install via snap to latest stable 18 and retest

**Comment by TopherBrowne** [comment]
I was able to get it running after the 12.22 purge. closing.
