### ISSUE TITLE
"Payment sent successfully" - payment not sent at all

### ISSUE THREAD

**Issue by MDIMSMM** [Ride-The-Lightning/RTL#1210]
**Describe the bug**
Lightning address placed and it says "payment sent" with no changes to any data or received by the wallet.
This is the first time this lightning node is being used.
Local capacity: just shy of 3,000,000
Remote capacity: 0

Peer: Start9 HQ (open channel)

**To Reproduce**
1. Go to 'Lightning transactions'
2. Click on 'send payment'
3. Fill in lightning address
4. "Payment sent successfully"
5. No changes, no payment sent

**Screenshots**

**Your environment**
* Version of `RTL`0.13.6
* Version of `lnd`/`core lightning`/`eclair`LND 0.15.5-beta
* Version of `btcd`, `bitcoind`, or other backend
* Browser & browser version: Impervious ? (up to date)
* Operating system (`uname -a` on *Nix) Mac Ventura 13.2
* any other relevant environment details

**Additional context**

**Comment by saubyk** [comment]
Hi @MDIMSMM are you trying to pay a lightning invoice or a lightning address?

If the latter, there is no support yet to pay a lightning address on RTL. This is something we are looking to fix in the near future though.

Please clarify. thanks.

**Comment by MDIMSMM** [comment]
Good to know.

I'm using the Blixt wallet (admittedly I'm very new at all this). It says "create invoice" after I fill in all of the required fields.

Thanks

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by saubyk** [comment]
can you post a sample invoice (for a few sats) here, that you're trying to pay?

**Comment by MDIMSMM** [comment]
I'm unclear what you want. Do you want a screenshot from my Blixt wallet, a screenshot from RTL, or something else?

**Comment by saubyk** [comment]
create an invoice for a few sats, which you trying to pay via RTL and paste it here

I am trying to figure out, what you are entering on RTL

**Comment by MDIMSMM** [comment]
lnbc312450n1pjqqqaepp59v3qupwz73p3cl3wu9u97d0e475fx9jnn42zwnx5rlarkt6zsxmqdpsgfjkx6me8gszqnn0yp5kuan0d93k2gryv4ekxunfwp6xjmmwcqzpgxqrrssrzjqgc2t099trn8g9rqcy7axnnrdk3gu540myw0j0dc0mgmqwf2w3nwhapyqqqqqqqr0qqqqqqqqqqqztqq9qsp5tg5ghldmtk9ades8xnq94zt97m8rdtxhdkljwwywxgae7e8r5khq9qyyssqfnvtt56dp0xwzx6nsxdymacwd7ahddqzz8mphkt5m5k84xjafcfssfs2xcz37xp863q8jq9ghndprxzk77mjjhl7he3xw9xm3qrzyvgpnvzqsm

**Comment by MDIMSMM** [comment]
did more than a few sats... oops. Oh well. That's about the amount I'm trying to move

**Comment by saubyk** [comment]
Ok this invoice should be easily paid via RTL. Can you provide screenshots of what happens when you try to pay it?

Also, if you post one with a smaller amount, I can try to pay it myself.

**Comment by MDIMSMM** [comment]
lnbc31510n1pjqzn8rpp5332uq4utp2070f5fk62rpl477detdudrq0k6w2z7nsesunglnghqdpsgfjkx6me8gszqnn0yp5kuan0d93k2gryv4ekxunfwp6xjmmwcqzpgxqrrssrzjqgc2t099trn8g9rqcy7axnnrdk3gu540myw0j0dc0mgmqwf2w3nwhapyqqqqqqqr0qqqqqqqqqqqztqq9qsp5ydjsf8majwcyngtqxwcm8d7jass0hl50gz9s43qxqqrf3jvm4ams9qyyssqc7s43t0yk7y5nl5ql9gckjx0jcpz89680jlhyjvx5sg8f7vanchh5tdrgtgz37vjwqm0ygrrgfz8mup366pftvthluxl0du0f2qhndqqeqjs0p

**Comment by MDIMSMM** [comment]
<img width="1431" alt="Screenshot 2023-03-02 at 5 28 24 PM" src="https://user-images.githubusercontent.com/126630342/2226093
<img width="1440" alt="Screenshot 2023-03-02 at 5 30 49 PM" src="https://user-images.githubusercontent.com/126630342/222609349-10037011-2dda-43e7-b035-f7c56f0f9219.png">
27-6fe3290d-86e6-4664-9f2b-23e90e256859.png">

**Comment by saubyk** [comment]
> lnbc31510n1pjqzn8rpp5332uq4utp2070f5fk62rpl477detdudrq0k6w2z7nsesunglnghqdpsgfjkx6me8gszqnn0yp5kuan0d93k2gryv4ekxunfwp6xjmmwcqzpgxqrrssrzjqgc2t099trn8g9rqcy7axnnrdk3gu540myw0j0dc0mgmqwf2w3nwhapyqqqqqqqr0qqqqqqqqqqqztqq9qsp5ydjsf8majwcyngtqxwcm8d7jass0hl50gz9s43qxqqrf3jvm4ams9qyyssqc7s43t0yk7y5nl5ql9gckjx0jcpz89680jlhyjvx5sg8f7vanchh5tdrgtgz37vjwqm0ygrrgfz8mup366pftvthluxl0du0f2qhndqqeqjs0p

Well, I was hoping for a smaller amount like 100 sat or something, regardless I paid this 3151 sat invoice, did you get the payment?

**Comment by saubyk** [comment]
Interestingly, I am not able to track the above payment at my end as well.

Can you please generate a 10 sat invoice and post here? So that I can try to debug, what's happening without incurring significant cost! 😅

**Comment by MDIMSMM** [comment]
Sorry about that! I tried to do less and it was being weird with me. I'm happy to send same amount back to you. Maybe I could try to send with my Blixt account to you to see if it might be the wallet?

**Comment by MDIMSMM** [comment]
I didn't receive the payment... square?
I'll get you a 10 sat invoice. I figured it out. Not my brightest moment.

**Comment by MDIMSMM** [comment]
On another note... I have to email myself my invoice since RTL doesn't allow for scanning QR invoices. Unless I'm missing something?

**Comment by MDIMSMM** [comment]
lnbc100n1pjqzhfnpp55u5h7tptsmw2qkkvsetnxlk9lmj3qkghfc609dwn2dapxs6csrssdpsgfjkx6me8gszqnn0yp5kuan0d93k2gryv4ekxunfwp6xjmmwcqzpgxqrrssrzjqgc2t099trn8g9rqcy7axnnrdk3gu540myw0j0dc0mgmqwf2w3nwhapyqqqqqqqr0qqqqqqqqqqqztqq9qsp5zs09pzxn8a6w9u780kfdrd0e4ud9gsq7wwhfjpf7qd4h8nnevuws9qyyssqaffk6a7h72txh89cqpldhaq97e2n5v6caekfas0g9sk0xhrcdq7qf0xrtfkhw5wxet26kfcpg9rwuspgl42aysvl6pyd5snlgpagxgspxqcq69

**Comment by saubyk** [comment]
it's behaving the same way at my end as well, shows payment sent successfully, but nothing is actually sent.

Can you do me one last favor? generate another invoice but this time put in some description.

**Comment by saubyk** [comment]
> On another note... I have to email myself my invoice since RTL doesn't allow for scanning QR invoices. Unless I'm missing something?

yeah, RTL is not optimized for mobile devices (hence no scanning), it's meant to be a desktop tool primarily

**Comment by MDIMSMM** [comment]
lnbc100n1pjqzczmpp5pxfuu3hknmf0stjkevqx7j70etkwpc965vxyupz2cj75dyg5mjcsdqagfjkx6me8gszq4r9wd6xjmn89chzucqzpgxqrrssrzjqgc2t099trn8g9rqcy7axnnrdk3gu540myw0j0dc0mgmqwf2w3nwhapyqqqqqqqr0qqqqqqqqqqqztqq9qsp5qk29p39gxld8jt9ndaa3t3y2g8rut84a8chlm7rueguyy7hrrarq9qyyssqpu3zp6nzyen6cr3tzwn7x4u8anfmj8rr0g3kgxvj6qvszpxf3ht4nf5yseham77kwehxmvhxpvkvclzpap62l4eucwd7hsxw6zg8xqcpvawyfs

**Comment by MDIMSMM** [comment]
> > On another note... I have to email myself my invoice since RTL doesn't allow for scanning QR invoices. Unless I'm missing something?
> 
> yeah, RTL is not optimized for mobile devices (hence no scanning), it's meant to be a desktop tool primarily

Bummer... it makes it hard to use it a central hot wallet. Any chance you'd all be willing to add that feature at some point?

**Comment by saubyk** [comment]
> lnbc100n1pjqzczmpp5pxfuu3hknmf0stjkevqx7j70etkwpc965vxyupz2cj75dyg5mjcsdqagfjkx6me8gszq4r9wd6xjmn89chzucqzpgxqrrssrzjqgc2t099trn8g9rqcy7axnnrdk3gu540myw0j0dc0mgmqwf2w3nwhapyqqqqqqqr0qqqqqqqqqqqztqq9qsp5qk29p39gxld8jt9ndaa3t3y2g8rut84a8chlm7rueguyy7hrrarq9qyyssqpu3zp6nzyen6cr3tzwn7x4u8anfmj8rr0g3kgxvj6qvszpxf3ht4nf5yseham77kwehxmvhxpvkvclzpap62l4eucwd7hsxw6zg8xqcpvawyfs

definitely an issue. need further investigation with @ShahanaFarooqui

Thanks for the invoices, will post later when I have an update

**Comment by MDIMSMM** [comment]
Thanks! I appreciate the prompt response.

**Comment by MDIMSMM** [comment]
Just had a thought... could it be my wallet? If you want to try with other lightning wallets... Granted, I'm no dev so that may be illogical

**Comment by saubyk** [comment]
> Just had a thought... could it be my wallet? If you want to try with other lightning wallets... Granted, I'm no dev so that may be illogical

There is some peculiarity here for your wallet, but at least if there is an error condition, it should throw an error. My aim is to figure out why the error is not being displayed on the UI

**Comment by MDIMSMM** [comment]
Fair enough. I'll try to experiment with the wallet. Thanks!

**Comment by saubyk** [comment]
Hi @MDIMSMM will it possible for you to share one more invoice? please make the expiry period longer, like a week or so, if possible. Thanks

**Comment by MDIMSMM** [comment]
lnbc100n1pjq9dmypp50gdepk9920ajcpf8zf32nuzlsg930ch85dgtflescm2ksxh870dqdp2gfjkx6me8gszq4r9wd6zqvfqwajk26eqv4u8q6tj0ycqzpgxqyjw5qrzjqgc2t099trn8g9rqcy7axnnrdk3gu540myw0j0dc0mgmqwf2w3nwhapyqqqqqqqr0qqqqqqqqqqqztqq9qsp5d3npp58uqqrl8ssm0j2vfdj9przy7uveqd78tj9z375qvck2qtms9qyyssqcr0hyngtxandujc9uynt7a7gk4gqtp84x3rtxhgu6ltrpv405qgr74ee6k7nrnvlal4vs0afkwm8t4k89fd4uj346jhu58d3p5zx3tgq3rx3x6

**Comment by saubyk** [comment]
Thanks. Your payment is failing as there is no route to your node (wallet)
Please ensure that your node (wallet) where this invoice has been generated, as enough inbound capacity to be able to receive payments.

![image](https://user-images.githubusercontent.com/39208279/222873980-3cc53403-ecf3-4dbe-9e62-d7e6fdd69170.png)

**Comment by MDIMSMM** [comment]
Hmmm... I'm using the wallet's default lightning node. Should that not be up to the wallet's devs then? I wouldn't know how to fix that. 10 sats can't exactly be over capacity...

**Comment by MDIMSMM** [comment]
With the help of the Blixt devs I finally got my wallet sorted out, so the invoice should work now.

**Comment by MDIMSMM** [comment]
NM... I think it wouldn't work as my channel says it'll take a minimum of $3

**Comment by saubyk** [comment]
tried again from different wallets, still no route. I was also not able to find your wallet's node on the network graph on my node.
There are two more things you can investigate:
1. Are you generating an invoice with 'private' flag as yes?
2. Is there any channel between your wallet's node and a public node which can route payments to you?

![SmartSelect_20230305_102536_Wallet of Satoshi](https://user-images.githubusercontent.com/39208279/222978885-6020b032-f4c9-4313-89ed-872d72c08d10.jpg)
![SmartSelect_20230305_102353_Phoenix](https://user-images.githubusercontent.com/39208279/222978886-813f3404-387e-4ed5-b0a1-9145dfbcc4d7.jpg)

**Comment by MDIMSMM** [comment]
1. I don't know - checking with Blixt devs
2. Is it safe for me to send you a screen shot of node data? I've looked at it and it says "synced to chain: true" and "synced to graph: true". I've also sent a payment from my WoS to this wallet with success.
3. The channel that I managed to open says minimum $3 payment. Could that be why it's not going through? Though I suppose that doesn't explain why you don't see it...

**Comment by MDIMSMM** [comment]
I just spoke to the Blixt devs and they figured it out - I was unaware that with non-custodial lightning wallets mine has to be open to accept payments, and it's normally closed! I'm so sorry about that.

If you want to try the payment, I'll leave my wallet open for a couple of days. If not, no worries and feel free to close this issue. Thanks for all the help! (Hopefully it'll work when its just running in the background)

**Comment by saubyk** [comment]
> I just spoke to the Blixt devs and they figured it out - I was unaware that with non-custodial lightning wallets mine has to be open to accept payments, and it's normally closed! I'm so sorry about that.
> 
> If you want to try the payment, I'll leave my wallet open for a couple of days. If not, no worries and feel free to close this issue. Thanks for all the help! (Hopefully it'll work when its just running in the background)

I tried now. Still no dice. I think we'll need to coordinate real time, when you have app open and I try to pay at the same time.

Will keep the issue open, as we still need to address the issue of showing the error message to the user.

**Comment by MDIMSMM** [comment]
Weird. Ok. I'm on PST. You?

**Comment by saubyk** [comment]
Find me on Twitter or Telegram. I am My2Sats on both.

**Comment by ShahanaFarooqui** [comment]
Fixed with PR #1222.
