### ISSUE TITLE
It is not possible to set the channel fees with CLN

### ISSUE THREAD

**Issue by ekimber** [Ride-The-Lightning/RTL#1213]
**Describe the bug**
Using Core Lightning it is not possible to set channel fees.
This is because the deprecated RPC `setchannelfee` has finally been removed in the latest release.  `setchannel` should be used instead.

**To Reproduce**
1. Try to set the fee on a channel

**Your environment**
RTL 0.13.6-beta
Core Lightning v23.02

**Comment by saubyk** [comment]
Hi @ekimber please update your cl-rest to the latest version (v0.10.2) and it should address the problem.

**Comment by saubyk** [comment]
FYI...
https://github.com/Ride-The-Lightning/c-lightning-REST/releases/tag/v0.10.2
