### ISSUE TITLE
I closed a channel but my on chain funds are not appearing

### ISSUE THREAD

**Issue by Kruwed** [Ride-The-Lightning/RTL#1214]
**Describe the bug**

I closed my channel but my on chain balance never showed up in my wallet.  Also, the channel close transaction created way too many outputs and also reused an address 6 times - a0d6801c934cd81b78eded62a8a9925b67b2d2e8382b102ae382ef80aa39ffaf

**To Reproduce**

That's the funny thing, I closed 2 channels that confirmed in the same block, but I did actually receive the coins from the other channel.  So idk how I got my sats back from one channel but not the other.

**Your environment**
* Version of `RTL`  **0.13.3-beta**
* Version of `lnd`/`core lightning`/`eclair` **Core Lightning basedon-v23.02-1**
* Version of `btcd`, `bitcoind`, or other backend **I'm not sure how to check the version on my BTCPay Server, no version is given under RTL's "Bitcoind config"**
* Browser & browser version **Firefox 111.0**
* Operating system (`uname -a` on *Nix) **Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-105-generic x86_64) on BTCPay Server, Windows 10 on my machine running the browser**

**Comment by saubyk** [comment]
Hi @Kruwed did you force close the channel? If yes, you'd need to wait till your lock time (or CSV delay), before the local balance appear on your wallet. Also, assuming you have more than the dust amount on your local balance when you closed the channel.

**Comment by saubyk** [comment]
Regarding the outputs created and address re-use it's best to open the issue on Core Lightning repo, as RTL just calls a core lightning api to close the channel. They can best advise on what might've happened in your case.

**Comment by Kruwed** [comment]
I did not attempt a force close the channel, I did a cooperative close.  There is a lock time of 539,175,698 on the closing transaction ( a0d6801c934cd81b78eded62a8a9925b67b2d2e8382b102ae382ef80aa39ffaf ), but I can't tell if it applies to my coins or how long that actually lasts.  My channel counterparty, opennode, has already spend their 400k sat share of the channel.

**Comment by Kruwed** [comment]
My 1.6 million sats reappeared in my wallet and I was able to send it out.  All of the outputs remain in bc1qej62dnyw344tjlutswxwgnje46z8wz73uuanc7sjm2sdx4facdjqhusazj however.

**Comment by saubyk** [comment]
recommend creating an issue on core lightning, to investigate these mystery outputs. I have no clue, why these outputs got created.

Curious about your opening channel balance though. Also, did you use coin selection to open this channel?

**Comment by Kruwed** [comment]
When originally opening the channel, I had only one UTXO in my on chain wallet and I created the channel using the full amount of that UTXO.

**Comment by Kruwed** [comment]
Another update:  The UTXOs from this address are now visible/spendable in my RTL client as well - bc1qej62dnyw344tjlutswxwgnje46z8wz73uuanc7sjm2sdx4facdjqhusazj

**Comment by saubyk** [comment]
Hi @Kruwed thanks for the feedback. The feature that you're requesting has to be supported by the underlying implementation first. It would be certainly helpful to understand how those outputs got created and eventually became spendable.
