### ISSUE TITLE
Could not afford to send on-chain transaction even though wallet is funded.

### ISSUE THREAD

**Issue by TowyTowy** [Ride-The-Lightning/RTL#1217]
**Describe the bug**
The bug is that the user is experiencing an error message stating "Could Not Afford 77777sat Using All 0 Available Utxos: 78570sat Short", despite having a funded on-chain wallet with 6+ confirmations.

**To Reproduce**
1. Attempt to send a transaction using the wallet
2. Input the recipient address and amount to send
3. Click on "Send" or "Confirm" button
4. See the error message, in my case: "Could Not Afford 77777sat Using All 0 Available Utxos: 78570sat Short"

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/85077986/231310536-9cb3a6ca-8680-49c2-9433-389866fd09cf.png">

**Your environment**
* Version of `RTL`: [0.13.3]
* Core lightning: [23.02.2]

**Comment by TowyTowy** [comment]
> Hi @TowyTowy I was pondering over this issue last evening, but couldn't find a plausible explanation. Wondering why did you close it? Was the problem resolved somehow?

Hey. Yes the problem went away after enough time. It must have been that the balance I was trying to spend hand't been cleared from the day before. I explicitly checked this and saw that it had 6+ confirmations, so I didn't think that could be the issue. 
So all in all, I was able to transfer the funds out, and the issue wasn't with Ride the lightning, even though I could have wished for a more straight-forward error message :)

**Comment by saubyk** [comment]
ok. good to know that it's resolved now. FWIW, the error message is being returned by core lightning, we are just relaying it to the user. Thanks for the response.
