### ISSUE TITLE
Can't access RTL info on Umbrel

### ISSUE THREAD

**Issue by gcpc1** [Ride-The-Lightning/RTL#1219]
Hi, 

Can anyone help/advise me please?  

Today was first time in a while that I've logged into the RTL app on Umbrel.  I can't see any of my channels and my sats balance is showing as -1, so unsure what's going on.  

I'm seeing "Wallet Locked, Unlock It To Enable Full Rpc Access".  I try to unlock it with the default password but get the message below: 

"Unlock Wallet Failed
Error Code
500
Error Message
Invalid Passphrase For Master Public Key
API URL
./api/lnd/wallet/unlockwallet"   

If I try to "Initialize" the wallet, this message appears: "Warning: Your connection is unsecure, it's not safe to generate private keys over this connection.Are you sure you want to proceed?", so I don't proceed :-) 

Any ideas about what I can do?  FYI I'm a tech noob.

Thanks in advance!

**Comment by saubyk** [comment]
Hi @gcpc1 which Lightning implementation are you working with?  Do you have any channels or funds on Lightning on Umbrel already?

**Comment by gcpc1** [comment]
Hi @saubyk Thanks for your response.  Yes, I have a few channels open & funds on Umbrel.  My node = gcpc on 1ml.com, if that helps.  I logged on today to Ride The Lightning on Umbrel, only to find my sats were showing as -1!

**Comment by saubyk** [comment]
I am assuming you're running LND on umbrel. Have you ever accessed RTL on Umbrel or is it the first time?
Are you running RTL (Core Lightning) or RTL? If the former, you need to uninstall and install the latter. You can find the two different RTLs on the app store, make sure you run the RTL only (as that's the one which works with LND)

**Comment by gcpc1** [comment]
Hi @saubyk, Yes, I’m running LND.  I’ve had the RTL app for approx 20 months and used it many times before.  To confirm: I’ve the RTL app, not RTL Core Lightning.  To be honest, all my Umbrel apps are currently glitchy (for the last week or so) so unsure if there’s something else going on.  I’ve tried resetting Umbrel but glitches still happening.

**Comment by saubyk** [comment]
Hi @gcpc1 in that case, it's better to open an issue with Umbrel, as this is not an issue we can help you with.
If your LND lightning node is working on Umbrel, you should be able to connect to it via RTL, without any issue.

Closing this ticket, as there is no specific action for us to take here. Please reopen in case you get more information, which we need to investigate. Thanks.

**Comment by gcpc1** [comment]
Hi @saubyk Thanks for the info.  I’ll contact Umbrel.  I appreciate your help.  Best wishes.
