### ISSUE TITLE
"Lease UTXO" (LND) appears to be broken 

### ISSUE THREAD

**Issue by theborakompanioni** [Ride-The-Lightning/RTL#1227]
**Describe the bug**
"Lease UTXO" (LND) does not work anymore (no http request is made). Worked with `v0.12.3-beta`, does not work with `v0.13.6-beta`. 

**To Reproduce**
1. Go to 'On-chain' > 'On-chain Transactions' > 'UTXOs' Tab
2. Click on 'Actions' dropdown > 'Lease'
3. A confirmation modal appears
4. Click 'Lease UTXO'

A success alert appears, but the UTXO is not actually leased. In previous version, the UTXO would disappear from the table.
If you go to the network tab in the developer tools, you'll notice that not even an HTTP request is made.

**Your environment**
* Version of `RTL`: `v0.13.6-beta`

**Additional context**
Before creating this ticket, I confirmed that it worked with RTL `v0.12.3-beta`. I did not check any other version between `v0.12.3-beta` and `v0.13.6-beta`.

**Comment by ShahanaFarooqui** [comment]
Closing with #1230

**Comment by theborakompanioni** [comment]
Confirmed working. Thanks for the incredibly speedy fix! :pray:
