### ISSUE TITLE
Update RTL for CLN v23.05 with msat purge

### ISSUE THREAD

**Issue by ShahanaFarooqui** [Ride-The-Lightning/RTL#1231]
Update RTL for CLN v23.05 with msat purge

**Comment by shyfire131** [comment]
> Yes does not seem current RTL version is working with CLN 23.05?

Correct. There was an issue with c-lightning-rest which has been resolved, but I think RTL needs an update too. 
https://github.com/Ride-The-Lightning/c-lightning-REST/issues/168

**Comment by ShahanaFarooqui** [comment]
Closing with PR #1244.
