### ISSUE TITLE
Show Loop version on RTL page

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#1238]
User should have the context of which version of Loop they're running in the UI.
It can be displayed at the top of the page, next to the page label

![Screenshot 2023-05-08 at 9 17 54 PM](https://user-images.githubusercontent.com/39208279/236993026-345bf911-ad3a-44f5-a8fc-e49836522850.png)

**Comment by ShahanaFarooqui** [comment]
@saubyk Please share the API endpoint to get the loop version.
