### ISSUE TITLE
Sats unconfirmed for 22 days

### ISSUE THREAD

**Issue by redOz92** [Ride-The-Lightning/RTL#1239]
https://www.blockchain.com/explorer/transactions/btc/a8484fabc9bfd500e82ea8a0b51a67c1801e180637d23e9ec7f0010758d50a09

I can't use this amount on my Node, it's still unconfirmed I'm getting a little bit worried..

**Comment by saubyk** [comment]
The transaction above has been replaced, and the replaced transaction is confirmed as well
![image](https://github.com/Ride-The-Lightning/RTL/assets/39208279/c4f70d26-e37f-490c-b083-45607af3711a)

**Comment by saubyk** [comment]
No action expected here. Closing this issue.
