### ISSUE TITLE
Active channels are showing as Inactive in channels list

### ISSUE THREAD

**Issue by ShahanaFarooqui** [Ride-The-Lightning/RTL#1240]
Active channels are showing as Inactive in channels list.

**Comment by ShahanaFarooqui** [comment]
Closing with @1241.

**Comment by pabpas** [comment]
For me this has the opposite effect:
RTL Release-0.13.6: channel info looks correct everywhere (dashboard, peers/channels).
RTL on 0.13.7 branch: all channels show as Pending/Inactive. However, the balance of Active channels seem correct and the list of Inactive show them as connected+active.

c-lightning-REST is on current v0.10.3 branch, CLN v23.05

**Comment by ShahanaFarooqui** [comment]
Thank you for testing. I am not yet done testing/updating the code. It should not be the issue once I am done with all the changes. Will confim before release.

**Comment by ShahanaFarooqui** [comment]
> For me this has the opposite effect: RTL Release-0.13.6: channel info looks correct everywhere (dashboard, peers/channels). RTL on 0.13.7 branch: all channels show as Pending/Inactive. However, the balance of Active channels seem correct and the list of Inactive show them as connected+active.

Hi, the msatoshi migration is complete and merged in Release 0.13.7 branch. I verified that connected and active channels should be shown in active tab.

**Comment by pabpas** [comment]
> Hi, the msatoshi migration is complete and merged in Release 0.13.7 branch. I verified that connected and active channels should be shown in active tab.

Now everything looks wonderful. Thanks a lot for fixing this!
