### ISSUE TITLE
BUG: ECL eclair trampoline related routing amounts / fees calculated x1000 too high

### ISSUE THREAD

**Issue by EagleTM** [Ride-The-Lightning/RTL#1251]
With current master (0.14.0) and previously, I've noticed for eclair payments which have the "trampoline-payment-relayed" flag the total amount and fees get represented by a factor 1000 too high when shown in the routing tab and in the total fee report.

The eclair version is eclair-node-0.8.0-0077471 release version from Dec 2022

The fees on the eclair console look fine but I can't find the section in the code which may treat trampoline differently and thus show the fees as too high.

I had assumed
https://github.com/Ride-The-Lightning/RTL/blob/895b1de27d8505d781b1d4c43b9962581da3dcf0/src/app/eclair/store/ecl.reducers.ts#L320

might require an extra line such as:
`` rlEvent.amountIn = Math.round(rlEvent.amountIn / 1000); ``
but that doesn't appear to be it, as it didn't have any effect when i modified it (but maybe I failed to compile it correctly)

**Comment by EagleTM** [comment]
This shows a sample of the too high fees - actually it's not just the fees it's the total amounts that are too high by a factor of x1000

The yellow dot in front of the transaction markt it as "trampoline related"

![ecl-bug-routing-trampoline](https://github.com/Ride-The-Lightning/RTL/assets/2886147/deb0b58c-e83a-4dda-924d-64799e3ef208)

**Comment by ShahanaFarooqui** [comment]
@EagleTM Thank you for raising the issue and debugging it as well. Closing the issue with PR #1301.

Dividing the `amountIn` and `amountOut` by 1000 was the solution. For future reference, `npm run buildfrontend` compiles the frontend Angular code and for development server `npm run start` can be used.
