### ISSUE TITLE
new eclair 0.9.0 release no longer working with RTL

### ISSUE THREAD

**Issue by DerEwige** [Ride-The-Lightning/RTL#1259]
It looks like the new release from eclair (0.9.0) changed some API calls.
RTL can not load most of the information from eclair anymore

**Comment by viaj3ro** [comment]
yeah, I got the same problem and flying blind now. downgrade to eclair 0.8 is not possible since 0.9 already did some backwards incompatible database changes unfortunately.

Would be great, if this could be fixed asap

**Comment by ShahanaFarooqui** [comment]
@DerEwige Thanks for raising the issue. It has been fixed with PR #1293 and will be released with v0.14.1.

However, the change is not backward compatible. Only upgrade to RTL v0.14.1 if Eclair is on >=v0.9.0.
