### ISSUE TITLE
Is a lack of documentation a bug or a feature request?

### ISSUE THREAD

**Issue by dscotese** [Ride-The-Lightning/RTL#1272]
**Describe the bug**
I didn't see any explanation of how to write the config file for Core or Eclair.

**To Reproduce**
1. Install a LN node that isn't LND
2. Install RTL
3. Realize that you need to tell RTL about your node and can't find any info about what the config file should look like to do that.

It has been a long time since I looked at the config file that worked for my Core node and my Eclair node, but I lost access to that machine, so I can't copy the configuration :-(.  Luckily for all the newbies, this means I'm like a newbie who needs documentation on how to indicate the necessary information in the config file to connect RTL to Core and Eclair.

**Comment by saubyk** [comment]
Hi, you can find the directions for the setting up the config files for Core Lightning or Eclair from the main readme page. Linking them here as well:
Core Lightning: https://github.com/Ride-The-Lightning/RTL/blob/master/.github/docs/Core_lightning_setup.md
Eclair: https://github.com/Ride-The-Lightning/RTL/blob/master/.github/docs/Eclair_setup.md
