### ISSUE TITLE
Bug Report: Ride The Lightning - Payment Failure with Core Lightning

### ISSUE THREAD

**Issue by TowyTowy** [Ride-The-Lightning/RTL#1276]
I encountered a payment failure while attempting to send 300,000 SATS to a specified LN wallet using the Ride The Lightning (RTL) interface, which utilizes Core Lightning as its backend. The error message indicates that the payment failed due to running out of routes after 34 attempts.

Error Details:

Error Code: 500
Error Message: Ran Out Of Routes To Try After 34 Attempts: See paystatus
API URL: ./api/cln/payments
Context:
I initiated a payment of 300,000 SATS using the RTL interface with the following details:

Recipient LN Wallet Address: lnbc3m1pjwrl5rpp5e94mev7yc4cdl2re42xuqd7pxm0k2a2lk4ngxytghgndjle5802sdqqcqpjsp5a5rl5lns86yf4pq0e39n670d8txdh5d8dxh82mqy2p5r4d4e8hvq9q7sqqqqqqqqqqqqqqqqqqqsqqqqqysgqmqz9gxqyjw5qrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glcllmpua4z2zsm6cqqqqlgqqqqqeqqjq50sm9zr4ggptawvcvj3cn2jme8qma9p064pdd28qf5veeaajdvzszy6msa0alr7spa62dlqwjpfw6vgzavk4fut8zqd7urw095wvd5sp304q5k

Outbound Liquidity: I have a total of 700,000 SATS in outbound liquidity distributed across 4 channels.

**Your environment**
* [Release v0.14.0-beta](https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.14.0)
* Core Lightning v23.05.2
* Bitcoind 25.0
* Arc (Browser)
* MacOS

**Comment by saubyk** [comment]
Hi @TowyTowy not really a RTL issue. This is an error that you're getting from core lightning.
I can provide you some pointers for better understanding of the issue you're facing, but nothing we or core lightning can do to fix it.

1. The complete path from your node to the destination needs to support the liquidity for the amount you're trying to send. So you may have the overall capacity, it cannot be said for certain for your peers
2. You can try to gain more outbound liquidity with better network peers which can support the size of the payment you're trying to send
3. You can also try to send multiple payments with reduced amounts, if you have that flexibility

Hope this is helpful, thanks.

**Comment by TowyTowy** [comment]
Okay, I appreciate the response!
