### ISSUE TITLE
RTL not work with Eclair 0.9.0

### ISSUE THREAD

**Issue by xbukorg** [Ride-The-Lightning/RTL#1277]
RTL not work with Eclair 0.9.0 because breaking API change in Eclair code

See attached picture and logfile.

[new 1.txt](https://github.com/Ride-The-Lightning/RTL/files/12406140/new.1.txt)
![RTL](https://github.com/Ride-The-Lightning/RTL/assets/60103142/757dd3cb-00f0-457d-8b56-65b5c1aa7b77)

**Comment by xbukorg** [comment]
The fix below solved problem only partially I am thinking.
When I open more channels parallelly I get still empty list.
Please test fix before release new version of RTL.

**Comment by ShahanaFarooqui** [comment]
PR #1293 fixes the issue where Eclair 0.9.0 changed their channel list response. However, the change is not backward compatible. Only upgrade to RTL v0.14.1 if Eclair is on >=v0.9.0.
