### ISSUE TITLE
Core-Lightning - List Channels Error

### ISSUE THREAD

**Issue by mercurytoxic** [Ride-The-Lightning/RTL#1279]
**Describe the bug**
RTL works fine listing peers and payments but fails to list channels, logs show `ERROR: Channels => List Channels Error: {}`

**To Reproduce**
1. Load 127.0.0.1:3000/rtl/cln/home

**Screenshots**

**Your environment**
RTL: v0.14.0-1-gd9eb7eee
core-lightning-git 23.08rc3.r13541.d2e39f7af-1
bitcoin-daemon 25.0-2
https://github.com/Ride-The-Lightning/c-lightning-REST/commit/29de0b08613d4f7866e2c604d09ce25c690bc118
Linux testnet 6.4.11-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 19 Aug 2023 15:38:34 +0000 x86_64 GNU/Linux

`testnet node[1303480]: [8/23/2023, 1:59:32 PM] ERROR: Channels => List Channels Error: {} `
all other queries are successful inluding Peers. payments, fees, etc.

![image](https://github.com/Ride-The-Lightning/RTL/assets/739809/e1f3a002-b1b4-425b-b5a0-1ad7e109d32d)

**Comment by mercurytoxic** [comment]
Can confirm https://github.com/Ride-The-Lightning/RTL/commit/97689638624bed666937a68b9d11347593977bcd fixes issue.

**Comment by ShahanaFarooqui** [comment]
Thanks for opening the issue and confirmation. I am closing the issue now as the fix will be released with v0.14.1.
