### ISSUE TITLE
RTL channels and rate "Unknown Error"

### ISSUE THREAD

**Issue by Globalebill** [Ride-The-Lightning/RTL#1291]
@saubyk @ShahanaFarooqui @NicolasDorier 

After upgrading to BTCPay1.11.6 for the resolution of bug https://github.com/Ride-The-Lightning/c-lightning-REST/issues/199  the RTL front end is now giving errors on the Dashboard, Peers/Channels (peers list loads ok) and Rates pages as per the screen captures below, note: all other pages load with no errors

 
![rtl channels](https://github.com/Ride-The-Lightning/RTL/assets/63942253/2e37ea26-2c6a-42d8-aee9-db3abc8f4b3a)

![rtl dashboard](https://github.com/Ride-The-Lightning/RTL/assets/63942253/870da819-bd53-4323-8a47-6c87cb52050b)

![rtl rates](https://github.com/Ride-The-Lightning/RTL/assets/63942253/c1ab0a30-7ef0-4b43-98a0-d9882dbfbabd)

**Comment by ShahanaFarooqui** [comment]
@Globalebill Can you share logs from c-lightning-REST and RTL?

**Comment by ShahanaFarooqui** [comment]
`listChannels` endpoint is deprecated after CLN 23.02. RTL should call `listPeerChannels` instead. 

As per you last issue, you are on:
saubyk/c-lightning-rest:0.10.5
btcpayserver/lightning:v23.08
shahanafarooqui/rtl:0.14.0

But can you please confirm it in the UI also, like below:

![Screenshot from 2023-09-27 12-29-36](https://github.com/Ride-The-Lightning/RTL/assets/23240721/fa9a5397-bba3-4329-a565-97266e7623bf)

**Comment by Globalebill** [comment]
versions:
shahanafarooqui/rtl:0.14.0
btcpayserver/bitcoin:25.0
saubyk/c-lightning-rest:0.10.6
btcpayserver/lightning:v23.08

btcpay 1.11.6   upgraded from 1.11.5

![rtl version](https://github.com/Ride-The-Lightning/RTL/assets/63942253/52253a84-6ca3-45f6-9d67-0645e3413f9a)

**Comment by ShahanaFarooqui** [comment]
@Globalebill Thank you for raising the issue. It occurred due to Core lightning's version prefix (`basedon`) which has been prefixed by BTCPayServer. RTL expected the version to be starting with `v` only. Updated the regex to filter all prefix and postfix.

The fix will be released with v0.14.1 (hopefully this weekend). Closing the issue now.
