### ISSUE TITLE
Inconsistent sorting between Payments and Invoices pages

### ISSUE THREAD

**Issue by ok300** [Ride-The-Lightning/RTL#1295]
**Describe the bug**

On the Invoices page, the default sorting direction is Descending. Indeed, the top-most rows in the table are the most recent invoices.

On the Payments page, the default sorting direction is also Descending. However, here the top-most entries are the oldest payments on the node.

**To Reproduce**
1. Go to Transactions menu > Invoices
2. Select "Invoices per page" to be low enough that you have your table split across multiple pages
3. Go to the first page of the table
4. Notice that the top-most invoice shown is the **most recent** one on the node
5. Go to Transactions menu > Payments
6. Select "Payments per page" to be low enough that you have your table split across several pages
7. Go to the first page of the table
8. Notice that the top-most payment shown is the **oldest** one on the node

**Your environment**
* Version of `RTL`: v0.14.0-beta
* Version of `lnd`/`core lightning`/`eclair`: LND v0.16.4-beta
* Version of `btcd`, `bitcoind`, or other backend: bitcoind

**Comment by ShahanaFarooqui** [comment]
@ok300 Thank you for raising the issue. It has been fixed with PR #1300 and will be released with version 0.14.1.
