### ISSUE TITLE
Enable opening Taproot Channels for LND

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#1296]
LND v0.17 onwards will have the option to open Taproot channels, which should also be enabled via the RTL channel opening interface, provided the user has LND configured (`protocol.simple-taproot-chans=true`) to open taproot channels.

Openchannel API: https://lightning.engineering/api-docs/api/lnd/lightning/open-channel-sync
The argument to make it happen via the openchannel API is: `commitment_type`=`5`

The flag should be enabled by a toggle on the open channel modal under the `Advanced Options` section.

Currently, the additional argument to open taproot channels is also to set the `private` flag as true, but that should be left for the user to set when they are opening taproot channels. If the user doesn't set the flag, it will return an error which should indicate to the user that channels needs to be "private".

EDIT: updated the API argument for taproot channel

**Comment by ShahanaFarooqui** [comment]
Closing with PR #1305
