### ISSUE TITLE
LN payment history not shown 

### ISSUE THREAD

**Issue by Barba732** [Ride-The-Lightning/RTL#1306]
**Describe the bug**
LN payments history is stucked at a tx on 25th march, there were any tx after it that I can't see on RTL, soon after the tx I see then but a few minutes later they're gone and I see only old ones, like the screenshot bellow.

**Screenshots**
![immagine](https://github.com/Ride-The-Lightning/RTL/assets/146669079/77413e04-45b0-4268-82b1-b0f29ffb4488)

**Your environment**
* Version of `RTL` 0.14.0
* Version of `lnd` 0.17.0
* Version of `btcd`, `bitcoind`, 25
* Browser & browser version firefox 118
* Operating system debian
* any other relevant environment details

**Comment by ShahanaFarooqui** [comment]
@Barba732 approximately how many payments do you have on this node?

**Comment by Barba732** [comment]
Hard to be precise but about 30 missing on RTL

**Comment by ShahanaFarooqui** [comment]
Can you check with `lncli listpayments`, I do not need an exact number.

**Comment by Barba732** [comment]
I can't see them all like that, already tried. I see only the last ones on terminal. But what I see on RTL count is 82 in total

**Comment by ShahanaFarooqui** [comment]
if `listpayments` is not returning payments list then it might be an issue with lnd. 

Also, I tried to reproduce it locally but I am able to see all 350 payments available on my node.

**Comment by Barba732** [comment]
I see all tx on zeus though

**Comment by Barba732** [comment]
I was fixed with the last update to 0.14.1!!!
