### ISSUE TITLE
Post upgrade to 0.14.1 channel details show zero Nov-3-2023

### ISSUE THREAD

**Issue by jairunet** [Ride-The-Lightning/RTL#1323]
**Describe the bug**
After upgrading RTL to version 0.14.1 today Nov-3-2023 after a number of hours the channel details still shows zero sats on the local and remote capacity of the lightning channels.

**To Reproduce**
1. Install update 0.14.1
2. Access RTL UI
3. Select "Lightning" then "peer/channels"
4. See the value on all channels as local and remote "zero"

**Screenshots**
![image](https://github.com/Ride-The-Lightning/RTL/assets/5609312/f0deb8fb-a3cb-4939-92a3-7f1430472882)

![image](https://github.com/Ride-The-Lightning/RTL/assets/5609312/971d535b-67a1-4e9e-be1e-ac7be7ca016e)

**Your environment**
* Version of `RTL 0.14.1`
* Version of `core lightning 23.02.2 2~8 `
* Version of `bitcoind 25.0.0~3`
* Browser & browser version Firefox 119 & Chrome 118
* Operating system (`uname -a` on *Nix) MAC OS Ventura | `5.15.0-86-generic #96~20.04.1-Ubuntu SMP Thu Sep 21 13:23:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
* any other relevant environment details

**Additional context**
I have not try to restart the node yet. Should I try that?

**Comment by ShahanaFarooqui** [comment]
@jairunet This RTL version is not compatible with CLN 23.02 as mentioned in the release below:

https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.14.0

`Core Lightning users should note that this update depends on cl-rest v0.10.3 and Core Lightning v23.05. If you are running any version older than 23.05, you should not upgrade to this UI. The changes are not backwards compatible with older versions of Core Lightning`

Either downgrade RTL to <0.14.0 or Upgrade CLN to v23.05 & c-lightning-rest to v0.10.3.

Closing the issue now but please feel free to comment if issue still persists are following above instructions.

**Comment by jairunet** [comment]
Hello @ShahanaFarooqui ,

Thank you for the clarification and my apologies for missing that detail, I did not read the release notes for the RTL version 0.14.0 I will proceed with the recommendations or just hold until startOS (the implementation I am currently using) upgrade CLN to version 23.05 before trying to install RTL again.

Thank you again for all the Proof of Work!
