### ISSUE TITLE
RTL no longer works with new eclair version 0.10.0

### ISSUE THREAD

**Issue by DerEwige** [Ride-The-Lightning/RTL#1361]
If you connect RTL to an eclair with version 0.10.0 some sections will not load (see screenshots)

![image](https://github.com/Ride-The-Lightning/RTL/assets/6146383/d46803d2-cd8b-427c-8622-7e39bcab0108)
![image](https://github.com/Ride-The-Lightning/RTL/assets/6146383/53d74031-8372-4e4a-97d3-8a022968e692)

I assume the reason for this is the change of one field.
The field "timestamp" was replaced by two new fields "startedAt" and "settledAt".
I guess "startedAt" should always have data, but settledAt might be empty or missing if a payment/relay is not yet settled.

Also old payments from before the upgrade will still show the old field

**Comment by ShahanaFarooqui** [comment]
Closing with #1363.
