### ISSUE TITLE
Block opening of channels with rate of 1 sat/vbyte if mempool fee rates are high

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#1368]
RTL should check the mempool fee rates when user is submitting an open channel request and fail submission if the minimum fee rate returned by the mempoolspace api (`minimumFee`) is higher than the rate specified by the user

user should get an error: `Specified fee rate is lower than the minimum prevailing fee rate in the mempool`

mempool.space API: https://mempool.space/docs/api/rest#get-recommended-fees

Compare the user specified fee rate with the value of `minimumFee` in the api response

**Comment by ShahanaFarooqui** [comment]
Closing with #1388.
