### ISSUE TITLE
HELP missing on-chain funds!

### ISSUE THREAD

**Issue by uskrusader** [Ride-The-Lightning/RTL#1395]
I recently sent from RTL onchain to another RTL onchain. While upgrading to a new start9 node.

I sent the funds from my old node (RTL) to a new TAPROOT (P2TR) address generated by my new RTL on start9.

The transaction is confirmed but I'm not seeing the funds.  IS THERE a way to see the receive addresses that I previously generated on RTL?!

I can see the address it went to, but I cannot verify if I generated it.
I need to see if I somehow made an error in the copy/pasting of address.

I'm feeling pretty sick about this right now.  Thanks for any help.

**Comment by saubyk** [comment]
Hi @uskrusader my guess is your new start9 node is not done syncing to the chain yet. When it's done syncing you'll be able to see your funds.

**Comment by saubyk** [comment]
hmm...ok, if it's a LND node, you can get the list of addresses generated by running this command on the terminal:
`lncli wallet addresses list`

Also, have you tried restarting your node?

**Comment by uskrusader** [comment]
$ lncli wallet addresses list

Will that work for seeing onchain addresses?

It will take me a bit.  I don't think a start9 server gives direct access to the command line by default.  I think I still need to add SSH keys for remote access

**Comment by saubyk** [comment]
> Will that work for seeing onchain addresses?

That's what this command is for

**Comment by uskrusader** [comment]
Restart did it!!!!
Weird because it really looked like everything was connected and functioning fine.  Sorry for the panic.

I've been doing this for awhile, but I'm obviously new to start9

Restart seems like obviously solution for newbs lol.  I'm humbled

I'll close this out.
