### ISSUE TITLE
multiple error at first run 

### ISSUE THREAD

**Issue by ElucGeek** [Ride-The-Lightning/RTL#1398]
**Describe the bug**
At first run I get: SyntaxError: Unexpected string in JSON at position 406.

**To Reproduce**
after fresh install and config file prepared.
in the RTL folder I do: node rtl
Get a SyntaxError

**Screenshots**
```
[5/26/2024, 8:34:57 PM] ERROR: Config => Something went wrong while configuring the node server: 
SyntaxError: Unexpected string in JSON at position 406.

file:///home/rtl/RTL/backend/utils/config.js:369
                throw new Error(err);
                      ^

Error: SyntaxError: Unexpected string in JSON at position 406
    at ConfigService.setServerConfiguration (file:///home/rtl/RTL/backend/utils/config.js:369:23)
    at new ConfigService (file:///home/rtl/RTL/backend/utils/config.js:372:14)
    at file:///home/rtl/RTL/backend/utils/config.js:375:23
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12)
```

**Your environment**
* RTL 0.15.0
* cln 24.02.2
* bitcoind 27.0
* Browser & browser version
* Operating system Linux 5.15.0-107-generic #117-Ubuntu SMP

**Additional context**
I did install with npm install --omit=dev then I did npm audit and npm audit fix for the warning and error but couldn't remove all of them.
I remove RTL and redownload and retry several time, always this error (or similar).

Is it my config file? the way I install? something else?

**Comment by ShahanaFarooqui** [comment]
The issue seems to be from your RTL-config.json. Is it valid json?

**Comment by ElucGeek** [comment]
> The issue seems to be from your RTL-config.json. Is it valid json?

Ok thanks for the help, I tried everything to fix the RTL-config.json but in the end I start it from scratch from the example and now it works. Probably just one character was wrong but I couldn't figue out where.

Now I have a 404 error an error "Please check the server connection" when I login to RTL. I'm trying to investigate, I will open a separate issue if needed, now I close this one.
