### ISSUE TITLE
Error 404 when I login

### ISSUE THREAD

**Issue by ElucGeek** [Ride-The-Lightning/RTL#1405]
**Describe the bug**
I have a problem to connect RTL to my CLN. I setup the rune, it looks like working first but when I login on the webUI, I get a 404 error. In the log it's not helping much:

`ERROR: GetInfo => Get Info Error: {"name":"StatusCodeError","statusCode":404,"message":"404 - \"<!DOCTYPE html>\\n<html lang=\\\"en\\\">\\n<head>\\n<meta charset=\\\"utf-8\\\">\\n<title>Error</title>\\n</head>\\n<body>\\n<pre>Cannot POST /v1/getinfo</pre>\\n</body>\\n</html>\\n\"","error":"404 - \"<!DOCTYPE html>\\n<html lang=\\\"en\\\">\\n<head>\\n<meta charset=\\\"utf-8\\\">\\n<title>Error</title>\\n</head>\\n<body>\\n<pre>Cannot POST /v1/getinfo</pre>\\n</body>\\n</html>\\n\"","options":{"url":"https://localhost:3001/v1/getinfo","rejectUnauthorized":false,"json":true,"headers":{"rune":"XXXXXXXXXXXXXXXXXXXXXXXXXXXX=="},"method":"POST","qs":{},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":404,"body":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /v1/getinfo</pre>\n</body>\n</html>\n","headers":{"x-powered-by":"Express","access-control-allow-origin":"*","access-control-allow-headers":"Origin, X-Requested-With, Content-Type, Accept, Authorization, filePath, macaroon, encodingtype","access-control-allow-methods":"GET, POST, PATCH, PUT, DELETE, OPTIONS","content-security-policy":"default-src 'none'","x-content-type-options":"nosniff","content-type":"text/html; charset=utf-8","content-length":"150","date":"Thu, 06 Jun 2024 19:53:37 GMT","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"localhost:3001","port":"3001","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/v1/getinfo","path":"/v1/getinfo","href":"https://localhost:3001/v1/getinfo"},"method":"POST","headers":{"rune":"XXXXXXXXXXXXXXXXXXXXXXXXX==","accept":"application/json","content-length":0}}}}
`

**To Reproduce**
1. login to RTL

My RTL config:
`{
  "port": "3000",
  "defaultNodeIndex": 1,
  "dbDirectoryPath": "/home/rtl/rtl-db",
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "mynode",
      "lnImplementation": "CLN",
      "Authentication": {
        "runePath": "/home/rtl/rune-fullaccess",
        "configPath": "/home/lightning/.lightning/config"
      },
      "Settings": {
        "userPersona": "OPERATOR",
        "themeMode": "NIGHT",
        "themeColor": "PURPLE",
        "channelBackupPath": "/home/rtl/backup-rtl",
        "logLevel": "DEBUG",
        "lnServerUrl": "https://localhost:3001",
        "fiatConversion": false,
        "unannouncedChannels": false
      }
    }
  ],
`

**Screenshots**
none

**Your environment**
* Version of `RTL` 0.15.0
* Version of cln 24.02.2
* Version of  `bitcoind` 27.0
* Browser & browser version Firefox 125.0.2
* Operating system (`uname -a` on *Nix) Linux 6.8.0-35-generic

**Additional context**
Any clue were is the problem comes form? My config file? CLN config?

**Comment by ShahanaFarooqui** [comment]
Seems like the rune is incorrect or not saved in the file in correct format (eg. LIGHTNING_RUNE="mRX...24j").

**Comment by ElucGeek** [comment]
> Seems like the rune is incorrect or not saved in the file in correct format (eg. LIGHTNING_RUNE="mRX...24j").

It's exactly that:
`LIGHTNING_RUNE="XXXXXXXXXXXXXXXXXXXXX=="`
That's the content of the file /home/rtl/run-fullaccess which is read only for user rtl only which is running rtl.
Other clue? Is it the c-lightning-REST which is messing up? I cannot have both c-lightning-REST and CLNrest in CLN? In RTL I configured only the rune, so it should be ok, right?

**Comment by ShahanaFarooqui** [comment]
c-lightning-REST could not be the problem. Both c-lightning-REST and CLNRest can run on the same node without any issue. 

For RTL, you only need runePath, no more macaroonPath for CLN.

Can you check if you are using a valid rune ([showrunes](https://docs.corelightning.org/reference/lightning-showrunes) or [decode](https://docs.corelightning.org/reference/lightning-decode))?

Did you update your lnServerUrl from older c-lightning-REST's url with the new clnrest's server url?

**Comment by ElucGeek** [comment]
> c-lightning-REST could not be the problem. Both c-lightning-REST and CLNRest can run on the same node without any issue.
> 
> For RTL, you only need runePath, no more macaroonPath for CLN.
> 
> Can you check if you are using a valid rune ([showrunes](https://docs.corelightning.org/reference/lightning-showrunes) or [decode](https://docs.corelightning.org/reference/lightning-decode))?
> 
> Did you update your lnServerUrl from older c-lightning-REST's url to the new clnrest's server url?

This is my rune (without the secret of course):

`{
   "runes": [
      {
         "rune": "djdkjdkj..SECRET...dkjdkj==",
         "unique_id": "0",
         "restrictions": [],
         "restrictions_as_english": ""
      }
   ]
}
`
Looks good to me, no?

I was wondering if it has something to do with port, should I set a different port for CLNrest in my CLN config?
I have this:
`# REST Server
rest-port=3001
rest-docport=4001
rest-protocol=https
`
Is there something else needed for the CLNrest rune (this naming is so confusing to me).

**Comment by ElucGeek** [comment]
Ok I manager to solve it as follow:
1) I install the following missing dependencies as the user running lighting:
`pip3 install --user flask-cors flask_restx pyln-client flask-socketio gevent gevent-websocket`
2) I added these lines to the lightning config file
`clnrest-port=3010

clnrest-host=0.0.0.0

clnrest-prototcol=https
`
Note that the clnrest-host might not be necessary, I guess it's for external access but not 100% sure. you can try to remove it if you don't need external access.

3) I changed the port in the config file of RTL:
`"lnServerUrl": "https://localhost:3010",`

I restarted cln and rtl, and both are running.

Now I can login to RTL and see my node, generate on-chain address, open a channel...
