### ISSUE TITLE
2 empty spaces before pkey when pasting on connect to a new node fields

### ISSUE THREAD

**Issue by ghost** [Ride-The-Lightning/RTL#1422]
**To Reproduce**
1. Go to peers>add peers>paste lightning address and see two empy spaces before the address

**Comment by ShahanaFarooqui** [comment]
Text pasted from the clipboard is inserted exactly as copied, including any leading or trailing spaces. Therefore, if the copied text includes spaces, they will appear in the pasted result.

Closing the issue now.
