### ISSUE TITLE
Inconsistent docker image tag for 0.15.2

### ISSUE THREAD

**Issue by Misza13** [Ride-The-Lightning/RTL#1426]
Release 0.15.2 has been inconsistently tagged on [Docker Hub](https://hub.docker.com/r/shahanafarooqui/rtl/tags) as `v0.15.2`, breaking the convention by including a "`v`" in the tag name.

Not sure if this was intentional or just a result of the release process not being entirely automated. It's certainly a minor thing but it broke my flow and might break any update scripts out there that look for releases on GitHub and assume that the Docker tag will be the same.

**Comment by ShahanaFarooqui** [comment]
Hey, sorry for the inconvenience. We mentioned it in the release notes https://github.com/Ride-The-Lightning/RTL/releases.

It was intentional and it will be consistently including "v" in future tags also.
