### ISSUE TITLE
New Umbrel install, no idea what the password is.

### ISSUE THREAD

**Issue by vistajadez** [Ride-The-Lightning/RTL#1428]
I am running this on Umbrel. I install the app, open it, and I am immediately asked for my "password." I was never given one, and there is no option to set one up. Help?

**Comment by saubyk** [comment]
Hi @vistajadez you can find the password for the app on the app page in the Umbrel App Store:
![image](https://github.com/Ride-The-Lightning/RTL/assets/39208279/433e0fe5-fa78-483e-8821-9274e313c560)

**Comment by vistajadez** [comment]
Hi, thanks for getting back to me. However, don't see any password:
<img width="1240" alt="image" src="https://github.com/Ride-The-Lightning/RTL/assets/3536817/0664b877-8b6d-4e65-a628-00ea7dec1992">

**Comment by saubyk** [comment]
There are two versions of RTL on Umbrel, one for LND and another for Core Lightning. Make sure you're looking at the app page for the one you have installed

If that doesn't help, please reach out to Umbrel support. They will be able to guide you better

**Comment by vistajadez** [comment]
Thanks, I found the password; it's further down in the app store page than the "Open" button, I just didn't see it:
<img width="403" alt="image" src="https://github.com/Ride-The-Lightning/RTL/assets/3536817/d1edea90-81e9-429c-a2e2-10d31fb774f2">
