### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by themax55** [Ride-The-Lightning/RTL#1431]
Just installed RTL and is asking for a password. What password do i use?

**Comment by saubyk** [comment]
Hi @themax55 have you installed on your own or on a node setup like Umbrel?

If its your own install, default password is "password", which you'd need to change after login
If its on Umbrel, you can find the password somewhere on the app page of their app store

**Comment by themax55** [comment]
> Hi @themax55 have you installed on your own or on a node setup like Umbrel?
> 
> If its your own install, default password is "password", which you'd need to change after login If its on Umbrel, you can find the password somewhere on the app page of their app store

Thanks for your reply Suheb! Installed on node setup Umbrel. But I found the password. Now i´m searching how to change the password...Would be very happy when you can help me with a hint to find that. :-)

**Comment by saubyk** [comment]
> > Hi @themax55 have you installed on your own or on a node setup like Umbrel?
> > If its your own install, default password is "password", which you'd need to change after login If its on Umbrel, you can find the password somewhere on the app page of their app store
> 
> Thanks for your reply Suheb! Installed on node setup Umbrel. But I found the password. Now i´m searching how to change the password...Would be very happy when you can help me with a hint to find that. :-)

Umbrel has a specific password functionality as they generate unique passwords for the app, which I believe is derived from the node's seed deterministically (I may be wrong on the specifics here). So the change password feature is not enabled there. You should use the password generated by their App Store.

**Comment by saubyk** [comment]
Another thing to keep in mind is that we're working on a single sign-on solution with Umbrel, which should be available in the next release. This will simplify your sign-on UX significantly, not requiring to copy paste passwords from the app page etc.

So stay tuned for that. Closing this issue now. Thanks

**Comment by themax55** [comment]
Thanks for your help Suheb!
