### ISSUE TITLE
Unable to disable offer

### ISSUE THREAD

**Issue by pycanis** [Ride-The-Lightning/RTL#1433]
**Describe the bug**
Clicking on "Disable Offer" button doesn't work. Error in console: `Unknown command 'disableOffer'`.

**Your environment**
* Version of `RTL`: v0.15.2-beta
* Version of `core lightning`: v24.05-modded
* Version of `bitcoind`: Satoshi:24.0.1

**Comment by ShahanaFarooqui** [comment]
Closing with #1451.
