### ISSUE TITLE
404 error `Unknown Command 'delexpiredinvoice'` when trying to delete expired invoices using CLN

### ISSUE THREAD

**Issue by Javihache** [Ride-The-Lightning/RTL#1444]
Deleting expired invoices on RTL with CLN doesn't seem to work.

1. Go to Transactions
2. Click on Delete Expired Invoices
3. Confirm

<img width="1030" alt="Screenshot 2024-10-01 at 13 37 14" src="https://github.com/user-attachments/assets/a83e62aa-bce4-47a2-8773-17b65174362c">

Environment
Latest RTL on Core Lightning v24.08.1-modded
Ubuntu 24.04

I actually can't seem to find 'delexpiredinvoice' in the API reference of Core Lightning. Is it possible that this function only exists in LND implementation?

**Comment by saubyk** [comment]
> I actually can't seem to find 'delexpiredinvoice' in the API reference of Core Lightning. Is it possible that this function only exists in LND implementation?

LND doesn't have a feature like this. Need to figure out if the API has been discontinued and replaced with something else. This is an important feature and shouldn't be pulled.

**Comment by ShahanaFarooqui** [comment]
`deleteexpiredinvoice` has been deprecated in CLN v22.11 (EoL v24.02), I forgot to update it with `autoclean-once` :(.
