### ISSUE TITLE
Lost funds when restoring channels from backup

### ISSUE THREAD

**Issue by umpahpah67** [Ride-The-Lightning/RTL#1446]
Hi, I have set up a new node and backed up the Lightning channels from my old node using RTL. I then restored the backup file of my new node via RTL. Restore force closed the channels and recovered the funds. So far, so good.
But then RTL made a transaction with the recovered funds to two different addresses without rebuilding the channels. Result: The channel fund is gone and I have lost my channels.
Why is RTL sending the transactions without creating new channels? I am using RTL v 0.14.1-beta on my new node.
![Transaction](https://github.com/user-attachments/assets/3d082c4e-b46b-4212-ba42-6f5ea25f8e1b)

**Comment by saubyk** [comment]
Hi @umpahpah67 given what you have shared on this issue, there seems to be a profound misunderstanding of how channel backups work. Let me try to break it down:

1. The objective of channel backup is to provide an option to recover the funds you have in your channels **onchain**, in case you lose your node somehow. It will **not** restore your channels. There is no "rebuilding" of channels. When you recover, all your channels are force closed to recover the funds.
2. To initiate this recovery, you need to recover the node first i.e. initiate the node from its original backup seed. You **cannot** recover the funds of your old node on a new node.

To address other items you mentioned...
Most important, RTL **does not** make any transactions on its own, it's either initiated by you on the UI or actions taken by the underlying node.

Please advise the following to investigate further:
1. What version of LND are you running?
2. What's the transaction id of the transactions you posted above? Cannot advise on the actions taken by the node without looking at the onchain transaction history

**Comment by umpahpah67** [comment]
Hi saubyk, thanks for the quick reply. As you described, I built the new node from the backup seed of my Lightning wallet, which worked fine.

I then imported the backup file into RTL, after which the channels were force closed. But I don't understand who/what initiated the second transaction.

I'm running the LND-version 0.17.2-beta

The transaction id of the first transaction (13:12) is:
0681d4b642af6204bc2e475c6865e8f12363cb7f82b22aae37f9ec66898f2bf1

The transaction id of the second transaction (15:03) is:
8c7fcbe26bc3c91f69225d5c7982bd914d4140f986847ee1c9839931ea6fbdda

**Comment by saubyk** [comment]
> The transaction id of the first transaction (13:12) is:
> 0681d4b642af6204bc2e475c6865e8f12363cb7f82b22aae37f9ec66898f2bf1

https://mempool.space/tx/0681d4b642af6204bc2e475c6865e8f12363cb7f82b22aae37f9ec66898f2bf1
The first transaction is the sweeping of the funds from the channel force closes on your node.

> The transaction id of the second transaction (15:03) is:
> 8c7fcbe26bc3c91f69225d5c7982bd914d4140f986847ee1c9839931ea6fbdda

https://mempool.space/tx/8c7fcbe26bc3c91f69225d5c7982bd914d4140f986847ee1c9839931ea6fbdda
Unclear what this transaction is. It doesn't seem like a channel open as well (from autopilot).
Couple of questions to look into it further:
Did you do any onchain transfer from your node after the recovery?
Do you see any new channels open on your node?
What's the wallet balance on your node now?
Also, can you share the content of the lnd.conf on the new node (do mask any sensitive info there in)?

**Comment by saubyk** [comment]
correction on the above, it seems to be a channel open transaction. The answers to the following questions should help solve the mystery...
1. current onchain balance which should include a utxo of 24436 sats
2. Any open channel with a local balance of 65940 sats

![image](https://github.com/user-attachments/assets/8f71f747-0599-4413-a351-4c278b54a595)

**Comment by umpahpah67** [comment]
> Couple of questions to look into it further:
> Did you do any onchain transfer from your node after the recovery?

No, I haven't done any onchain transfers.

> Do you see any new channels open on your node?

No, there are no open or new channels (see screenshot)

> What's the wallet balance on your node now?

The wallet has a balance of 20.000 sats. This ist the same balance as before the forced close.

To your additional questions: 

> current onchain balance? (which should include a utxo of 24436 sats)

No, as you can see on the screenshot, the balance was - and still is - 20,000 sats.

> Any new open channel with a local balance of 65940 sats?

No, there are no open channels
![Channels](https://github.com/user-attachments/assets/35e6c697-1847-43d0-975a-cf6e267363cb)

**Comment by umpahpah67** [comment]
content of the lnd.conf:

# lnd configuration
# /home/bitcoin/.lnd/lnd.conf

[Application Options]
maxpendingchannels=5
alias=xxx
color=#68F442

acceptortimeout=30s

rpclisten=0.0.0.0:10009
restlisten=0.0.0.0:10080

tlsextraip=0.0.0.0
tlsextradomain=mynode.local

debuglevel=info
#debuglevel=debug

# This line needs to be uncommented if you have a lnd wallet and commented if you do not
wallet-unlock-password-file=/mnt/hdd/mynode/settings/.lndpw
wallet-unlock-allow-create=true

ignore-historical-gossip-filters=true
accept-keysend=true
accept-amp=true
caches.channel-cache-size=35000

[Bitcoin]
bitcoin.active=1

# enable either testnet or mainnet
bitcoin.mainnet=1
bitcoin.testnet=0

bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=127.0.0.1:8332

[autopilot]
#autopilot.active=1
#autopilot.maxchannels=5
#autopilot.allocation=0.6

[healthcheck]
; Number of attempts before failure
healthcheck.chainbackend.attempts=3
; Timeout for a single healthcheck attempt
healthcheck.chainbackend.timeout=30s
; The amount of time we should backoff between failed attempts
healthcheck.chainbackend.backoff=30s
; How often should chain backend checks occur
healthcheck.chainbackend.interval=5m

[bolt]
db.bolt.auto-compact=true

[routing]
routing.strictgraphpruning=true

[rpcmiddleware]
rpcmiddleware.enable=true
rpcmiddleware.intercepttimeout=5s


[Watchtower]
watchtower.active=1


[Wtclient]
wtclient.active=1


[Application Options]
# No NAT if IPv4 is set to off
nat=false

# Tor-only by default
listen=localhost
[Tor]
tor.active=true
tor.v3=true
tor.streamisolation=true


[Application Options]
tlsextradomain=xxx.onion
tlsextradomain=host.docker.internal

**Comment by saubyk** [comment]
have you restarted your node, after performing the recovery operation?

**Comment by umpahpah67** [comment]
I was not quite sure, so I did a restart of the node now - no effect.

**Comment by ziggie1984** [comment]
can you access your node without RTL, meaning via the `lncli` tool ?

**Comment by ziggie1984** [comment]
is the lnd node fully synced, I have the feeling that something did not update, because those 20k sats you now see are not available and prob. result from the anchor reserve you have to keep as a response because you opened 2 channels.

**Comment by umpahpah67** [comment]
The node and the Lightning wallet are fully synced and I can edit the node configuration directly/manually.
I have since updated my node to the latest releases as you can see in the screenshot.

On my old node I also had the 20k sats as on-chain balance and this is the same on the new node. It is noticeable that only the 91,089 sats from the channel backup were sent automatically (i.e. without me doing any transaction) to two new addresses.

![Node-Status](https://github.com/user-attachments/assets/b2c6d351-ca98-4d24-b651-cbeb5ff1efae)
![Lightning Status](https://github.com/user-attachments/assets/168c4a1f-519a-4fd5-8aeb-ebb9b3d1c692)

**Comment by saubyk** [comment]
can you paste the output of `lncli getinfo` from the terminal?

**Comment by umpahpah67** [comment]
{
    "version":  "0.18.3-beta commit=v0.18.3-beta",
    "commit_hash":  "d72a3aaf261e278fa4aad5be4453df2f74ab50ee",
    "identity_pubkey":  "xxx",
    "alias":  "xxx",
    "color":  "#68f442",
    "num_pending_channels":  0,
    "num_active_channels":  0,
    "num_inactive_channels":  0,
    "num_peers":  4,
    "block_height":  865626,
    "block_hash":  "000000000000000000004888ff87cbbdeb71cede0bd93f97cc9ae7b69c17a040",
    "best_header_timestamp":  "1728924087",
    "synced_to_chain":  true,
    "synced_to_graph":  true,
    "testnet":  false,
    "chains":  [
        {
            "chain":  "bitcoin",
            "network":  "mainnet"
        }
    ],
    "uris":  [
        "xxx.onion:9735"
    ],
    "features":  {
        "0":  {
            "name":  "data-loss-protect",
            "is_required":  true,
            "is_known":  true
        },
        "5":  {
            "name":  "upfront-shutdown-script",
            "is_required":  false,
            "is_known":  true
        },
        "7":  {
            "name":  "gossip-queries",
            "is_required":  false,
            "is_known":  true
        },
        "8":  {
            "name":  "tlv-onion",
            "is_required":  true,
            "is_known":  true
        },
        "12":  {
            "name":  "static-remote-key",
            "is_required":  true,
            "is_known":  true
        },
        "14":  {
            "name":  "payment-addr",
            "is_required":  true,
            "is_known":  true
        },
        "17":  {
            "name":  "multi-path-payments",
            "is_required":  false,
            "is_known":  true
        },
        "23":  {
            "name":  "anchors-zero-fee-htlc-tx",
            "is_required":  false,
            "is_known":  true
        },
        "25":  {
            "name":  "route-blinding",
            "is_required":  false,
            "is_known":  true
        },
        "27":  {
            "name":  "shutdown-any-segwit",
            "is_required":  false,
            "is_known":  true
        },
        "30":  {
            "name":  "amp",
            "is_required":  true,
            "is_known":  true
        },
        "31":  {
            "name":  "amp",
            "is_required":  false,
            "is_known":  true
        },
        "45":  {
            "name":  "explicit-commitment-type",
            "is_required":  false,
            "is_known":  true
        },
        "55":  {
            "name":  "keysend",
            "is_required":  false,
            "is_known":  true
        },
        "263":  {
            "name":  "bolt-11-blinded-paths",
            "is_required":  false,
            "is_known":  true
        },
        "2023":  {
            "name":  "script-enforced-lease",
            "is_required":  false,
            "is_known":  true
        }
    },
    "require_htlc_interceptor":  false,
    "store_final_htlc_resolutions":  false
}

**Comment by ziggie1984** [comment]
can you verify with `lncli closedchannels` that you see the old channels resolved ?

**Comment by ziggie1984** [comment]
is the pubkey of your node the old pubkey before you started the SCB ?

**Comment by umpahpah67** [comment]
lncli closedchannels:

{
    "channels":  [
        {
            "channel_point":  "3cef305c9eda155601e5c83efac2a4d0b0a0832cc04f38ea32a1d3b1ce88a346:1",
            "chan_id":  "925431449425084417",
            "chain_hash":  "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
            "closing_tx_hash":  "8196b7503cab02614f9ce2a446c1dd2c35075203f531303a87c4638ea2a8d97e",
            "remote_pubkey":  "0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266",
            "capacity":  "34501",
            "close_height":  864423,
            "settled_balance":  "32416",
            "time_locked_balance":  "0",
            "close_type":  "REMOTE_FORCE_CLOSE",
            "open_initiator":  "INITIATOR_LOCAL",
            "close_initiator":  "INITIATOR_REMOTE",
            "resolutions":  [
                {
                    "resolution_type":  "COMMIT",
                    "outcome":  "CLAIMED",
                    "outpoint":  {
                        "txid_bytes":  "7ed9a8a28e63c4873a3031f5035207352cddc146a4e29c4f6102ab3c50b79681",
                        "txid_str":  "8196b7503cab02614f9ce2a446c1dd2c35075203f531303a87c4638ea2a8d97e",
                        "output_index":  1
                    },
                    "amount_sat":  "32416",
                    "sweep_txid":  "0681d4b642af6204bc2e475c6865e8f12363cb7f82b22aae37f9ec66898f2bf1"
                }
            ],
            "alias_scids":  [],
            "zero_conf_confirmed_scid":  "0"
        },
        {
            "channel_point":  "bb606769c0cdc4397b78f3fe9ba389813f1de6d06864661f33a765a96dfd4af1:1",
            "chan_id":  "923569976164876289",
            "chain_hash":  "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
            "closing_tx_hash":  "39a8213cdfe4ba368cdab7bd5c5888d2fc059b397f01e37521aed67a8a0e7747",
            "remote_pubkey":  "027537449dbaf56360c2157a605637ee1c594a3c21c67f66059007c7e7493a842e",
            "capacity":  "71315",
            "close_height":  864423,
            "settled_balance":  "59249",
            "time_locked_balance":  "0",
            "close_type":  "REMOTE_FORCE_CLOSE",
            "open_initiator":  "INITIATOR_LOCAL",
            "close_initiator":  "INITIATOR_REMOTE",
            "resolutions":  [
                {
                    "resolution_type":  "COMMIT",
                    "outcome":  "CLAIMED",
                    "outpoint":  {
                        "txid_bytes":  "47770e8a7ad6ae2175e3017f399b05fcd288585cbdb7da8c36bae4df3c21a839",
                        "txid_str":  "39a8213cdfe4ba368cdab7bd5c5888d2fc059b397f01e37521aed67a8a0e7747",
                        "output_index":  3
                    },
                    "amount_sat":  "59249",
                    "sweep_txid":  "0681d4b642af6204bc2e475c6865e8f12363cb7f82b22aae37f9ec66898f2bf1"
                }
            ],
            "alias_scids":  [],
            "zero_conf_confirmed_scid":  "0"
        }
    ]
}

**Comment by umpahpah67** [comment]
In the URI, the public key before the @ remains the same, but the socket behind it changes.

**Comment by ziggie1984** [comment]
could you do:

```
lncli listchaintxn
```

and check whether you can find the following transaction:

`8c7fcbe26bc3c91f69225d5c7982bd914d4140f986847ee1c9839931ea6fbdda`

**Comment by umpahpah67** [comment]
Yes, this is the first entry:

{
    "transactions":  [
        {
            "tx_hash":  "8c7fcbe26bc3c91f69225d5c7982bd914d4140f986847ee1c9839931ea6fbdda",
            "amount":  "-91089",
            "num_confirmations":  1252,
            "block_hash":  "000000000000000000007b4b1c20f50cef4ccf2096963b47440557441d80d1cc",
            "block_height":  864441,
            "time_stamp":  "1728219829",
            "total_fees":  "713",
            "dest_addresses":  [
                "bc1p6l2vg50wcwmytf0da54wrua6a64svcc08ptaqyqeypp0vezlgjps6ck7c8",
                "bc1qv53t9gmrefnhwuwzs6vxgaa7yh6482kej43w5aqrxpg92f0srpnsjm3gq8"
            ],
            "output_details":  [
                {
                    "output_type":  "SCRIPT_TYPE_WITNESS_V1_TAPROOT",
                    "address":  "bc1p6l2vg50wcwmytf0da54wrua6a64svcc08ptaqyqeypp0vezlgjps6ck7c8",
                    "pk_script":  "5120d7d4c451eec3b645a5eded2ae1f3baeeab06630f3857d010192042f6645f4483",
                    "output_index":  "0",
                    "amount":  "24436",
                    "is_our_address":  false
                },
                {
                    "output_type":  "SCRIPT_TYPE_WITNESS_V0_SCRIPT_HASH",
                    "address":  "bc1qv53t9gmrefnhwuwzs6vxgaa7yh6482kej43w5aqrxpg92f0srpnsjm3gq8",
                    "pk_script":  "00206522b2a363ca677771c286986477be25f553aad99562ea740330505525f01867",
                    "output_index":  "1",
                    "amount":  "65940",
                    "is_our_address":  false
                }
            ],
            "raw_tx_hex":  "02000000000101f12b8f8966ecf937ae2ab2827fcb6323f1e865685c472ebc0462af42b6d4810600000000000000000002745f000000000000225120d7d4c451eec3b645a5eded2ae1f3baeeab06630f3857d010192042f6645f448394010100000000002200206522b2a363ca677771c286986477be25f553aad99562ea740330505525f018670140c59c3fa0d323c29ffa3e8a275644a95e757614d898af1ce980cdb4a9a968b384e38e3a5f34e0a20c1f6b4147a7c89af545fc263a5bc9d39a5df822290a2d957f00000000",
            "label":  "",
            "previous_outpoints":  [
                {
                    "outpoint":  "0681d4b642af6204bc2e475c6865e8f12363cb7f82b22aae37f9ec66898f2bf1:0",
                    "is_our_output":  true
                }
            ]
        },

[…]

**Comment by ziggie1984** [comment]
you can also sent me a DM on slack regarding your setup infos.

**Comment by umpahpah67** [comment]
The mystery is solved. Something went wrong in the migration: The autopilot opened a new channel, but this channel was not displayed on the new node. Shutting down the new node, starting the old node, restoring the channels and sending the funds to the new nodes solved the problem.

Many thanks for the great support and patience to saubyk and especially ziggie.
