### ISSUE TITLE
Updating to 0.15.2 from 0.14.1 causes Error: Error: Error: ENOENT: no such file or directory, open ''

### ISSUE THREAD

**Issue by rockstardev** [Ride-The-Lightning/RTL#1452]
I am trying to update RTL in BTCPay Server docker to 0.15.2 and am running into this issue. Previously my instance on RTL 0.14.1 that was working without problems:

![image](https://github.com/user-attachments/assets/0844fa6c-efb0-4d1f-b9c5-a7ed2daa80f6)

I've bumped it to v0.15.2 and now I am getting error:

![image](https://github.com/user-attachments/assets/e18d3a3b-64dd-41c3-8cc8-d8389ba70823)

You can see the history of commits on https://github.com/btcpayserver/btcpayserver-docker/pull/941. The relevant docker container configuration is on: https://github.com/btcpayserver/btcpayserver-docker/blob/39c4558f9d952e973272d2418884543b4126bd77/docker-compose-generator/docker-fragments/bitcoin-lnd.yml#L49

Let me know if configuration settings changed between versions and how to best proceed so that we update users on BTCPay Server to the latest version.

**Comment by saubyk** [comment]
cc: @ShahanaFarooqui

**Comment by ShahanaFarooqui** [comment]
The configuration was not being assigned to the variable. Fixed with PR #1455.

**Comment by rockstardev** [comment]
Thank you, I will try version 0.15.3.

**Comment by saubyk** [comment]
> Thank you, I will try version 0.15.3.

@rockstardev version 0.15.3 has now been published:
https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.15.3

**Comment by rockstardev** [comment]
Unfortunately still running into problems, see: #1468
