### ISSUE TITLE
RTL with Core Lightning & CLNRest - "Invalid CSRF token, form tempered"

### ISSUE THREAD

**Issue by GTCLive** [Ride-The-Lightning/RTL#1453]
Hi. I'm not sure if this should be posted here or on the CLN github, or both. I've just finished a new installation of CLN and RTL on Debian 12 and although everything seems to be running and installing perfectly fine, can access the swagger over https, rune is checked valid, I'm getting this strange cookie error right after I logon in RTL. 

Both CLN and RTL are latest releases. 
Debian 12, stock uspace.
Firefox 128.3.1esr.

**cnc@debian12-vm:~/RTL$ node rtl**

_[10/28/2024, 10:56:19 PM] INFO: RTL => Server is up and running, please open the UI at http://localhost:3000 or your proxy configured url.

[10/28/2024, 10:56:29 PM] **ERROR: App => Invalid CSRF token. Form tempered..**

[10/28/2024, 10:56:29 PM] ERROR: GetInfo => Get Info Error: {"name":"StatusCodeError","statusCode":403,"message":"403 - \"Invalid CSRF token, form tempered.\"","error":"Invalid CSRF token, form tempered.","options":{"url":"http://localhost:3000/v1/getinfo","rejectUnauthorized":false,"json":true,"headers":{},"method":"POST","qs":{},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":403,"body":"Invalid CSRF token, form tempered.","headers":{"x-powered-by":"Express","cache-control":"no-cache","access-control-allow-headers":"Origin, X-Requested-With, Content-Type, Accept, Authorization, filePath","access-control-allow-methods":"GET, POST, PATCH, PUT, DELETE, OPTIONS","set-cookie":["_csrf=PT13lrviXSkBBkhXoZfgzn_d; Path=/","connect.sid=s%3A6n23uWtFvoD8B0QI9GR9ujkXl9G8_3LZ.1ifnTCNzYmRdDjVYbOBmYJUqTD%2BmA7V267b9huIoSD8; Path=/; Expires=Wed, 30 Oct 2024 02:56:29 GMT; HttpOnly"],"content-type":"text/html; charset=utf-8","content-length":"34","etag":"W/\"22-g6N794wK8KWxViJzSBOIVSkxwac\"","date":"Tue, 29 Oct 2024 02:56:29 GMT","connection":"close"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"localhost:3000","port":"3000","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/v1/getinfo","path":"/v1/getinfo","href":"http://localhost:3000/v1/getinfo"},"method":"POST","headers":{"accept":"application/json","content-length":0}}}}_

**Comment by ShahanaFarooqui** [comment]
It is the browser issue, so related to RTL not CLN. I saw it twice on Firefox but restarting RTL server and reopening the browser window fixed it for me. Can you try that before I try to reproduce it locally?

**Comment by GTCLive** [comment]
Awesome, thanks for your help and for looking into this. It appears to be server side as I'm getting the same weird error when using the chrome and brave browsers (remote access). What I can't figure out is if it's caused by the Node/Npm or the CLNRest pckg. Including the setup below, see if you can spot anything obvious from that. 

Please let me know if you need logs/traces of any sort, I'm super keep on getting RTL working with CLN here. Cool tools (thanks for that btw 🙏).

### INSTALL CORE LIGHTNING
$ cd ~
$ git clone https://github.com/ElementsProject/lightning.git
$ cd lightning
$ git checkout v24.08.2
$ ./configure --disable-rust
$ make
$ sudo make install
$ mkdir ~/.lightning
$ nano ~/.lightning/config
//////////// CNF CONF //////////////////
alias=gtcdev
rgb=00ff00
daemon
network=bitcoin
log-file=/home/cnc/.lightning/lightning.log
log-level=debug
fee-base=1000
fee-per-satoshi=1
min-capacity-sat=20000
funding-confirms=2
### CLNRest
clnrest-port=3010
#clnrest-protocol=https
#clnrest-host=127.0.0.1
#clnrest-certs=/home/cnc/.lightning/bitcoin
/////////////////////////////////////////


### INSTALL RIDE THE LIGHTNING
$ cd ~
$ git clone https://github.com/Ride-The-Lightning/RTL
$ cd RTL
$ git checkout v0.15.2
$ npm install --omit=dev --legacy-peer-deps

$ lightning-cli createrune
$ nano /home/cnc/.lightning/rtl.rune
LIGHTNING_RUNE="f0xmdZVpNljkHFxVwX7bhEfeH9lQpR4YE0FmC-wqMYE9MA=="

$ mkdir /home/cnc/.lightning/backup/
$ nano RTL-Config.json
//////////// RTL CONF //////////////////
{
  "multiPass": "123456789",
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "mecanix",
      "lnImplementation": "CLN",
      "Authentication": {
	"nodeAuthType": ="DEFAULT",
        "runePath": "/home/cnc/.lightning/rtl.rune",
        "configPath": "/home/cnc/.lightning/config"
      },
      "Settings": {
        "userPersona": "OPERATOR",
        "themeMode": "NIGHT",
        "themeColor": "PURPLE",
        "channelBackupPath": "/home/cnc/.lightning/backup",
        "logLevel": "ERROR",
        "lnServerUrl": "http://localhost:3000",
        "fiatConversion": false
      }
    }
  ]
}
/////////////////////////////////////////

**Comment by GTCLive** [comment]
@ShahanaFarooqui 

Awesome, too kind. Thanks for your help and for looking into this. It appears to be server side as I'm getting the same weird error when using the chrome and brave browsers (remote access). What I can't figure out is if it's caused by the Node/Npm or the CLNRest pckg. Including the setup below, see if you can spot anything obvious from that. 

Please let me know if you need logs/traces of any sort, I'm super keen on getting RTL working with CLN here. Cool tools (thanks for that btw 🙏).

# INSTALL CORE LIGHTNING
$ cd ~
$ git clone https://github.com/ElementsProject/lightning.git
$ cd lightning
$ git checkout v24.08.2
$ ./configure --disable-rust
$ make
$ sudo make install
$ mkdir ~/.lightning
$ nano ~/.lightning/config
//////////// CNL CONF //////////////////
alias=gtcdev
rgb=00ff00
daemon
network=bitcoin
log-file=/home/cnc/.lightning/lightning.log
log-level=debug
fee-base=1000
fee-per-satoshi=1
min-capacity-sat=20000
funding-confirms=2
#CLNRest
clnrest-port=3010
#clnrest-protocol=https
#clnrest-host=127.0.0.1
#clnrest-certs=/home/cnc/.lightning/bitcoin
/////////////////////////////////////////


# INSTALL RIDE THE LIGHTNING
$ cd ~
$ git clone https://github.com/Ride-The-Lightning/RTL
$ cd RTL
$ git checkout v0.15.2
$ npm install --omit=dev --legacy-peer-deps

$ lightning-cli createrune
$ nano /home/cnc/.lightning/rtl.rune
LIGHTNING_RUNE="f0xmdZVpNljkHFxVwX7bhEfeH9lQpR4YE0FmC-wqMYE9MA=="

$ mkdir /home/cnc/.lightning/backup/
$ nano RTL-Config.json
//////////// RTL CONF //////////////////
{
  "multiPass": "123456789",
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "mecanix",
      "lnImplementation": "CLN",
      "Authentication": {
	"nodeAuthType": ="DEFAULT",
        "runePath": "/home/cnc/.lightning/rtl.rune",
        "configPath": "/home/cnc/.lightning/config"
      },
      "Settings": {
        "userPersona": "OPERATOR",
        "themeMode": "NIGHT",
        "themeColor": "PURPLE",
        "channelBackupPath": "/home/cnc/.lightning/backup",
        "logLevel": "ERROR",
        "lnServerUrl": "http://localhost:3000",
        "fiatConversion": false
      }
    }
  ]
}
/////////////////////////////////////////

**Comment by ShahanaFarooqui** [comment]
> Awesome, too kind. Thanks for your help and for looking into this. It appears to be server side as I'm getting the same weird error when using the chrome and brave browsers (remote access). What I can't figure out is if it's caused by the Node/Npm or the CLNRest pckg. Including the setup below, see if you can spot anything obvious from that.
> 

The server generates a unique CSRF token and includes it in the initial response to the browser. When the browser submits a form or performs an action, this token is sent with the request. The server then validates that the token matches the one originally generated to ensure security. You can find several detailed articles on CSRF security online for more information.

In RTL’s case, the CSRF token is generated by RTL’s server (Node.js) and sent to the browser with the initial response. clnrest becomes relevant only after the browser-server communication is secured and the user is logged into the RTL server. Since the issue is unrelated to CLN or RTL configurations, their setup is not useful for debugging in this scenario.

**Comment by GTCLive** [comment]
Thanks. That's great info to understand what's CSRF tokens, unfortunately, and given my trade, it will take me 2.5 lifetime to understand half of all what that do and mean!! I'll call it a pass on that one and look for an alternative LN solution.

Damn lol Failed on LND last week, failed on CLN (I can't even make their cln_application working). Incoherent documentations, etc etc.   

Can you recommend a (another) simple yet functional LN implementation with a proven set-up?
