### ISSUE TITLE
Cannot open RTL dashboard through previously working BTCPay Server URL

### ISSUE THREAD

**Issue by rockstardev** [Ride-The-Lightning/RTL#1468]
In BTCPay Server, we have a special URL used for logging in, as shown below:

https://BTCPAY_URL/rtl/api/authenticate/cookie?access-key=ACCESS_KEY

However, after upgrading to version 0.15.3, navigating to this URL now results in the Page Not Found:

![image](https://github.com/user-attachments/assets/22550a37-96ea-4845-8570-8281dd8c9937)

The container logs do not indicate any specific issues:

```
(node:7) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[11/12/2024, 2:23:30 PM] INFO: RTL => Server is up and running, please open the UI at http://localhost:3000 or your proxy configured url.
```

I've tried deleting RTL docker container and volume, and restarting to no avail. 

You can see all the docker container settings if you visit https://github.com/btcpayserver/btcpayserver-docker/pull/954/files

**Comment by ShahanaFarooqui** [comment]
@rockstardev I have tested the changes locally and submitted a PR for the version update at https://github.com/btcpayserver/btcpayserver-docker/pull/956.

Keeping this issue open till you test that PR.

**Comment by rockstardev** [comment]
OK, tested and it works: https://github.com/btcpayserver/btcpayserver-docker/pull/956#issuecomment-2487456702

I've merged the PR and will ask for more people to test, now that we have unified versions of RTL across different lightning implementations.
