### ISSUE TITLE
Display LND logs

### ISSUE THREAD

**Issue by rbndg** [Ride-The-Lightning/RTL#164]
Hello everyone

RTL does a great job of giving users a good overview of the current state of the node, one feature that I thought would be useful is to be able to see the logs of LND as well. 
Do you think this is something RTL should also do?

**Comment by seth586** [comment]
This would be very nice to see live lnd logs.

A good example of this is the web ui for freenas. The bottom of the screen has a black box that shows a live console output.

**Comment by saubyk** [comment]
There is no API available on LND to stream the logs. We feel that displaying logs in the UI will require us to add a lot of libraries and will make the application heavy and complex.
This requirement is best addressed by viewing the logs on the console.

Closing this issue. Thanks.
