### ISSUE TITLE
[UI] - minor change to copy 

### ISSUE THREAD

**Issue by FKrauss** [Ride-The-Lightning/RTL#179]
**Is your feature request related to a problem? Please describe.**
I started using RTL when I set up my BTCpay server with lightning. I tried with a few payments and found the UI a bit confusing in terms of copy. The one thing that confused me the most was the fact that in RTL "Wallet" is a term used for on-chain wallet, which is not clear when you're in the Lightning context. This issue is a small proposal to rephrase that and make it more clear for users to understand what they're doing

**Describe the solution you'd like**
See [here](https://i.imgur.com/S42xMwo.png). This is how I would call each box:

1. `Wallet Balance (On-chain)`
2. `Peers`
3. `Channel Balance (Lightning)`
4. Chain Sync Status

**Additional context**
It took me a while to understand that RTL had also a on-chain set of features and my default place to look for the LN payments I collected was the `Wallet`.

**Comment by saubyk** [comment]
Hi @FKrauss. Thanks for highlighting this UX challenge.
We will include this input, in our UI revision, which we are working on currently.

**Comment by Ride-The-Lightning** [comment]
Fixed with new UI.
