### ISSUE TITLE
Small Adjustments Needed to Allow RTL-c-lightning usage in BTCPay-Docker

### ISSUE THREAD

**Issue by JeffVandrewJr** [Ride-The-Lightning/RTL#184]
**Is your feature request related to a problem? Please describe.**
There are settings you have your JSON file that would be better if could be optionally set via environmental variable. This is similar to the situation when you first integrated the lnd-only version of RTL into BTCPay and I similarly asked for some of these settings to be set via env variable. By allowing setting via environmental variable, I can make an agnostic Dockerfile for the RTL repo that's not BTCPay-specific, and add the BTCPay-specific stuff in the docker-compose fragment that resides in the BTCPay-Docker repo.

**Describe the solution you'd like**
The following variables should be able to be set via env variable:
```
    lnImplementation - This should be CLT, indicating that RTL is connecting to a c-lightning node.
    macaroonPath - Path of the folder containing access.macaroon file from cl-rest server.
    lnServerUrl - complete url with ip address and port of the cl-rest server.
    multiPass - Specify the password (in plain text) to access RTL. This password will be hashed and not stored as plain text.
    configPath (optional) - File path of the c-lightning config file, if RTL server is local to the c-lightning server.
```

[I'm assuming the SSO stuff can still be set via env variable as was the case in earlier versions of RTL.]

There are also some settings for `c-lightning-rest` that need to be able to be optionally set via env variable for the same reasons. I'll list them here, but @saubyk feel free to open these as a separate ticket in the `c-lightning-rest` repo if you believe that to be cleaner:
```
    PORT (Default: 3001)
    PROTOCOL (Default: https) - Two options are supported https and http(unencrypted and insecure communication between c-lightning and API server).
    EXECMODE (Default: production) - Control for more detailed log info.
```

**Describe alternatives you've considered**
I could have your RTL Dockerfile generate a JSON file for these settings but then your Dockerfile would be locked to BTCPay instead of being more agnostic and able to be used on platforms other than BTCPay.

**Additional context**

**Comment by saubyk** [comment]
hey @JeffVandrewJr thanks for the help on this, as always...

Regarding the `cl-rest` changes, I would like to collaborate with you on the below PR:
https://github.com/saubyk/c-lightning-REST/pull/16

The idea is to convert it into a `c-lightning` plugin.

**Comment by JeffVandrewJr** [comment]
@saubyk That sounds like a good idea, however I haven't messed with the c-lightning plugin architecture at all so I'm not much help there.

**Comment by ShahanaFarooqui** [comment]
@JeffVandrewJr thank you for helping us to on-board C-lightning RTLon BTCPayserver. Below are the added values for environment variables:
    lnImplementation - LN_IMPLEMENTATION
    macaroonPath - MACAROON_PATH
    lnServerUrl - LN_SERVER_URL
    configPath - CONFIG_PATH
    multiPass - this is the password value for RTL multinode setup. BTC payserver users are SSO authenticated, so we do not need to add it to environment variables. Other users need to enter it on the login screen to log into the application. 

Please let us know if you want anything else to be added or if adding multiPass is required for some reason. Thanks again :).

**Comment by JeffVandrewJr** [comment]
@ShahanaFarooqui Thanks! If @saubyk is refactoring his REST API as a c-lightning plugin, I'll wait for that to be completed before integrating this all together into BTCPay-Docker.

**Comment by saubyk** [comment]
@JeffVandrewJr  @ShahanaFarooqui 
cl-rest apis can now be run as plugin.

**Comment by JeffVandrewJr** [comment]
@saubyk Cool I'll try to get on this soon.

**Comment by ShahanaFarooqui** [comment]
RTL Clightning is available now BTCPay now.
