### ISSUE TITLE
Password Validation Failed with custom auth type

### ISSUE THREAD

**Issue by bucko13** [Ride-The-Lightning/RTL#193]
**Describe the bug**
I'm trying to connect RTL running in a docker container to an lnd instance running in another docker container. With `NODE_AUTH_TYPE` set to CUSTOM and `RTC_PASS` set to a simple string, after starting up the container (shahanafarooqui/rtl:0.5.2) I get the message `rtl_1      | Server is up and running, please open the UI at http://localhost:5000` then access the dashboard (which looks normal) but then when enter my password I get an error:

```
ERROR: Authenticate(54) => Password Validation Failed!
```

**Your environment**
I'm using btcd and lnd for the backends, docker images based on their latest builds

**Comment by saubyk** [comment]
Hi @bucko13 
Have you looked at the directions provided [here](https://github.com/ShahanaFarooqui/RTL/tree/master/docker)?

The instructions are provided by @MrHash

**Comment by saubyk** [comment]
@bucko13 also note that the env. variable for password is `RTL_PASS` not `RTC_PASS` as you mentioned above.

**Comment by bucko13** [comment]
Ah yeah, sorry that was a typo. I've got it set as `RTL_PASS` in my project. 

I have seen those instructions but unfortunately I'm running it in an external project against my own containers so can't follow those directly as they are meant for running out of that local directory. I used the docker-compose there as a model though. I also know all the other checks mentioned there pass as my lnd and btcd nodes are all running and accessible (I'm setting up a self-contained simnet network of 3 nodes and can confirm that they are running, have funds, and have channels open with each other).

**Comment by bucko13** [comment]
Ah ok, so I went back and double checked the version in the sample compose file you linked to. I downgraded the image version I was using to match, from shahanafarooqui/rtl:0.5.2 to shahanafarooqui/rtl:0.2.6 and that seems to have fixed it. Seems like there was maybe a bug in using the RTL_PASS for auth in between those versions?

**Comment by saubyk** [comment]
Hi @bucko13 can you please try with the latest release v0.5.3?

**Comment by bucko13** [comment]
Unfortunately same thing.

**Comment by saubyk** [comment]
In case it doesn't work with v0.5.3, we suspect that this was broken in one of our releases when we included a password hashing logic to not store a plain text password in the conf file.

We may need your help to zero that down. In case it does not work with 0.5.3, can you please first try with release v0.3.0 and then with release v0.3.1?

We suspect that we broke it with v0.3.1

**Comment by bucko13** [comment]
Yep, that was it. 3.0 worked and 3.1 was broken.

**Comment by saubyk** [comment]
@bucko13 Thanks for testing and confirming.
We will work on a fix. May need your help with testing. Do not have a local docker setup.

**Comment by bucko13** [comment]
Sure! just let me know.

**Comment by ShahanaFarooqui** [comment]
@bucko13 Thanks for opening the issue and testing the authentication with different versions.
We have fixed the issue and released it with v0.5.4. 

Please check and let us know if anything else needs to be fixed or if something is missing from the documentation.

**Comment by bucko13** [comment]
Great! Looking from the commit seems like you found it. I guess it hasn't been published to docker yet though since I can't pull the image. I tried with `image: shahanafarooqui/rtl:0.3.0` and it works but `docker-compose up` fails with `image: shahanafarooqui/rtl:0.5.4`

**Comment by ShahanaFarooqui** [comment]
I sent the last comment after confirming the docket publish. I can see docker image for 0.5.4 version.

**Comment by bucko13** [comment]
Got it! All seems good. Thanks for the fast response time and quick fix!

**Comment by TyBranham** [comment]
Hi, I seem to be experiencing something similar. However, I am not on docker. I am running bitcoind with lnd on arm. Below is my RTL.conf. 

When I try to log in with DEFAULT, after the node has started using my bitcoind.rpcpass set in lnd.conf and bitcoin.conf, I still cant login using the that password.

When I try to log in with CUSTOM the node fails to start stating the below error:
Error: 
rtlPass hash conversion failed!
Custom Node Authentication can be set with RTL password only. Please set RTL Password through environment or RTL.conf

--Note: *** is censor for file path--
[Authentication]
macaroonPath=***/.lnd/data/chain/bitcoin/mainnet
nodeAuthType=CUSTOM
rtlPass=*password*

[SSO]
rtlSSO=0
rtlCookiePath=***/rtl/cookies/auth.cookie
logoutRedirectLink=/login

[Settings]
flgSidenavOpened=true

flgSidnavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
lndServerUrl=https://localhost:8089/v1
bitcoindConfigPath=***/.bitcoin/bitcoin.conf
enableLogging=false
port=3000

I have also set up environment variables to no avail.
import { VERSION } from './version';

export const API_URL = 'http://localhost:3000/rtl/api';

export const environment = {
  production: false,
  isDebugMode: true,
  AUTHENTICATE_API: API_URL + '/authenticate',
  RTL_PASS: '*password*',
  CONF_API: API_URL + '/conf',
  BALANCE_API: '/balance',
  FEES_API: '/fees',
  PEERS_API: '/peers',
  CHANNELS_API: '/channels',
  CHANNELS_BACKUP_API: '/channels/backup',
  GETINFO_API: '/getinfo',
  WALLET_API: '/wallet',
  NETWORK_API: '/network',
  NEW_ADDRESS_API : '/newaddress',
  TRANSACTIONS_API : '/transactions',
  PAYREQUEST_API: '/payreq',
  PAYMENTS_API: '/payments',
  INVOICES_API: '/invoices',
  SWITCH_API: '/switch',
  ON_CHAIN_API: '/onchain',
  VERSION: VERSION
};

Am I missing something?

**Comment by ShahanaFarooqui** [comment]
@TyBranham What RTL version you are using?

**Comment by TyBranham** [comment]
The newest version. Ran the below just to be sure. Same thing
git reset --hard HEAD
$ git clean -f -d
$ git pull
$ npm install

**Comment by ShahanaFarooqui** [comment]
@TyBranham, I tried to run the application with above RTL.conf and below are the suggestions to be able to authenticate successfully.

1. CUSTOM AuthType: 
Your config file details are complete but the node server is unable to modify the config file. When node server runs for the first time, it converts the 'rtlPass' into its hashed value to make it more secure. Error message 'rtlPass hash conversion failed!' shows that the server is unable to modify the file. Please run the application with admin access to solve this issue.

2. DEFAULT AuthType: 
For default authentication, the server reads the password value from lnd.conf's bitcoind.rpcpass. So, lndConfigPath is mandatory for DEFAULT authentication to work. Example conf:
[SSO]
...
[Settings]
...
[Authentication]
macaroonPath=***/.lnd/data/chain/bitcoin/mainnet
nodeAuthType=DEFAULT
lndConfigPath=***/AppData/Local/Lnd/lnd.conf

3. Also, regarding "Set RTL Password through environment":
The suggestion is to set Node server's environment variable. Something like:
    process.env.RTL_PASS="password"
    node rtl

Please let us know if issue still persists.

**Comment by TyBranham** [comment]
Thank you for the guidance. I am able to login now.
