### ISSUE TITLE
Lacking information on "Waiting close channels"

### ISSUE THREAD

**Issue by nanguapie** [Ride-The-Lightning/RTL#203]
**Describe the bug**
In the view "Channels" - "Pending" I can see 6 channels that are listed as "Waiting Close Channels".  I can see the capacity of the channels, the remote Node Pub and the Channel Point. However, important information for me as a user here would be to also be able to see how much of the channel balance is on my side and on the other side.  And even more crucially, if there is any "Maturity height" or estimated time until closing of these waiting channels such as there is shown under "Pending Force Closing Channels".  

**To Reproduce**

Have your node fail while upgrading from Raspiblitz 1.1 to Raspiblitz 1.3 and instead restore your node from file and seed phrase to a fresh new Raspiblitz 1.3 installation. 

**Expected behavior**
I expected to be able to use RTL to look at the channel situation after this node restoration and draw conclusions as to if there is any action I can take further to make sure that the "Waiting" channels are closed, or at least find out how long time there is until the channels will be closed and the balances finally settled if still possible. 

**Actual behavior**
I see too little information under the "Waiting Close Channels"

**Screenshots**
Screenshot attached. 
<img width="1302" alt="Screenshot 2019-11-09 at 21 19 08" src="https://user-images.githubusercontent.com/30684361/68534696-a2f0dc00-0337-11ea-9fba-bfe8745e06d0.png">

**Your environment**
* version of `lnd`  0.7.1 beta
* operating system (`uname -a` on *Nix) MacOS
* version of `btcd`, `bitcoind`, or other backend  bitcoind .18
* any other relevant environment details

**Additional context**

**Comment by saubyk** [comment]
Hi @nanguapie 
We can add the local and remote balance, which is available in the 'Waiting close channel' response from the API.
But the maturity height is not available in the API response and hence cannot be shown.
You can inspect the response documentation here:
https://api.lightning.community/?shell#waitingclosechannel

You can get this addressed by LND. If and when the API is updated, we can make that field available in the RTL UI.

**Comment by nanguapie** [comment]
@saubyk , That's great thank you, true that it is more of an enhancement than a bug of RTL really.

I looked at the response documentation link that you sent, and perhaps this is also something to be addressed more to LND.

But can you really add both local and remote balance? in the response doc, it only says "channel" and "limbo balance" ? 

And I would question if it's really correct as they write under Channel description on the same link https://api.lightning.community/?shell#waitingclosechannel 
 "The pending channel waiting for closing tx to confirm"

I don't believe that my 6 waiting channels are merely waiting for an already sent closing tx to confirm. The mempool has been empty many many times since these channels ended up in limbo.  Their status must be something else than waiting for closing tx to confirm. 

Thank you very much for your feedback - should I address my above questions to LND instead (as issue on Github?) or do you know lnd in that detail already yourself?  Again many thanks

**Comment by saubyk** [comment]
Hi @nanguapie we will add local and remote balance to the page, that's why I kept the issue open.
Regarding your other query. LND is not really providing the transaction details to track, with the pending channel close information.
I would recommend looking at the `List Transactions` section under `LND Wallet` page. It should show the unconfirmed transactions for your closing channels.

If you are not able to find the same, please ask around on the LND slack first, before opening a issue on Github.

**Comment by saubyk** [comment]
Hi @nanguapie local and remote balance fields are already available on the "waiting close channels" page. Closing this issue now.

**Comment by nanguapie** [comment]
OK, thank you! I can now see the local balance clearly shown in the column "local balance" under "Pending Force Closing Channels".  I can still not see anything displayed under neither "local balance" nor "remote balance" for my 6 "Waiting Close Channels" though.  I am running RTL in the browser, connected to my Raspiblitz which is running LND 0.7.1.  Do I need to actively upgrade RTL somehow? I initially activated RTL by using the interface that is provided by Raspiblitz.    

The lack of shown balances may be due to the fact that Im running a node restored from its state in late August 2019 from which I still have a number of locked sats which I'm experimenting on unlocking by trying to provoke force closing of the channels.
