### ISSUE TITLE
Convert RTL app into Web Component

### ISSUE THREAD

**Issue by ShahanaFarooqui** [Ride-The-Lightning/RTL#204]
Convert RTL app into Web Component, so that BTCPayserver or other apps can open the application as Web Component rather than opening it in the IFrame.

**Comment by ShahanaFarooqui** [comment]
RTL's application to web component conversion is currently a complicated process and has a potential to break major features. 

First, It will require a major setup change to call server API's. RTL is installed with multiple lightning node solutions with/without proxy servers and can break their setups with these changes.

Second, RTL's current routing will not work within web component. [vaadin router](https://vaadin.com/router) provides a client side routing solution but is a less maintained and immature library, which is a concern.

After that also, I cannot ensure that the updated solution will work for everyone. Putting this development on hold for near future. Will revisit it later.

**Comment by saubyk** [comment]
Closing this for now.
