### ISSUE TITLE
cannot login even with correct password

### ISSUE THREAD

**Issue by turco32** [Ride-The-Lightning/RTL#211]
Hello,

i just setup a raspiblitz node to get on the network, and i wanted to access the device via RTL. i setup the RTL access as per the instructions on the raspiblitz repo page, and when i try to login with the correct password, i get the following pop-up error:

lstrusted : True

anyone know what im doing wrong? let me know if you need more info.

**Comment by ShahanaFarooqui** [comment]
Hi, there has been similar issue on raspiblitz some time back #187 . But, we did not get any clear response on that issue from the user. 

Please refer to that issue and let us know if those steps solve your problem. If not, we will need more details on all the hardware and software involved and happy to debug the issue further.

**Comment by turco32** [comment]
thanks for the response. i gave #187 a peek, but im not having any of the other issues. when i ssh into the node everything seems to be functioning correctly. i did notice the question asked if RTL was behind any other service. I can confirm there is no other type of web serving service running like nginx or apache other than what the raspiblitz installer put in place (which looks like a node.js instance). I am accessing this from a chromium browser on a Linux laptop. the hardware is a rpi 3b+ running the raspiblitz distro (newest release). if you need me to check anymore software versions let me know.

**Comment by saubyk** [comment]
Hi @turco32  can you please confirm the version of RTL you are running?

**Comment by turco32** [comment]
sure,

V 0.4.2 Beta

**Comment by saubyk** [comment]
@turco32 you are quite behind on the RTL version.
can you please update your RTL version to the latest version 0.5.4?
There has been a lot of bug fixes which have been made since 0.4.2.

**Comment by turco32** [comment]
ok, so i tried updating going into the RTL project folder that was made during the raspiblitz install, and did `npm update` which failed as it asked for root access, so i passed it again with `sudo npm update` and it failed updating. please bear with me as i am very new with node.js/javascript code so i dont know much about it. Should i foward this issue to the raspiblitz devs as well? i feel like its using a pre-packed version of RTL and not pulling the newest version.

**Comment by saubyk** [comment]
Go to the RTL folder and run `git pull` to update RTL.
Once RTL is updated, run `npm install` once, before starting the server.

**Comment by saubyk** [comment]
Hi @turco32 assuming your issue has been addressed with the latest version of RTL.
Closing this issue now. Feel free to re-open if you face the same issue again.

Thanks.
