### ISSUE TITLE
Add max fees when send payment

### ISSUE THREAD

**Issue by bota87** [Ride-The-Lightning/RTL#216]
When send payment it's possible to set the --fee_limit parameter?

**Comment by ShahanaFarooqui** [comment]
@bota87, thanks for the great suggestion. We have included fee_limit and outgoing_chan_id options in the payments now. The code has been checked in the UX branch and will be released with the next version.

**Comment by saubyk** [comment]
This requirement has been addressed with release v0.6.0
Closing this ticket.
