### ISSUE TITLE
Wrong fees estimate from Query Routes

### ISSUE THREAD

**Issue by bota87** [Ride-The-Lightning/RTL#217]
I used the query routes to have an idea about the fees to pay to send a payment to a node, it give me about 3 sats, then I send the payment and it's executed with 200 sats of fee

**Comment by saubyk** [comment]
Hi @bota87 
This question is best addressed by LND. We are just providing a UI to the API response.

That being said, below is my understanding on what you experienced.
The query route response is not a guarantee on the fee that will be charged for the actual route which your payment may take.
The actual route for the payment can vary depending on the direction and quantity of liquidity on the channels present, between your node and the final destination.

The new UX will have a disclaimer sign on the query routes, to indicate that actual fee can be different from the estimate shown on the query route.

**Comment by saubyk** [comment]
This issue has been fixed with the release 0.6.0.
Closing the ticket now. Thanks.
