### ISSUE TITLE
Upgrade to node-sass v5

### ISSUE THREAD

**Issue by frennkie** [Ride-The-Lightning/RTL#220]
Currently RTL depends on node-sass version 4.x which depends on node-gyp 3.x (3.8). This old node-gyp release requires Python2 during Installation. Python2 is still very commonly available but it has been deprecated by the Python developers.

Node-sass already has a branch in which they are working on a version 5 (which upgrade node-gyp to v6). It would be great if RTL could already prepare and test/develop against the (hopefully soon to be released) node-sass v5.

**Comment by ShahanaFarooqui** [comment]
@frennkie, @openoms We have a watch on its releases and will be happy to upgrade node-sass to v5 as soon as they will release it.

**Comment by Ride-The-Lightning** [comment]
We are closing this issue as it should not have any impact on production build after converting node-sass into development dependency. Updated the documentation for the same.
