### ISSUE TITLE
multi node password change

### ISSUE THREAD

**Issue by thephizzz** [Ride-The-Lightning/RTL#221]
I attempted to change my RTL password on a multi-node setup. I added "multipass": newpassword to the RTL-multi-Node-Conf.json file and removed the hash of the old password at the end of the file.
Unfortunately - i can no longer connect to the RTL interface.
How would i go about changing passwords?

LND 0.8.0-beta
RTL 0.5.3-beta
W10

**Comment by ShahanaFarooqui** [comment]
@thephizzz  Did you restart the node server after this update?

**Comment by thephizzz** [comment]
Yes. No change. Im receiving a "refused to connect" error.

**Comment by thephizzz** [comment]
I restarted both nodes

**Comment by ShahanaFarooqui** [comment]
The steps you used to change the password are correct and it should have worked after restarting the node server. 

Not nodes but node server with 'node rtl' command.

**Comment by ShahanaFarooqui** [comment]
Please ensure that you are running it as admin because the server will try to replace the text password with hashed at the time of restart. If you do not have write permission on the system then it will fail otherwise it will show the message and start the server like below:

![image](https://user-images.githubusercontent.com/23240721/72097722-01601980-32eb-11ea-94ef-49d469c3a641.png)

**Comment by thephizzz** [comment]
I can SSH into each node but not RTL. It all was working fine until I tried to change the pas
sword

**Comment by thephizzz** [comment]
Thank you for your help. It looks like I may have made an editing error in the JSON file (big surprise).
But of course now my Raspi is saying the disk is full and i can't edit. So i'm off to try and solve that - then edit the JSON - and then see the results.

**Comment by thephizzz** [comment]
Now I'm receiving this error after running node rtl:
Multi Node Authentication can be set with multiPass only. Please set MultiPass in RTL-Multi-Node-Conf.json

I do have the multipass set in the file.
Any help?

{
  "multipass": "###########",
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "RaspiBlitz LND",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "/mnt/hdd/lnd/data/chain/bitcoin/mainnet",
        "lndConfigPath": ""
      },
      "Settings": {
        "flgSidenavOpened": "true",
        "flgSidenavPinned": "true",
        "menu": "Vertical",
        "menuType": "Regular",
        "theme": "dark-blue",
        "satsToBTC": "false",
        "channelBackupPath": "C:\\RTL\\backup\\node-1",
        "bitcoindConfigPath": "",
        "enableLogging": "true",
        "lndServerUrl": "https://192.168.1.237:8080/v1"
      }
    },
    {
      "index": 2,
      "lnNode": "XPS LND",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "/mnt/hdd/xps",
        "lndConfigPath": ""
      },
      "Settings": {
        "flgSidenavOpened": "true",
        "flgSidenavPinned": "true",
        "menu": "Vertical",
        "menuType": "Regular",
        "theme": "light-teal",
        "satsToBTC": "false",
        "channelBackupPath": "C:\\RTL\\backup\\node-2",
        "bitcoindConfigPath": "",
        "enableLogging": "true",
        "lndServerUrl": "https://192.168.1.14:8080/v1"
      }
    }
  ]
}

**Comment by ShahanaFarooqui** [comment]
JSON keys are case sensitive. Please use “multiPass” with “P”.

**Comment by thephizzz** [comment]
Thank you.
