### ISSUE TITLE
ERROR TypeError: "t.sideNavigation is undefined"

### ISSUE THREAD

**Issue by grunch** [Ride-The-Lightning/RTL#223]
I just update to master (d7460a289334ae755e8a11076cb29e042cd9ed29) and the sidebar stop working.

I sign in, then I see the sidebar very quickly but it hides and there's no any button or link to open the sidebar again

If I refresh the page I can see the same behavior again.

I can see this in the firefox js console
```
ERROR TypeError: "t.sideNavigation is undefined"
    ngOnInit https://node.app.graaf.one/rtl/main.1cd2fd1ee376a61a6116.js:1
    invokeTask https://node.app.graaf.one/rtl/polyfills.f1c3d2a0bcdfc4e93ca8.js:1
    onInvokeTask https://node.app.graaf.one/rtl/main.1cd2fd1ee376a61a6116.js:1
    invokeTask https://node.app.graaf.one/rtl/polyfills.f1c3d2a0bcdfc4e93ca8.js:1
    runTask https://node.app.graaf.one/rtl/polyfills.f1c3d2a0bcdfc4e93ca8.js:1
    invokeTask https://node.app.graaf.one/rtl/polyfills.f1c3d2a0bcdfc4e93ca8.js:1
    invoke https://node.app.graaf.one/rtl/polyfills.f1c3d2a0bcdfc4e93ca8.js:1
    0 https://node.app.graaf.one/rtl/polyfills.f1c3d2a0bcdfc4e93ca8.js:1
main.1cd2fd1ee376a61a6116.js:1:220617
```
In the google chrome console the error look like this
```
main.1cd2fd1ee376a61a6116.js:1 ERROR TypeError: Cannot read property 'toggle' of undefined
    at main.1cd2fd1ee376a61a6116.js:1
    at e.invokeTask (polyfills.f1c3d2a0bcdfc4e93ca8.js:1)
    at Object.onInvokeTask (main.1cd2fd1ee376a61a6116.js:1)
    at e.invokeTask (polyfills.f1c3d2a0bcdfc4e93ca8.js:1)
    at t.runTask (polyfills.f1c3d2a0bcdfc4e93ca8.js:1)
    at t.invokeTask (polyfills.f1c3d2a0bcdfc4e93ca8.js:1)
    at invoke (polyfills.f1c3d2a0bcdfc4e93ca8.js:1)
    at n.args.<computed> (polyfills.f1c3d2a0bcdfc4e93ca8.js:1)
```

**Expected behavior**
the system should let to the user to open the sidebar

**Your environment**
* lncli version 0.8.2-beta commit=queue/v1.0.2-101-g8ce9e15f4a327f703623b4269d644a9c9a356411
* Linux lnd-node 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Bitcoin Core RPC client version v0.18.1

**Comment by ShahanaFarooqui** [comment]
@grunch master has major release updates and will need some configurations to be changed first.  Please check release notes from v0.6.0 as it suggests:

“The RTL config file RTL.conf, has been updated to include new config options for the UI. These config options must be configured to work with the new UI. The best approach is to rename the sample conf file and update per your config options.

You can also modify the existing config file.
Following options must be added:

userPersona=OPERATOR
themeMode=DAY
themeColor=PURPLE
currencyUnit=USD
The following config options are now redundant and must be deleted from the config file:

flgSidenavOpened
flgSidenavPinned
menu
menuType
satsToBTC
theme”

**Comment by ShahanaFarooqui** [comment]
Apart from above, we have added another configuration as ‘fiatConversion’ to be set as true/false to opt-in/opt-out from fiat currency conversion in the UI. Please check related details in release 0.6.1 notes.

**Comment by grunch** [comment]
done, thanks bro, keep up the hard work :fist_oncoming:
