### ISSUE TITLE
Support for Eclair?

### ISSUE THREAD

**Issue by rbndg** [Ride-The-Lightning/RTL#224]
Since this project now supports C-Lightning, do you think it's possible to also build support for Eclair?

**Comment by saubyk** [comment]
Hi @rbndg 
Eclair support is on our development roadmap. You can expect it sometime in 2020.

**Comment by Kixunil** [comment]
Depending on the complexity, I might find some time to help with this (in a few months maybe). Unfortunately I'm not a JS dev, so I shouldn't do it on my own.

**Comment by rbndg** [comment]
Eclair API is quite good and their dev team is quite responsive. I don't think it will be too difficult to pull this off

**Comment by araspitzu** [comment]
+1 for this, it would be awesome to have a web gui for eclair.

**Comment by viaj3ro** [comment]
+2 since the eclair team discontinued their aging GUI, this is desperately needed!

**Comment by ShahanaFarooqui** [comment]
@viaj3ro Will I get this reward if I will on-board Eclair by the end of May :P?

**Comment by viaj3ro** [comment]
yes :) 

I only care about two things: that it's done properly and sooner rather than later.

can't hope for anyone better than you I guess ;)

**Comment by GCinellu** [comment]
Hi @viaj3ro and @ShahanaFarooqui, I am interested in the bounty and have time to work on it within this weeks if you guys didn't start development already.
I already reviewed the lnd and clightning implementations and making a port for eclair wouldn't take long, beside being something I'd like to add to my resumé.
Kindly let me know about the status of this feature :)

**Comment by viaj3ro** [comment]
Hi @GCinellu 

I assume @ShahanaFarooqui was mostly joking but maybe double check with him and @araspitzu who had it on his 2do list since quite a while as well just to be sure.

**Comment by GCinellu** [comment]
Hi @viaj3ro, it is @araspitzu who mentioned me this bounty, he knows well my experience with JS technologies and suggested me to participate :)

I'll be waiting for @ShahanaFarooqui to let me know about his intentions, if he wasn't joking I would be happy to start working on it straight away. :)

**Comment by ShahanaFarooqui** [comment]
@GCinellu Adding Eclair to RTL is our next top priority. I was working on some pages redesigning and bug fixes so that we can reuse the most mature designs for Eclair. 

I was joking about the bounty but was very serious about finishing it by May. But, contributions are always welcome as long as they follow our coding standard :). So please feel free to check the implementation and let me know if you need any information/assistance. We can connect on telegram for more frequent conversations if you decide to move forward with it. BTW, I am a girl :).

**Comment by GCinellu** [comment]
Apologies for misgendering you :)

Fantasic, let's connect on Telegram then! 
I reviewed the current implementation and the code is readable and straightforward, yet if something will come up during development a direct line is surely the best thing to have :)

Do you already have a Telegram channel I can join?

**Comment by saubyk** [comment]
Hey @GCinellu we are keeping the TG group small and not sharing it publicly to keep the scammers away.
If you let me know you TG handle or any other platform to DM you, I will share the TG group directly with you.

**Comment by GCinellu** [comment]
Hi @saubyk completely understandable :) 
Are you in any public Bitcoin group?

For example we could meet in **Bitcoin Dev**
https://t.me/BitcoinCore

**Comment by GCinellu** [comment]
@saubyk I've been shown your Twitter profile but unfortunately I cannot access my account right now since the 2fa is set to another device that takes ages to turn on.

If the Bitcoin Dev group is not an option, I'll ping you on Twitter between tonight and tomorrow.

**Comment by saubyk** [comment]
@GCinellu I  joined the Bitcoin Dev TG group. My ID is `My2Sats`.

**Comment by viaj3ro** [comment]
> I was joking about the bounty but was very serious about finishing it by May

ha, looks like I chose the perfect time for my bounty ;)
But happy to hear that things are moving already.

when all is said and done, just let me know how you wanna share the reward in case more than one person is involved.

**Comment by ShahanaFarooqui** [comment]
@viaj3ro, @GCinellu. We as RTL team want to make it clear that, we will not partake in any bounty related to development. And we will not be facilitating any transactions as well. 

You can decide to transact independently, if you both agree.

@GCinellu, please note that, we are conservative in adding new dependencies and follow basic coding standards. We will make an honest effort to review and merge your code in time. But, cannot be held responsible if approvals are delayed for quality or other reasons.

**Comment by viaj3ro** [comment]
any progress?
