### ISSUE TITLE
"latest" tag missing on Docker

### ISSUE THREAD

**Issue by nicolasburtey** [Ride-The-Lightning/RTL#225]
A version has to be set to pull the image from docker.

eg: `pull shahanafarooqui/rtl` returns

`Failed to pull image "shahanafarooqui/rtl": rpc error: code = Unknown desc = Error response from daemon: manifest for shahanafarooqui/rtl:latest not found`

`pull shahanafarooqui/rtl:0.6.1` works.

**Comment by Ride-The-Lightning** [comment]
First, let me clear that I am not an expert in DevOps/docker and i might not be able to understand the issue completly.

Second, if it is about pulling without tagged version, i believe that it might not be a good idea as suggested in multiple blogs like:
https://vsupalov.com/docker-latest-tag/
https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375

**Comment by ShahanaFarooqui** [comment]
First, let me be clear that I am not an expert in DevOps/docker and i might not be able to fully understand the issue.

Second, if it is about pulling without tagged version, i believe that it might not be a good idea as suggested in multiple blogs like:
https://vsupalov.com/docker-latest-tag/
https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375

**Comment by nicolasburtey** [comment]
It may or may not be an issue to use :latest depending on your workflow. It's like using the master branch of a github repo. As a developer, you should know that there are risks of regression by using the latest version. 

My goal is to do some testing on testnet, and all that I would want for now is to have the latest version of RTL. For this using :latest is the best way to go. 

It will also make people migrate to the last version faster to you can get more immediate feedback.

**Comment by ShahanaFarooqui** [comment]
That makes sense. But, right now, our users are already struggling with the latest breaking release. So, let us keep the issue open and add the tag after the release is more stable.

**Comment by ShahanaFarooqui** [comment]
@nicolasburtey, We are deciding to not to add latest tag in docker script, as the application is installed on multiple hardware and software stacks. With all these different stack, testing and debugging is already a challange for us and including 'latest' will add another layer of complexity in debugging. 

Thanks for the suggestion and looking forward to more inputs and suggestions.
