### ISSUE TITLE
Add missing environment variables

### ISSUE THREAD

**Issue by ShahanaFarooqui** [Ride-The-Lightning/RTL#226]
Add 3 missing environment variables USER_PERSONA, THEME_MODE, THEME_COLOR.

**Comment by Ride-The-Lightning** [comment]
Not needed anymore. These should always be supplied and updated through config file. Removed FIAT_CONVERSION, CURRENCY_UNIT & DEFAULT_NODE_INDEX from environment variable setup for the same reason.
