### ISSUE TITLE
Can not see menu bar

### ISSUE THREAD

**Issue by MrManPew** [Ride-The-Lightning/RTL#229]
I can not see the left menu bar in the new version, and therefore can not move between difference pages 
![image](https://user-images.githubusercontent.com/35897350/72660413-3ac51300-39d6-11ea-813e-be6997bd9f65.png)

**Comment by MrManPew** [comment]
I know see it is the same as https://github.com/Ride-The-Lightning/RTL/issues/223

**Comment by ShahanaFarooqui** [comment]
@MrManPew were you able to fix this by following issue #223 instructions?

**Comment by dmac7123786** [comment]
Following the instructions in #223 fixed it for me

**Comment by saubyk** [comment]
@MrManPew is this still an issue for you? please let us know.

**Comment by MrManPew** [comment]
Yes @saubyk, I managed to solve it.Thanks
