### ISSUE TITLE
See nodes names in Forwarding History instead of Channel ID

### ISSUE THREAD

**Issue by MrManPew** [Ride-The-Lightning/RTL#230]
**Is your feature request related to a problem? Please describe.**
Usually when checking the routing page, I would like to know which **Node** have been most active in amount of transactions. For that I need to go the the _Forwarding History_ page and click View info in each transaction.. (I know I can see the sum in _Routing Peers_ but I like to see the time distribution) 

**Describe the solution you'd like**
It would be great if it was possible to see Nodes names instead of Channel ID in the Forwarding History. I can suggest a click box that automatically change form Channel ID to Forwarding nodes:
![image](https://user-images.githubusercontent.com/35897350/72660527-f76ba400-39d7-11ea-9dcc-e199faf2cc1a.png)

Thanks

**Comment by ShahanaFarooqui** [comment]
@MrManPew Thanks for the suggestion.

We decided to show 'Alias' on the table and channel ids can be checked through 'View Info'.  We pushed the change into 0.6.5 branch and will release v0.6.5 in 1-2 days.

**Comment by MrManPew** [comment]
Looks good, thanks!
