### ISSUE TITLE
Allow setting Sat/byte on closing channel

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#233]
When closing a channel there is no option to set Sat/byte. using lnd on the command line allows you to do this. 

RTL should allow me to set the fee I want to use when closing a channel the same way it allows it when making an on-chain transaction

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin Thanks for the suggestion.

Included Target confirmation blocks and Fees (Sats/byte) for channel close. Pushed the code to feature branch, will be released with v0.6.5.
