### ISSUE TITLE
Closing channel real time information

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#234]
when i close an inactive channel i get the spinning wheel with "Closing Channel..." for a really long time (minutes) and its unclear what is going on.
![2020-01-19 21_23_45-192 168 1 195 - Remotedesktopverbindung](https://user-images.githubusercontent.com/60074674/72687822-149c9180-3b02-11ea-81ff-d00a45c1230d.png)

meanwhile in the LND console i can see stuff like "Inserting unconfirmed transaction" and "Waiting for confirmation of cooperative close of ChannelPoint"

it would be nice if RTL kept me up to date in realtime what stage of closing the channel is going on with a couple different simple status updates instead of just a generic "closing channel" through out

**Comment by saubyk** [comment]
RTL invokes the API to close the channel and can only show the response it gets from the API.

What you are observing on the console is not returned in the API response, so cannot be shown on the UI.
