### ISSUE TITLE
Unable to Backup Channel.

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#235]
When I close a channel I receive this error:

![2020-01-19 21_14_51-192 168 1 195 - Remotedesktopverbindung](https://user-images.githubusercontent.com/60074674/72687973-68f44100-3b03-11ea-9c1d-8dd3c9f52973.png)

the error is unclear and doesn't tell me what the problem is

checking the Backup page i can see the this:
![2020-01-19 21_35_06-192 168 1 195 - Remotedesktopverbindung](https://user-images.githubusercontent.com/60074674/72687992-95a85880-3b03-11ea-92ab-5987cd544a7a.png)

Im guessing this means it's not set, but it's kinda unclear

and pressing verify all results in this error:
![2020-01-19 21_35_59-192 168 1 195 - Remotedesktopverbindung](https://user-images.githubusercontent.com/60074674/72688010-bffa1600-3b03-11ea-8df5-0d38d505ad2e.png)

the error is unclear and doesn't tell me what happened or what the problem is

and pressing backup all i get this error:
![2020-01-19 21_36_59-192 168 1 195 - Remotedesktopverbindung](https://user-images.githubusercontent.com/60074674/72688028-db652100-3b03-11ea-89a8-c2e9570f22be.png)

the error is unclear and doesn't tell me what happened or what the problem is

I don't recall ever configuring backup location, but i can't figure out where to change the backup location from the backup page. the backup page should display the information displayed under help on it somewhere (maybe as an ⓘ tooltip next to the title):

> Channel Backups are important to ensure that you have means to recover funds in case of node failures.
> Backup folder location can be customized in the RTL config file with the channelBackupPath field.
> RTL automatically creates all channel backup on server startup, as well as everytime a channel is opened or closed
> You can verify the all channel backup file by clicking on "Verify All" Button on the backup page.
> You can also backup each channel individually and verify them.
> ** Keep taking backups of your channels regularly and store them in redundant locations **.

Ideally The channel backup path should be configurable from the settings and/or backups page and not only with the RTL.conf, that way you can just display a message if the backup locations is not set like "please configure backup location under settings"

edit: after adding backup location (channelBackupPath=D:\RTL\channel_backups) to RTL.conf and restarting RTL i still get this on the Backup page:
![2020-01-19 21_35_06-192 168 1 195 - Remotedesktopverbindung](https://user-images.githubusercontent.com/60074674/72687992-95a85880-3b03-11ea-92ab-5987cd544a7a.png)

and stil get the same errors

**Comment by goodc0re** [comment]
I am observing the exact same problem. 
It must have started after one of the recent version upgrades, as backups were previously working.

**Comment by ShahanaFarooqui** [comment]
Fixed, will be available in next release.

**Comment by ShahanaFarooqui** [comment]
Regarding configurable channel backup path: This feature is already on our roadmap and will be covered, when it will be prioritized.
