### ISSUE TITLE
Scrolling position carry over

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#236]
when you scroll down on a long list like when you have displayed 100 payments per page and then switch to a different page, the position of scrolling is carried over and you just get a black screen. if you scroll all the way up again you can find the content you are looking for but if you don't know that it just looks like blank page

also all pages allow for infinite scrolling which makes the issue worse. ideally you should only be able to scroll down until the content stops.

1. Go to any page
2. scroll down pretty far
3. switch to any other page where the content is shorter (for example peers/cannels)
4. you should immediatly see your peers but instead you just get a black screen
5.) if you scroll all the way up again you can find the content

**Comment by ShahanaFarooqui** [comment]
Done, will be available in next release.
