### ISSUE TITLE
Unable to close channel error

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#237]
I tried closing a inactive channel and after a couple minutes of the spinning circle and "closing channel" i got this error:

![2020-01-19 23_06_14-192 168 1 195 - Remotedesktopverbindung](https://user-images.githubusercontent.com/60074674/72689340-a14e4c00-3b10-11ea-8ed3-3f6d95528cf7.png)

The error doesn't really tell my WHY the channel was not able to be closed

if it can't be closed I would expect it to force close it or give me the option to force close it and if that doesn't work i would like to get more detailed info on what happened.

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin, thanks for raising the issue. We use LND's REST APIs to manage these features thus we can only show as much information as the REST API returns to us. As you can already see in above attached image:

1: WHY the channel was not closed: We already have the space and logic to show the error message, if LND returns any. In this case, the empty 'Error Message' shows that REST API did return the error without specifying any reason.

2: If it can't be closed, it should be force closed: Whenever the channel is inactive, we are already sending the request to force close the channel. As the 'API URL' in above image shows 'force' parameter to be true.

3: Detailed info: Same as note 1. We can only show the error details when we receive it from LND.

Hope this helps to understand our limitations and dependency on LND REST. We are closing the issue as no further action is possible. Please feel free to reopen if needed.
