### ISSUE TITLE
RTL Server JS to TS migration and Linting

### ISSUE THREAD

**Issue by ShahanaFarooqui** [Ride-The-Lightning/RTL#238]
Migrate RTL server code from Javascript to Typescript.
Add TS Linting
Code cleanup

**Comment by bolatovumar** [comment]
Is this something that's been decided on and is on the roadmap or a suggestion?

**Comment by ShahanaFarooqui** [comment]
It is on the roadmap but we are unable to do it currently due to other high priority issues. We will appreciate a PR also :).

**Comment by ShahanaFarooqui** [comment]
Done with commit eff5bfa45fa70dd456f5ae4acadead80e936ff21.
