### ISSUE TITLE
RTL v0.6.3 shows wrongly as version v0.6.2

### ISSUE THREAD

**Issue by Amiga500** [Ride-The-Lightning/RTL#239]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
Tell us what happens instead

**Screenshots**

**Your environment**
* version of `lnd`
* operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

**Additional context**

**Comment by ShahanaFarooqui** [comment]
@Amiga500, Apologies for the confusion. We have updated the version number in 'master' branch for now and it will be correctly updated from next release onwards.

**Comment by Amiga500** [comment]
Thanks!
