### ISSUE TITLE
Sign / Verify messages 

### ISSUE THREAD

**Issue by alevchuk** [Ride-The-Lightning/RTL#240]
**Is your feature request related to a problem? Please describe.**
Without Sign / Verify messages lightning is purely anonymous. I'd like to be able to apply lightgtning in pseudonymous use cases which involves Sign / Verify. Without a UI users will have a hard time using lncli or c-lightning CLI.

**Describe the solution you'd like**
Similar to Zap https://github.com/LN-Zap/zap-desktop/issues/2023

**Describe alternatives you've considered**
CLI

**Comment by ShahanaFarooqui** [comment]
@saubyk Need more details to address it.

**Comment by ShahanaFarooqui** [comment]
@alevchuk Thanks for the suggestion.

The feature code has been merged into feature branch and will be release with v0.6.5.
