### ISSUE TITLE
Small, Non-Zero Invoice Rejected as Zero Amount Invoice

### ISSUE THREAD

**Issue by HamishMacEwan** [Ride-The-Lightning/RTL#241]
**Describe the bug**
This invoice is rejected as it pays < 1.0 sat.  850 milli-sats.

**To Reproduce**

Try to pay this invoice from RTL:

lnbc8500p1p0zk786pp5uxxuuqlrqsuqfn8u9fmxr4hwutzk23tdn2exszyv6n6ympecgr6sdphgfkx7cmtwd68yetpd5s9xct5v4kxc6t5v5s9gunpdeek66tnwd5k7mscqp2sp5qn4ra8r6ygzep4exmucnlpwxwvpkk638dlw8kg6mn0qm2ws7xwusrzjqvrmgda3plazqh4q4aa7nh22j6twxttq2ave6qy2gzyjtdl9jy2ggz2f3uqq8pgqqqqqqqlgqqqqqqgq9q9qy9qsqr29emuhd8vktqdtejgemz63pd9xjfepjzxhjy5delx0gm7x5krxyx8k06zs6zagzzq8rpzr6wx36wt3yx40xjrvkvxgc7rymyz3pp9qq4872wa

**Expected behavior**

The invoice to be paid.

**Actual behavior**

"It is a zero amount invoice. Enter the amount (Sats) to pay."

**Your environment**
* version of `lnd` 0.8.2
* operating system Linux myNode 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
* version of `bitcoind` v0.19.0
* Source of invoice https://satlite.space/send_broadcast  Use a single character as the message.  Enter 850 millisatoshis and generate the invoice.

**Comment by ShahanaFarooqui** [comment]
@HamishMacEwan Thanks for raising the issue. We fixed the issue with latest release 0.6.4 at our side but LND has fixed it with v0.9.0. With lnd v0.8.2, we are not receiving num_msat value and are still showing it as zero amount invoice. So, please upgrade both, lnd and RTL, in order to fix it.
