### ISSUE TITLE
Hanging after update

### ISSUE THREAD

**Issue by thephizzz** [Ride-The-Lightning/RTL#243]
**Describe the bug**
After upgrading to v0.6.1 and restarting rtl with 'node rtl', the program hangs at the 'Loading RTL...' page.

**To Reproduce**
1. Upgrade to v 0.6.1 using 'Update Existing Dependencies'
2. Start server 'node rtl'
3. Access localhost:3000
4. this is a multi-node configuration

**Expected behavior**
be presented with login page.

**Actual behavior**
program accesses http://192.168.1.237:3000/rtl/login and displays 'Loading RTL...'

**Screenshots**

**Your environment**
* version of `lnd`: 0.9.0-beta
* operating system: raspi debian
* version of `bitcoind`: v0.18.1
* multi-node environment. Previously working with rtl v0.4.2

**Additional context**

**Comment by ShahanaFarooqui** [comment]
@thephizzz There are some breaking changes in the release and config file needs to be manually updated for v0.6.1. Either upgrade RTL to v0.6.4-RC (v0.6.4 to be released today) OR please share your RTL config file after masking critical information.

**Comment by thephizzz** [comment]
Thank you.
After restarting lnd, i was able to login, but now i see no way to switch nodes.

**Comment by thephizzz** [comment]
Here is my multinode config:

{
  "multiPass": "################",
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "##########",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "/mnt/hdd/lnd/data/chain/bitcoin/mainnet",
        "lndConfigPath": ""
        },
      "Settings": {
        "flgSidenavOpened": "true",
        "flgSidenavPinned": "true",
        "menu": "Vertical",
        "menuType": "Regular",
        "theme": "dark-blue",
        "satsToBTC": "false",
        "channelBackupPath": "C:\\RTL\\backup\\node-1",
        "bitcoindConfigPath": "",
        "enableLogging": "true",
        "lndServerUrl": "https://192.168.#####:8080/v1"
        }
    },
    {
      "index": 2,
      "lnNode": "############",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "/mnt/hdd/xps"
        },
      "Settings": {
        "flgSidenavOpened": "true",
        "flgSidenavPinned": "true",
        "menu": "Vertical",
        "menuType": "Regular",
        "theme": "light-teal",
        "satsToBTC": "false",
        "channelBackupPath": "C:\\RTL\\backup\\node-2",
        "bitcoindConfigPath": "",
        "enableLogging": "true",
        "lndServerUrl": "https://192.168.####:8080/v1"
        }
    }
  ]
}

**Comment by ShahanaFarooqui** [comment]
@thephizzz you should be able to see the dropdown with existing nodes on the left top corner above navigation menu.

**Comment by ShahanaFarooqui** [comment]
Yup, the config needs some updates, give me 10 mins please :)

**Comment by ShahanaFarooqui** [comment]
@thephizzz, The config file needed some adjustments above 0.6.0 release (https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.6.0). With v0.6.4-RC and above, these manual changes will not be required anymore, as RTL server will upgrade the single & multi node configs on first server start. For now, either upgrade to 0.6.4-RC or use below JSON for the config:

{
  "multiPass": "################",
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "##########",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "/mnt/hdd/lnd/data/chain/bitcoin/mainnet"
      },
      "Settings": {
        "userPersona": "MERCHANT",
        "enableLogging": true,
        "fiatConversion": false,
        "themeMode": "NIGHT",
        "themeColor": "INDIGO",
        "channelBackupPath": "C:\\RTL\\backup\\node-1",
        "lnServerUrl": "https://192.168.#####:8080/v1"
      }
    },
    {
      "index": 2,
      "lnNode": "############",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "/mnt/hdd/xps"
      },
      "Settings": {
        "userPersona": "MERCHANT",
        "enableLogging": true,
        "fiatConversion": false,
        "themeMode": "DAY",
        "themeColor": "TEAL",
        "channelBackupPath": "C:\\RTL\\backup\\node-2",
        "lnServerUrl": "https://192.168.####:8080/v1"
      }
    }
  ]
}

**Comment by thephizzz** [comment]
Perfect!
That did it. Thank you.
Any major differences with 0.6.4-RC1?

**Comment by thephizzz** [comment]
I like the new interface. Very nice. Thank you for your work.

**Comment by ShahanaFarooqui** [comment]
Thank you for the feedback :). No major difference, only single & multi node config are deprecated, only one file named ‘RTL-Config.json’ will be used for all setups, RTL will generate/upgrade the existing config, C-lightning env setup was fixed and ‘DEFAULT’ authentication is deprecated (which is already irrelevant for existing multi node setup users).
