### ISSUE TITLE
Local Channel Rebalancing - LND

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#244]
With the LND v0.9.0, local re-balancing of channels is possible, by the nodes making circular payments to themselves. Since the payment is circular. This mechanism will not change the overall local/remote balance ratio of the channels on the node, but will effect the local/remote  balance ratio of the channels involved in the circular payment. Check that Version >= 0.9.0.

The channel balancing process will be executed with the following steps:
1. On the 'Peers/Channels' page, the user will select the channel to rebalance by clicking on the 'Local Rebalance' menu option from the 'Actions' menu.
2. User will enter the amount to rebalance on the channel
3. User will select the receiving node's alias through which the payment will be paid to self, and execute the re-balance.
4. The re-balance process will, generate an invoice for the amount selected by the user, and then execute the payments api to pay the invoice to self.

**Comment by saubyk** [comment]
Step 1:
User selects the channel to local-rebalance by clicking on the 'Local Rebalance' option from the 'Actions' menu.
![Channels - Local-Rebalance](https://user-images.githubusercontent.com/39208279/73322132-4e604d00-4212-11ea-8f12-9660062bd578.png)

**Comment by saubyk** [comment]
Step 2:
User specifies the amount to be used for balancing the channel. The maximum amount that the user can input is the local balance on the channel.
![Channels - Local-Rebalance-selection](https://user-images.githubusercontent.com/39208279/73322383-af882080-4212-11ea-9d84-bdc02c594857.png)

**Comment by saubyk** [comment]
Step 3:
User selects the receiving node alias, which will be used to return back the payment on the node. The node selection available for the user should be based on the amount user has input to balance. The selection should only be a list of aliases with channels, having remote balances more than the amount selected.

**Comment by saubyk** [comment]
Step 4:
RTL should execute the following steps to complete the circular payment.
1. Create an invoice with the amount specified by the user to balance the channel with.
2. Pay the invoice with the following options:
API - `POST /v1/channels/transactions`
`outgoing_chan_id` set as the channel which has been selected by the user
`last_hop_pubkey` set as the pub key selected by the user
`allow_self_payment` set as `true`
`payment_request` set as the bolt11 invoice generated in the previous step.

**Comment by MrManPew** [comment]
Hi @saubyk  I think you should also add the `--fee_limit` option

**Comment by ShahanaFarooqui** [comment]
Done, pushed in 0.6.5 branch.
