### ISSUE TITLE
Transaction Info display path as alias <-> alias

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#246]
on the transaction page when you click "view info" you get the path as a long string of numbers. this doesnt tell me much. I would like for it to display as "alice <-> bob" so i can understand which path/peer it took

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin Thanks for the suggestion.

We pushed the code for this enhancement to feature branch and will release it with v0.6.5.
