### ISSUE TITLE
Channel information: add date/time + blockheight + age in days

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#248]
On the Peer/channel page when i click "actions -> View info" on a channel i get information about that channel, but I can't tell how old the channel is with the information displayed. I think it should have 3 additional fields:

Opening Blockheight
Opening Date/Time
Age (Days since opening)

that way i know when exactly the channel was opened and how long ago that was at a glance without having to use the CLI. it would be nice if the age could also be added as a column in the overview, or if the overview is getting to crowded make the columns displayed configurable.

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin Thank for opening the issue. The information was added with v0.6.5. Closing it now.
