### ISSUE TITLE
Channel information: Display channel active/inactive %

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#249]
On the Peers/channels page under view info on a channel It would be nice if the showed a "active time" as a % of active vs inactive if at all possible.

so if a channel is almost always active it would show: 99%
and if its down/inactive half the time it would show: 50%

If that information isn't available from LND one possible solution would be for RTL to take a snapshot of all the channel states (active/inactive) every X minutes and save that and then use that to calculate an approx "uptime"-% for each channel

It would also be nice to get a "last seen" for inactive channels, (just display the date/time the channel was last active und view info). right now if i'm looking at a inactive channel i don't know if it was last up a year ago or yesterday

may be related to: https://github.com/Ride-The-Lightning/RTL/issues/82

**Comment by saubyk** [comment]
Closing this ticket as RTL is not maintaining any local data on the node other than the config params or the channel backups.
