### ISSUE TITLE
Left sidebar sometimes overlaps content

### ISSUE THREAD

**Issue by bolatovumar** [Ride-The-Lightning/RTL#251]
**Describe the bug**
Left sidebar sometimes overlaps main content and there is nothing one can do to fix it outside of reloading the page. Sometimes even that doesn't help and the page has to be reloaded multiple times.

**To Reproduce**
1. Click around the app and notice that the sidebar sometimes overlaps content

**Expected behavior**
Sidebar should never overlap content.

**Actual behavior**
Sidebar overlaps content sometimes.

**Screenshots**
![Screen Shot 2020-02-02 at 7 42 29 PM](https://user-images.githubusercontent.com/1934678/73624546-1da75b80-45f6-11ea-9519-0d2a8df6c36c.png)

**Your environment**
* operating system: macOS Mojave 10.14.6
* browser: Chrome 65
* RTL version: dc0581b3ab593d5bf8f77b4a2ade0d2be8bc2b1f

**Additional context**
I'm using macOS on Mac Air 13" with my browser window taking up about 75% of the screen. This may not be an issue on larger screens or when the browser window is full-screen.

**Comment by ShahanaFarooqui** [comment]
@bolatovumar  
This can be reset by pinning/unpinning the 'Side Navigation Menu' from top left corner of the screen.

![image](https://user-images.githubusercontent.com/23240721/73677372-1d55a180-4684-11ea-92e0-302514c487f9.png)

But, this overlap setting used to be a feature in RTL's <0.6 versions and has been removed from config settings with 0.6.0 release. It looks like your config file still have these flags. Please check release notes at https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.6.0 and ensure that 'flgSidenavOpened' and 'flgSidenavPinned' do not exist in your config anymore.

Or 

You can share your RTL.conf/RTL-Multi-Node-Conf.json/RTL-Config.json file after masking sensitive information and we will modify them according to the new format. Also note that RTL.conf & RTL-Multi-Node-Conf.json configuration files are deprecated from 0.6.4, details can be checked at https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.6.4.

**Comment by ShahanaFarooqui** [comment]
It can be another issue with Material SideNav container which is discussed [here](https://github.com/angular/components/issues/6743). 

We decided to fix it with the help of renderer rather than using 'autoSize' property to keep the time complexity low.

**Comment by ShahanaFarooqui** [comment]
Pushed the fix into feature/0.6.5 branch and will be released in the next version.

**Comment by bolatovumar** [comment]
@ShahanaFarooqui thanks. I'm using the latest configuration file and I don't have the `flgSidenavOpened` flag so it must be some sort of UI issue.
