### ISSUE TITLE
Incorrect Channel ID Search Yields Screen-Freeze

### ISSUE THREAD

**Issue by PaulKania** [Ride-The-Lightning/RTL#252]
**Describe the bug**
If you lookup a channel ID that doesn't exist, an empty error dialogue box occurs, and worse yet. it won't close. the screen is effectively locked and requires a reload.

**To Reproduce**
Lightning-> Graph Lookup:
Search Toggle On Channel (Not Node): If an incorrect Channel ID is inputted And you then confirm your entry AKA press lookup, an empty error code dialogue box appears, and it is impossible to exit it, requiring instead to reload the page.

**Expected behavior**
show error.
allow exiting from error and continuing about my day.

**Actual behavior**
site freezes, requires reload

**Screenshots**
attempting to look
![rtl_issue_screen](https://user-images.githubusercontent.com/4791983/73805992-3fd7df80-4796-11ea-937d-379e5ddef7f9.png)

**Your environment**
* version of `lnd` --- 0.9.0.beta
* operating system --- Windows 10
* version of `btcd`, `bitcoind` -- bitcoind

Additional: using localhost.

**Comment by ShahanaFarooqui** [comment]
@PaulKania Thanks for raising the issue.

The fix has been pushed to feature branch and will be released with v0.6.5.
