### ISSUE TITLE
RTL 0.6.4 sweep all inoperative

### ISSUE THREAD

**Issue by seth586** [Ride-The-Lightning/RTL#253]
**Describe the bug**
Sweep all function does not appear to work.

**To Reproduce**
1. Go to 'on chain'
2. Click on 'sweep all'
3. Fill out address and sat/byte
4. Click 'send funds'
5. Nothing happens

**Your environment**
* lnd 0.9.0
* operating system FreeBSD 11.2
* version of bitcoind 0.19.0.1
* command line `lncli -lnddir "/var/db/lnd" sendcoins --sweepall --sat_per_byte 1 [address]` runs sucessfully

**Comment by ShahanaFarooqui** [comment]
@seth586, Thanks for opening the issue.

The fix has been pushed in the feature branch. It will be released in next version 0.6.5.
