### ISSUE TITLE
500 Error : checksum failed . Send Payment Failed

### ISSUE THREAD

**Issue by emonazad** [Ride-The-Lightning/RTL#257]
**Describe the bug**
Hi , when i try to pay invoice i get error : 

```

> Send Payment Failed
> Error Code
> 500
> Error Message
> checksum failed. Expected xz9p9y, got 20af6r.
> API URL
> ./api/lnd/channels/transactions

```

**To Reproduce**
1. Go to RTL
2. Click on Pay Invoice

**Expected behavior**
Invoice paid sucessfully

**Actual behavior**
Send Payment Failed 500 Error

**Your environment**
* version of `lnd`  Version: 0.9.0-beta commit=v0.9.0-beta-68-g2cd26d75564345c0c37fa83785ebe8e4f1fb8f28, build=production, logging=default
* operating system (`uname -a` on *Nix) Ubuntu 16.04 64 bIt
* version of `btcd`, `bitcoind`, or other backend 
* any other relevant environment details

**Additional context**

**Comment by ShahanaFarooqui** [comment]
@emonazad Looks like you are using an older version of RTL where POST queries were failing. Please upgrade RTL to v0.6.7. I tested the payment feature with the latest release and it is working as expected.

**Comment by emonazad** [comment]
> 
> 
> @emonazad Looks like you are using an older version of RTL where POST queries were failing. Please upgrade RTL to v0.6.7. I tested the payment feature with the latest release and it is working as expected.

Thanks ! . i will update the RTL and inform here.

**Comment by emonazad** [comment]
> 
> 
> @emonazad Looks like you are using an older version of RTL where POST queries were failing. Please upgrade RTL to v0.6.7. I tested the payment feature with the latest release and it is working as expected.

Thanks ! . i will update the RTL and inform here. 

> 
> 
> @emonazad Looks like you are using an older version of RTL where POST queries were failing. Please upgrade RTL to v0.6.7. I tested the payment feature with the latest release and it is working as expected.

i deleted the old RTL and downloaded the : Release v0.6.7-CLT-POST-Bug-fix

Installed by npm and started but i see the error again . 

at lncli when i do the payment i works (invoice) , did i mistake anywhere ?

**Comment by ShahanaFarooqui** [comment]
Can you try with any other invoice? The error 'checksum failed. Expected xz9p9y, got 20af6r.' is being returned by LND, so either the invoice number is incorrect or LND has to debug the issue at their end.

**Comment by emonazad** [comment]
> Can you try with any other invoice? The error 'checksum failed. Expected xz9p9y, got 20af6r.' is being returned by LND, so either the invoice number is incorrect or LND has to debug the issue at their end.

Today after restarting server issue has been solved now i see i can pay every invoice that i have created .
