### ISSUE TITLE
Password shouldn't be mandatory if SSO is turned on

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#264]
**Is your feature request related to a problem? Please describe.**
I've started looking at how to integrate RTL in [my project](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/) and from my understanding of the documentation, password is mandatory even if SSO is turned on. This is problematic for automatic integration.

**Describe the solution you'd like**
When SSO is turned on, and password isn't specified, just reject all requests without cookie. Don't mandate password in this case.

**Describe alternatives you've considered**
Generating garbage password by some external tool (`head -c 18 /dev/urandom | base64`). This would work, but increase complexity of integration. I guess making password optional is easier to do, but maybe I'm wrong.

**Additional context**
N/A

**Comment by ShahanaFarooqui** [comment]
@Kixunil Good catch, we recently deprecated single node configuration and before that, multinode setup was not allowed with SSO. Password should not be required with multinode.

**Comment by ShahanaFarooqui** [comment]
Pushed the fix to 'loop' branch, will be released in the next version.

**Comment by Kixunil** [comment]
Awesome, thanks a lot! Any ETA when the new version is released?

**Comment by ShahanaFarooqui** [comment]
We are almost ready with the code updates but waiting till LND loop team fixes below issues for our next release to be able to work as expected. So, anytime soon :)

https://github.com/lightninglabs/loop/issues/142
https://github.com/lightninglabs/loop/issues/157
