### ISSUE TITLE
Make RTL configurable from UI

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#265]
**Is your feature request related to a problem? Please describe.**
When attempting to make RTL more easily accessible, I notice that there's lot of configuration options in the configuration file that aren't critical for it to function. Like theme, persona... These should be configurable from the UI, rather than config file.

**Describe the solution you'd like**
Some kind of settings page to configure all this stuff (pretty much everything outside ports, authentication, etc) with reasonable defaults, so that integration scripts only need to fill connection information into the config file.

**Describe alternatives you've considered**
Making some kind of external UI for configuring RTL. While technically possible, I don't think that this kind of fracturing has any important benefit. It's integral part of RTL, so it makes sense to bundle it in.

**Additional context**
N/A

**Comment by ShahanaFarooqui** [comment]
Closing the issue as it is already under progress [here](https://github.com/Ride-The-Lightning/RTL-Design/issues/28)

**Comment by ShahanaFarooqui** [comment]
BTW, Some non critical settings already configurable through UI 'Settings' menu. But, we are working on UX to configure all the settings through UI itself.

![image](https://user-images.githubusercontent.com/23240721/75381349-996b8f80-58a6-11ea-8e53-e05b3c3a8b73.png)

**Comment by Kixunil** [comment]
Ah, sorry, was confused by the name of the issue, thought it has something to do with multiple nodes.

Thanks for letting me know!

**Comment by Kixunil** [comment]
Where is the state stored, BTW?

**Comment by Kixunil** [comment]
Yes, that, thanks! Any plans to make it stored somewhere else? It'd be nice to be able to make a proper Linux service with read-only configuration (nodes mainly) in `/etc` and dynamic content in `/var/lib/rtl`. Not a critical issue, for now I can work with `/var/lib/rtl` only, without `/etc`.

**Comment by Kixunil** [comment]
Thanks!
