### ISSUE TITLE
c-lightning invoice labels incorrect

### ISSUE THREAD

**Issue by k3tan172** [Ride-The-Lightning/RTL#271]
**Describe the bug**
c-lightning invoice labels incorrect

**To Reproduce**
1. Go to Lightning > Transactions > Invoices tab

**Expected behavior**
Invoice "Label" column to be readable in English

**Actual behavior**
Invoice labels are what appears to be encoded.
Note there is some nuances with description field and label field when creating an invoice. It appears the 'description' when creating an invoice is put into the Label column. However, when an invoice is generated with btcpayserver or spark-wallet, it is encoded. 

**Your environment**
* c-lightning 0.8.1
* ubuntu

**Comment by ShahanaFarooqui** [comment]
Invoices table will show 'Description' field now. Removed 'label' input from create invoice as well. Now, Label will be auto generated Unique ID.
