### ISSUE TITLE
Invoice re-use logic for circular re-balancing is broken

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#273]
Unsettled Invoices are not being re-used for circular rebalancing re-tries.

**Comment by ShahanaFarooqui** [comment]
@saubyk The logic was not broken for invoice reuse. It was working on testnet and failing on mainnet due to different response for settle_date values. On LND testnet, if the invoice is not settled, it does not return the 'settle_date' field but on mainnet, it return the 'settle_date' as '0'.
