### ISSUE TITLE
Show node name in closed channels history

### ISSUE THREAD

**Issue by MrManPew** [Ride-The-Lightning/RTL#275]
It would be very efficient to see the node name in the closed channel history:

![image](https://user-images.githubusercontent.com/35897350/76388955-f79e7500-6372-11ea-9558-bf0388a669ed.png)

**Comment by ShahanaFarooqui** [comment]
Related issue: 
https://github.com/Ride-The-Lightning/RTL/issues/285

**Comment by ShahanaFarooqui** [comment]
Done with PR #336.
