### ISSUE TITLE
Persistence info so I can create a docker volume

### ISSUE THREAD

**Issue by iangregsondev** [Ride-The-Lightning/RTL#276]
Hi,

I am using your docker image for creating RTL, when ever I update the settings, i.e. password for example and redeploy the docker from the image - I lose the settings I created.

This is easily overcome with a volume but I am not sure where RTL saves its settings, can you help.

I have done an ls in the container and I see this

```
/ # cd RTL/
/RTL # ls
Dockerfile              README.md               angular.json            controllers             node_modules            product management      sample-RTL-Config.json  tslint.json
Dockerfile.arm32v7      RTL-Config.json         app.js                  docker                  package-lock.json       protractor.conf.js      screenshots
Dockerfile.arm64v8      _config.yml             common.js               docs                    package.json            routes                  src
LICENSE                 angular                 connect.js              e2e                     prebuild.js             rtl.js                  tsconfig.json
```

I am currently using the following in my compose.

```
  rtl1:
    image: shahanafarooqui/rtl:0.6.7
    volumes:
      - lnd1-data:/lnd:ro

    networks:
      - net
      - traefik
```

Any ideas? 

Thanks in advance

**Comment by iangregsondev** [comment]
Are you just updating the RTL config json file ?

**Comment by ShahanaFarooqui** [comment]
Yes, RTL-Config.json is your file.

**Comment by iangregsondev** [comment]
Ok thank you. One quick question also, the latest version, the fee panel has a red outline and doesn't seen to update

![image](https://user-images.githubusercontent.com/2370364/76644353-22e1b980-6557-11ea-8d3d-5f3c823271dd.png)

**Comment by ShahanaFarooqui** [comment]
Seems like you recently initiated/unlocked your lnd wallet...refreshing after 2-5 mins should fix the error.

**Comment by iangregsondev** [comment]
I don't think its that as it never recovers. I do see the following in the network tab

![image](https://user-images.githubusercontent.com/2370364/76650749-87a31100-6563-11ea-81fb-ab7783764b97.png)

**Comment by iangregsondev** [comment]
Actually I have 2 x lnd nodes - they both do the same. Strange.

**Comment by iangregsondev** [comment]
i should probably mentioned.

1 x bitcoind

2 x lnd

and 2 x rtl - each point to its own lnd.

**Comment by ShahanaFarooqui** [comment]
That is strange. I am assuming that, you are using same RTL with multinode setup for both LND instances.

1) Can you try to fetch fee report directly from LND. something like..https://<your-node-ip>:<lnd-port>/v1/fees

2) Are you getting any data of 'Routing' page? Routing and fee report are 'kind of' interconnected in RTL.

3) Can you share your RTL logs? Usual log path is '<rtl-root>/logs/RTL-Node-<node-index>.log

**Comment by iangregsondev** [comment]
Sorry for the delay. I am on it now. here is the logs.

[RTL-Node-1.log](https://github.com/Ride-The-Lightning/RTL/files/4339658/RTL-Node-1.log)

Yes The routing page works pretty well or seems to

![image](https://user-images.githubusercontent.com/2370364/76787267-ef9e6500-67b8-11ea-8ae0-4eda17abb9f5.png)

**Comment by iangregsondev** [comment]
I hope that helps, I can't call the endpoint right now - as I need to pass in the macaroons and things like that.. need to get into the docker container..

I will look at it now

But i notice in the chromedev tools that RTL is calling the fees and gets 500 and returns this

```
{"message":"Fetching fee failed!","error":{"error":"no policy for outgoing channel 1831772078236434433 ","message":"no policy for outgoing channel 1831772078236434433 ","code":2,"details":[]}}
```

**Comment by iangregsondev** [comment]
This was an example from lnd1 and rtl1 - I have another lnd2 and rtl2 and i get ..

```
{"message":"Fetching fee failed!","error":{"error":"no policy for outgoing channel 1831772078236368896 ","message":"no policy for outgoing channel 1831772078236368896 ","code":2,"details":[]}}
```

So same error but different channel

**Comment by iangregsondev** [comment]
when creating a new channel I chose the default

![image](https://user-images.githubusercontent.com/2370364/76787967-540df400-67ba-11ea-8797-94d7c1ef87c1.png)

**Comment by ShahanaFarooqui** [comment]
@iangregsondev, This issue is related to LND and has to be address/fixed by them. Please check on the LND's slack or open an issue on github.

**Comment by iangregsondev** [comment]
Ok thank you. I will close this. I will try and investigate it.
