### ISSUE TITLE
set Hourglass animation when logging to RTL

### ISSUE THREAD

**Issue by MrManPew** [Ride-The-Lightning/RTL#277]
**Is your feature request related to a problem? Please describe.**
Log-ing in (the time after entering the password and clicking login) to RTL takes a couple of seconds (sometimes 10 seconds) depending on the amount of channels that one have. I think it will be very effect (especially for new users) if there was some kind of an hourglass [animation ](https://www.google.com/url?sa=i&url=https%3A%2F%2Fdribbble.com%2Fshots%2F2538227-Animated-SVG-Hourglass-Preloader&psig=AOvVaw3PcPmepcoBCnnKyEGSd-zc&ust=1584271506359000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLin57XtmegCFQAAAAAdAAAAABAD) that was running while RTL is loading, or even that it will write... Please wait loading node information.

Best

**Comment by ShahanaFarooqui** [comment]
@MrManPew, RTL does NOT take any time between login and dashboard load. Can you please confirm  your RTL version?

**Comment by MrManPew** [comment]
Thanks, but when you have many channels it does:

![ezgif-6-c0c1a58fc08c](https://user-images.githubusercontent.com/35897350/86478193-91d75e00-bd52-11ea-897b-ed7ce0f9e368.gif)
About 8 seconds

**Comment by ShahanaFarooqui** [comment]
@MrManPew thanks for the helpful snippet. Will try to reproduce the same at my end.

**Comment by ShahanaFarooqui** [comment]
Added spinner till the node data is not loaded with PR #374. Will be released with v0.8.0.
