### ISSUE TITLE
Lightning payment doesnt work

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#283]
When I try to do a payment the window just dissapears and nothing happens. the transaction is not listed in the payments history and doesnt get paid. there is no error.

I've tried this on 2 seperate lnd with rtl 0.6.8 and 0.7.0 and it's the same issue. I can still pay the invoice from the CLI no problem. I cannot pay the invoice using rtl. nothing happens and in LND console i get this error:

[ERR] RPCS: [/lnrpc.Lightning/SendPaymentSync]: checksum failed. Expected atuqrp, got wzz8es.

I restarted lnd and rtl and the issue still persists

**Comment by saubyk** [comment]
hi @sendbitcoin 
Can you provide a sample invoice, which you are trying to pay?

**Comment by sendbitcoin** [comment]
Amount Requested
420 Sats
Memo
Test RTL payment

expires in 10 days

generated on RTL 0.6.8 using LND 0.8.2 inside btcpayserver docker deployment

lnbc4200n1p08kfa8pp5uycuhfx763ukhpurdm34k4cywqwtkh7w76d3qgwp6t88qtg59cysdq623jhxapq2f2ycgrsv9uk6etwwscqzpgxqy6tcqecwh3ahl4srhtexzqkgap5xe78gck27vls54vlfv8tygf9yj8204242c8elwlvw3jgstc0y5le297t3ade4vtjkhychcguvvm2zdngsp3z3tlj

------------------------------------------------------------
Amount Requested
69 Sats
Memo
RTL payment test #2 

expires in 10 days

generated on RTL 0.7.0 using LND 0.9.0 on windows

lnbc690n1p08k2y6pp502m7pgkmgrvd57d2mz8krvva7fw9pqgrer4ga2ky0gsyh344dmysdpq2f2ycgrsv9uk6etwwss8getnwsszxv3qcqzpgxqy6tcqsp5f3yexl8tm5hzvhem0t9t93wrazgh7nlf36fjusqxpvdhhzx26rdq9qy9qsqrtglmx20wtgh4hrfcg3xhurttvy7e2g7yyt0h73d8plj0pshadfqz5tvktnzdfh5sdasmc2gr2qkd9at75unywmycxz260xkd5pk60cpd4mxum


I can't pay either using RTL

**Comment by sendbitcoin** [comment]
oh and I only started noticing this issue after I tried using the "first outgoing channel" option. may be related but perhaps it's just a coincedence and completely unrelated as right now i can't pay any invoices at all using RTL.

just something to keep in mind

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin Hi, the issue seems to be related to LND not RTL. We opened an issue on LND's github [here](https://github.com/lightningnetwork/lnd/issues/4171). 

Can you please share a new non-expired request on that issue for debugging. Thanks.

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin Can you please share your browser details. Another user was facing the same issue on Firefox 74.0.1 64bit but Safari worked fine. For some reason, Firefox pasted the payment requested twice in the input box.

**Comment by eatocia** [comment]
Same issue with Firefox 75.0 64, Safari worked fine

**Comment by ShahanaFarooqui** [comment]
Fixed by PR #309

**Comment by bitcoinheiro** [comment]
Experiencing same issue here with latest Tor Browser
