### ISSUE TITLE
Channel Uptime as hours displayed/calculated wrong

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#284]
under Peer/channels the uptime displayed as days/hours doesnt seem to be calculated correctly.

probably introduced with: #258

inactive channels are showing null:null or 00:00

all other channels are showing 02:09 - 02:17

![2020-03-25 10_56_14-192 168 1 195 - Remotedesktopverbindung](https://user-images.githubusercontent.com/60074674/77524487-b4222b80-6e87-11ea-8546-243309d5f881.png)

**Comment by ShahanaFarooqui** [comment]
Fixed with PR #329
