### ISSUE TITLE
btcd support?

### ISSUE THREAD

**Issue by cilphex** [Ride-The-Lightning/RTL#293]
**Is your feature request related to a problem? Please describe.**

I'm trying to decide to use btcd or bitcoind in my project, so curious if RTL supports both. My intuition would be that RTL is an interface to the lightning node and doesn't care about what type of bitcoin node the lightning node is talking to, but I see that there is a `bitcoindConfigPath` settings field in `RTL-Config.json`, so I'm not sure.

**Describe the solution you'd like**

Don't know the software well enough yet, but I suppose RTL would ideally not need any bitcoin node settings at all. If it does need them, it would be nice to have support for more than just bitcoind.

**Describe alternatives you've considered**

btcd.

**Additional context**

No additional context.

**Comment by saubyk** [comment]
RTL does not have any interaction with the Bitcoin layer. It interfaces only with lightning.
`bitcoindConfigPath` config setting was just provided as a convenient tool to read the config file from RTL. There is no functionality in RTL dependent on the underlying Bitcoin layer.

Closing this issue. Thanks.
