### ISSUE TITLE
Wallet unlock page does not render error

### ISSUE THREAD

**Issue by cilphex** [Ride-The-Lightning/RTL#298]
**Describe the bug**

RTL has a wallet unlock page located at `localhost:3000/rtl/lnd/wallet`. If RTL cannot connect to LND, then the RTL server will return an error, but the page does not show this error anywhere.

**To Reproduce**

1. Build new RTL container
2. Start RTL without starting LND
3. Sign in to RTL at localhost:3000
4. Go to localhost:3000/rtl/lnd/wallet (you should be brought here automatically after sign-in)
5. Enter a non-existent wallet password (like "bedbug")
6. Click "Unlock Wallet"

**Expected behavior**

I expect the page to show an error

**Actual behavior**

No error is displayed

**Screenshots**

![Screen Shot 2020-03-30 at 5 17 05 PM](https://user-images.githubusercontent.com/611803/77974206-4c1a7d80-72ab-11ea-9491-b69c6698fa0c.png)

**Your environment**

* LND not running or running but not reachable by RTL due to improper configuration
* RTL running in docker

**Additional context**

The specific error returned is a 500 with this content:

```
{"message":"Unlocking wallet failed! Verify that lnd is running and the wallet is locked!","error":"connect ECONNREFUSED 127.0.0.1:8080"}
```

**Comment by ShahanaFarooqui** [comment]
Fixed with PR #321
