### ISSUE TITLE
Wallet initialize page does not render error

### ISSUE THREAD

**Issue by cilphex** [Ride-The-Lightning/RTL#299]
**Describe the bug**

The wallet "initialize" page does not render an error upon submit, if LND is not running or unreachable.

**To Reproduce**

1. Build new RTL container
2. Stop LND or make it unreachable
3. Sign in to RTL
4. Navigate to localhost:3000/rtl/lnd/wallet
5. Enter a random wallet password
6. Use defaults for "cipher" and "passphrase" steps
7. Click "initialize wallet"

**Expected behavior**

I expect the page to render a descriptive error.

**Actual behavior**

The page does not render an error

**Screenshots**

![Screen Shot 2020-03-30 at 5 27 26 PM](https://user-images.githubusercontent.com/611803/77974479-22ae2180-72ac-11ea-81ec-d77db08f7b99.png)

**Your environment**

- LND not running or running but not reachable by RTL due to improper configuration
- RTL running in docker

**Additional context**

The specific error returned is a 500 with this content:

```
{"message":"Genseed failed!","error":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8080}}
```

**Comment by ShahanaFarooqui** [comment]
Fixed with PR #321
