### ISSUE TITLE
Add LND Faraday support

### ISSUE THREAD

**Issue by MitchellCash** [Ride-The-Lightning/RTL#301]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to see Faraday support in RTL to see insights into my LND node and track metrics like underperforming channels and channel close recommendations.

Faraday is built by Lightning Labs (https://github.com/lightninglabs/faraday).

**Comment by saubyk** [comment]
@MitchellCash Faraday currently does not have API support. Integration with RTL would require APIs.

**Comment by MitchellCash** [comment]
@saubyk I think it already had a RPC API, but REST API support was also just merged in today (https://github.com/lightninglabs/faraday/pull/20). Was this what you would be looking for?

**Comment by MitchellCash** [comment]
@saubyk I have only just seen you made the original issue on the faraday repo for REST API support! Thanks for prompting that to happen 😃

**Comment by ShahanaFarooqui** [comment]
Closing this as there is lack of clarity on the requirement.
