### ISSUE TITLE
RTL attempts to open RTL-Config.json for writing

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#307]
**Describe the bug**
When RTL-Config.json is placed into `/etc`, which is a standard location for read-only configuration files, RTL fails with `EACCESS`

**To Reproduce**
1. sudo mkdir /etc/ridetheln
2. sudo vim /etc/ridetheln/RTL-Config.json
3. RTL_CONFIG_PATH=/etc/ridetheln-system nodejs rtl.js

**Expected behavior**
RTL starts and serves the application on configured port, using configured lightning nodes

**Actual behavior**
RTL aborts with `EACCESS`

**Screenshots**

**Your environment**
* version of `lnd`
* operating system (`uname -a` on *Nix)
* version of `btcd`, `bitcoind`, or other backend
* any other relevant environment details

**Additional context**

**Comment by saubyk** [comment]
We are expecting RTL's config file to be located in /RTL folder. Besides config files of Bitcoin or LND or C-Lightning implementations are also not located in `/etc` folder, so it does not make sense for RTL to implement this as a standard.
If you do want to place the config file, in that folder for your implementation, please make sure you run the server with the user, which has access to read and write the file in that location.

Another important thing to note is that RTL-Config.json file is *not* a read only file. Any user preferences set by the user like day-night mode or skin selection or persona etc. are all saved in the config file and RTL needs access to write to the config file.

Closing this ticket.

**Comment by Kixunil** [comment]
Yeah, I figured it's not a config file, but a database. :) Bitcoind and LND **do** work in `/etc` when launched with proper argument, because their config files are not databases. Found a workaround for this anyway and forgot to close. Thanks!
