### ISSUE TITLE
Make backups optional

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#310]
**Is your feature request related to a problem? Please describe.**
Backups embedded in **GUI** application have number of issue, such as:
* Increase the complexity of application, making it more likely to fail (I still can't launch RTL because of that)
* Don't really help, as they are basically copying the data within the same storage. If the storage fails, both the original data and the backup are lost.
* Are redundant if a separate, more appropriate backup scheme is implemented.

**Describe the solution you'd like**
A global configuration option `disableBackups = true` could turn off backups completely.

**Describe alternatives you've considered**
* Spending more time trying to make RTL work, ignore redundancy of backups
* Writing my own backend from scratch in a different language I'm familiar with.

**Additional context**
I'm hitting this error: `no such file or directory, open '/var/lib/ridetheln-system/backup/node-1/channel-all.bak'`
`/var/lib/ridetheln-system/` exists and has proper permissions, so clearly RTL fails to create the directory structure it needs before attempting to open the file.

**Comment by saubyk** [comment]
We want to force the user to configure the backup folder location to ensure that a channel backups are created by RTL. Providing optionality around backups is not an advisable strategy, especially when this technology is still new and new users are coming onboard all the time, with limited or zero operational understanding of LN.

Unfortunately, the functionality of creating redundant copies of backups is not something which RTL can implement, but we do post a persistent warning on the backups page to continue to remind users to do the same on their own.

Node hardware implementors integrating RTL in their solutions can implement a strategy to keep redundant copy of backup files.

Additionally, we can also consider providing options to the users to upload backups files to a cloud storage like Google or Dropbox.

Closing this issue with the above explanation, as making backups optional is not something we are considering. Thanks.

**Comment by Kixunil** [comment]
Thank you for your answer!

I'm currently actively working on a solution of achieving redundant backups, and I believe that anything about backups in the UI would only confuse the users. I want to have a completely separate facility that also backups other stuff (e.g. BTCPay database). I prefer to avoid duplicating the logic.

Would you consider at least hiding the backup stuff from the UI? I might be do the PR when I need it if you don't have the time.
