### ISSUE TITLE
Bogus warning about unsecure connection when forwarding using nginx.

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#312]
**Describe the bug**
When forwarding the traffic using nginx to secure the traffic, RTL still complains about unsecure connection in the wallet initialization tab. I have same headers set as for BTCPay:
```
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

**To Reproduce**
1. Setup empty LND
2. Setup frowarding for RTL on nginx
3. Go to initialization tab
4. See warning

**Screenshots**
![rtl-bogus-warning](https://user-images.githubusercontent.com/1178779/79256094-b7597780-7e87-11ea-892b-5c81962752cc.png)

**Your environment**
* Version of `RTL` 0.7.0
* Version of `lnd` 0.8.0
* Version of `btcd`, `bitcoind`, or other backend bitcoind 0.18.1
* Browser & browser version firefox 68.7.0esr
* Operating system (`uname -a` on *Nix) Linux disp5398 4.19.107-1.pvops.qubes.x86_64 #1 SMP Sat Feb 29 16:04:42 UTC 2020 x86_64 GNU/Linux

**Additional context**
The same warning is **not** present at unlock tab.

**Comment by ShahanaFarooqui** [comment]
Fixed with PR #316
