### ISSUE TITLE
Confusing configuration keys referring to directories

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#313]
**Describe the bug**
The configuration keys like `RTL_CONFIG_PATH` and `macaroon_path` are confusing, because it's not apparent that they point to directories. I did the mistake of supplying direct paths twice already. I suggest to rename them:

* `RTL_CONFIG_PATH` to `RTL_DATA_DIR`
* `macaroonPath` to `macaroonDir` or even better, don't append `/admin.macaroon` at the end. (Doing so is extremely non-standard and I didn't see such handling of macaroons in any other software.)
* Do similar for any other files that I didn't encountered yet

**To Reproduce**
1. Give the task of configuring RTL to several sysadmins that don't know its internals
2. Observe them setting `macaroonPath` to `/var/lib/lnd-mainnet/admin.macaroon` instead of `/var/lib/lnd-mainnet` and being confused

**Your environment**
* Version of `RTL` 0.7.0
The rest of environment isn't related.

**Comment by saubyk** [comment]
This is not something we can change at this stage, as we have the solution integrated with multiple node solution providers, as it will risk breaking their implementations.

We are planning to address this peculiarity by provide a UI for the setup, so the regular users does not have to manually edit the config file.

**Comment by Kixunil** [comment]
How about phasing it out slowly? I'd imagine this sequence:

* Create aliases that are named `*Dir`
* If `*Path` is set, emit deprecation warnings
* Keep it so for a while, possibly contact specific providers explicitly
* Make `*Path` hard error (abort RTL) and keep it for a few releases
* Maybe later reintroduce it doing exactly what one would expect.
