### ISSUE TITLE
On-Chain transaction details non scrollable

### ISSUE THREAD

**Issue by ketominer** [Ride-The-Lightning/RTL#324]
**Describe the bug**
The details of on-chain transactions are not scrollable so transactions with a lot if inputs/outputs are not fully visible

**To Reproduce**
Click View Info on a transaction with a lot of inputs and/or outputs

**Screenshots**
<img width="1787" alt="Screenshot 2020-04-19 at 14 41 07" src="https://user-images.githubusercontent.com/43620256/79688140-847aff00-824c-11ea-8f7e-4f1280d90051.png">

**Your environment**
* Version of `RTL` : 0.7.0-beta

**Comment by ShahanaFarooqui** [comment]
Fixed with PR #333
