### ISSUE TITLE
Compactify RTL into fewer files?

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#330]
**Is your feature request related to a problem? Please describe.**
Building and installing Debian package for RTL is currently extremely slow process, presumably because of many files in the directory after node modules are downloaded. (The resulting package has 116297 files!!!)

**Describe the solution you'd like**
Some way of concatenating those files if that's even possible with NPM/JS/whatever in order to create a fewer smaller files.

**Describe alternatives you've considered**
* Continue using RTL as is
* Intentionally slow down updates to RTL package
* Ditch RTL from the project
* Rewrite RTL in Rust
* Repackage every single dependency into a separate native debian package - this would be actually beautiful, but extremely laborious.

**Additional context**
[The scripts used for building the package](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/tree/master/ridetheln)

**Comment by ShahanaFarooqui** [comment]
@Kixunil, It is not possible to build smaller package than the existing. 

We are already releasing the AOT compiled bundled JS version of the frontend. 
Suggesting to only install absolutely required dependencies (npm install --only=prod).

Closing the issue for now. Please feel free to reopen if you have any followup question/suggestion.
