### ISSUE TITLE
Open channel with output from closing channel

### ISSUE THREAD

**Issue by nzwallaby** [Ride-The-Lightning/RTL#332]
**Save fees by skipping intermediate transaction**
If I want to close a channel to use its capacity in another channel, it would be wasteful to send the output to an intermediate public key, and then spend it immediately into the newly created channel.

**Describe the solution you'd like**
An interface for spending an open channel to open a new channel.

**Describe alternatives you've considered**
In the dialog for opening channel, allow option to spend an existing channel.

**Comment by seth586** [comment]
Could be a useful feature to add to the new PSBT abilities of lnd 0.10, which would include an interface for opening multiple channels with the same transaction.

**Comment by saubyk** [comment]
This needs support on the underlying implementations. Handling it via the UI only is unsafe. Will revisit, when supported with the appropriate APIs.
