### ISSUE TITLE
No error message on transaction too large for liquidity

### ISSUE THREAD

**Issue by Jestopher-BTC** [Ride-The-Lightning/RTL#339]
**Describe the bug**
When attempting to pay a lightning invoice that is greater than the available outbound liquidity, no error message is produced and the Send Payment function exits without any prompt to the user explaining what the issue is.

**To Reproduce**
1. Go to 'Lightning > Transactions > Payment Request' where request is greater than outbound liquidity.
2. Click on 'Send, Send Payment'
3. ????
4. See no error

**Your environment**
* Version of `RTL` MyNode

**Comment by ShahanaFarooqui** [comment]
Fixed after Transactions page redesign. Issue #286 & PR #315.
