### ISSUE TITLE
Can not access RTL after last update

### ISSUE THREAD

**Issue by MrManPew** [Ride-The-Lightning/RTL#341]
**Describe the bug**
It seems that I can not access RTL after the lastest update.
To debug I cloned RTL and followed the instructions, but I still see the same thing, just a black screen in the browser

**Screenshots**
![image](https://user-images.githubusercontent.com/35897350/80964892-4ec44180-8e1a-11ea-86ee-7769bd90a889.png)

**Your environment**
lnd 0.10
RTL - just cloned the latest 
```
admin@rock64:~/download/RTL$ uname -a
Linux rock64 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 GNU/Linux
```
Thanks

**Comment by MrManPew** [comment]
Fixed by - https://github.com/Ride-The-Lightning/RTL/commit/d2958650e6fc27711fee24f5319c1b78592628cd

**Comment by ShahanaFarooqui** [comment]
Great, thanks for the update. Closing the issue now 🙂.
