### ISSUE TITLE
Support Multi Path Payment for invoice payment on LND

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#343]
With LND release v0.10.0 Multi Path Payment (MPP) support has been added to outgoing payments.
This feature can be added to the invoice payment interface to provide an option to the user to leverage MPP. The benefit of MPP for the end user should be more reliable payments and lower probability of payment failures for larger value transactions.

**Comment by anon2414691** [comment]
Does RTL _not_ support multi path payments?

**Comment by saubyk** [comment]
Closing this, as its not relevant
