### ISSUE TITLE
CONTRIBUTING.md for new contributors

### ISSUE THREAD

**Issue by AryanJ-NYC** [Ride-The-Lightning/RTL#347]
**Is your feature request related to a problem? Please describe.**
I tried to stand up this project for development but got rather lost (I was met with a message about not being able to connect to port 8080 and was unable to find information on the README about standing up port 8080).

**Describe the solution you'd like**
A CONTRIBUTING.md that clarifies the commands necessary to stand up a development environment.

**Comment by ShahanaFarooqui** [comment]
Great idea, it might be the reason for not having much contributors 😜. We will add it ASAP. Thanks.

**Comment by ShahanaFarooqui** [comment]
Closing with v0.12.0 release.
