### ISSUE TITLE
C-Lightning: Replace short channel id with alias on routing grids

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#349]
Replace 'In Channel' and 'Out Channel' fields with alias on the routing grids for better understanding of the routing traffic.

**Comment by ShahanaFarooqui** [comment]
@saubyk Aliases for 'InChannel' and 'OutChannel' are not readily available in the response. Calling network node lookup API twice for every record will increase the time complexity of the operation. It should be better handled at C-Lightning-REST layer. 

We will change the fields mapping at RTL, once aliases will be available in the response.

**Comment by ShahanaFarooqui** [comment]
Done with PR #395
