### ISSUE TITLE
C-Lightning: Remove 'Local Features' and 'Global Features' fields from Peers grid

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#350]
With the C-Lightning version v0.8.2 the 'Local Features' and 'Global Features' fields are removed from the `listpeers` command output. Need to remove these unsupported fields from the Peers page.

**Comment by ShahanaFarooqui** [comment]
Done with PR #372. Also added peer connected field on the table and included 'Reconnect' functionality.
