### ISSUE TITLE
Incorrent R Hash and R Preimage Displayed

### ISSUE THREAD

**Issue by AryanJ-NYC** [Ride-The-Lightning/RTL#364]
**Describe the bug**
For an invoice paid by LND, The R Hash and R Preimage displayed in RTL are different than the R Hash and R Preimage displayed by the LND CLI.

**Screenshots**
![Screen Shot 2020-06-16 at 9 30 49 PM](https://user-images.githubusercontent.com/8263430/84844669-d8ba1980-b018-11ea-891d-cf4f4b6ac296.png)
☝️ is not correct.

![Screen Shot 2020-06-16 at 9 31 46 PM](https://user-images.githubusercontent.com/8263430/84844680-de176400-b018-11ea-985d-a10b2d3aa38e.png)
☝️ correct.

**Your environment**
* Version of `RTL`: 0.6.8-beta
* Version of `lnd`: 0.9.2-beta
* Version of `bitcoind`: v0.19.0.1
* Browser & browser version: Brave

I'm using BTCPay

**Comment by saubyk** [comment]
@AryanJ-NYC This should be taken up with LND.
LND has a different response for `lncli` and REST API. Once the API response is addressed by them, this should automatically reflected in RTL.
