### ISSUE TITLE
LND Sweep all: Unable to decode address error

### ISSUE THREAD

**Issue by khny258** [Ride-The-Lightning/RTL#368]
Describe the bug
While trying to sweep all funds from RTL, I received an error: "decoded address is of unknown format".

To Reproduce

Go to On-Chain -> Sweep All Tab
Click on "Sweep All" Button
Enter np2wkh address after authentication.
Click on "Sweep All"

Your environment
![Annotation 2020-07-05 223208](https://user-images.githubusercontent.com/55590940/86550190-bb89b400-bf0f-11ea-9812-2efa7a633acd.jpg)

Version of RTL: 0.7.1-beta
Version of lnd: 0.10.0
Browser & browser version: All
Operating system (uname -a on *Nix): All

**Comment by ShahanaFarooqui** [comment]
@khny258 thanks for opening the issue.
It is a known bug, fixed with PR #353. Will be released with version 0.8.0 in 1-2 days. Closing the issue now.
