### ISSUE TITLE
LND configuration requires /v1, which is useless

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#369]
**Describe the bug**
LND server URL must contain `/v1` suffix in order to work, however that is pointless. RTL should know on its own if it can speak v1 protocol or a different version. If LND changes protocol to e.g. v2, just changing the suffix in configuration won't help as RTL won't support the new protocol anyway and could even lead to a serious breakage. There's no reason to expect that the suffix will ever change without also changing how the protocol works.

**To Reproduce**
1. Configure RTL without `/v1` suffix in server URL
2. Access RTL from browser
3. See wallet locked screen

**Your environment**
* Version of `RTL`: 0.7.1
* Version of `lnd`: 0.10.0
* Version of `btcd`, `bitcoind`, or other backend: irrelevant
* Browser & browser version: irrelevant
* Operating system (`uname -a` on *Nix): Linux <censored> 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux

**Additional context**
This was the issue behind #367

**Comment by ShahanaFarooqui** [comment]
Done with PR #433
