### ISSUE TITLE
Disable missing lnd.conf alert when logging in if env vars are set

### ISSUE THREAD

**Issue by reynico** [Ride-The-Lightning/RTL#376]
**Is your feature request related to a problem? Please describe.**
I'm running RTL as part of a pod in Kubernetes. I didn't setup any lnd.conf file as I'm setting up every value as an env var.

Everytime I log in into RTL it redirects me to /rtl/settings, and then the next error shows up

```
Fetch Config Failed!
Error Code
500
Error Message
{"errno":-2,"code":"ENOENT","syscall":"open","path":"/root/.lnd/lnd.conf"}
API URL
./api/conf/config/ln
```
Which is actually true, I do not have any lnd.conf file

**Describe the solution you'd like**
Do not look for a lnd.conf file if everything is set up as env vars

**Describe alternatives you've considered**
Not really sure if I have an "alternative" but I just click OK on the error and everything works good.

**Additional context**
RTL tag 0.6.7
Running on kubernetes as a sidecar container inside a pod

**Comment by ShahanaFarooqui** [comment]
@reynico It is possible for you to update RTL to 0.8.0? Updating the version might possibly fix this issue already.

**Comment by reynico** [comment]
Hi @ShahanaFarooqui ! got a similar error, 

```
INFO: RTLConf => Node Type: ln, File Path: /root/.lnd/lnd.conf

ERROR: Conf(171) => Reading Conf Failed!
```

**Comment by ShahanaFarooqui** [comment]
Thanks for the confirmation. Will check soon.

**Comment by ShahanaFarooqui** [comment]
@reynico, This situation is a combination of two issues:

1) RTL redirects you to 'rtl/settings' after login whenever you are using `password` as password. As it is a default password value for RTL and we do not want our users to keep using it after initial setup. So please update your password to avoid getting redeirected to settings page.

2) Please remove 'CONFIG_PATH' or 'LND_CONFIG_PATH' from your environment variables. RTL tries to fetch the file whenever you are on settings page and the value is set.

**Comment by reynico** [comment]
Thanks! as a workaround I'm sourcing a RTL-Config.json file to the pod volume.
