### ISSUE TITLE
Problem parsing eclair.conf

### ISSUE THREAD

**Issue by n1bor** [Ride-The-Lightning/RTL#383]
**Describe the bug**
The eclair config is HOCON format:
https://github.com/lightbend/config/blob/master/HOCON.md

so:

```
eclair.api.password=test1234
```
is the same as
```
eclair {
  api {
   password=test1234
  }
}
```
but you are not parsing it correctly if file is in the later format.

**To Reproduce**
Enter password in eclair.conf as per the second code sample and the config in RTL is confused.

You could just document this and people could rewrite their config so is in the a.b.c format.

**Comment by ShahanaFarooqui** [comment]
@n1bor you can use ‘lnApiPassword’ key directly under Authentication rather than ‘configPath’. It is available for v0.8.2.

**Comment by ShahanaFarooqui** [comment]
@n1bor Were you able to fix the issue with lnApiPassword?

**Comment by ShahanaFarooqui** [comment]
Closing with PR #505.
