### ISSUE TITLE
Rebalancing is impossible since 0.8.0 version with LND

### ISSUE THREAD

**Issue by Pantamis** [Ride-The-Lightning/RTL#387]
**Describe the bug**
When I generate an invoice for rebalancing with RTL, the windows close immediatly and the payment seems to be cancelled, this makes channel rebalancing infeasible through RTL (the main selling point for a node operator like me). My node is an LND one and this happens only with version after 0.8.0 (no problem when I downgrade to 0.7.1). Maybe eclair support breaks something for LND. It seems I am not the only one to have this problem as this post on Reddt shows the same behaviors: https://www.reddit.com/r/lightningnetwork/comments/hvox9z/cant_create_invoice_on_rtl/

**To Reproduce**
1. Go to 'Peer/Channels' with 
2. Click on 'Actions' of any channels
3. Scroll down to 'Circular rebalancing', set an amount, the receiving peer validate and use higher enough fees
4. Channel rebalancing windows is closed right after invoice is generated and no payment is send.

**Screenshots**

**Your environment**
* RTL version >0.8.0
* LND version 0.10.4
* bitcoind version 0.20.0
* Brave (chromium based)

**Additional context**
In the logs of RTL, a RPC send payment is called but it seems to be cancelled instantly ? 

Otherwise, RTL is amazing, great work :+1: thank you very much

**Comment by saubyk** [comment]
Hi @Pantamis 
this issues has been fixed and is targeted for the next release.
https://github.com/Ride-The-Lightning/RTL/issues/384

**Comment by Pantamis** [comment]
Awesome ! :+1:

**Comment by ShahanaFarooqui** [comment]
Fixed with PR #386, Related to #384.
