### ISSUE TITLE
LOOP IN via RTL no working

### ISSUE THREAD

**Issue by marssystems** [Ride-The-Lightning/RTL#388]
**Describe the bug**

I'm trying to do a "loop in" using RTL but it is failing with this error -

2020-07-27 18:10:42.634 [INF] LOOPD: Loop in request received
2020-07-27 18:10:42.634 [INF] LOOP: Loop in 0.0025 BTC (last hop: )
2020-07-27 18:10:42.826 [WRN] LOOP: Swap fee 0.00001375 BTC exceeding maximum of 0 BTC
2020-07-27 18:10:42.826 [ERR] LOOPD: Loop in: swap fee too high

**Your environment**
* Version of `RTL` 0.8.2-beta
* Version of `lnd` 0.10.4-beta
* Version of `btcd`, `bitcoind`, or other backend 20.0
* Browser & browser version Windows 10 Edge
* Operating system (`uname -a` on *Nix) RaspiBlitz 1.5.1
* any other relevant environment details

**Additional context**

**Comment by saubyk** [comment]
Hi @marssystems  are you able to execute `Loop In` via the command line?
If you are facing the same error on cli, this issue should be opened in the `loop` repo.

**Comment by marssystems** [comment]
Yes - LOOP IN via command line works fine, it just doesn't work in RTL.

**Comment by marssystems** [comment]
After updating RTL to ver. 0.8.3-beta I still get this error when doing a LOOP IN -

Error: {"error":"swap fee too high","code":2,"message":"swap fee too high","details":[]}

**Comment by ShahanaFarooqui** [comment]
Fixed with PR #396. Variables names were updated by loop. Compatible with Loop v7.0 onwards.

**Comment by marssystems** [comment]
Yep!! - that seems to have fixed the problem - thanks!
