### ISSUE TITLE
ln invoice close down 

### ISSUE THREAD

**Issue by zorbamorba** [Ride-The-Lightning/RTL#392]
**Describe the bug**
Every  time a new LN invoice is created  invoice window close. you have to reopen it from list to see QR code and cope the invoice text.

**To Reproduce**
1. Go to 'Lightning -  transactions - invoices'
2. Click on ' create invoice'
43 See error 'invoice window close down'

**Screenshots**

**Your environment**
* Version of `RTL` 0.8.2
* Version of `lnd` 0.10.3
* Version of `bitcoind`,  0.20
* Browser & browser version Google Chrome  84.0.4147.105 (Officiell version) (64 bitar)

**Comment by ShahanaFarooqui** [comment]
@zorbamorba It is a bug which closes all modals after first operation. It is fixed with PR #386 and will be released by the eod.
