### ISSUE TITLE
pending_htlcs is not handled when closing channel

### ISSUE THREAD

**Issue by zorbamorba** [Ride-The-Lightning/RTL#393]
**Describe the bug**
If lnd node  is routing a transaction and user try to close the channel RTL show unknown error try later .  

**To Reproduce**
cleate a pending_htlcs
try to close the channel which is routing the transaction .

**Your environment**
* Version of `RTL` 0.8.2
* Version of `lnd` 0.10.3
* Version of `bitcoind` 0.20 

**Additional context**
pending_htlcs information should be in channel info

**Comment by saubyk** [comment]
@ShahanaFarooqui this can be handled in the following manner:
1. Upon click of the `Close Channel` action, fetch the channel information with the `listchannels` api.
2. If the channel has pending HTLCs in the response json, throw an error to the user
3. The error should state: `Uncleared HTLCs currently pending within the channel. Please wait for the HTLCs to clear before attempting channel closure`

**Comment by ShahanaFarooqui** [comment]
Done with PR #444.
