### ISSUE TITLE
Onchain payment: "cannot unmarshal number into Go value of type int64"

### ISSUE THREAD

**Issue by STAWKEYE** [Ride-The-Lightning/RTL#398]
While trying to make an on-chain payment directly from my LND [0.10.3] wallet via RTL [0.8.2-beta] I repeatedly received the following error: "jason: cannot unmarshal number [amount in BTC] into Go value of type int64."

**To Reproduce**
1. Navigate to Onchain transactions/ send/ send funds
2. Change units from sat to BTC
3. fill out form with address, amount, fee  **Note the amount sent was approx 0.1 BTC i.e. "less than one".
4. see error

*I don't recall what order I did the steps when filling out the fields and swapping units. The error may stem from the units still being interpreted as satoshis despite being selected as BTC. Note the value is less than 1 and so if the units field was being ignored, an onchain payment of 0.1 satoshis would indeed be invalid.

* Version of `RTL` [0.8.2-beta]
* Version of `lnd` [0.10.3]
* Version of `btcd`, `bitcoind`, or other backend [myNode ver 0.2.13]
* Browser & browser version [Firefox 79.0 64 bit]
* Operating system (`uname -a` on *Nix) [myNode running under Debian in a VM within a Win10 host]

**Comment by ShahanaFarooqui** [comment]
@STAWKEYE We will fix the bug in next release. However, you can specify the amount in Sats till then.

**Comment by ShahanaFarooqui** [comment]
Fixed with PR #413.
