### ISSUE TITLE
[CLT] Show the output lists on the On-chain section

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#403]
The `outputs` json array from listfunds API (/listFunds) can be used to show the onchain outputs list on the `On-Chain` section of C-Lightning menu.

The list should be labeled `Outputs` and the following records can be displayed on the grid:
- txid
- output
- value
- status
- blockheight

The rest of the fields from the json can be shown on the details modal

**Comment by ShahanaFarooqui** [comment]
Done.
