### ISSUE TITLE
LND Config - Fetch Config Failed!

### ISSUE THREAD

**Issue by danielhw2** [Ride-The-Lightning/RTL#405]
**Describe the bug**

When I go to "Settings -> LND Config" I receive the following message:

**Fetch Config Failed!
   Error Code
   500
   Error Message
   Unknown Error
   API URL
   ./api/conf/config/ln**

**To Reproduce**
1. Open the RTL page;
2. Click on Settings;
3.  Click on LND Config

MY ENVIRONMENT
* Version of `RTL`: 0.8.4-beta
* Version of `lnd`: 0.11.0-beta-rc1
* Version of `bitcoind`: 0.20.1
* Browser & browser version: Brave 1.11.104 - Chromium: 84.0.4147.105 - 64bits
* Operating system: Debian 10

**My lnd.conf file**

[Application Options]
alias=btcnode.com.br
debuglevel=info
maxpendingchannels=5
color=#E68A00
restlisten=0.0.0.0:9999
listen=localhost

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
bitcoin.basefee=350
bitcoin.feerate=1000
bitcoin.timelockdelta=144

[tor]
tor.active=true
tor.v3=true
tor.streamisolation=true

[autopilot]
autopilot.active=true
autopilot.maxchannels=400
autopilot.allocation=0.9
autopilot.minchansize=182817
autopilot.maxchansize=682819

[wtclient]
wtclient.active=true
wtclient.sweep-fee-rate=10

[watchtower]
watchtower.active=true
watchtower.listen=0.0.0.0:9911
watchtower.externalip=lndnode.ddns.net

**My RTL-config.json file**

{
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "Node 1",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "xxxx",
        "configPath": "xxxx"
      },
      "Settings": {
        "userPersona": "OPERATOR",
        "themeMode": "NIGHT",
        "themeColor": "PURPLE",
        "channelBackupPath": "xxxx",
        "enableLogging": false,
        "lnServerUrl": "https://xxxx/v1",
        "swapServerUrl": "http://xxxx/v1",
        "fiatConversion": true,
        "currencyUnit": "USD"
      }
    }
  ],
  "multiPassHashed": "xxxx"
}

**Comment by ShahanaFarooqui** [comment]
@danielhw2 please share your RTL-config.json after masking sensitive information.

**Comment by ShahanaFarooqui** [comment]
The config looks fine and RTL should be able to fetch the file as long as:
- It is on the same machine where RTL server is running.
- The file exists on the provided path.

Can you please check RTL logs for more information about the error?

**Comment by danielhw2** [comment]
> The config looks fine and RTL should be able to fetch the file as long as:
> 
> * It is on the same machine where RTL server is running.
> * The file exists on the provided path.
> 
> Can you please check RTL logs for more information about the error?

Thank you very much for the reply...
I'm running the browser in a different machine, I guess this is the problem then.
However, It would be nice to edit the config file from anywhere...

Thanks for the help. =)

**Comment by ShahanaFarooqui** [comment]
Glad to be able to help. Also, we only show local lnd/bitcoind config in ‘read only’ mode. We cannot allow layer 1 & 2 configurations to be updated from the UI for safety purposes.

**Comment by worthwhileindustries** [comment]
I'm having the same issue after updating btcpay server 1.4 to 1.9 RTL - 0.13.6-beta when I go to node info and click config info tab...

Fetch Config Failed!
Error Code
500
Error Message
Reading Config Error
API URL
./api/conf/config/ln

// logs
```
[4/16/2023, 1:02:02 AM] ERROR: RTLConf => Reading Config Error: {"statusCode":500,"message":"Reading Config Error","error":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/root/.lnd/lnd.conf"}}
```

```
# cat /var/lib/docker/volumes/generated_lnd_bitcoin_rtl_datadir/_data/RTL-Config.json
{
  "multiPass": "password",
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "Node 1",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "/root/.lnd/data/chain/bitcoin/mainnet",
        "configPath": "/root/.lnd/lnd.conf"
      },
      "Settings": {
        "userPersona": "MERCHANT",
        "themeMode": "DAY",
        "themeColor": "PURPLE",
        "channelBackupPath": "/root/backup/node-1",
        "lnServerUrl": "https://localhost:8080",
        "fiatConversion": false,
        "logLevel": "ERROR"
      }
    }
  ]
}
```

**Comment by ShahanaFarooqui** [comment]
The error `ENOENT` means "Error NO ENTity." It occurs when a program attempts to access a file or directory that does not exist. Can you confirm if a valid `lnd.conf` file exists at the location `/root/.lnd`?

**Comment by worthwhileindustries** [comment]
@ShahanaFarooqui Maybe something do do with docker-compose config not sharing the right dirs or something. It's here a the below path but, I'm not sure how they have the pathing configured here. 

I get the same problem when I try to go to loop

Loop Not Connected
Error Code
503
Error Message
Unable to Connect to Loop Server
API URL
./api/loop/swaps

```
# ls -al /var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data/
total 44
drwxr-xr-x 5 root root 4096 Oct 11  2022 .
drwxr-xr-x 3 root root 4096 Mar 31  2021 ..
-rw------- 1 root root  280 Apr  6  2021 admin.macaroon
drwx------ 5 root root 4096 Feb  6  2022 data
-rw-r--r-- 1 root root  132 Apr  6  2021 invoice.macaroon
drwx------ 2 root root 4096 Feb  6  2022 letsencrypt
-rw-r--r-- 1 root root  813 Apr 15 23:23 lnd.conf
drwx------ 3 root root 4096 Apr  6  2021 logs
-rw-r--r-- 1 root root  199 Apr  6  2021 readonly.macaroon
-rw-r--r-- 1 root root  822 Oct 11  2022 tls.cert
-rw------- 1 root root  227 Oct 11  2022 tls.key
```

**Comment by worthwhileindustries** [comment]
@ShahanaFarooqui assuming it should show up here inside the container?
```
# docker exec -it generated_bitcoin_rtl_1 sh
/RTL # ls -al /root/
total 24
drwx------    1 root     root          4096 Apr 16 01:37 .
drwxr-xr-x    1 root     root          4096 Apr 15 22:31 ..
-rw-------    1 root     root            75 Apr 16 01:38 .ash_history
drwx------    4 root     root          4096 Feb 21 22:13 .gnupg
drwxr-xr-x    3 root     root          4096 Feb 21 22:13 .npm
drwxr-xr-x    3 root     root          4096 Apr 15 22:31 backup
```

**Comment by worthwhileindustries** [comment]
@ShahanaFarooqui dug a little deeper and looks like maybe it's btc server's config that is wrong?

I went here and it looks like maybe the paths aren't lined up

https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/bitcoin-lnd.yml#L48

in the container I found the config here 
```
/RTL # ls -al /etc/lnd
total 44
drwxr-xr-x    5 root     root          4096 Oct 11  2022 .
drwxr-xr-x    1 root     root          4096 Apr 15 22:31 ..
-rw-------    1 root     root           280 Apr  6  2021 admin.macaroon
drwx------    5 root     root          4096 Feb  6  2022 data
-rw-r--r--    1 root     root           132 Apr  6  2021 invoice.macaroon
drwx------    2 root     root          4096 Feb  6  2022 letsencrypt
-rw-r--r--    1 root     root           813 Apr 15 23:23 lnd.conf
drwx------    3 root     root          4096 Apr  6  2021 logs
-rw-r--r--    1 root     root           199 Apr  6  2021 readonly.macaroon
-rw-r--r--    1 root     root           822 Oct 11  2022 tls.cert
-rw-------    1 root     root           227 Oct 11  2022 tls.key

```

**Comment by worthwhileindustries** [comment]
@ShahanaFarooqui looks like maybe BTCPayServer updated the config but, then didn't have it update an existing config maybe... here the config shows /etc

https://github.com/btcpayserver/btcpayserver-doc/blob/b1432054e147836d7286e1bae2f98e62f2752363/docs/Deployment/ManualDeploymentExtended.md
