### ISSUE TITLE
[CLT] C-Lightning coin selection for on-chain withdrawal

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#406]
Enable coin selection for the on-chain withdrawal:
- On the `Send Payment` modal create an `Advanced Options` drop down (similar to the one on Open channel modal)
- Display a label for `Coin Selection` with a list of coins (`output` json array from the `listfunds` api)
- Display the amounts against each coin
- Allow user to select one or many coins from the drop down
- Pass the "txid:vout" for each coin selected as an array for the `utxos` param in the body of the `/withdrawal` api to submit the withdrawal request

**Comment by ShahanaFarooqui** [comment]
Done with PR #422
