### ISSUE TITLE
[LND] Loop infographics on the mobile resolution

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#408]
Loop infographics are not rendering well on the mobile resolution:
![Screen Shot 2020-08-09 at 6 12 51 PM](https://user-images.githubusercontent.com/39208279/89742995-e7e3a380-da6c-11ea-9313-bd1f9fdb529d.png)

**Comment by ShahanaFarooqui** [comment]
Fixed with PR #421
