### ISSUE TITLE
[CLT] Coin selection on open channel

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#409]
Coin selection feature should be provided to the user at the time of opening the channel, to provide more fine grained control over the UTXO management.
On the `Open Channel` modal:
- `Advanced Options` should include a section for `Coin Selection`
- 'Coin Selection` list the outputs from the `ListFunds` api, with the amounts listed in a drop down.
- User should be able to select one of many coins from the drop down.
- The coins selected by the user should be passed as an array of "txid:vout" in the `utxos` param of the open channel api.
The same option should also be provided on the connect peer - channel opening flow as well.

**Comment by ShahanaFarooqui** [comment]
Done with PR #423
