### ISSUE TITLE
Can't select priority on channel close

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#410]
When I want to close a channel i can't click on priority to change it. no dropdown appears and i cant select an other option then default

RTL version 0.8.4
Firefox version 79.0
Chrome version 84.0.4147.125

![2020-08-11 19_02_30-192 168 1 195 - Remotedesktopverbindung](https://user-images.githubusercontent.com/60074674/89926481-43e13000-dc05-11ea-81f9-e16fec3816ba.png)

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin We disabled priority options if the channel is inactive because LND doesn't allow priority values when the channel is inactive. Please let us know if it is disabled for active channel as well.

**Comment by ShahanaFarooqui** [comment]
Related with #365

**Comment by sendbitcoin** [comment]
Yeah i just figured that out closing the channel with lnd.

maybe don't display the dropdown on inactive channels and instead display the message that lnd gives:

force closing a channel uses a pre-defined fee


or even better would be if you could display exactly what that pre-defined fee will be if I force close a channel, but not sure if lnd gives that info

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin 
`or even better would be if you could display exactly what that pre-defined fee will be if I force close a channel, but not sure if lnd gives that info`
You are correct, LND neither provides the information not let us set the value for inactive channels.

`maybe don't display the dropdown on inactive channels and instead display the message that lnd gives?
force closing a channel uses a pre-defined fee`
- Removing the dropdown will be against our current UX. 
- Showing message is a great suggestion. Assigning the issue to Diogo for further advise.

**Comment by sendbitcoin** [comment]
>Removing the dropdown will be against our current UX.

as a user when i see a dropdown that i can't click on and can't interact with at all I immediatly think it's a bug/error

maybe displaying the message will solve the confusion, but I still think if you can't interact with it, it shouldnt be displayed at all (or at least be greyed out or something to indicate it's supposed to be not-clickable)

**Comment by ShahanaFarooqui** [comment]
Done with PR #444.
