### ISSUE TITLE
Adding a peer gives EOF

### ISSUE THREAD

**Issue by iangregsondev** [Ride-The-Lightning/RTL#415]
**Describe the bug**
Errors out with EOF when adding a peer

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to add a peer using  02d2a32ff298cf347a96929f2719babb3775360616b8a993a4f862ec9f0b3ccd51@213.97.71.182:9735

**Screenshots**

![image](https://user-images.githubusercontent.com/2370364/90114794-86188780-dd53-11ea-9f6d-72d4a5ce25d3.png)

![image](https://user-images.githubusercontent.com/2370364/90111367-d8a37500-dd4e-11ea-9247-f4e096745b0a.png)

![image](https://user-images.githubusercontent.com/2370364/90111398-e48f3700-dd4e-11ea-8db3-5bd78b61db77.png)

**Your environment**
* Version of rtl 0.8.3-beta
* Version of lnd lnd:0.11.0-beta.rc1
* Version of bitcoin core 0.20 bitcoin core
* Browser & browser version chrome
* Operating system 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
* any other relevant environment details

**Comment by iangregsondev** [comment]
Both LND instances belong to me, both have an RTL instance running.

**Comment by ShahanaFarooqui** [comment]
@iangregsondev Thanks for providing all the required details with the issue. As shown in the above network response tab, the error is returned from LND's API request and the application is just showing it as is. Hence, it cannot be fixed from our end. 

Closing the issue now. Please feel free to reopen if needed.
