### ISSUE TITLE
GUI crop when viewing more than 10 on-chain tx

### ISSUE THREAD

**Issue by STAWKEYE** [Ride-The-Lightning/RTL#417]
**Describe the bug**
When viewing more than 10 on-chain tx the GUI expands the bottom to make room, but crops off the top line (where DASHBOARD resides)

**To Reproduce**
From main screen, click on "On-chain"
Scroll to bottom of tx list
change "Transaction per page" to either 25 or 100
Observe that Dashboard is cropped off on left navigation frame.
Closing and reopening fixes it until steps are repeated

**Your environment**
* Version of `RTL` 0.8.2beta
* Version of `lnd` 0.10.3
* Version of `btcd`, `bitcoind`, or other backend v0.20.0
* Browser & browser version Firefox 79.0
* Operating system (`uname -a` on *Nix) myNodeBTC (Debian)
* any other relevant environment details

**Comment by ShahanaFarooqui** [comment]
Duplicate issue: https://github.com/Ride-The-Lightning/RTL/issues/268

**Comment by ShahanaFarooqui** [comment]
Fixed with PR #645 (by reducing mat-sidenav-container height in root.scss file.). Will be released with v0.10.2.
