### ISSUE TITLE
Consider verbiage for Lightning balances

### ISSUE THREAD

**Issue by STAWKEYE** [Ride-The-Lightning/RTL#418]
After an hour of auditing in panic trying to find approx 8 million missing satoshis I realized that LND and RTL calculate lightning balances differently:

LND --> Channel Balance  --> Includes local capacity for all channels regardless of status

RTL --> Dashboard --> Balances --> Lightning --> Does not include local balances for offline nodes.

Which way is ideal is not obvious. To audit your holdings you would need to account for offline peers, but if you're interested in how much buying power you have on Lightning at the moment, offline peers do not help you. Because you also show "Out bound liquidity" on the same dashboard, I'd personally propose including offline peers for the "Balances" section but leave "Out-bound liquidity" alone, to serve as the metric for immediately available purchasing power.

**Comment by saubyk** [comment]
Hi @STAWKEYE this is something we thought about a lot while designing the dashboard.
And, the current balances view appears to be most practical as it gives you the view of usable funds on lighting.

We have provided a break up of the funds in different states on the dashboard on the `Channels` panel which gives you the balances in Pending, Inactive and Closing states. You can use that panel to reconcile your complete "lightning" funds.
