### ISSUE TITLE
[eclair] Only shows routed tx for last month

### ISSUE THREAD

**Issue by viaj3ro** [Ride-The-Lightning/RTL#428]
the full history is missing. 

Running latest RTL 0.8.4 beta and latest eclair 0.4.1

**Comment by ShahanaFarooqui** [comment]
@viaj3ro We are unable to reproduce it at our end. I tried with your logs as well and the complete data is showing up on the UI. Please confirm the steps to reproduce it.

**Comment by viaj3ro** [comment]
It seems to just show routed payments for the last month. `http://localhost:3000/rtl/ecl/routing` is consistent with what is shown on the Dashboard for last month.

**Comment by viaj3ro** [comment]
Double checked again today and can confirm. Number of routed payments in `http://localhost:3000/rtl/ecl/routing` is always consistent with what is shown in the Dashboard under `Routing Fee` for `Monthly`.

So it seems the 'full history' is actually just always the last 30 days or so. Today is 9/11 and the history ends at 12/8

**Comment by ShahanaFarooqui** [comment]
Closing with #506
