### ISSUE TITLE
C-Lightning: Rebalance.py plugin: conflict with RTL?

### ISSUE THREAD

**Issue by BTCBellyButton** [Ride-The-Lightning/RTL#439]
**Describe the bug**
I was trying to use the Rebalance plugin for c-lightning but after restarting Lightningd, RTL stops working.
The plugin and everything else work fine. To have RTL back to normal I have to remove the c-lightning plugins directory.

Below there is the Systemctl status output.
Before adding the Rebalance plugin this line for RTL was present:
├─35207 node /home/go/c-lightning-REST/plugin.js
During service start up the line is still there but after starting it goes away and you get the error reported below by systemctl
So it seems that there is a conflict between the two services:
├─35207 node /home/go/c-lightning-REST/plugin.js
├─35208 python3 /home/go/.lightning/plugins/rebalance/rebalance.py

**To Reproduce**
stop c-lightning
add the rebalance.py plugin in the plugins directory
restart c-lightning
reload RTL in browser, --> no connection (can't remember the error msg, at work now)

**Screenshots**
● lightningd.service - C-Lightning daemon
Loaded: loaded (/etc/systemd/system/lightningd.service; enabled; vendor preset: enabled)
Active: active (running) since Tue 2020-08-18 23:02:04 CDT; 39s ago
Process: 35200 ExecStart=/usr/local/bin/lightningd --daemon --pid-file=/run/lightningd/lightningd.pid (code=exited, status=0/SUCCESS)
Main PID: 35201 (lightningd)
Tasks: 16 (limit: 14187)
Memory: 274.1M
CGroup: /system.slice/lightningd.service
├─35201 /usr/local/bin/lightningd --daemon --pid-file=/run/lightningd/lightningd.pid
├─35202 /usr/local/bin/../libexec/c-lightning/plugins/autoclean
├─35203 /usr/local/bin/../libexec/c-lightning/plugins/bcli
├─35204 /usr/local/bin/../libexec/c-lightning/plugins/fundchannel
├─35205 /usr/local/bin/../libexec/c-lightning/plugins/keysend
├─35206 /usr/local/bin/../libexec/c-lightning/plugins/pay
├─35208 python3 /home/go/.lightning/plugins/rebalance/rebalance.py
├─35223 /usr/local/libexec/c-lightning/lightning_hsmd
├─35224 /usr/local/libexec/c-lightning/lightning_connectd
├─35236 /usr/local/libexec/c-lightning/lightning_gossipd
├─35255 /usr/local/libexec/c-lightning/lightning_channeld
├─35256 /usr/local/libexec/c-lightning/lightning_channeld
├─35258 /usr/local/libexec/c-lightning/lightning_channeld
├─35259 /usr/local/libexec/c-lightning/lightning_channeld
└─35263 /usr/local/libexec/c-lightning/lightning_channeld

Aug 18 23:02:10 BTCPayServer lightningd[35207]: **Error: Unexpected "T" at position 10 in state STOP**
Aug 18 23:02:10 BTCPayServer lightningd[35207]: at Parser.proto.charError (/home/go/c-lightning-REST/node_modules/jsonparse/jsonparse.js:90:16)
Aug 18 23:02:10 BTCPayServer lightningd[35207]: at Parser.proto.write (/home/go/c-lightning-REST/node_modules/jsonparse/jsonparse.js:267:27)
Aug 18 23:02:10 BTCPayServer lightningd[35207]: at LightningClient._handledata (/home/go/c-lightning-REST/lightning-client-js.js:143:29)
Aug 18 23:02:10 BTCPayServer lightningd[35207]: at Socket.LightningClient.client.on.data (/home/go/c-lightning-REST/lightning-client-js.js:77:46)
Aug 18 23:02:10 BTCPayServer lightningd[35207]: at Socket.emit (events.js:198:13)
Aug 18 23:02:10 BTCPayServer lightningd[35207]: at addChunk (_stream_readable.js:288:12)
Aug 18 23:02:10 BTCPayServer lightningd[35207]: at readableAddChunk (_stream_readable.js:269:11)
Aug 18 23:02:10 BTCPayServer lightningd[35207]: at Socket.Readable.push (_stream_readable.js:224:10)
Aug 18 23:02:10 BTCPayServer lightningd[35207]: at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Your environment**
* Version of `RTL`: 0.8.4
* Version of `lnd`: c-lightning 0.9.0
* Version of  `bitcoind`: 0.20.0
* Browser & browser version
* Operating system (`uname -a` on *Nix): Ubuntu 20.04

**Comment by ShahanaFarooqui** [comment]
@saubyk Need more details for any further action.

**Comment by saubyk** [comment]
Closing this issue, as this needs to be handled by cl-rest.
