### ISSUE TITLE
LND's Payment page showing the `Path` incorrectly

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#445]
With the updated versions of LND, the `Path` value is incorrectly displayed as `0` for all the records, in the grid.
There appears to be a change in the API signature, which is resulting in this value displayed incorrectly.

The payments grid, now need to show all the attempts made at the payments as well as the part payments if the payment is split by way of MPP.

**Comment by ShahanaFarooqui** [comment]
Closing with PR #446
