### ISSUE TITLE
Enable channel closure on inactive channels for C-Lightning

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#447]
Currently in RTL, the inactive channels for C-Lightning does not have any controls other than view detail.
Explore channel closure option for inactive channels, so that the user has the flexibility to get rid of channels with inactive peers.

**Comment by saubyk** [comment]
The channel closure action on the inactive channels should only be allowed on the channels which have the peer in disconnected state and the status of the channel is `CHANNELD_NORMAL`

**Comment by ShahanaFarooqui** [comment]
@saubyk This is blocked due to `socket hang up` error thrown by CLT.

**Comment by ShahanaFarooqui** [comment]
Closing with RP #512
