### ISSUE TITLE
Can't do Loop Out on channels

### ISSUE THREAD

**Issue by Nisaba** [Ride-The-Lightning/RTL#456]
Hi,

I use RTL v 0.8.4 beta that comes with BTCPay Server.

I can't do Loop out on channels, I get the error 'ECONNREFUSED'
What can I do to clear this message ? I'm newbie on Lightning...

Thanks !

![image](https://user-images.githubusercontent.com/34550856/91640354-42916f00-ea1d-11ea-93ed-5e181ccfca16.png)

**Comment by saubyk** [comment]
Hi @Nisaba does BTCPay even have `Loopd` service installed?

Without loopd, you will not be able to do loop out or in on BTCPay.

**Comment by saubyk** [comment]
Hi @Kukks @NicolasDorier @rockstardev
Is `Loopd` service now available on BTCPay?

**Comment by Kukks** [comment]
Not yet, we're looking into it though

**Comment by Kukks** [comment]
I would suggest a way to disable the UI options for loop through config.

Would be cool to abstractify the loop functionality in the case some other providers have similar functionality.

**Comment by Nisaba** [comment]
Hi all,
Waiting for this feature is available on a future release, is there a way to install / use loop in the current BTCPay site ?

**Comment by saubyk** [comment]
> I would suggest a way to disable the UI options for loop through config.
> 
> Would be cool to abstractify the loop functionality in the case some other providers have similar functionality.

Yup. Working on it.
This PR might be of interest to you...
https://github.com/Ride-The-Lightning/RTL/pull/361

**Comment by saubyk** [comment]
Closing this issue, as there is no action for RTL here. Thanks.
