### ISSUE TITLE
Cannot do Loop Out 

### ISSUE THREAD

**Issue by davterra** [Ride-The-Lightning/RTL#457]
Using RTL 0.8.3-beta in myNode v2.14, on Debian 10 VM:

I have a channel open with plenty of outbound liquidity. 
When I view it in my RTL/Dashboard it has a small "Loop Out" link next to the outbound liquidity, but when I click on the link, I get the error shown in the attached image.
![Screenshot_2020-08-30_10-57-28](https://user-images.githubusercontent.com/37884409/91666239-0e1ac300-eab0-11ea-983d-22a24ede550c.png)

**Comment by saubyk** [comment]
Hi @davterra can you please confirm if the `loopd` service is running on your node?

**Comment by davterra** [comment]
According to the myNode service/status page it is running with no issues. Are there any lncli commands to verify or test it?

**Comment by saubyk** [comment]
Hi @davterra please confirm the version of LND and Loop running on your node. Please note the version compatibility per loop's github:
![Screen Shot 2020-08-31 at 10 58 45 AM](https://user-images.githubusercontent.com/39208279/91734586-1ab71e00-eb79-11ea-84d6-55424e4f535e.png)

**Comment by davterra** [comment]
Using RTL v0.8.3-beta with LND v0.11.0 and Loop v0.8.0 in myNode v2.14, on Debian 10 VM

**Comment by davterra** [comment]
Upgrade within myNode to v0.2.15 including RTL 0.9.0 & Loop 0.8.1 fixes the issue. I will close this issue.
Thanks for your attention to it.
