### ISSUE TITLE
Problem in Routing Fee stats ?

### ISSUE THREAD

**Issue by Nisaba** [Ride-The-Lightning/RTL#458]
Hi all,

In Routing Fee screen, it display 0 sats as fee.

![image](https://user-images.githubusercontent.com/34550856/91898898-f435d780-ec8b-11ea-8d15-d2da171f4923.png)

Whereas it display fees in Routing screen

![image](https://user-images.githubusercontent.com/34550856/91899187-52fb5100-ec8c-11ea-95c8-178c513c96c3.png)

Is there any reason about that ?
Thank you for your precisions !

**Comment by saubyk** [comment]
Hi @Nisaba the fee you see on the routing page is in milli sats (mSats). So the fee collected is 0.086, 0.097, 0.099 and 0.057 sats on the screen grab above. In total it's still less than a Sat.

On the dashboard we show the data at sat level only, hence you see 0 sats.
