### ISSUE TITLE
Top menu items disappears with the channel pagination tweak

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#464]
On the Firefox browser, when the pagination setting is changed to 100, the home page or the node switcher menu disappears. The menu items does not re-appear after refresh.

It gets to normal only if the session is closed and a fresh session is started.

**Comment by ShahanaFarooqui** [comment]
Duplicate issue: https://github.com/Ride-The-Lightning/RTL/issues/268

**Comment by ShahanaFarooqui** [comment]
Fixed with PR #645 (by reducing mat-sidenav-container height in root.scss file.). Will be released with v0.10.2.
