### ISSUE TITLE
Mobile view of channels lacks content

### ISSUE THREAD

**Issue by rene78** [Ride-The-Lightning/RTL#470]
**Is your feature request related to a problem? Please describe.**
Almost no information regarding open channels in mobile view, except name of peer and Actions.

**Describe the solution you'd like**
Add at least local and remote balance. Decrease borders and paddings in order to gain more space.

**Additional context**
![Screenshot_2020-09-19-01-08-50-403_com android chrome](https://user-images.githubusercontent.com/36115705/93652456-6725a900-fa15-11ea-8d4f-671cb3895761.jpg)

**Comment by ShahanaFarooqui** [comment]
Closing with PR #592.

**Comment by rene78** [comment]
👍 Thanks!
