### ISSUE TITLE
"Path (hops)" on transaction page shows 0 for all transactions

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#475]
On the transactions page all the transactions are showing 0 under the column path (hops):

![path](https://user-images.githubusercontent.com/60074674/93809615-c40ba400-fc4d-11ea-8dd3-1871b0e263b2.png)

Under "View Info" it shows nothing:

![rtl_path2](https://user-images.githubusercontent.com/60074674/93809865-1b117900-fc4e-11ea-8b6c-0c0b9ecce739.png)

**To Reproduce**
no idea how I got it into this state. Was working in the past on this version and I didn't really change anything

**Your environment**
Version of RTL: 0.8.4-beta
Version of lnd: LND 0.11.0-beta
Version of BTCPayServer docker: v1.0.5.5
Browser: Firefox and Chrome

**Comment by ShahanaFarooqui** [comment]
Updating the RTL to latest v0.9.0 will fix this.
