### ISSUE TITLE
Inbound/Outbound Channel empty on routing page after closing the channel

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#481]
On the Routing page the "inbound channel" or "outbound channel" column is empty if you have since closed the channel

![2020-09-23 20_16_36-RTL](https://user-images.githubusercontent.com/60074674/94052925-eb8f7780-fdd9-11ea-99ea-6ff0722005b3.png)

same goes for "view info" for the routing event:

![2020-09-23 20_20_50-RTL](https://user-images.githubusercontent.com/60074674/94053257-66f12900-fdda-11ea-8497-5c510bad3652.png)

**To Reproduce**
1. wait for routing event
2. close a channel that participated in the routing event
3. column on the routing page is now empty 

* Version of RTL `0.8.4`

**Comment by ShahanaFarooqui** [comment]
Duplicate #495. It only occurs when the channel is in pending state. Once the channel goes into closed state, alias will again be available in the table.

> Added inbound channel ID and outbound channel ID values whenever we are unable to find the channel in active & closed channels list.

> We are using peer aliases already available in open and closed channels array in the application's store. We compare channel's chan_id with event's chan_id_in' and chan_id_out` values and map their aliases accordingly. But, pending channels do not have chan_id thus cannot be mapped.

> In other words, we have to send as many requests to the server as the number of missing aliases in the forwarding history. It can increase the time complexity of the page. Therefore we would prefer to not to proceed with it for now.

**Comment by ShahanaFarooqui** [comment]
Closing with PR #509
