### ISSUE TITLE
Can't rebalance full amount in channel

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#482]
**Describe the bug**
When I try to rebalance a channel down to zero (or as close as possible to zero) rebalancing immediately fails with error code 500 "insufficient funds"

**To Reproduce**
1. start a circular rebalance
2. enter max amount available as local balance, pick a peer
![2020-09-23 20_36_18-RTL](https://user-images.githubusercontent.com/60074674/94054929-8e48f580-fddc-11ea-8bc0-47f08a98ac7d.png)

3. click "estimate fee"

4. immediatly receive error code 500 "insufficient funds"
![2020-09-23 20_37_26-RTL](https://user-images.githubusercontent.com/60074674/94055076-bdf7fd80-fddc-11ea-837b-6bcf68dc4ef1.png)

5.) try again this time entering amount equal to: available local balance - "local reserve" (40164 - 11694 = 28470 in this case)

6.) get same error (error code 500 "insufficient funds")

7.) try again this time entering amount equal to: available local balance - "local reserve" - 1000 (40164 - 11694 - 1000= 27470 in this case)

8.) get same error (error code 500 "insufficient funds")

9.) keep lowering the amount by trial and error until the error 500 doesnt appear (24470 in this case)

**Expected behavior:**
The circular rebalance dialog should only show the available balance that can actually be rebalanced (so a number >24470 but <27470 in the above example)

* Version of RTL `0.8.4`

**Comment by saubyk** [comment]
Hi @sendbitcoin, couple of points to note:
- Fee estimate is derived from the query route API. This estimate is highly unreliable and in most instances you will end up paying more fee than this estimate.
- Its practically impossible to predict the exact route a transaction can take on LN and hence not possible to determine what fee it will cost to route.
- This requirement is best addressed at LND level as they would have more visibility in the probabilistic determination of routes and fee to handle this better.

Closing this ticket.

**Comment by sendbitcoin** [comment]
I dont think this is cause by fees. the fees are a couple sats maybe a couple hundred sats at most... but i have to leave like 20k+ sats in each channel at least

example: try rebalancing a channel with 20k sats local balance over a known route that only takes 2 sats routing fee -> try 19k rebalance (1000 left for fee even though its only 2) and it wont work

**Comment by sendbitcoin** [comment]
@saubyk channel with 50k local 450k remote -> try rebalance for 44444 sats -> click estimate fee -> immediate error 500

try rebalance for 33333 sats -> no error 500

why do i get a error? does it have to do with local reserve?
