### ISSUE TITLE
Peer alias not visible on pending channels

### ISSUE THREAD

**Issue by bota87** [Ride-The-Lightning/RTL#495]
When closing a channel its alias is not visible in the routing tab. After the close confirmation the alias becomes visible again. 
Maybe this is because the lookup is made with the listchannels, closedchannels but not with pendingchannels? 

![foto1](https://user-images.githubusercontent.com/52842374/94338912-5c12e000-fff6-11ea-887e-fffe88a96b2f.PNG)

![foto2](https://user-images.githubusercontent.com/52842374/94338913-5cab7680-fff6-11ea-9edf-d3bafeafdd6c.PNG)

![foto3](https://user-images.githubusercontent.com/52842374/94338914-5cab7680-fff6-11ea-81e2-210c8bcccafc.PNG)

**Comment by ShahanaFarooqui** [comment]
@bota87 @saubyk We are using peer aliases already available in open and closed channels array in the application's store.  We compare channel's `chan_id` with event's `chan_id_in' and `chan_id_out` values and map their aliases accordingly. But, pending channels do not have chan_id thus cannot be mapped.

In other words, we have to send as many requests to the server as the number of missing aliases in the forwarding history. It can increase the time complexity of the page. Therefore we would prefer to not to proceed with it for now.

**Comment by ShahanaFarooqui** [comment]
Duplicate #481. We added inbound channel ID and outbound channel ID values whenever we are unable to find the channel in active & closed channels list.
