### ISSUE TITLE
Path information missing for transaction (under view info)

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#497]
I upgraded to 0.9.0 and now the transaction page shows the number of hops again in the column... but if I click on view info I cannot see the actual peers that were involved in the transaction.

currently I have no way of figuring out what path a transaction took.

for failed transactions the hops are displayed correctly under view info. (and I can scroll down infinitely)

**Comment by ShahanaFarooqui** [comment]
Closing with PR #504
