### ISSUE TITLE
Expired GPG key

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#500]
**Describe the bug**
The GPG key is expired

**To Reproduce**
1. `gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 3E9BD4436C288039CA827A9200C9E2BC2E45666F`
2. `git clone https://github.com/Ride-The-Lightning/RTL`
3. `cd RTL`
4. `git verify-tag "v0.9.0"`

**Output**

```
gpg: Signature made Wed 26 Aug 2020 04:45:10 PM CEST
gpg:                using RSA key 3E9BD4436C288039CA827A9200C9E2BC2E45666F
gpg: Good signature from "Suheb (approves) <39208279+saubyk@users.noreply.github.com>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 3E9B D443 6C28 8039 CA82  7A92 00C9 E2BC 2E45 666F
```

**Comment by saubyk** [comment]
GPG key has been renewed.
