### ISSUE TITLE
Loop v0.10.0 - beta not working with RTL v0.9.1-beta

### ISSUE THREAD

**Issue by marssystems** [Ride-The-Lightning/RTL#515]
**Describe the bug**

I'm getting an Error 500 - Client sent an HTTP request to an HTTPS server - when running the latest version of Loop (0.10.0) with version 0.9.1 of RTL.

**Comment by ShahanaFarooqui** [comment]
What is your swapServerUrl value in RTL-config.json file? Loop server runs on https on version 0.10.0. Please update the url from http to https, restart RTL server and test again.

**Comment by marssystems** [comment]
Yep! - changing this to https solved the problem.

Now I am getting - expected 1 macaroon, got 0 . Searching for loop.macaroon shows it residing in /home/loop/.loop/mainnet/ but for some reason Loop is unable to find it. It could be some quirk of Razpiblitz.

**Comment by saubyk** [comment]
@ShahanaFarooqui Loop v0.10.0 implemented macaroons.

@marssystems you'll need to wait for the next release, so that we add macaroon support for Loop.
For now, please use Loop v0.9.0 which has been tested and supported on RTL v0.9.1

**Comment by Kixunil** [comment]
Any ETA on this? I'd like to use loop with RTL but so far I avoided it because the absence of authentication made it unsecure. Solving this would unblock me.

**Comment by ShahanaFarooqui** [comment]
Closing with #543.

**Comment by openoms** [comment]
> What is your swapServerUrl value in RTL-config.json file? Loop server runs on https on version 0.10.0. Please update the url from http to https, restart RTL server and test again.

@ShahanaFarooqui thsi needs to be updated in the sample-config file: https://github.com/Ride-The-Lightning/RTL/blob/6e036d838255124d83a33d55e52b9d8e0aef933a/sample-RTL-Config.json#L26
