### ISSUE TITLE
Loop: "ERROR: Client sent an HTTP request to an HTTPS server"

### ISSUE THREAD

**Issue by beeforbacon** [Ride-The-Lightning/RTL#516]
All programs are fully updated, unlocked, and running,  including LND, LOOP, and RTL. What does this error mean and how can it be resolved? It shows up on the Loop tab on the RTL UI. 

Loop: "ERROR: Client sent an HTTP request to an HTTPS server"

 Thanks.

**Comment by saubyk** [comment]
Hi @beeforbacon please update the `swapServerUrl` to https in the RTL-Config.json file

**Comment by beeforbacon** [comment]
> 
> 
> Hi @beeforbacon please update the `swapServerUrl` to https in the RTL-Config.json file

Hi! Thank you. I made the changes. New error is
ERROR: Fetching Swaps Failed.

**Comment by saubyk** [comment]
hey, so RTL does not support Loop v0.10.0 yet. This version was released a few days after RTL's latest release.
RTL v0.9.1 has been tested with Loop v0.9.0, please use that version and it will work fine.

**Comment by beeforbacon** [comment]
> 
> 
> hey, so RTL does not support Loop v0.10.0 yet. This version was released a few days after RTL's latest release.
> RTL v0.9.1 has been tested with Loop v0.9.0, please use that version and it will work fine.

Oh Okay. Sorry about that. Thank you for the info!

**Comment by saubyk** [comment]
No problem. Closing this issue now. Thanks.
