### ISSUE TITLE
Provide some logo/icon

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#522]
**Is your feature request related to a problem? Please describe.**
I'm making a nice dashboard with various Bitcoin apps and each app needs an icon. To my knowledge RTL doesn't have a unique logo or icon.

**Describe the solution you'd like**
I'd prefer to use official icon provided by you as you're the authors and should choose what you like.

**Describe alternatives you've considered**
Drawing my own (or let someone else draw it). This would risk that if RTL introduces an icon later, the difference would be confusing.

**Additional context**
The [backend of the dashboard](https://github.com/Kixunil/selfhost-dashboard) is pretty much done, frontend is WIP, so I can't show it to you yet.

**Comment by Kixunil** [comment]
Hmm, found something in `angular/assets/images/favicon-dark/android-chrome-192x192.png` - is that an official logo?

**Comment by ShahanaFarooqui** [comment]
Yes, above file can be uses as our official logo. Designed by Bitco (https://twitter.com/BitkoYinowsky). Attaching jpg format of the same. Thanks.

![RTL-logo-BY](https://user-images.githubusercontent.com/23240721/96920228-e413ca80-147a-11eb-9d2a-260fd6f3dfeb.jpg)

![RTL-logo-with-text-BY](https://user-images.githubusercontent.com/23240721/96920234-e5dd8e00-147a-11eb-9e59-2cb5dd8ff680.jpg)
