### ISSUE TITLE
Feature request: Show number of routed payments and routing fee in Channels tab

### ISSUE THREAD

**Issue by viaj3ro** [Ride-The-Lightning/RTL#527]
Thanks a lot for implementing this: https://github.com/Ride-The-Lightning/RTL/issues/437
This makes analyzing routing behavior so much easier! :)

Another big improvement would be to have three more columns in the Channels tab:

Number of routed Payments In | out  | proportional fee in %

With those 3 it would be straight forward to determine which channels are active and useful and what effect the the channel fees have.

Would also be useful to see who opened the channel when clicking on `view info`. Like funder yes/no

**Comment by ShahanaFarooqui** [comment]
> Another big improvement would be to have three more columns in the Channels tab:
Number of routed Payments In | out | proportional fee in %
With those 3 it would be straight forward to determine which channels are active and useful and what effect the the channel fees have.

Added "Routing Peers" tab on the Routing page to show this information while keeping the channels table cleaner and following our UX standards. The page contains channel ID, alias, total number of rounting events, total routed amount and total fee collected.


>Would also be useful to see who opened the channel when clicking on view info. Like funder yes/no

Added "Funder" field on the view info modal.

**Comment by viaj3ro** [comment]
sounds good. definitely helpful, if routing events and amount is split into incoming and outgoing. liquidity mostly moves one way and knowing where it comes in is as important as where it goes out.

Channel age or funding date would also be very useful either in channels or Routing Peers tab. Same goes for channel capacity which is actually more important info than local/remote balance. If space is to limited for all, maybe local and remote balance can be moved together the score column like that:
![image](https://user-images.githubusercontent.com/42124006/97508657-71c24f00-1980-11eb-8898-177c8e218b79.png)

Could also just show up when hovering the mouse over the balance bar.

For the view info modal, could you also ad full fee info (base, proportional, local, remote)

**Comment by ShahanaFarooqui** [comment]
> Channel age in days would also be very useful either in channels or Routing Peers tab. 

We do not receive this information from the API, thus making it impossible to show on the UI.

> Same goes for channel capacity which is actually more important info than local/remote balance. 
> 1: If space is to limited for all, maybe local and remote balance can be moved together in the score column
>2: Could also just show up when hovering the mouse over the balance bar.

1: Many users prefer to sort the channels list with local/remote capacity. Moving it with the score will destruct this feature.
2: Besides, channel capacity has already been shown on the Dashboard. Merchant's dashboard has separate inbound and outbound channel capacities while operator's dashboard shows combined channel capacity.

![image](https://user-images.githubusercontent.com/23240721/97628585-46347880-1a03-11eb-8d7b-d8d1930179bf.png)


> For the view info modal, could you also ad full fee info (base, proportional, local, remote)

Base and proportional fee are already available on 'view info' modal. Clicking on the `Show advanced` button will show the details. Local and remote fee details are missing in the API response.

![image](https://user-images.githubusercontent.com/23240721/97627793-3ec09f80-1a02-11eb-8557-3adcdd26b8e4.png)

**Comment by ShahanaFarooqui** [comment]
Closing with PR #530.
