### ISSUE TITLE
Cannot Open/Close Pending Opening Channel

### ISSUE THREAD

**Issue by 3pit0m3** [Ride-The-Lightning/RTL#528]
**Describe the bug**
For about 1 week now, I have been trying to pen a channel, and it's just stuck in the pending state. I cannot seem to force close the channel and either try again, or open with another channel.

**To Reproduce**
1. Add peer.
2. Select Add channel.
3. Choose peer alias (in this case it's 1ML.com node ALPHA)
4. enter the amount of SATS (440000)
5. Advanced
6. Choose the Fee rate to be 1 sats/byte
7. Been stuck in pending for a week

**Screenshots**

![image](https://user-images.githubusercontent.com/69397837/97380509-94c80280-189d-11eb-83b4-61f117ae65ed.png)

![image](https://user-images.githubusercontent.com/69397837/97380528-a01b2e00-189d-11eb-9b5a-54bddb2ab4fc.png)

**Your environment**
Latest version of myNode running on RPi4

![image](https://user-images.githubusercontent.com/69397837/97380619-d0fb6300-189d-11eb-8a8d-537563c63f00.png)

**Additional context**
The unconfirmed BTC transactions at the top of the screenshots were confirmed prior to this issue. They have since been in that state too for 1 week.

**Comment by saubyk** [comment]
Hi your channel opening transaction is still unconfirmed.
Mempool's been running crazy hot since last week, transactions with 1 sat/byte fee rate can take awfully long time to confirm unfortunately.
![Screen Shot 2020-10-27 at 9 57 17 PM](https://user-images.githubusercontent.com/39208279/97381589-c5a93700-189f-11eb-8045-38cb20647979.png)

LND has added API for bumping fee to confirm the transactions (https://api.lightning.community/?javascript#bumpfee), but we've not added support for it yet in RTL.

Your options at this point are:
Try checking out LND's slack channel, to see if there is a way to do it via command line.
or
Wait until mempool clears and your transaction confirms.

**Comment by 3pit0m3** [comment]
So it was the fee choice? Man that sucks. I chose that since I had no issues before. Understood. Thanks for letting me know. One more thing, based on your opinion (and I know it's just a best guess) how much longer do you think, based on the mempool load you're seeing?

**Comment by saubyk** [comment]
> So it was the fee choice? Man that sucks. I chose that since I had no issues before. Understood. Thanks for letting me know. One more thing, based on your opinion (and I know it's just a best guess) how much longer do you think, based on the mempool load you're seeing?

:-)
Cannot say for certain, markets running crazy. Heightened market activity adds significant transaction load and clogs up the mempool for days. On top of that hash rate has also dropped by a lot for some reason, which is making the backlog huge (the current 85 MB mempool size is crazy!).

I have opened an [issue](https://github.com/Ride-The-Lightning/RTL/issues/529) to explore adding RBF feature.
Will attempt to test and release early, if possible. RBF can be a tricky feature, people need to know what they are doing, hence a little hesitant to rush the feature.

Meanwhile, be patient and enjoy the bull run! :-)

**Comment by 3pit0m3** [comment]
OK, thanks a lot man. I really learned a lot here. You can close this out. I will just wait for the transaction to be confirmed, or you guys issue the new feature. Either way, I guess I will go on to setting up an Ethereum node/become a testnet validator. Wish me luck.

**Comment by saubyk** [comment]
@3pit0m3 Fee bump has been added to RTL with the release v0.9.3 you can upgrade and try to raise the priority of your channel open transaction.

**Comment by 3pit0m3** [comment]
Awesome! Let me give it a shot.
