### ISSUE TITLE
No spinner indicator on login

### ISSUE THREAD

**Issue by elvece** [Ride-The-Lightning/RTL#533]
**Describe the bug**
When logging in, no indicator immediately appears denoting the page is loading. The "Logout" button appears in the menu, but the spinner is delayed a solid ~20seconds until a spinner with "Initializing Node Data" appears. 

When the "Initializing Node Data" spinner appears, the browser console throws the following error: 

`ERROR Error: InvalidPipeArgument: 'NaN is not a number' for pipe 't'`

**To Reproduce**
1. Enter password in login screen
2. Notice no loader
3. Wait ~20seconds
4. Loader will appear with greyed out dashboard in background (see image below)

**Screenshots**

Right after logging in:

<img width="1680" alt="Screen Shot 2020-11-02 at 5 08 41 PM" src="https://user-images.githubusercontent.com/12953208/97932849-4350c500-1d2e-11eb-983b-828ac1a18022.png">

A few seconds after logging in, "Logout appears":

<img width="1680" alt="Screen Shot 2020-11-02 at 5 08 46 PM" src="https://user-images.githubusercontent.com/12953208/97932860-48ae0f80-1d2e-11eb-92fb-57cc48f05981.png">

Delayed loading spinner over dashboard:

<img width="1680" alt="Screen Shot 2020-11-02 at 5 06 56 PM" src="https://user-images.githubusercontent.com/12953208/97932715-f5d45800-1d2d-11eb-8297-856edc442545.png">

**Your environment**
* RTL 0.9.3
* LND 0.11.0
* bitcoind 0.20.1
* Firefox 82.0 (64-bit)
* macOS Catalina 10.15.7 (19H2)
* Hosted and running over Tor

**Comment by saubyk** [comment]
Hi @elvece unable to replicate this issue. I am able to load and login to RTL on Tor/Firefox within 5 secs with RTL being served on TOR.

Would you try and update RTL to the latest version (v0.10.0) and see if this is still an issue?

**Comment by ShahanaFarooqui** [comment]
@elvece, I recall running into this issue in 9.x versions and fixing it with v10.0. Can you please recheck it with the latest RTL version?

**Comment by ShahanaFarooqui** [comment]
@elvece & @saubyk 
It was happening due to above mentioned console erorr.
`ERROR Error: InvalidPipeArgument: 'NaN is not a number' for pipe 't'`

This was a bug and has been fixed with Release 0.10.0 via PR #562. 
Closing the issue now.
