### ISSUE TITLE
Circular rebalancing for Eclair

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#535]
**Is your feature request related to a problem? Please describe.**
I'd like to rebalance Eclair channels just as it's possible with LND. However RTL doesn't provide this feature for Eclair now.

**Describe the solution you'd like**
Same feature as provided for LND

**Describe alternatives you've considered**
Figure out how to do it using CLI, or try to find some other app with this feature being able to work with Eclair.

**Comment by saubyk** [comment]
Hi @Kixunil 
This will not be currently possible to do in Eclair, as circular rebalancing is actually a payment you make to yourselves and it requires two specific changes to be made to payment API.
1. The payment API should allow the invoice generated by the node to be paid by the same node.
2. The payment API should allow to specify the node via which to receive the payment back (this allows to complete the circular circuit).

Once the API has these features we can make the changes in RTL to support circular payments to balance channels.
