### ISSUE TITLE
Download CSV broken on Payments grid

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#544]
Unable to download csv file on the payments grid.
Getting Error code 413.
<img width="308" alt="Screen Shot 2020-11-20 at 1 47 10 PM" src="https://user-images.githubusercontent.com/39208279/99838343-fdba3780-2b36-11eb-8348-6e0215084849.png">

**Comment by ShahanaFarooqui** [comment]
Fixed the Express body parser issue by increasing the request body size to 25 MB with PR #564.

However, if RTL is hosted on NGINX, then please add the following line to /etc/nginx/sites-available directory and restart your server to increase the request body size at NGINX.

`client_max_body_size 25M; #25mb`
