### ISSUE TITLE
Loop swap server calls not including macaroon

### ISSUE THREAD

**Issue by MrRGnome** [Ride-The-Lightning/RTL#546]
**Describe the bug**
While attempting to use a local instance of LN Loop and RTL I ran into an issue where RTL was not including the Loop macaroons in swap server calls. See the end of this post for my quick hardcoded fix for my own needs. 

**To Reproduce**
1, Run RTL 0.9.3: node rtl
2. Run default Loop server and rest on port 8081 and LND on 8080
3. Attempt to use Loop via /rtl/lnd/loop

**Results**
Loop page on RTL given defaults:
![image](https://user-images.githubusercontent.com/5963774/99892844-a56a5f00-2c36-11eb-99b1-880dd09966f7.png)

RTL console:
`ERROR: Loop(327) => List Swaps Error: {"name":"StatusCodeError","statusCode":500,"message":"500 - {\"error\":\"expected 1 macaroon, got 0\",\"code\":2,\"message\":\"expected 1 macaroon, got 0\",\"details\":[]}","error":{"error":"expected 1 macaroon, got 0","code":2,"message":"expected 1 macaroon, got 0","details":[]},"options":{"url":"https://127.0.0.1:8081/v1/loop/swaps","rejectUnauthorized":false,"json":true,"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":500,"body":{"error":"expected 1 macaroon, got 0","code":2,"message":"expected 1 macaroon, got 0","details":[]},"headers":{"content-type":"application/json","trailer":"Grpc-Trailer-Content-Type","date":"Sun, 22 Nov 2020 03:15:50 GMT","connection":"close","transfer-encoding":"chunked"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"127.0.0.1:8081","port":"8081","hostname":"127.0.0.1","hash":null,"search":null,"query":null,"pathname":"/v1/loop/swaps","path":"/v1/loop/swaps","href":"https://127.0.0.1:8081/v1/loop/swaps"},"method":"GET","headers":{"accept":"application/json"}}}}

ERROR: Loop(146) => Loop Out Terms Error: {"name":"StatusCodeError","statusCode":500,"message":"500 - {\"error\":\"expected 1 macaroon, got 0\",\"code\":2,\"message\":\"expected 1 macaroon, got 0\",\"details\":[]}","error":{"error":"expected 1 macaroon, got 0","code":2,"message":"expected 1 macaroon, got 0","details":[]},"options":{"url":"https://127.0.0.1:8081/v1/loop/out/terms","rejectUnauthorized":false,"json":true,"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":500,"body":{"error":"expected 1 macaroon, got 0","code":2,"message":"expected 1 macaroon, got 0","details":[]},"headers":{"content-type":"application/json","trailer":"Grpc-Trailer-Content-Type","date":"Sun, 22 Nov 2020 03:17:28 GMT","connection":"close","transfer-encoding":"chunked"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"127.0.0.1:8081","port":"8081","hostname":"127.0.0.1","hash":null,"search":null,"query":null,"pathname":"/v1/loop/out/terms","path":"/v1/loop/out/terms","href":"https://127.0.0.1:8081/v1/loop/out/terms"},"method":"GET","headers":{"accept":"application/json"}}}}`

**Your environment**
* Version of `RTL`: 0.9.3
* Version of `lnd`: 0.11.1
* Version of ``bitcoind`: 0.20.1
* Operating system: Windows 10 64 home

**Temporary Solution**
I've solved this problem for myself by modifying common.js and common.getSwapServerOptions, I've hard coding the Loop macaroon into the swap server headers variable.

`common.getSwapServerOptions = () => {
  return {
    url: common.selectedNode.swap_server_url,
    rejectUnauthorized: false,
    json: true,
    headers: { 'Grpc-Metadata-macaroon': fs.readFileSync(path.join('my\\loop\\path', 'loop.macaroon')).toString('hex') }
  }
};`

This is obviously not a fix for the codebase but illustrates the problem and a solution.

**Comment by ShahanaFarooqui** [comment]
Duplicate issue #515. It has already been handled with PR #543, merged in `Release 0.10 branch` and will be released soon. Thanks.
