### ISSUE TITLE
Flag Dust UTXOs as suspicious

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#552]
Flag any UTXO with amount less than 1000 sats as suspicious.
This should enable the user to take action to label or lock the UTXOs, in case they suspect a dust attack in progress.
- Such dust UTXOs can be listed in a separate tab on the 'On-Chain' page.
- The main UTXO page should also list these UTXOs, but can possible color code them to visually identify,

**Comment by ShahanaFarooqui** [comment]
Color code the table row background with warning yellow color.

**Comment by ShahanaFarooqui** [comment]
Closing with PR #594.
