### ISSUE TITLE
Label Transactions

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#553]
Users should be able to label Transactions to enable simple identification of specific UTXOs

- Add 'Actions' menu on the row under the Transactions tab and add an action for 'Label'
- Allow user to add a label (max limit of 500 chars).
- User can also edit/overwrite an existing label.

LND REST API: https://api.lightning.community/?javascript#v2-wallet-tx-label

**Comment by ShahanaFarooqui** [comment]
Done with PR #599
