### ISSUE TITLE
LND Lease and Release UTXOs

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#554]
Lease and Release of UTXOs is a desired control on the UTXOs for a variety of functions.

- Enable `Lease` and `Release` actions on the Actions menu for the UTXO rows.
- Lease action would require a input of random string of 32 bytes which is the locking ID (this needs to be generated by RTL)
- Upon successful completion lease API will return an expiration timestamp of the lease, which should be displayed to the user
- Release action will allow the user to release the UTXO, so that it can be used. Release API requires the ID which was used to lease the UTXO.

API:
https://api.lightning.community/?javascript#v2-wallet-utxos-lease
https://api.lightning.community/?javascript#v2-wallet-utxos-release

**Comment by ShahanaFarooqui** [comment]
Added lease UTXO feature through PR #599. We decided to not to implement 'Release' feature independently. We will utilize release with PSBT. Closing the issue now.
