### ISSUE TITLE
Macaroon authentication for Loopd

### ISSUE THREAD

**Issue by ale-rinaldi** [Ride-The-Lightning/RTL#565]
**Is your feature request related to a problem? Please describe.**
It seems that the latest versions of loopd require a macaroon to access the API. Unfortunately it seems there's not a clean way to disable it (and it's not the best option, ofc). The Loopd macaroon is separated from the LND ones and is stored by default in `~/.loop/mainnet/loop.macaroon`. I can't find a way to set it in the RTL configuration, so of course all the calls fail with `expected 1 macaroon, got 0`.

**Describe the solution you'd like**
I'd like to be able to configure the macaron usage for Loopd in the RTL configuration file, and to have RTL use it to call Loopd.

**Describe alternatives you've considered**
I tried to disable macaroon authentication for loopd (it's a local-only endpoint, after all) but it seems it isn't officially possible.

**Comment by ShahanaFarooqui** [comment]
Duplicate issue #515. It has already been handled with PR #543, merged in Release 0.10 branch and will be released soon. Thanks.
