### ISSUE TITLE
Convert the 'Generate Address' button to 'Receive' button

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#570]
For consistency of the UX across 'Receive', 'Send' and 'Sweep All' actions on the On-Chain page, 'Generate Address' button should be changed to 'Receive' button.
The click of the button should open a modal with the drop-down to choose the address type and a button with 'Generate Address' button to generate new address to receive funds.

**Comment by ShahanaFarooqui** [comment]
@saubyk Closing the issue after discussion. No action is taken.
