### ISSUE TITLE
RTL v10.0 Loop - empty macaroon data

### ISSUE THREAD

**Issue by marssystems** [Ride-The-Lightning/RTL#572]
**Describe the bug**

When opening loop in or loop out get this error

Error Code
500
Error Message
empty macaroon data
API URL
./api/lnd/loop/in/termsAndQuotes

**To Reproduce**
1. Open loop in or loop out
2. See error

**Your environment**
* Version of `RTL` 10.0
* Version of `lnd` 11.1
* Version of `btcd`, `bitcoind`, or other backend 20.1
* Browser & browser version Microsoft Edge
* Operating system (`uname -a` on *Nix) Razblitz 
*

**Comment by ShahanaFarooqui** [comment]
Did you set the macaroon location  with ‘swapMacaroonPath’? If yes, does the loop.macaroon file exist at the location?

**Comment by marssystems** [comment]
No - I didn't set any path. I just removed the old RTL using the Activate/Deactivate Services in the Razblitz Menu, Then re installed the latest version. I've checked and the loop.macaroon is in ~/.loop/<network>/loop.macaroon. This is the default location set by Loop on installation.

**Comment by marssystems** [comment]
This is the loop.macaroon contents:-

^B^A^Dloop^Bw^C
^P��    �r���(�^PR��?�^R^A0^Z^L
^Dauth^R^Dread^Z^O
^Dloop^R^Bin^R^Cout^Z^Z
^Ksuggestions^R^Dread^R^Ewrite^Z^U
^Dswap^R^Gexecute^R^Dread^Z
^Eterms^R^Dread^@^@^F ŪY�=^C�w��X^@�1�:�^N��9����R�
��T�

**Comment by saubyk** [comment]
Hi @marssystems
You would need to specify the path of the Loop macaroon file in the RTL-Config.json file.
The value of `swapMacaroonPath` needs to be set with the complete path of the folder containing `loop.macaroon` file.

The value has to be defined in the `Authentication` section of the config file. Please refer to the (configuration documentation)[https://github.com/Ride-The-Lightning/RTL/blob/master/docs/Application_configurations].

once you've made the change, RTL server needs to be restarted.

**Comment by marssystems** [comment]
I thought that this would have been set already as part of the 'fix'. This could cause problems for many users.

**Comment by saubyk** [comment]
> I thought that this would have been set already as part of the 'fix'. This could cause problems for many users.

Its a config setting which can vary depending upon your hardware, OS etc. Additionally, Loop is an optional service, which the user has to consciously opt in. We cannot force this change into every user's config files.

The fix was to add this variable so that macaroon can be specified in the config file to work with the latest version of Loop. I am hopeful that Raspiblitiz's next update will include this config change, so that you don't need to tinker with it.

Until then, users would need to add it in manually.

**Comment by marssystems** [comment]
OK - no worries. I'm doing it now. Will let you know how it goes.

**Comment by marssystems** [comment]
OK - I added the path - rebooted - and I am still getting the same error.

**Comment by saubyk** [comment]
can you please share the config file? Hide the sensitive info (if any).

**Comment by saubyk** [comment]
Also, please confirm the version of loop on Raspiblitz.

**Comment by marssystems** [comment]
Loop version - 11.2

RTL-Config.json
{
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "MarsSystems1Routing",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "/home/rtl/.lnd/data/chain/bitcoin/mainnet/",
        "configPath": "/home/rtl/.lnd/lnd.conf",
        "swapMacaroonPath": "/home/loop/loop/mainnet/",
        "swapMacaroonPath": "C:\\Users\\xyz\\AppData\\Local\\Loop\\mainnet"
      },
      "Settings": {
        "userPersona": "OPERATOR",
        "themeMode": "NIGHT",
        "themeColor": "TEAL",
        "channelBackupPath": "/home/rtl/RTL-SCB-backup-MarsSystems1Routing",
        "enableLogging": false,
        "lnServerUrl": "https://localhost:8080",
        "swapServerUrl": "https://localhost:8081",
        "fiatConversion": false
      }
    }

I think this line -  "swapMacaroonPath": "C:\\Users\\xyz\\AppData\\Local\\Loop\\mainnet" - is a mistake and is not required.
I have removed it and rebooted but I'm still getting the same error.

**Comment by saubyk** [comment]
can you please verify again is this path is right one `/home/loop/loop/mainnet/`?

This seems to be the only thing off in your config.

**Comment by marssystems** [comment]
Yes it is.

**Comment by ShahanaFarooqui** [comment]
@marssystems 

1: `I think this line - "swapMacaroonPath": "C:\Users\xyz\AppData\Local\Loop\mainnet" - is a mistake and is not required. `

Yes, it is just an example value and should be replaced with the real location value.

2: Usually the path only contains one ‘loop’ folder not two. For example, ‘.../loop/loop.macaroon’. However in your config it is ‘.../loop/loop/...’. 

3: please remove last forward slash from the end of the path location. So it should be ‘ .../mainnet’
NOT  ‘ .../mainnet/‘.

**Comment by marssystems** [comment]
OK I will try that.

But the line -

"macaroonPath": "/home/rtl/.lnd/data/chain/bitcoin/mainnet/",

has the / at the end and it works.

**Comment by ShahanaFarooqui** [comment]
Yeah, that used to be initial setting. To keep RTL backwards compatible, we are allowing that location to still be configured with forward slash but with our new parameters we are not supporting it.

**Comment by marssystems** [comment]
OK - removing the / seems to have fixed the problem.

Thanks for your help.
