### ISSUE TITLE
Circular Rebalance shows as failed on every rebalancing attempt

### ISSUE THREAD

**Issue by gked** [Ride-The-Lightning/RTL#573]
**Describe the bug**
When I attempt to rebalance my channels, I get "Payment failed" error message.

**To Reproduce**
1. Navigate to "Peers/Channels"
2. Click on "Actions dropdown" of the channel you want to rebalance and choose Circular rebalance option.
3. Choose suggested fee 
4. Click on "rebalance"
5. The invoice will be generated
6. After some time, you will see "Payment Failed" error.

**Screenshots**
![image](https://user-images.githubusercontent.com/12704474/102834935-3190b300-43aa-11eb-98a4-920742f35ed3.png)

**Your environment**
* Version of `RTL` **0.9.1 - beta**
* Version of `lnd` **0.11.1**
* Version of `btcd`, `bitcoind` - **bitcoin v0.20.0 mainnet** 
* Browser & browser version- **Microsoft Edge | 87.0.664.66 (Official build) (64-bit)**
* Operating system - **Windows 10. 20H2 (OS Build 19042.685)**

**Comment by saubyk** [comment]
Hi @gked 

Please try increasing the fee limit for rebalancing attempt. Depending upon the amount you are trying to rebalance, 2 sats may not be enough to complete the route.

Also note that using the suggested fee is almost likely to be not enough for completing the route, as its a poor estimate which we get from the LND API.

**Comment by gked** [comment]
@saubyk thanks, let me try that and report back.

**Comment by gked** [comment]
Even after allowing for 1.25% of the total transaction, the thing still fails. 
![image](https://user-images.githubusercontent.com/12704474/102918597-0b1b5800-443c-11eb-84a4-91682fdfd054.png)

Is there anything else there?

**Comment by saubyk** [comment]
Try rebalancing with smaller amounts first. Instead of 200000, try with 20000 and then keep increasing, to see what levels are sustainable.

Circular rebalancing depends on how well your peers are connected and what their respective channel balances are to be able to successfully complete the loop.

**Comment by gked** [comment]
Thanks, @saubyk for suggested workaround. Reducing to 5k sats with 1% did the trick.

I think, it would be a good idea to add mitigation options on failure in RTL so folks know what to do.

**Comment by saubyk** [comment]
@gked its very difficult to code for all the scenarios in the software. And if we abstract it too much, users will have no idea how lightning works under the hood. Since its early stage in the evolution of lightning, we are still keeping it a bit raw. :-)

Closing this issue. Since you know how to make it work now. ;-)
