### ISSUE TITLE
Channel Closed with Low TX Fees - Transactions Stuck in Mempool. Any way to add TX fees?

### ISSUE THREAD

**Issue by kaimeinke** [Ride-The-Lightning/RTL#575]
Oh my ... I made a mistake. My full node had an HDD issue and after I was able to recover the node I went to close the channels in order to prepare a migration to a new SDD (never did this before).

While I was kind of distracted I missed the proper fee settings and now my closing on-chain transactions are stuck at the bottom of the mempool ... maybe for weeks / months / years?

These are the corresponding transaction hashes of the six channels:
cd83a1f799b45fc2de34a897f864c516008c9be0133b6159b1bca57e94c54347
![image](https://user-images.githubusercontent.com/59994024/102894067-d1aa1300-4462-11eb-8c43-3926e5f46fc8.png)

7e11e26a28e63fdb7bf6738ae0c995b59bb8fea47ad17f2e148bd407d3d34fda
![image](https://user-images.githubusercontent.com/59994024/102894134-f0100e80-4462-11eb-8e2e-15b1689a939d.png)

461941d6ac765645a69f6c8fc5e163988caa34e06189a700007ec45f9c435662
![image](https://user-images.githubusercontent.com/59994024/102894190-04eca200-4463-11eb-92d9-0feb68f1afa7.png)

ec0e9080682f9a0dd3e8e314ca3bfd5f58799c2e98b7766ac0a837b4149c4437
![image](https://user-images.githubusercontent.com/59994024/102894245-19309f00-4463-11eb-8f72-7b57b7643f23.png)

a8ced51fc15d48d628a6d55e1ce69ea710c0c3a2b2b901d09e5bcc21f5f00fd5
![image](https://user-images.githubusercontent.com/59994024/102894302-2cdc0580-4463-11eb-856f-059e70b0c051.png)

3610bd52841b792814aac2b7cb4cadd8759af46b6fd39f669e98ecf41e3bd7af
![image](https://user-images.githubusercontent.com/59994024/102894368-454c2000-4463-11eb-91a9-94b8d1dc0a9e.png)

Do I have any chance to help these transactions to move on from here? Any assistance would be highly appreciated. Thank you a lot. I am running a Raspiblitz and willing to learn.

A look at the current mempool does not make me optimistic.

![image](https://user-images.githubusercontent.com/59994024/102893918-97407600-4462-11eb-8c60-22b3bc36f767.png)

**Comment by saubyk** [comment]
For the transactions which have a change output, you can try to CPFP (child pays for parent) to raise the priority of your transaction to get picked up. I saw that few of your transactions have change output and can possibly be bumped up this way. For the transactions which do not have the change output, there is nothing you can do unfortunately.

RTL does not have that feature for pending channel closing transactions in the UI. We do have it for pending open.

If you want to do it via the command line you can follow the below wiki link on how to:
https://lightningwiki.net/index.php/Bumping_fee_for_lightning_channel_open

But please note that this wiki documentation is for channel open transactions, I am not sure if it can apply to channel close as well. Although I can't see why not (if the transactions have the change output). Still, I would strongly recommend hopping on the LND slack channel and posing this question there for the channel closing transactions, before you actually try it.

Hope this helps.

**Comment by kaimeinke** [comment]
Thanks a lot @saubyk , I will check the documentation for this and try to help the transaction via the free transaction accelerator of viabtc (they offer 100 free slots each hour.) The last clean mempool was like 9 days ago I have heard from @senf42 (Raspiblitz GitHub) and that gives me hope I will not be stuck forever. Thanks a lot for helping me out here. Stay safe and healthy.
