### ISSUE TITLE
Two local nodes

### ISSUE THREAD

**Issue by thephizzz** [Ride-The-Lightning/RTL#579]
I have a RaspiBlitz lnd node behind Tor and another lnd node on a separate computer. all on the same local network.
I have both nodes configured in RTL and they show up fine.
I cannot establish a peer between the two. 
When trying to connect from the Tor node to the clearnet node nothing happens in RTL. No errors message.
I'm trying to eventually establish channel between the two to experiment with transferring funds, etc.
Thanks.

**Comment by saubyk** [comment]
Hi @thephizzz, the connection between Tor and clearnet has to be initiated by Tor node. Clearnet node will not be able to connect to Tor node first.

You can follow the below steps to establish the connection:
1. Generate the Node URI on your clearnet node via the `Public Key` menu on RTL and copy it.
2. Go the peers section of RTL on your Tor node and click on `Add Peer`.
3. Paste the full address and click on `Add Peer` button. This will connect the two nodes.
4. You can skip the channel opening step and close.

Once the nodes are connected, channels can be opened from either side.

Hope this helps.

**Comment by thephizzz** [comment]
Thank you saubyk.
Perhaps I wasn't clear.
That is just what I did. But when I click Add Peer, nothing happens. The message window remains and I can press Add Peer several times and the is no response.
Eventually I cancel.
I thought I had seen in the past a comment about a Tor node and clearnet node on the same local network.

**Comment by saubyk** [comment]
Can you please confirm the version of RTL you are on?

I just did exactly the same thing, connected a Tor and clearnet node both on the same local network, and it worked perfectly.

**Comment by thephizzz** [comment]
Version: 0.8.1-beta

**Comment by saubyk** [comment]
You’re quite behind on RTL version. Can you please update to the latest one v0.10.0 and try once?

**Comment by thephizzz** [comment]
Certainly. I’ll do that and let you know.

Thank you.

Jim

**Comment by thephizzz** [comment]
Suheb,

I know remember why I’m so far behind in versions.

I tried to upgrade before, but when I was done and started rtl, the old version always came up (0.8.1).

 

I’m fairly new to unix, so am not familiar where programs are stored etc.

 

After I’ve installed v0.10.1 I input ‘node rtl’ and received an error ‘MODULE_NOT_FOUND’

Any help in how to get the new version running.

Thank you.

Jim

**Comment by thephizzz** [comment]
Suheb,

Please ignore the last complaint.

I was able to figure out how to get the newest version running.

I will see if I have the same Add Peer problem next.

Jim

**Comment by thephizzz** [comment]
Suheb,

Now with RTL V 0.10.0:

 

*	Added Clearnet public key to Tor node ‘Add Peer’
*	Tor node processed for a few minutes
*	‘Peer Connection Failed’

**Comment by thephizzz** [comment]
Suheb,

FYI the nodes are:

 

1.	Tor:  03498c2308b2bc24457af7f82605a112186bdb40835e9283548b5b9b574b1bf84c
2.	Clearnet:  030bfe79edbab48b93bab7a550bb87d0c1a32bb8c8db1cc22fe4a13b54a3b0442e

 

Thank you for your patience.

Jim

**Comment by ShahanaFarooqui** [comment]
Can you please share more details of the error? You can either open browser console to see the error details OR you can check the RTL server’s command prompt OR you can check logs at /rtl/logs/your-node-id.

**Comment by thephizzz** [comment]
Here is the error from the Clearnet LND node:

 

INFO: Peers => Peer Added: {"error":"socks connect tcp 127.0.0.1:9050->108.55.28.192:9735: unknown error general SOCKS server failure","code":2,"message":"socks connect tcp 127.0.0.1:9050->108.55.28.192:9735: unknown error general SOCKS server failure","details":[]}

ERROR: Peers(63) => Add Peer Error: "socks connect tcp 127.0.0.1:9050->108.55.28.192:9735: unknown error general SOCKS server failure"

**Comment by saubyk** [comment]
@thephizzz 

Please note that you need to connect with the complete node URI, not just the node Pubkey.

e.g. in your case the node URI, which you need to connect the Tor node with should be:
030bfe79edbab48b93bab7a550bb87d0c1a32bb8c8db1cc22fe4a13b54a3b0442e@1xx.x5.2x.1xx:9735

Note: In the example above, I have obfuscated your IP address, you need to ensure the IP address is correct. The node will only connect with the full URI.

You can get the full URI from the pubkey menu of RTL (please use the drop down to chose the full URI).

**Comment by thephizzz** [comment]
When using the full URL I receive the following error in the rtl log:

INFO: Peers => Peer Added: {"error":"socks connect tcp 127.0.0.1:9050->1xx.x5.2x.1xx:9735: unknown error general SOCKS server failure","code":2,"message":"socks connect tcp 127.0.0.1:9050->108.55.28.192:9735: unknown error general SOCKS server failure","details":[]}

ERROR: Peers(63) => Add Peer Error: "socks connect tcp 127.0.0.1:9050->1xx.x5.2x.1xx:9735: unknown error general SOCKS server failure"
Unhandled rejection StatusCodeError: 500 - {"error":"socks connect tcp 127.0.0.1:9050->1xx.x5.2x.1xx:9735: unknown error general SOCKS server failure","code":2,"message":"socks connect tcp 127.0.0.1:9050->108.55.28.192:9735: unknown error general SOCKS server failure","details":[]}
    at new StatusCodeError (/home/admin/RTL-0.10.0/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/admin/RTL-0.10.0/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/admin/RTL-0.10.0/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/admin/RTL-0.10.0/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/home/admin/RTL-0.10.0/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/home/admin/RTL-0.10.0/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

and "Peer Connection Failed" on the Tor node RTL.

**Comment by thephizzz** [comment]
When using the full URL to add the peer i receive the following error in the logs:

INFO: Peers => Peer Added: {"error":"socks connect tcp 127.0.0.1:9050->1xx.x5.2x.1xx:9735: unknown error general SOCKS server failure","code":2,"message":"socks connect tcp 127.0.0.1:9050->1xx.x5.2x.1xx:9735: unknown error general SOCKS server failure","details":[]}

ERROR: Peers(63) => Add Peer Error: "socks connect tcp 127.0.0.1:9050->1xx.x5.2x.1xx:9735: unknown error general SOCKS server failure"
Unhandled rejection StatusCodeError: 500 - {"error":"socks connect tcp 127.0.0.1:9050->1xx.x5.2x.1xx:9735: unknown error general SOCKS server failure","code":2,"message":"socks connect tcp 127.0.0.1:9050->1xx.x5.2x.1xx:9735: unknown error general SOCKS server failure","details":[]}
    at new StatusCodeError (/home/admin/RTL-0.10.0/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/admin/RTL-0.10.0/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/admin/RTL-0.10.0/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/admin/RTL-0.10.0/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/home/admin/RTL-0.10.0/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/home/admin/RTL-0.10.0/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

And then "Peer Connection Failed." on the Tor RTL

**Comment by saubyk** [comment]
Hi @thephizzz 
One more thing I would suggest is, please ensure that you have the clearnet node’s port forwarded on your internet router. If you haven’t done that already.

I would also recommend changing the port of the clearnet node to something other than 9735.

**Comment by thephizzz** [comment]
Thank you for the help. 
I will try both.

**Comment by saubyk** [comment]
Hi @thephizzz I am assuming, you're able to make it work. Closing this issue now.
Feel free to open a new one, if you need further help.
