### ISSUE TITLE
npm ERR! typeerror Error: Missing required argument #1

### ISSUE THREAD

**Issue by goodc0re** [Ride-The-Lightning/RTL#580]
**Describe the bug**
$ sudo npm install --only=prod
loadDep:typescript → reso 
WARN engine @angular/compiler-cli@11.0.5: wanted: {"node":">=10.0"} (current: {"node":"8.10.0","npm":"3.5.2"})
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Linux 4.15.0-128-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--only=prod"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

**To Reproduce**

1. run sudo npm install --only=prod

**Your environment**
* after git pull
* Version of `lnd` : 0.11.99-beta

**Comment by ShahanaFarooqui** [comment]
@goodc0re it is due to older versions of NodeJS and NPM. It is encouraged to upgrade the nodejs and npm to keep them less vulnerable and updated. Angular 8 and above versions are only compatible with node 10.9.x.

**Comment by goodc0re** [comment]
Thanks! Updated npm and nodejs and it's working now.
