### ISSUE TITLE
Downloading all channels backup fails

### ISSUE THREAD

**Issue by dennisreimann** [Ride-The-Lightning/RTL#582]
**Describe the bug**

The download of the "All Channels" backup does not work. This is most likely a case sensitive filename issue.
We received a [note about this on the BTCPay Server Mattermost](https://chat.btcpayserver.org/btcpayserver/pl/c4zy3ypexfdpdnj5no81e1m8my). I investigated it and with our docker deployment this is the case for me:

The frontend expects the file to be named channel-ALL.bak ([requesting `api/conf/file?channel=ALL`](https://github.com/Ride-The-Lightning/RTL/blob/master/src/app/lnd/backup/channel-backup-table/channel-backup-table.component.ts#L94)), but it actually gets [saved](https://github.com/Ride-The-Lightning/RTL/blob/master/controllers/lnd/channelsBackup.js#L33) and [looked up](https://github.com/Ride-The-Lightning/RTL/blob/master/controllers/RTLConf.js#L227) with lowercase letters (channel-all.bak) and hence cannot be found.

**Screenshots**

<img width="718" alt="download" src="https://user-images.githubusercontent.com/886/103941225-d80ce000-512e-11eb-8444-578c73d25c85.png">

**Your environment**
* Version of `RTL`: 0.9.3-beta
* BTCPay Server Docker Deployment on a Raspberry Pi.

**Comment by ShahanaFarooqui** [comment]
@dennisreimann Thanks for opening the issue and the PR. However, this bug has been fixed with our last release ie v0.10.0.

Issue: https://github.com/Ride-The-Lightning/RTL/issues/536
Fix: https://github.com/Ride-The-Lightning/RTL/pull/571

Closing the issue now. Please feel free to reopen if issue still persists with newer versions.

**Comment by dennisreimann** [comment]
Alright, thanks!
