### ISSUE TITLE
Make filters case insensitive

### ISSUE THREAD

**Issue by bota87** [Ride-The-Lightning/RTL#584]
In the peers/channels page the filters are case sensitive, I think it's better to make that case insensitive like the routing and reports pages

**Comment by ShahanaFarooqui** [comment]
@bota87 Thanks for raising the issue. The code has been pushed with commit '212b1047c4f2d74df7dd6616adbd2ffe3789a4ce' and will be released in the next one.

**Comment by ShahanaFarooqui** [comment]
Closing with PR #590
