### ISSUE TITLE
Show timestamp of first seen pending channel open

### ISSUE THREAD

**Issue by ProofOfKeags** [Ride-The-Lightning/RTL#585]
It would be nice to see how long a pending channel open has been stuck in the mempool to decide whether we want to bump the fee higher or not.

**Comment by ShahanaFarooqui** [comment]
@ProofOfKeags This requirement can only be handled via a block explorer API. No such support is available currently in the LND API stack.

**Comment by ProofOfKeags** [comment]
Does RTL not have any of its own state?

**Comment by ShahanaFarooqui** [comment]
No, RTL only consumes LNP REST APIs to show  the information.
