### ISSUE TITLE
Boltz swap service integration with RTL

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#587]
Scope of Boltz swap service with RTL
- Menu segregation for 3rd party services
- Integration of Boltz submarine swap and reverse submarine swap
- Configuration of swap services via the setup menu

**Comment by ShahanaFarooqui** [comment]
Covered first and second points with PR #590. 

Third point is related to setting page reorganization and will be covered whenever the page will be redesign. 
Issue is open at: https://github.com/Ride-The-Lightning/RTL-Design/issues/57

Closing the issue now.

**Comment by saubyk** [comment]
Issue re-opened to cover the setup page re-organization. The mockups are updated on the design issue.

**Comment by ShahanaFarooqui** [comment]
Done with PR #604.
