### ISSUE TITLE
Error connecting to loop: Client sent an HTTP request to an HTTPS server

### ISSUE THREAD

**Issue by ramontayag** [Ride-The-Lightning/RTL#595]
What versions of loop is RTL 0.10.0-beta compatible with? The issue I'm seeing might just be like https://github.com/Ride-The-Lightning/RTL/issues/516#issuecomment-711417972, but I couldn't find a list of compatible versions

**Comment by Kixunil** [comment]
The latest RTL should be compatible (disclaimer: didn't try yet).

**Comment by ramontayag** [comment]
Ok, let me dig in some more. Running `loop version 0.11.2-beta`.

**Comment by saubyk** [comment]
Hi @ramontayag are you able to make it work with RTL v0.10.0?
You would need to make two updates to your `RTL-Config.json` file:
- under the "Settings" section: update the `swapServerUrl` value to https
- under the "Authentication" section: add `swapMacaroonPath`, setting it to the folder containing the `loop.macaroon` file.

Check this for reference: https://github.com/Ride-The-Lightning/RTL/blob/master/docs/Application_configurations

**Comment by ramontayag** [comment]
@saubyk I haven't been able to get it to work, but I will try that. Will report back shortly.

**Comment by ramontayag** [comment]
Thank you @saubyk this worked. I setup RTL with the older version of raspiblitz. The new version of raspiblitz has these, but upgrading raspiblitz didn't add these new settings.
