### ISSUE TITLE
RTL not showing Routings on c-lightning implementation

### ISSUE THREAD

**Issue by PsySc0rpi0n** [Ride-The-Lightning/RTL#600]
**Describe the bug**
Not sure if it's a bug or just something wrong in my setup but the **Routing** tab of my RTL front-end is empty. 

**To Reproduce**
1. Start c-lightning-REST
2. Start RTL
3. Open the web frontend
4. Check **Routing** tab, which is empty

**Screenshots**
https://i.ibb.co/Bt0gZ55/image.png

My c-lightning node output for the ``listforward`` command is something like:
```
{
         "payment_hash": "[REPLACED]",
         "in_channel": "[REPLACED]",
         "out_channel": "[REPLACED]",
         "in_msatoshi": 240819086,
         "in_msat": "240819086msat",
         "out_msatoshi": 240757897,
         "out_msat": "240757897msat",
         "fee": 61189,
         "fee_msat": "61189msat",
         "status": "settled",
         "received_time": 1613299979.261,
         "resolved_time": 1613300137.733
      },
      {
         "payment_hash": "[REPLACED]",
         "in_channel": "[REPLACED]",
         "out_channel": "[REPLACED]",
         "in_msatoshi": 30025664,
         "in_msat": "30025664msat",
         "out_msatoshi": 30017160,
         "out_msat": "30017160msat",
         "fee": 8504,
         "fee_msat": "8504msat",
         "status": "failed",
         "received_time": 1613302050.096,
         "resolved_time": 1613304051.006
      },
      {
         "payment_hash": "[REPLACED]",
         "in_channel": "[REPLACED]",
         "out_channel": "[REPLACED]",
         "in_msatoshi": 30025664,
         "in_msat": "30025664msat",
         "out_msatoshi": 30017160,
         "out_msat": "30017160msat",
         "fee": 8504,
         "fee_msat": "8504msat",
         "status": "failed",
         "received_time": 1613305408.845,
         "resolved_time": 1613307409.865
      }
```

**Your environment**
* Version 0.10.0 beta of `RTL`
* Version v0.9.2-67-gff88308 of `lc-lightning`
* Version v21.99.0-32b191fb66e6 of `bitcoind`
* Firfeox 78.7.0esr (64-bit)
* Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

**Additional context**

**Comment by saubyk** [comment]
Hi @PsySc0rpi0n do you see anything on the `Failed Transactions` tab?

**Comment by PsySc0rpi0n** [comment]
> Hi @PsySc0rpi0n do you see anything on the `Failed Transactions` tab?

This is how my RTL looks like:
https://i.ibb.co/x5xjQPK/RTL-2021-02-14-21-18-23.jpg

Not sure if this is what you wanted. Let me know if you need something else, please!

**Comment by saubyk** [comment]
Hi @PsySc0rpi0n should have asked this first.
- what version of c-Lightning-REST are you on?
- do you see any routing fee on the `Routing Fee` panel of your dashboard?

**Comment by PsySc0rpi0n** [comment]
> Hi @PsySc0rpi0n should have asked this first.
> 
>     * what version of c-Lightning-REST are you on?
> 
>     * do you see any routing fee on the `Routing Fee` panel of your dashboard?

Hi @saubyk , and I should have informed about the versions of the software I'm using, in the first place. :p

About the versions, as of now, I can only say I have cloned the repositories of both c-lightning-REST and RTL like a couple of days ago, so, if they haven't made any further updates, then the versions are the ones from the master branches. I'm not sure I can tell c-lightning-REST but I can say that RTL is version 0.10.0-beta.

Anyways, somehow the routing history is already showing up. Seems that sometimes the web frontend refuses to show the results and after I hit the reload button on the web browser, then the info show up.

I think this can be closed!
Thank you for the help!

**Comment by PsySc0rpi0n** [comment]
In the meantime, I have 2 more questions, @saubyk .
I hope it's ok to use the same issue/thread to ask about these too.

1 - The tab Transactions are payments I made or received, right? Not forwardings. Is this accurate?

2 - When I look to **Peers/Channels** tab at the **Balance Score**, I see some numbers above the thin green bars. What do these numbers represent? Some kind of percentage?

**Comment by saubyk** [comment]
> 1 - The tab Transactions are payments I made or received, right? Not forwardings. Is this accurate?

Yes. Transactions menu is for the payments made or received.

> 2 - When I look to **Peers/Channels** tab at the **Balance Score**, I see some numbers above the thin green bars. What do these numbers represent? Some kind of percentage?

The balance score, provides a numerical measurement of how balanced your channel is. Its value varies from 0 to 1, for a channel with completely lop-sided balances to a perfectly balanced channel.

Closing this issue. Feel free to post, if you have more questions.
