### ISSUE TITLE
New IP Address

### ISSUE THREAD

**Issue by thephizzz** [Ride-The-Lightning/RTL#601]
I have 2 nodes running on my local network. All worked well with RTL as set up in the RTL-config.json
I recently moved one node to a new system.
After changing the IP address in RTL-config.json, restarting the node the new node will not come up in RTL.
In checking the log, it shows that it is still trying to access the old IP address.
Where else do I need to change the IP address?

version 0.8.4-beta
1 Raspi lnd node (working in RTL)
1 W10 lnd node - node working - not accessed in RTL

RTL-config.json

{
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "xxxxx",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "/home/rtl/.lnd/data/chain/bitcoin/mainnet/",
        "configPath": "/home/rtl/.lnd/lnd.conf"
      },
      "Settings": {
        "userPersona": "OPERATOR",
        "themeMode": "DAY",
        "themeColor": "PURPLE",
        "channelBackupPath": "/home/rtl/RTL-SCB-backup-xxxxx",
        "enableLogging": false,
        "lnServerUrl": "https://localhost:8080/v1",
        "swapServerUrl": "http://localhost:8081/v1",
        "fiatConversion": false
      }
    },
    {
      "index": 2,
      "lnNode": "xxxxx",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "/mnt/hdd/xps"
      },
      "Settings": {
        "flgSidenavOpened": "true",
        "flgSidenavPinned": "true",
        "menu": "Vertical",
        "menuType": "Regular",
        "theme": "light-teal",
        "satsToBTC": "false",
        "channelBackupPath": "/home/rtl/RTL-SCB-backup-xxxxx",
        "bitcoindConfigPath": "",
        "enableLogging": "true",
        "lndServerUrl": "https://xxx.xxx.xxx.xxx:8080/v1", **<= this node not responding with new IP address**
        "userPersona": "MERCHANT",
        "themeMode": "DAY",
        "themeColor": "TEAL",
        "fiatConversion": false
      }
    }
  ],
  "multiPassHashed": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}

**Comment by saubyk** [comment]
@thephizzz 
In your config for the 2nd node, you've set the variable name incorrectly.
It should be `lnServerUrl`, where as you have it as `lndServerUrl`.

**Comment by saubyk** [comment]
Also, please confirm, if you restarted RTL server, after updating the config file.

**Comment by ShahanaFarooqui** [comment]
@thephizzz & @saubyk, I tried the same config on my local and it is successfully connecting with both the nodes.  

@saubyk, we used `lndServerUrl` key in older versions and now it is updated to `lnServerUrl`. But it is still considered as valid key to keep RTL backward compatibility.

@thephizzz, restarting the RTL server should fix your issue. The log shows that the RTL server is still loaded with the older values.

Although your current config file is still compatible with current RTL release, we would recommend to update it as follows to avoid future issues:

{
    "port": "3000",
    "defaultNodeIndex": 1,
    "SSO": {
        "rtlSSO": 0,
        "rtlCookiePath": "",
        "logoutRedirectLink": ""
    },
    "nodes": [
        {
            "index": 1,
            "lnNode": "xxxxx",
            "lnImplementation": "LND",
            "Authentication": {
                "macaroonPath": "/home/rtl/.lnd/data/chain/bitcoin/mainnet/",
                "configPath": "/home/rtl/.lnd/lnd.conf"
            },
            "Settings": {
                "userPersona": "OPERATOR",
                "themeMode": "DAY",
                "themeColor": "PURPLE",
                "channelBackupPath": "/home/rtl/RTL-SCB-backup-xxxxx",
                "enableLogging": false,
                "lnServerUrl": "https://localhost:8080",
                "swapServerUrl": "http://localhost:8081",
                "fiatConversion": false
            }
        },
        {
            "index": 2,
            "lnNode": "yyyyyy",
            "lnImplementation": "LND",
            "Authentication": {
                "macaroonPath": "/mnt/hdd/xps"
            },
            "Settings": {
                "userPersona": "MERCHANT",
                "themeMode": "DAY",
                "themeColor": "TEAL",
                "channelBackupPath": "/home/rtl/RTL-SCB-backup-xxxxx",
                "enableLogging": true,
                "lnServerUrl": "https://xxx.xxx.xxx.xxx:8080",
                "fiatConversion": false
            }
        }
    ],
    "multiPassHashed": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}

**Comment by thephizzz** [comment]
@ShahanaFarooqui & @saubyk <https://github.com/saubyk> ,

 

Thank you. That did it.

I thought I was restarting the server by using “node RTL” but realized I needed to

$ sudo systemctl stop RTL

$ sudo systemctl start RTL

 

Thank you for your help.

**Comment by saubyk** [comment]
Thanks for the update @thephizzz

Closing this issue.
