### ISSUE TITLE
Add Transaction ID on the detail modal for 'Waiting Close' channels

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#603]
Show the transaction id of the commitment transaction on the detail modal of the `Waiting Close` channels.
This should help in tracking the transaction status in the mempool, for closing transactions which may be waiting to be confirmed.
The field to show in the detail modal is `local_txid` from the `commitments` field of the response json.
API documentation links below:
https://api.lightning.community/#lnrpcpendingchannelsresponsewaitingclosechannel
https://api.lightning.community/#lnrpcpendingchannelsresponsecommitments

**Comment by ShahanaFarooqui** [comment]
Closing with PR #645
