### ISSUE TITLE
Update tooltips all over the project with updated UX

### ISSUE THREAD

**Issue by ShahanaFarooqui** [Ride-The-Lightning/RTL#608]
Update tooltips all over the project with updated UX.

Reference issue: https://github.com/Ride-The-Lightning/RTL-Design/issues/40.

**Comment by saiy2k** [comment]
Is this still open? Is there a list of which tooltip needs to appear where? I think I can work on this and make a PR.

**Comment by ShahanaFarooqui** [comment]
@saiy2k thank you for the query. I think it is still open. Let me check and get back to you asap. A little bit busy currently but can find some good first issues if you are interested in contributing.

**Comment by saubyk** [comment]
Hi @saiy2k 
This one is a good issue for you to work on if you are interested. We don't have the list of tool tips used all over the application, but you can search for `mat-tooltip` in the code to locate where it's being used.

we would need to change all the tool tips, per the design recommendation. Reach out to @ShahanaFarooqui for development guidance if needed. Thanks.

**Comment by saiy2k** [comment]
Thanks @saubyk. Excited to work on this. Will go through the code in a day and revert, if I need any help.

**Comment by saiy2k** [comment]
Hi @ShahanaFarooqui and @saubyk,

I had a look at the code and the new design requirement.

Summarising my understanding here:
 1. Tooltips are now shown on hovering on specific controls. Rather we should add a 'Exclamation / Info' icon button and show tool tip, on hovering over that control. Right?

 2. Was looking at the source code:
> grep -rn  src -e 'matTooltip' | wc
> 95    1301   24625
> grep -rn  src -e 'mat-tooltip' | wc
> 2       6     141  //  This is in 2 sltylesheets
So there are ~95 lines where matTooltip attribute is used.

 3. In the UI, most of the tooltips are like this
<img width="673" alt="RTL Tooltip A 002" src="https://user-images.githubusercontent.com/701985/149138558-6940341d-4190-4e62-987e-c2b7a69e8ce2.png">
They are to be converted to new design, while the following few tooltips
<img width="276" alt="RTL Tooltip B 004" src="https://user-images.githubusercontent.com/701985/149138625-4379f906-831e-46fd-92a6-6d622ab62420.png">
will remain the same. Right?


Please confirm If my understanding is correct. If not, please clarify.

Thanks.

**Comment by ShahanaFarooqui** [comment]
@saiy2k Absolutely correct. Tooltips which are on icons/svg will remain the same. Tooltips which are on input elements should be moved to the caption with info icon.

**Comment by ShahanaFarooqui** [comment]
Though we cannot move tooltips available on input boxes yet as current design uses floating style. 

@saubyk Changing the input styles from floating to static is in our tech debt section. Can we do it with this issue so that everything will be as per standards?

**Comment by saiy2k** [comment]
Hi @ShahanaFarooqui.
Need some help in setting up 'dev' env. When I do 'node rtl', things were working fine in localhost:3000.

But when I do 'npm run start', the app is launched in localhost:4200/rtl/login, as expected.

Now attempting to login throws this error:

    Http failure response for http://localhost:3000/rtl/api/authenticate: 0 unknown error 

Can you please help me with this?!

Thanks.

**Comment by ShahanaFarooqui** [comment]
@saiy2k `node rtl` is for production environment. When you want to run the frontend in dev you need to start the server with dev setup too. For windows machine, the script is `npm run server` and for Ubuntu, it is `npm run serverUbuntu`. Basically, the idea is to set `NODE_ENV` to `development`. 

To run backend in dev also, you can run another script as `npm run watchserver`. 

Please read [contribution section](https://github.com/Ride-The-Lightning/RTL/blob/master/.github/docs/Contributing.md#code)  and let me know if you want to setup a meeting. We can connect on telegram/google meet.

**Comment by ShahanaFarooqui** [comment]
Closing with PR #928.
