### ISSUE TITLE
Bug/feature request: Support eclair trampoline routing statistics

### ISSUE THREAD

**Issue by bitromortac** [Ride-The-Lightning/RTL#611]
I'm currently running elcair 0.5.0 and tested out trampoline forwardings. When running RTL, it remains in the "Initializing Node Data..." phase and the spinner doesn't disappear.
My browser says `ERROR TypeError: t.fromChannelId is undefined` and I guess this has to do with JSON responses from routed trampoline payments in the `audit` command.

In the RTL logs I see lines
`INFO: Fees => Fee Relayed Transaction: {"type":"payment-relayed","amountIn":XXX,"amountOut":XXX,"paymentHash":"XXX","fromChannelId":"XXX","toChannelId":"XXX","timestamp":XXX}`

but also
`INFO: Fees => Fee Relayed Transaction: {"type":"trampoline-payment-relayed","paymentHash":"XXX","incoming":[{"amount":XXX,"channelId":"XXX"}],"outgoing":[{"amount":XXX,"channelId":"XXX"}],"timestamp":XXX}`

Note that incoming and outgoing lists can have multiple items, as there can be a multipart payment coming in and/or a multipart payment going out.

It would be nice to have a fix to handle these trampoline payments (ignoring them in a first step) such that at least the software can be run for other tasks. Thank you very much and also for your nice project!

**Comment by ShahanaFarooqui** [comment]
@bitromortac Thank you for the issue and your kind words.

We updated the code to show the basic information for trampoline relayed payments. The UI will show the channel details of the first incoming and first outgoing channels for `In Channel` and `Out Channel`. For example:

If the trampoline payment is:
{"type":"trampoline-payment-relayed","paymentHash":"PAYMENT HASH","incoming":[{"amount":210,"channelId":"Incoming Channel ID"}],"outgoing":[{"amount":209,"channelId":"Outgoing Channel ID"}],"timestamp":1637700279000}

The forwarding and information modal screens will look like below:
![image](https://user-images.githubusercontent.com/23240721/143311301-85b65169-dd83-4c0c-8847-31e83198ec20.png)

The update will be released with v12.
