### ISSUE TITLE
Transaction page takes very long to load

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#613]
the page "lightning -> transactions" takes very very long to load (like over 10 minutes) for me. Probably has something to do with having over 10 thousand lightning transactions. Could you please look into why it takes so long and changes how RTL loads such a large amount of transactions. 

RTL version 0.10.0-beta

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin Can you please test it with version 0.10.1. Some table pagination and sorting were not working as expected and we recently have updated the code for multiple tables. 

Please let us know if that doesn’t fix the issue and I will look into it.

**Comment by sendbitcoin** [comment]
@ShahanaFarooqui Just upgraded to 0.10.1 and the problem is still the same. loading took 14+ minutes.

both chrome and firefox tell me RTL is slowing down my browser and ask if i want to stop it or wait.

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin thanks for the update. I will check the issue now.

**Comment by ShahanaFarooqui** [comment]
Closing with PR #708. We tried to remove as much time complex code as possible at RTL's side. However, it will further be improved once LND API starts returning total number of payments. Opened the issue with LND [here](https://github.com/lightningnetwork/lnd/issues/5382).

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin Please make sure to disable logging in the config file ( "enableLogging": false) in order to load the page faster.
