### ISSUE TITLE
Channel Rebalance does not allow selection of peer

### ISSUE THREAD

**Issue by chonshu** [Ride-The-Lightning/RTL#617]
**Describe the bug**
Unable to select the peer in the Channel Rebalance dialog.

**To Reproduce**
1. Under Actions menu for a peer select "Circular Rebalance"
2. Enter an amount. 100000 for example
3. Click on "Receive from Peer"
4. Nothing happens. 
5. Click again. It says "peer is required" underneath. The widget turns red. 

**Your environment**
* Version of `RTL` = 0.10.1-beta
* Version of `lnd` = v0.12.1-beta
* Version of `btcd`, `bitcoind` = 0.21.0
* Browser & browser version = Firefox 78.7.0esr (64-bit)
* Operating system = Linux laptop 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

Tested with all Firefox extensions turned off.
Browser console does not log anything. 
No network traffic is logged by Network tab in Web Developer Tools of Firefox when opening and interacting with the rebalance dialog.

**Comment by brandonshope** [comment]
Do you have inbound/channel capacity? It wont appear until you do.

**Comment by chonshu** [comment]
I see. I  misunderstood how it works.

**Comment by marxenegls** [comment]
... and so have i, .. got splattered against that inbound wall .. until i found brandon's hope line :Thanks B
