### ISSUE TITLE
UX improvement request: Fee Rate in percentage

### ISSUE THREAD

**Issue by theDavidCoen** [Ride-The-Lightning/RTL#621]
Today we can change the Fee Policy of the single channel by selecting the Base Fee in milliSat (mSat) and the Fee Rate in milli milliSat (milli mSat). It's cool to use fractions of a satoshi, because this could help us understand better how Bitcoin divisibility works, but it would be super useful if we can have also Fee Rate in percentage.

For example, if I want to have a Fee Rate of 1%, today I need to enter 10'000 milli mSat but could be a little tricky to calculate the value sometimes.

If we can simply enter 1 as Fee Rate (%), it could make the Policy update faster.

**Comment by Svobodan** [comment]
Agreed. I see two issues with the current state.

1. Wrong format. Standard way to express multiple and submultiple of a unit is to add a single prefix such as μ (micro) in the case of a millionth. Stacking multiple prefixes (such as milli mSat, milimiliSat) is not common.

2. Wrong unit. This Fee Rate is supposed to express fraction of the transferred amount that will make the fee, not a fixed amount. Thus it should be expressed as:

- fraction without unit - example: 4/1000, 0.004 

- percentage - 0.4%, 4‰, 400 ppm 

- a unit that has the same base unit in numerator and denominator - example mSat/Sat, Sat/BTC, μSat/Sat, Satoshi per 1000 Satoshi

I just looked into my raspiblitz to see how they do it and found it quite confusing there. There is: 

> "Fee-PerMil -> amount based fee (millisatoshis per 1 satoshi)"

 but then the numbers that it shows is 1000 times higher. Or perhaps they mean 1‰ millisatoshis per 1 satoshi which would be weird. My suggestion is to avoid combining the options stated above.

**Comment by Svobodan** [comment]
On 1ml.com they use sat/sat with many decimal places. I find it quite easy to read.
![fee_rate_1ML](https://user-images.githubusercontent.com/77900472/111086653-a0028e80-851d-11eb-97d0-8a041e623df2.png)

**Comment by saubyk** [comment]
The %age number can be shown under the Fee Rate field. Convert the fee rate in PPM to %age by dividing the ppm number by 10,000.

This conversion should be done on the following places:
1. 'Update Fee Policy' modal at the channel level
2. 'Update Fee Policy' modal at the grid level on the channel page
3. 'View Remote Fee' modal at the channel level

**Comment by ShahanaFarooqui** [comment]
Closing with PR #705.
