### ISSUE TITLE
Filter search bar for Peers/Channels view lowercases input

### ISSUE THREAD

**Issue by djkazic** [Ride-The-Lightning/RTL#623]
**Describe the bug**
When using the RTL page for Peers/Channel, any query placed in the searchbox appears to be lowercase. This means that entering a peer name with an upper case letter (or sequence of characters to result in lowercase + uppercase letters) does not return a result.

**To Reproduce**
1. Go to 'Peers/Channel'
2. Click on 'Filter'
3. Enter query with mixed case peer name
4. Lack of peer results

**Screenshots**
N/A

**Your environment**
* Version of `RTL` 0.10.1-beta
* Version of `lnd` 0.12.1
* Version of `btcd`, `bitcoind`, or other backend 0.22.1
* Browser & browser version Chrome 88
* Operating system (`uname -a` on *Nix) 4.15-lts

**Comment by JLSchuler99** [comment]
Just came here to report this, and found this thread. I am also having this problem and this makes RTL unusable for node operators with hundreds of peers.

**Comment by sendbitcoin** [comment]
seeing the same issue, filter doesn't work (likely due to uppercase starting letter of peer)

**Comment by ShahanaFarooqui** [comment]
Closing with PR #644
