### ISSUE TITLE
High CPU usage by browser when session inactivity dialog is showing

### ISSUE THREAD

**Issue by chonshu** [Ride-The-Lightning/RTL#624]
The browser CPU usage becomes very high when RTL goes to the "Time limit exceeded for session inactivity." dialog.

**To Reproduce**

1. Log in to RTL
2. Wait for session time out
3. Observe browser CPU usage

**Screenshots**
Top shows:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
26364 me      20   0 2799240 217076  86264 R 102.3   1.3   1450:03 Web Content  

```
![Screenshot from 2021-03-09 18-14-18](https://user-images.githubusercontent.com/11278760/110556517-8f75a100-8136-11eb-9ef5-950672222422.png)

**Your environment**
* Version of `RTL` 0.10.1-beta
* Version of `lnd`  0.12.1-beta
* Version of `bitcoind` v0.21.0
* Browser & browser version: Firefox 78.7.0esr (64-bit)
* Operating system Linux ebk 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

**Comment by ShahanaFarooqui** [comment]
Fixed with 2efa41c0cfa1fd868a315adb5712bc4bff9bce51.
