### ISSUE TITLE
ERROR: Authenticate(85) => Invalid Password!

### ISSUE THREAD

**Issue by pscopic** [Ride-The-Lightning/RTL#626]
Error message on subject line is on fresh install trying to log into web gui. What is auth error 85? 

I've tried both multiPassHashed and bitcoind.rpcpass. I saw a ticket from two years ago that default auth uses rpcpass. Is this still true? Both throw the same Authenticate(85) error. Please advise.

```
My RTL-Config.json

{
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "LND Mainnet",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "/srv/lnd/data/chain/bitcoin/mainnet",
        "configPath": "/srv/lnd/lnd.conf"
      },
      "Settings": {
        "userPersona": "OPERATOR",
        "themeMode": "DAY",
        "themeColor": "PURPLE",
        "channelBackupPath": "/home/rtl/backup/node-1",
        "enableLogging": true,
        "lnServerUrl": "https://localhost:8080",
        "swapServerUrl": "https://localhost:8081",
        "boltzServerUrl": "https://localhost:9003",
        "fiatConversion": false
      }
    }
  ],
  "multiPassHashed": "_mypw_"
}
```

**Comment by saubyk** [comment]
Hi @pscopic 
Please change `multiPassHashed` to `multiPass` in your config file and set a password in plain text. Restart RTL after that and login with the password you've set.

**Comment by pscopic** [comment]
Awesome! I'm grateful for your immediate response.

Is multiPassHashed even a thing anymore that it's still used as the default variable used in the example config file? 

Thanks for all your great work. This GUI greatly improves quality of life of managing a lightning node.

**Comment by ShahanaFarooqui** [comment]
The user can either save the plaintext password with ‘multipass’ key and the RTL server will convert and save it into ‘multipasshashed’ or the user can save the sha256 hashed password value directly into ‘multipasshashed’.

We usually suggest to save plaintext password to the user to avoid confusion.

The default password value is ‘password’. It is set by RTL server while creating the config file if RTL-config.json file is missing in the project.
