### ISSUE TITLE
unencrypted password

### ISSUE THREAD

**Issue by plickami** [Ride-The-Lightning/RTL#636]
Under LND config in the settings is visible unencrypted password "tor.password=*******" used for logging in to the RTL (raspiblitz password B)!

To Reproduce
1. log in to RTL
2. Go to: settings -> LND config -> scroll down
3. See "tor.password" unencrypted password used for RTL login

environment:
RaspiBlitz v1.6.3 
Bitcoin Fullnode + Lightning Network + Tor
RTL version 0.10.0 beta
Browser Edge and/or firefox

**Comment by ShahanaFarooqui** [comment]
Closing with PR #647.
