### ISSUE TITLE
Routing list disappears when navigating the interface @ c-lightning

### ISSUE THREAD

**Issue by PsySc0rpi0n** [Ride-The-Lightning/RTL#652]
**Describe the bug**
The **Routing** listing disappears while navigating the web interface of RTL

**To Reproduce**
1. Launch your RTL web interface
2. Click on Lightning menu to expand sub-menus
3. Click on Routing. List is available. Both the succeeded and failed routings.
4. Navigate to some other menu.
5. Click on Routing sub-menu under Lightning menu again. List is no longer available.
6. Refresh the web interface to get the Routing listing back. Both the succeeded and failed.

**Screenshots**
If needed, I'll add them

**Your environment**
* Version of `RTL` --> v0.10.1-beta
* Version of `c-lightning` --> 0.9.3 (arm64 arch)
* Version of `btcd`, `bitcoind`, or other backend --> bitcoind v0.21.0 (arm64 arch)
* Browser & browser version -- Firefox 78.9.0 esr
* Operating system (`uname -a` on *Nix) --> Linux Host 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Comment by ShahanaFarooqui** [comment]
Closing with PR #654.
