### ISSUE TITLE
[Bug] C-lightning: UpdateFeePolicy option doesn't show current fees

### ISSUE THREAD

**Issue by tukac** [Ride-The-Lightning/RTL#659]
**To Reproduce**
1. Run c-lightning
2. Go to Peers/Channels menu > Open Channels menu > Update Fee Policy option

Fees shown here are not current. Fees can be changed here correctly, change will be communicated to c-lightning correctly but change will not be shown correctly. This menu always displays default fees irregardless of what they actually are.

In order to see current fees:
`lightning-cli listchannels <short channel ID>`

Browser, RTL plugin nor c-lightning restart do not resolve this issue.

**Your environment**
* Version of `RTL` 0.10.0 beta
* Version of `c-lightning` 0.10.0-27
* Browser & browser version  Firefox 87.0
* Operating system (`uname -a` on *Nix) Linux Mint

**Additional context**
LND shows fees correctly in this menu. This is only c-lightning bug.

**Comment by tukac** [comment]
It seems bug is wrong grep return. `lightning-cli listchannels <short channel ID>` returns two dictionaries. Values shown in Update Fee Policy are from first dictionary instead of second one.

**Comment by ShahanaFarooqui** [comment]
Closing with PR #665
