### ISSUE TITLE
Cannot Connect to RTL in Web Browser

### ISSUE THREAD

**Issue by techric** [Ride-The-Lightning/RTL#664]
![Capture copy](https://user-images.githubusercontent.com/6571806/115966897-46668a00-a4f5-11eb-9dce-beef1393c623.png)
I've recently set up a new Raspiblitz on another home network. When I try to connect to RTL using:

https://myIPAddress:3001

I get the error message: "This site cannot be reached. myIPAddress refused to connect ERR_CONNECTION_REFUSED

**Comment by saubyk** [comment]
Hi @techric 

Are you certain that the port is 3001? also have tried with http instead?

**Comment by techric** [comment]
Yes, I entered https and followed the Raspiblitz directions on GitHub to use Port 3001 to access RTL in the web browser.

**Comment by eatocia** [comment]
Have you checked nginx? 

On your Raspiblitz command line enter: sudo systemctl status nginx 

To restart nginx: sudo systemctl restart nginx

**Comment by techric** [comment]
That still didn't work.

**Comment by 357384N** [comment]
I am now having this same issue today. Can't connect via http 3000 or https 3001.

I think it's more than typing the wrong code.

I've tried adding port 3000 as a rule within my firewall, but no luck.

Please help!

**Comment by 357384N** [comment]
I just restarted my node and it works now
