### ISSUE TITLE
Enable CPFP for channel close transactions

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#675]
Enable CPFP feature for channel close transactions on LND.

**Comment by hieblmi** [comment]
Would this also include the CPFP feature for regular on-chain transactions?
![image](https://user-images.githubusercontent.com/18631614/122770608-9d79a880-d273-11eb-8740-fa6fa5d94a94.png)

**Comment by saubyk** [comment]
Hi @hieblmi this ticket specifically addresses channel close transactions only.

Onchain receipts can also be bumped up, but it would be best to cover it in a separate ticket. Additionally, from your example above, it would not be advisable to try to bump up Loop Out on chain receives with CPFP, because the `loop` service automatically takes care of on-chain sweeps with RBF.
You can read more about it here:
https://blog.lightning.engineering/technical/posts/2019/04/15/loop-out-in-depth.html

**Comment by hieblmi** [comment]
Thank you @saubyk - I will create a separate ticket for this.
It looks like though that the Loop service is only bumping the fee up to a user specified max value.
I for example set the value(block height) too low(~1sat/vbyte) hence the loop service is not RBFing/CPFPing anymore.

In these instances would it be advised to bump up manually?

Here's the text:
![image](https://user-images.githubusercontent.com/18631614/122956944-755f7780-d34f-11eb-87e4-6af495b14686.png)

**Comment by ShahanaFarooqui** [comment]
Closing with PR #1394.
