### ISSUE TITLE
Enable redundant encrypted channel states backups on cloud

### ISSUE THREAD

**Issue by theDavidCoen** [Ride-The-Lightning/RTL#677]
**Local backup-only can have tradeoffs**
Today we can backup our channel states locally and eventually have a redundant backup on an external HDD/SSD. This can be done on VPS too, but there is still a single point of failure (see for example OVHservers on fire). What if the VPS is corrupted/force closed? What if my HDD fails or my or my node+SSD catches fire?

**Local backup + remote backup**
It would useful to have an automatic redundant backup on cloud too; it could be a personal server (via FTP) or a 3rd party server (example, Google Cloud), but in both cases, it should be fundamental to encrypt the channel states before sending the files to the remote servers.
My idea is to have a "Redundant remote backup" in the backup page, near backup/restore.
Here the user should specify the service it wants to use (FTP/Google Drive), and encrypt the files using a password (it could be the same used to login RTL)

I tried to manually do a similar process but without success, because of my really basic esperience with Linux. 
It would be useful to have this kind of redundant backup within RTL with an easy UI/UX so users with low Linux experience can keep their channel states safe both locally and remotely.

**Comment by saubyk** [comment]
Hi @theDavidCoen what's the need to encrypt the channel backup file?
The file on its own is does not expose any sensitive information and even if compromised is useless without your node's private key which it must be used with, when attempting fund restoration.

You can safely maintain redundant copies of the channel backup file in plain text. Encrypting this backup file is a needless operation in my opinion.

**Comment by saubyk** [comment]
Hi @theDavidCoen I am assuming you agree with my assessment in the last comment. Closing this issue now. Thanks.

**Comment by theDavidCoen** [comment]
@saubyk I apologize, i forgot to reply to the comment.
I thought the encryption could be a protection against attacks on the cloud server.
However, i think you are right.
