### ISSUE TITLE
Update channel fee only Fee Rate fails

### ISSUE THREAD

**Issue by TheeHandwoven** [Ride-The-Lightning/RTL#679]
**Describe the bug**
In Channels, with the action to Update Fee Policy, if you don't change the Base fee, and only change the fee rate, then nothing will happen when clicking the Update button.

**To Reproduce**
1. Go to Lightning -> Channels
2. See your channels, and select "Actions" for one, then Update Fee Policy
3. Change the Fee Rate, but DON'T change the Base fee.
4. Click on the Update button

**Your environment**
* RTL 0.10.2
* C-Lightning v0.10.0
* bitcoind 0.21.1

**Comment by saubyk** [comment]
This is fixed with the release v0.11.0. Please update and verify. Thanks.
