### ISSUE TITLE
Default server host is not localhost.

### ISSUE THREAD

**Issue by lightningbrie** [Ride-The-Lightning/RTL#683]
**Describe the bug**
If one does not configure "host" explicitly in RTL-Config.json, the server does not listen on localhost. [Documentation states it does.](https://github.com/Ride-The-Lightning/RTL/blob/e4d625680312629bd4270c4d2380c78f82b849a1/docs/Application_configurations#L9) Instead the server will listen on all interfaces. Besides that, it will only listen on IPv6. It does not listen on an IPv4 port.

**To Reproduce**
1. Stop RTL
2. Edit RTL-Config.json: remove the "host" item if present. Take note of the "port" item if present.
3. Start RTL
4. type `netstat -tan | grep :3000` (assuming "port" in step 2 was 3000 or lacking)

**Expected result**
tcp and tcp6. Both localhost (`127.0.0.1` resp. `::1`).
```
~/RTL $ netstat -tan|grep :3000
tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN
tcp6       0      0 ::1:3000                :::*                    LISTEN          
~/RTL $
```

**Actual Result**
Only tcp6. All interfaces (`::`).
```
~/RTL $ netstat -tan|grep :3000
tcp6       0      0 :::3000                 :::*                    LISTEN          
~/RTL $
```

**Environment**
* Version of `RTL`: v0.10.2
* Version of `lnd`: v0.13.0-beta.rc2 
* Version of `bitcoind`: v0.21.1
* Browser & browser version: NA
* Operating system (`uname -a` on *Nix): Linux raspberrypi 5.10.35-v7l+ #1417 SMP

**Comment by saubyk** [comment]
Hi @lightningbrie even if `netstat` is not listing tcp in the result, the application is listening to the IP4 and localhost addresses. You can access the app in the browser by specifying Localhost, IP4 or IP6 addresses.

Not sure if I am understanding the problem correctly.

**Comment by lightningbrie** [comment]
Hi @saubyk there is no problem accessing the app in the browser. The problem: the app listens to **more** than just localhost. This is a security problem, as the documentation states it only listens on localhost. It suggests RTL will not be reachable from the outside while it is.

If one is aware RTL listens on all interfaces, one can start to think about measures like configuring a firewall to prevent unwanted traffic. The documentation suggests that is not needed, and people not checking this (for instance by using netstat) will have RTL listening on all interfaces (instead of just localhost) without being aware.

I hope this is more clear :)

**Comment by lightningbrie** [comment]
By the way, the fix can be easy (just adding `"host": "127.0.0.1",` to RTL-Config.json makes it listen to localhost only).

**Comment by saubyk** [comment]
Hi @lightningbrie understood.
We can make it clear in the documentation that RTL is listening on all IPs not just `localhost` by default, unless user specifies a particular host in the config.

Although, do note that without use particularly configuring the IP to be reachable from outside via a Port forwarding on the router and a reverse proxy configured, in a typical setting it will not be accessible from outside your home network.

**Comment by saubyk** [comment]
Well, port forwarding the RTL port more than the reverse proxy makes the app reachable from outside network.

**Comment by lightningbrie** [comment]
Totally agreed. :+1: 

Changing the documentation might be the best solution. Setting the "host" like I do above stops RTL from listening for IPv6 traffic. Which is no problem if people do it explicitly and consiously, but might be unwanted for default behaviour.

**Comment by saubyk** [comment]
Specified in the Application Configuration file that the app is listening on 'App IPs'.
