### ISSUE TITLE
Dashboard button disappears

### ISSUE THREAD

**Issue by iliaster94** [Ride-The-Lightning/RTL#686]
**Describe the bug**
So the Dashboard button disappears every time I go to the Payments tab and change the Tx per page. Doesn't matter which number, but as soon as I change it, button is gone and doesn't come back if I change back to 10 per page. 

**To Reproduce**
1. Go to Lightning>Transactions
2. Scroll to bottom under Payments and change the number of transactions to show per page
3. Dashboard disappears
4. Dashboard reappears upon reloading RTL **correction: it reappears only when I click my bookmark for RTL, not when I refresh the page

**Your environment**
* Version of `RTL` 0.10.1-beta
* Version of `lnd` 0.12.1~4
* Version of `btcd` 0.21.1
* Browser & browser version Firefox 88.0.1
* Operating system on Raspberry Pi is EmbassyOS

**Comment by ShahanaFarooqui** [comment]
This bug has been fixed with release 0.10.2, please update your local RTL. Original issue #268, Bug fixed with PR #645. Please feel free to reopen the issue if it persists after the upgrade. Closing it for now. Thanks.
