### ISSUE TITLE
Set default page size of lists

### ISSUE THREAD

**Issue by martinatime** [Ride-The-Lightning/RTL#688]
**Is your feature request related to a problem? Please describe.**
I typically have more than 10 channels but less than 25. I would like to see all of them without the extra click on changing the page size on the list.

**Describe the solution you'd like**
A simple configuration to allow the default size to be selected.

**Describe alternatives you've considered**
Change the default to be 25 for everyone

**Comment by mb300sd** [comment]
+1 Would like to set my default to 100 or higher.

**Comment by ShahanaFarooqui** [comment]
Closing with PR #1127.

**Comment by ShahanaFarooqui** [comment]
No problem, take your time.
