### ISSUE TITLE
Remove the 2% max routing fee limit on Loop Out requests

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#690]
Currently Loop Out request caps the 'Max Off-chain Routing Fee (%)' to 2%. This can result in routing failures if the circuits routing the payments are charging premium on the routing.

The limit should be removed to allow the user to pay higher routing fee for Loop transactions.

<img width="793" alt="Screen Shot 2021-05-31 at 7 54 05 PM" src="https://user-images.githubusercontent.com/39208279/120250149-1b392e00-c24b-11eb-82c9-6bb6b03f7b19.png">

**Comment by ShahanaFarooqui** [comment]
Closing with PR #703
