### ISSUE TITLE
Routing fee amounts are being displayed differently between report and dashboard summary

### ISSUE THREAD

**Issue by martinatime** [Ride-The-Lightning/RTL#692]
**Describe the bug**
Today I had a single routing event (so far) and the routing fee amount is 2500 mSats. On the report graph it states that as 3 but on the dashboard summary for the "Daily" it has it as 2 Sats.

**Screenshots**
![Screenshot 2021-06-02 182322](https://user-images.githubusercontent.com/258678/120560006-03d77d80-c3d0-11eb-9e55-71d63eae3948.png)
![Screenshot 2021-06-02 182430](https://user-images.githubusercontent.com/258678/120560021-076b0480-c3d0-11eb-95af-d54f8d1bfaf5.png)
![Screenshot 2021-06-02 182507](https://user-images.githubusercontent.com/258678/120560026-09cd5e80-c3d0-11eb-9b4c-b03e722ae3d1.png)

**Your environment**
* Version of `RTL` - 0.10.2-beta
* Version of `lnd` - 0.12.1-beta
* Version of `bitcoind` - 0.21.1

**Comment by ShahanaFarooqui** [comment]
Fixed and closing with PR #702.
