### ISSUE TITLE
All numbers represented in RTL should be in millisats

### ISSUE THREAD

**Issue by junseth** [Ride-The-Lightning/RTL#717]
RTL displays everything differently. Some of the screens show sats. Some show millisats. Can we please unify the display. It is very difficult to sometimes operate in sats and other times to operate in millisats.

I would like all RTL's UX to use millisats instead of sats. Given that this is now how it operates now, displaying should probably be added as a possible setting.

**Comment by rsafier** [comment]
I concur, lack of uniformity really can cause confusion to end users.

**Comment by saubyk** [comment]
@junseth thanks for creating a ticket, but we will not be able to meet this requirement.
Superficially, converting all the numbers to msats, may appear to solving a problem, but it will make the numbers too big to be interpreted reasonably by all the users.

Besides milli sats is too low a denomination for channel balances, on-chain funds etc. Milli sats is only used in the context of routing fee earned and the unit it specified on the header, where it's used.

Closing this ticket. If you have any other UX suggestions fee free to open new tickets for the same. Thanks.
