### ISSUE TITLE
Spend Unconfirmed Output option ignored

### ISSUE THREAD

**Issue by brentkearney** [Ride-The-Lightning/RTL#719]
**Describe the bug**
On v0.11.0-beta, selecting the "Spend Unconfirmed Output" option in the Open Channel -> Advanced Options form should disable the Amount validation. Even better would be to include Remaining Bal + the amount in all pending transactions, to calculate the actual remaining balance. Otherwise, how is it possible to spend unconfirmed outputs?

If I enter more sats than I have in my wallet, but if my unconfirmed output is included, then there is enough -- I cannot submit the Open Channel form due to validation failure on the Amount field, with the "Spend Unconfirmed Output" option enabled. It says I have a negative balance beside "Remaining bal". There would be enough if the sats in the pending transaction were included. The pending transaction is an open channel request that is stuck in the mempool due to too low fee. I'd like to open another channel to free my sats locked up in that pending open channel transaction.

**To Reproduce**

Before you begin, open a channel with 1 sat/vbyte, with 51% of your available funds, and watch it languish in the mempool as a "pending" channel open. Now your total sats are 49% of the original plus the 51% in the pending transaction.

1. In the Peers/Channels section, Peers tab, choose a connected Peer that you do not have an open channel with, and choose Action -> Open Channel.
2. In the Open Channel form, note that it has 49% of your total original funds under the Amount field, beside Remaining Bal.
3. Open the Advanced Options and enable the Spend Unconfirmed Output option.
4. Enter over 50% of your original funds in the Amount field, and set a generous fee.
5. Click the Open Channel button.
6. Instead of broadcasting the new transaction, the form does not submit, due to validation error on the Amount field.

**Screenshots**

**Your environment**
* Version of `RTL`: 0.11.0-beta
* Version of `lnd`: 0.12.1-beta
* Version of `btcd`, `bitcoind`, or other backend: core v0.21.1
* Browser & browser version, Safari 14.1.1
* Operating system (`uname -a` on *Nix) macOS 1.15.7
* any other relevant environment details

**Additional context**

**Comment by saubyk** [comment]
@brentkearney Not clear on how this is an issue.

In the scenario you laid out:
1. You've sent 51% of your funds on opening an channel which is currently unconfirmed.
2. And now you're trying to spend *more* than you have in the unconfirmed balance.

This is not something which will technically go through even if the UI validation is removed, you'll encounter an error from the LND API.

**Comment by saubyk** [comment]
Closing this ticket as the expectation laid out on the ticket cannot be met technically.
