### ISSUE TITLE
Settings not displaying

### ISSUE THREAD

**Issue by viperperidot** [Ride-The-Lightning/RTL#721]
**Describe the bug**
When I click on the 'settings' button on the top right of the application it takes me to the Settings page. However, under the 'Application' tab there are no settings displayed for adjusting.

**To Reproduce**
1. Click settings in top right
2. Click on settings
3. View application tab by default

**Screenshots**
![image](https://user-images.githubusercontent.com/70721357/123483684-5c133100-d5c4-11eb-8bca-801a5a19c1bb.png)

**Your environment**
* Version of 0.11.0
* Version of 0.13.0
* Version of 0.21.1
* Brave 1.25.73
* Ubuntu
* Some browser extentions

**Additional context**
When I switch to the authentication settings tab it displays the information, this is only not showing for the application settings tab.

**Comment by willwooten** [comment]
hi-
i just checked this, and figured out what is happening. 

The Application Settings do not become visible unless you have at least 2 nodes in your RTL-config.json.
![application](https://user-images.githubusercontent.com/42416243/124047340-a12acf00-d9d9-11eb-8046-21b3dcacf40f.png)

In app-settings.component.html it checks to see if there is more than one node.

`<form *ngIf="appConfig.nodes && appConfig.nodes.length && appConfig.nodes.length > 1" fxLayout="column" fxFlex="100" fxLayoutAlign="start stretch" class="settings-container page-sub-title-container mt-1" #form="ngForm">`

I tried changing `appConfig.nodes.length > 1` to `appConfig.nodes.length > 1` but it had no effect. but adding a second node to the RTL-config.json makes the settings appear.

**Comment by ShahanaFarooqui** [comment]
@willwooten thanks for debugging the issue. Good catch. HTML file updates will not reflect directly on production server without building the angular app again. To check the changes in real time, you need to get the dev server up and running. I will add Contribution instructions soon on the GitHub to avoid these confusions.

**Comment by ShahanaFarooqui** [comment]
@viperperidot Thanks for raising the issue, @willwooten Thanks for the help. We updated the [contribution.md](https://github.com/Ride-The-Lightning/RTL/blob/Release-0.11.1/docs/Contributing.md) to explain the development environment setup in detail. The fix will be released with v0.11.1, closing the issue now.
