### ISSUE TITLE
RTL not connecting to local LND node

### ISSUE THREAD

**Issue by bensig** [Ride-The-Lightning/RTL#723]
**Describe the bug**
Followed installation steps - but I'm getting this error when I authenticate 

Error ECONNRESET
Fetching Info Failed! Unknown Error

![image](https://user-images.githubusercontent.com/1872138/124186746-c1669680-da8a-11eb-86c1-94f9b6d0b5e5.png)

and in the logs:

```[2021-07-01T20:30:48.272Z] ERROR: GetInfo => Get Info Error: {"name":"RequestError","message":"Error: read ECONNRESET","cause":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"error":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"options":{"url":"http://localhost:10009/v1/getinfo","rejectUnauthorized":false,"json":true,"headers":{},"method":"GET","qs":{},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
```

I can click around in RTL but no LND node information is appearing...

**To Reproduce**
1. install btcd (sync)
2. install lnd (connected to btcd and working normally)
3. clone github and install following steps in README
4. Login (password appears to work fine)
5. See error in log

**Screenshots**

**Your environment**
* Version of `RTL` `0.11.0-beta`
* Version of `lnd` `lnd version 0.13.99-beta commit=v0.13.0-beta-27-gf9a51882`
* Version of `btcd`, `bitcoind`, or other backend btcd version 0.22.0-beta`
* Browser & browser version
* Operating system (`uname -a` on *Nix) `5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* any other relevant environment details

**Additional context**
contents of RTL-config.json *anonymized with <>*

```{
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "<nodename>",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "<lndpath>/data/chain/bitcoin/mainnet",
        "configPath": "<lndpath>/lnd.conf"
      },
      "Settings": {
        "userPersona": "MERCHANT",
        "themeMode": "DAY",
        "themeColor": "PURPLE",
        "channelBackupPath": "<path>/backups",
        "enableLogging": false,
        "lnServerUrl": "http://localhost:10009/v1",
        "fiatConversion": false
      }
    }
  ],
  "multiPassHashed": "<hashed-pw>"
}
```

contents of lnd.conf
```
[Application Options]
bitcoin.active=true
bitcoin.mainnet=true
bitcoin.node=btcd
alias=<node>
color=#FDD023
rpclisten=127.0.0.1:10009

[autopilot]
autopilot.active=true
autopilot.maxchannels=5
autopilot.allocation=0.6
autopilot.maxchansize=20000
autopilot.minconfs=2
autopilot.conftarget=2
```

**Comment by ShahanaFarooqui** [comment]
1) `lnServerUrl` should be set to restlisten NOT rpclisten in RTL-config.JSON:

"lnServerUrl": "https://localhost:8080"

2) Need to add `restlisten` in lnd.conf, like below:

restlisten=0.0.0.0:8080

Please do not forget to restart the lnd and the RTL server after making above changes.

**Comment by saubyk** [comment]
@bensig are you able to get it working?

**Comment by bensig** [comment]
Thanks for the reply. 

I updated `restlisten` in lnd.conf and  `lnServerUrl` in RTL-Config.JSON

I got a new error now related to http requests being sent to an https server

```
[2021-07-04T01:16:25.707Z] ERROR: GetInfo => Get Info Error: {"name":"StatusCodeError","statusCode":400,"message":"400 - \"Client sent an HTTP request to an HTTPS server.\\n\"","error":"Client sent an HTTP request to an HTTPS server.\n","options":{"url":"http://localhost:8080/v1/getinfo","rejectUnauthorized":false,"json":true,"headers":{},"method":"GET","qs":{},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":400,"body":"Client sent an HTTP request to an HTTPS server.\n","headers":{},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"localhost:8080","port":"8080","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/v1/getinfo","path":"/v1/getinfo","href":"http://localhost:8080/v1/getinfo"},"method":"GET","headers":{"accept":"application/json"}}}}
```

**Comment by ShahanaFarooqui** [comment]
@bensig Please configure your `lnServerUrl` with `https://localhost:8080` NOT `http://localhost:8080`.

**Comment by bensig** [comment]
Seems to be working, but now I am seeing this in the lnd log:

`2021-07-04 01:30:49.026 [ERR] RPCS: [/lnrpc.Lightning/GetTransactions]: the RPC server is in the process of starting up, but not yet ready to accept calls`

**Comment by bensig** [comment]
My LND log after restarting
```
2021-07-04 01:35:44.979 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2021-07-04 01:35:44.980 [INF] RPCS: gRPC proxy started at 0.0.0.0:8080
2021-07-04 01:35:44.980 [INF] LTND: Opening the main database, this might take a few minutes...
2021-07-04 01:35:44.981 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=false
2021-07-04 01:35:45.390 [INF] CHDB: Checking for schema update: latest_version=22, db_version=22
2021-07-04 01:35:45.391 [INF] LTND: Database now open (time_to_open=409.74501ms)!
2021-07-04 01:35:45.391 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2021-07-04 01:35:50.948 [INF] LNWL: Opened wallet
2021-07-04 01:35:51.012 [INF] CHRE: Primary chain is set to: bitcoin
2021-07-04 01:35:51.023 [INF] CHRE: Initializing btcd backed fee estimator
```

**Comment by saubyk** [comment]
@bensig its working normally now. are you able to connect RTL?

**Comment by bensig** [comment]
No, it just says that my RPC server is still in the process of starting up.
`Fetching Info Failed! the RPC server is in the process of starting up, but not yet ready to accept calls`

![image](https://user-images.githubusercontent.com/1872138/124370561-020b0f00-dc47-11eb-90f3-22d4fe65e7e8.png)

**Comment by saubyk** [comment]
Please share your lnd.conf and RTL-Config.json again

**Comment by bensig** [comment]
RTL-Config.json

```
{
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "NobiLND",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "<lndpath>.lnd/data/chain/bitcoin/mainnet",
        "configPath": "<lndpath>.lnd/lnd.conf"
      },
      "Settings": {
        "userPersona": "MERCHANT",
        "themeMode": "DAY",
        "themeColor": "PURPLE",
        "channelBackupPath": "<path>/backups",
        "enableLogging": false,
        "lnServerUrl": "https://localhost:8080",
        "fiatConversion": false
      }
    }
  ],
  "multiPassHashed": "<removed>"
}
```

lnd.conf
```
[Application Options]
bitcoin.active=true
bitcoin.mainnet=true
bitcoin.node=btcd
alias=<name>
color=#FDD023
rpclisten=127.0.0.1:10009
restlisten=0.0.0.0:8080

[autopilot]
autopilot.active=true
autopilot.maxchannels=5
autopilot.allocation=0.6
autopilot.maxchansize=20000
autopilot.minconfs=2
autopilot.conftarget=2
```

**Comment by saubyk** [comment]
can you please try removing `rpclisten=127.0.0.1:10009` line from the lnd.conf and restart LND.
Are you using rpc port for any application? If not, I would recommend not enabling it.

**Comment by bensig** [comment]
Thanks again for your help. I removed that and restarted LND. My LND was previously loading fine, but now it seems to get stuck at:

`2021-07-04 01:55:01.721 [INF] CHRE: Initializing btcd backed fee estimator`

Any ideas?

**Comment by bensig** [comment]
I increased debugging on my btcd.conf to try to troubleshoot this -- could be a connection between my lnd and btcd causing an issue, but IDK why that was working fine before I started to connect RTL... strange!

**Comment by saubyk** [comment]
I am sorry, I don't have any experience with running LND with btcd. I have always run it with bitcoind

**Comment by bensig** [comment]
Thank you! At least we got the RTL config corrected. Appreciate the help.

**Comment by saubyk** [comment]
is your LND coming up at all? and are you able to connect RTL with it?

**Comment by bensig** [comment]
Not yet. I'm still stuck at the same spot. Maybe lnd takes some more time to start up? 🤷‍♀️  

Previously it seemed to be started and reading the network just fine. Not sure what changed.

**Comment by bensig** [comment]
Just wanted to come back here and say that I was able to overcome this error `CHRE: Initializing btcd backed fee estimator` by adding the following params to my lnd.conf
```
btcd.rpcuser=<hash>
btcd.rpcpass=<hash>
btcd.rpchost=127.0.0.1:8337
```

**Comment by saubyk** [comment]
Thanks for the update. Is your RTL connecting with LND now?

**Comment by bensig** [comment]
Yep. We are good! Thanks for the support!
