### ISSUE TITLE
[eclair] Reports -> Transactions doesn't show anything

### ISSUE THREAD

**Issue by viaj3ro** [Ride-The-Lightning/RTL#727]
Fee reports is working fine, when I switch to transactions, it says "No transactions report for the selected period"

eclair 0.6.0
RTL 0.11.0

**Comment by ShahanaFarooqui** [comment]
@viaj3ro As long as I recall, this issue was fixed over our Telegram discussion. Can you please confirm if I can close it or if it still persists?

**Comment by viaj3ro** [comment]
yeah, it's working fine now. Just one month of fee reports is missing for some reason.

**Comment by ShahanaFarooqui** [comment]
@viaj3ro The single month fee report missing points at some data specific issue. You can share your logs on Telegram if you want it to be debugged. Closing it here.
