### ISSUE TITLE
[eclair] Suggest zero base fee when setting fee rate

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#730]
**Is your feature request related to a problem? Please describe.**
Zero base fee seems to be the way to progress LN forward. However when updating channel fees, a non-zero fee is suggested despite the channel already having zero fee. Thus I have to change it every time I change fees.

**Describe the solution you'd like**
Either of these:

* Suggest previously set base fee
* Always suggest zero fee

Possibly also have a button to set all fees to zero.
Possibly also a setting to remove the base fee field from UI (and just set it to zero).

**Describe alternatives you've considered**
* Keep manually setting to zero
* Hack some horrible script to do it automatically
* Cease to use RTL

**Additional context**
[Why zero base fee is important](https://basefee.ln.rene-pickhardt.de/)

**Comment by ShahanaFarooqui** [comment]
@Kixunil Thank you for the suggestion. However, these suggestions are already available in RTL.

Current Eclair implementation:

- Suggests previously set base fee. So if the channel has zero fee then `0` fee will be shown in the modal.
- Update all channels fee policy can be found on the top `Actions` menu.

Closing the issue now.
