### ISSUE TITLE
How to return the balanse on-chain?

### ISSUE THREAD

**Issue by mass34** [Ride-The-Lightning/RTL#733]
Bitcoin Core RPC client version v0.21.1
RTL v.0.10.0-beta
bitcoin-lightning-cli.sh -V
basedon-v0.9.3-1

The channel is closed, forcibly.
RTL generate address (bech32)
bitcoin-lightning-cli.sh close id time(120) address (on-chain) (generate RTL)
Confirmed.
Peers/Channels > Pending/Inactive > "Connected NO", "State ONCHAIN"
On-chain Balance 0
UTXOs > No transactions available.
The transaction came to another address.
What you need to do that Satoshi appeared in "On-chain Balance"?

**Comment by saubyk** [comment]
Hi, trying to understand your problem better

1. Which lightning implementation are you running? C-Lightning or LND?
2. Who initiated the force channel closure, you or your peer?
3. Did the channel had *non-dust* local balance, which you are hoping to get back on-chain?

Also, please upgrade your RTL version to the latest v0.11.0 (Although, that does not have any bearing on this issue per se).

**Comment by mass34** [comment]
Hi.
C-Lightning. (BTCPayServer)
My initialization. Web interface: Peers/Channels>Open> Action>Dissconnect. The canal remained open, after 4 days it was "CHANNELD_SHUTTING_DOWN"

Made above described (bitcoin-lightning-cli.sh close id time(120) address (on-chain) (generate RTL)).
`bitcoin-lightning-cli.sh listpeers
{
   "peers": [
      {
         "id": "........fbec......",
         "connected": false,
         "channels": [
            {
               "state": "ONCHAIN",
               "scratch_txid": "0f12821e9f6c6576b3fc24667d416d0a77493952723731257be550d475a18b5a",
               "owner": "onchaind",
               "short_channel_id": "6....2x...x0",
               "direction": 1,
               "channel_id": "65f..........",
               "funding_txid": "214854fd7fe150bd76f5ee92d82a2ab826c613adf06c291c27076cb863dff965",
               "close_to_addr": "bc1qz.........",
               "close_to": "00141307bfde81af125ddb8cc59876ae824a2b8ff9b9",
               "private": false,
               "opener": "local",
               "closer": "local",
               "features": [
                  "option_static_remotekey"
               ],
               "funding_allocation_msat": {
                  "........fbec......": 0,
                  "........10cf......": 100000000
               },
               "funding_msat": {
                  "........fbec......": "0msat",
                  "........10cf......": "100000000msat"
               },
               "msatoshi_to_us": 100000000,`
Transactions were not .

**Comment by mass34** [comment]
Praise Heaven! My Satoshi came home.
Who will tell what happened? 
'bitcoin-lightning-cli.sh listpeers
{
   "peers": [
      {
         "id": "......fbec.....",
         "connected": false,
         "channels": [
            {
               "state": "ONCHAIN",
               "scratch_txid": "0f12821e9f6c6576b3fc24667d416d0a77493952723731257be550d475a18b5a",
               "owner": "onchaind",
               "short_channel_id": "691412x592x0",
               "direction": 1,
               "channel_id": "65f.....",
               "funding_txid": "214854fd7fe150bd76f5ee92d82a2ab826c613adf06c291c27076cb863dff965",
               "close_to_addr": "bc1qz....The address that was specified in the Forced",
               "close_to": "00141307bfde81af125ddb8cc59876ae824a2b8ff9b9",
               "private": false,
               "opener": "local",
               "closer": "local",
               "features": [
                  "option_static_remotekey"
               ],
               "funding_allocation_msat": {
                  ".........fbec........": 0,
                  ".........10cf........": 100000000
               },
               "funding_msat": {
                  ".........fbec..........": "0msat",
                  ".........10cf...........": "100000000msat"
               },
               "msatoshi_to_us": 100000000,
               "to_us_msat": "100000000msat",
               "msatoshi_to_us_min": 100000000,
               "min_to_us_msat": "100000000msat",
               "msatoshi_to_us_max": 100000000,
               "max_to_us_msat": "100000000msat",
               "msatoshi_total": 100000000,
               "total_msat": "100000000msat",
               "fee_base_msat": "1msat",
               "fee_proportional_millionths": 1,
               "dust_limit_satoshis": 546,
               "dust_limit_msat": "546000msat",
               "max_htlc_value_in_flight_msat": 18446744073709551615,
               "max_total_htlc_in_msat": "18446744073709551615msat",
               "their_channel_reserve_satoshis": 1000,
               "their_reserve_msat": "1000000msat",
               "our_channel_reserve_satoshis": 1000,
               "our_reserve_msat": "1000000msat",
               "spendable_msatoshi": 98460000,
               "spendable_msat": "98460000msat",
               "receivable_msatoshi": 0,
               "receivable_msat": "0msat",
               "htlc_minimum_msat": 0,
               "minimum_htlc_in_msat": "0msat",
               "their_to_self_delay": 144,
               "our_to_self_delay": 144,
               "max_accepted_htlcs": 30,
               "state_changes": [
                  {
                     "timestamp": "2021-07-17T09:55:42.003Z",
                     "old_state": "CHANNELD_AWAITING_LOCKIN",
                     "new_state": "CHANNELD_NORMAL",
                     "cause": "user",
                     "message": "Lockin complete"
                  },
                  {
                     "timestamp": "2021-07-17T10:29:56.769Z",
                     "old_state": "CHANNELD_NORMAL",
                     "new_state": "CHANNELD_SHUTTING_DOWN",
                     "cause": "user",
                     "message": "User or plugin invoked close command"
                  },
                  {
                     "timestamp": "2021-07-20T17:40:34.786Z",
                     "old_state": "CHANNELD_SHUTTING_DOWN",
                     "new_state": "AWAITING_UNILATERAL",
                     "cause": "user",
                     "message": "Forcibly closed by `close` command timeout"
                  },
                  {
                     "timestamp": "2021-07-20T23:15:19.350Z",
                     "old_state": "AWAITING_UNILATERAL",
                     "new_state": "FUNDING_SPEND_SEEN",
                     "cause": "user",
                     "message": "Onchain funding spend"
                  },
                  {
                     "timestamp": "2021-07-20T23:15:19.418Z",
                     "old_state": "FUNDING_SPEND_SEEN",
                     "new_state": "ONCHAIN",
                     "cause": "user",
                     "message": "Onchain init reply"
                  }
               ],
               "status": [
                  "CHANNELD_SHUTTING_DOWN:Reconnected, and reestablished.",
                  "ONCHAIN:Tracking our own unilateral close",
                  "ONCHAIN:All outputs resolved: waiting 53 more blocks before forgetting channel"
               ],
               "in_payments_offered": 0,
               "in_msatoshi_offered": 0,
               "in_offered_msat": "0msat",
               "in_payments_fulfilled": 0,
               "in_msatoshi_fulfilled": 0,
               "in_fulfilled_msat": "0msat",
               "out_payments_offered": 0,
               "out_msatoshi_offered": 0,
               "out_offered_msat": "0msat",
               "out_payments_fulfilled": 0,
               "out_msatoshi_fulfilled": 0,
               "out_fulfilled_msat": "0msat",
               "htlcs": []
            }
         ]
      }
   ]
}
'

**Comment by saubyk** [comment]
Hi @mass34 
When you force close a channel the local balance on your channel is locked for a set number of blocks, this is done to ensure that your peer is given enough time to come back online and ensure that you're not cheating by broadcasting an older channel state.

You can see from your channel information that this delay period was 144 blocks:
`"our_to_self_delay": 144`

Also, you could see from your channel information how many blocks were remaining for the on-chain funds to clear:
`ONCHAIN:2 outputs unresolved: in 62 blocks will spend DELAYED_OUTPUT_TO_US`

You can read more about this on the LN Book GitHub page below:
https://github.com/lnbook/lnbook/blob/develop/03_how_ln_works.asciidoc

Hope this clarified your doubts. Closing this ticket now. Thanks.
