### ISSUE TITLE
Changes to the circular rebalancing modal

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#739]
1. Remove the fee estimate control, as the fee estimate offers no practical value to the user and if the user uses the estimate, the rebalancing attempt almost always fails.
2. For the rebalance fee, allow fractional amounts to be specified in the percentage of payment amount. As 1% of the payment (the current minimum allowed) is too much fee to pay over LN.

**Comment by yik77** [comment]
why is fee estimate so useless? why are routes and fees hidden from user?

**Comment by ShahanaFarooqui** [comment]
@saubyk LND throws error as `Error: Json: cannot unmarshal number 0.1 into go value of type int64` if the UI sends the request with fractional fee percentage. So basically, LND doesn't allow fractional percentage. Please advice.

**Comment by ShahanaFarooqui** [comment]
> 1. Remove the fee estimate control, as the fee estimate offers no practical value to the user and if the user uses the estimate, the rebalancing attempt almost always fails.
Removed with PR #758.

> 2. For the rebalance fee, allow fractional amounts to be specified in the percentage of payment amount. As 1% of the payment (the current minimum allowed) is too much fee to pay over LN.
It is the limitation from LND and cannot be fixed at out end.
