### ISSUE TITLE
Contrast is off in a few toggle controls in dark mode

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#744]
The contrast is off in toggle controls on:
- The 'Spend Unconfirmed Output' and 'Private Channel' switch on the open channel modal
- 'Private Routing Hints' on the create invoice modal

<img width="384" alt="Screen Shot 2021-08-01 at 8 02 27 AM" src="https://user-images.githubusercontent.com/39208279/127770143-aa6d5ebe-5e03-4544-9e33-ed3b42733310.png">
<img width="384" alt="Screen Shot 2021-08-01 at 8 02 58 AM" src="https://user-images.githubusercontent.com/39208279/127770152-a4cfc10e-fe95-4c62-b9ab-20845670dce9.png">
<img width="257" alt="Screen Shot 2021-08-01 at 8 03 35 AM" src="https://user-images.githubusercontent.com/39208279/127770166-5a5fbdfd-9b6d-4b2c-a075-0d0c135f46be.png">

**Comment by ShahanaFarooqui** [comment]
It was a tiny CSS bug and has been fixed somewhere with last PR.
