### ISSUE TITLE
Attempt to loop out continues to fail

### ISSUE THREAD

**Issue by PatMulligan** [Ride-The-Lightning/RTL#752]
**Describe the bug**
I have a channel open with ACINQ on which I have a 2MM Sat local balance. I'd like to loop out 1.75MM of it and I'm using the loopout feature on Ride The Lightning.

In inspecting docker `logs generated_bitcoin_rtl_1`

I am seeing failure reasons of :

"FAILURE_REASON_OFFCHAIN"
"FAILURE_REASON_TIMEOUT"

Let me know if you need more from the logs, I'm just not sure if there's any sensitive info that's better of not to share...

I am running a lightning node using BTCPayServer on a RPi4 and I am using a reverse SSH tunnel in order to connect with the device from outside. I noticed that i wasn't forwarding port 3000, which the RTL container is on... I am currently trying to open up that port, attempt the loop out again and see if that fixes it.

for the parameters I put:
- sweep confirmation size : 40
- max off-chain routing fee : 1%
I have also tried the default parameters 6 and 2%, respectively.

**To Reproduce**
1. Go to ' Lightning > Peers/Channels > ACINQ > Actions > Loopout '
2. Fill out Amount : 1750000, Sweep Confirmation Target : 40, Max Off-chain Routing Fee: 1%
3. Estimate and confirm quote, select "node local address" for withdrawal address
4. Shows 'initiated' status in "Lightning > Loop" but eventually fails

**Screenshots**

**Your environment**
* `BTCPay Server  v1.2.1.0`
* Version `RTL 0.10.0` 
* Version `lnd 0.13.1-beta-withloop-fix` 
* Version `bitcoind 0.21.1`
* Browser `Chromium 92.0.4515.131 (Official Build) (64-bit)`
* OS `Linux raspberrypi 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l GNU/Linux`
* Hardware `RPi4B 8GB RAM `

**Additional context**
In order to connect with the raspberry pi, I use a [reverse auto ssh tunnel](https://docs.btcpayserver.org/ReverseSSHtunnel/)

**Comment by saubyk** [comment]
Hi @PatMulligan the most likely reason for loop out failure is the failure to route the transaction amount all the way to the Loop node. You can try the below:
- Reduce the amount you're trying to loop out. Try with the min possible amount first (250,000 sats)
- Bid up the off-chain routing fee limit to the max you can

If possible, update to the latest version of RTL (v0.11.0), which removed the routing cap of 2% so that you can pay more routing fee to route Loop transactions.

Please keep in mind that 'Loop out' is a service in high demand on LN, which results in liquidity providers bidding up the routing fee they are charging significantly.

**Comment by PatMulligan** [comment]
Hi @saubyk thanks for the quick reply. I tried again with 250k, 40 confirmation blocks and the max 2% since I'm still on v0.10.0, but still seeing the failure "FAILURE_REASON_OFFCHAIN".

I will keep trying and see if one goes through.

**Comment by ShahanaFarooqui** [comment]
@PatMulligan Hi, were you able to loop out successfully? 
@saubyk Can I close the issue if no further action is required from RTL?

**Comment by PatMulligan** [comment]
Yes, I have been able to loop out successfully the last time I tried! I think the issue has been solved. Thanks :)

**Comment by maximlomans** [comment]
Same here;
...but i'm on 0.13.3-beta "FAILURE_REASON_OFFCHAIN". one possible reason, or at least what i spotted in the logs, was offchain address type "htlc_address_np2wsh", apparently it didn't find one. - btw; i'm running Lightning Labs' lit-loop on- Raspiblitz 1.7.1 | Tor - so it's not an exclusively RTL bug  - I've disabled autoloop, till i find out why even when [lit-loop] 'Loops Complete', history logs show "failed".
