### ISSUE TITLE
No error message on modal when peer refuses to connect

### ISSUE THREAD

**Issue by violet360** [Ride-The-Lightning/RTL#766]
**bug description**
whenever you connect to weak peer and if the peer disconnects, no error is thrown on the modal

**To Reproduce**
1. connect to weak peer, I am on c-lightning implementation , so for me [this one](https://1ml.com/testnet/node/0260d9119979caedc570ada883ff614c6efb93f7f7382e25d73ecbeba0b62df2d7) worked.
2. the console shows this.newlyAddedPeer is undefined.

**screenshot**
![Screenshot from 2021-08-23 03-52-26](https://user-images.githubusercontent.com/46649871/130372173-22e6c71b-fee8-4acb-9fce-329a3df34c2f.png)

**Comment by ShahanaFarooqui** [comment]
It was a code merge issue and was fixed with latest merge. Closing it now.
