### ISSUE TITLE
reloading reports page throws error

### ISSUE THREAD

**Issue by darthginger** [Ride-The-Lightning/RTL#776]
**Describe the bug**
reloading the /rtl/lnd/reports/routingfees ("Reports") page shows a "Error: Unexpected Token < In Json At Position 0" instead of the data. Using the menu to the left to switch away and then back again and the data loads
**To Reproduce**
0.Login
1. Go to 'Reports'
2. Press 'F5'

**Screenshots**
![image](https://user-images.githubusercontent.com/8257956/131267833-00cb10b3-120c-4dd9-97aa-67fb9a89104d.png)

**Your environment**
* Version of `RTL` 0.11.1
* Version of `lnd` 0.13.1
* Version of `btcd`, `bitcoind`, or other backend bitcoind 0.21.1
* Browser & browser version Brave Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (64-bit)
* Operating system (`uname -a` on *Nix) Linux 5.10.0-8-amd64  SMP Debian 5.10.46-2 (2021-07-20) x86_64 GNU/Linux
* any other relevant environment details

**Additional context**
Didn't happen on 0.11.0

**Comment by ShahanaFarooqui** [comment]
@darthginger  Thanks for raising the issue. It was a bug which has been fixed with PR #783 and will be released with 0.11.2.
