### ISSUE TITLE
Cannot add peer 500

### ISSUE THREAD

**Issue by benjamin-wilson** [Ride-The-Lightning/RTL#778]
**Describe the bug**
Trying to add a peer results in the message Need: "lnc pubkeyhash@hostname"

**To Reproduce**
Lightning > Peers > Peers Tab > Add Peer > enter 02dfdcca40725ca204eec5d43a9201ff13fcd057c369c058ce4f19e5c178da09f3 > click add peer button
**Screenshots**

![Screenshot from 2021-09-01 09-25-35](https://user-images.githubusercontent.com/1399163/131679497-41969900-571f-4a1e-bb73-30c96765345f.png)

**Your environment**
* Version of `RTL` 11.1-beta
* Version of `lnd`  0.13.1-beta
* Version of `btcd`, `bitcoind`, or other backend 21.0
* Browser & browser version chrome
* Operating system (`uname -a` on *Nix) raspiblitz

**Additional context**
POST /rtl/api/lnd/peers
{"pubkey":"02dfdcca40725ca204eec5d43a9201ff13fcd057c369c058ce4f19e5c178da09f3","host":"46.101.138.202:9735","perm":false}
*returns* 
{"message":"need: lnc pubkeyhash@hostname","error":"need: lnc pubkeyhash@hostname"}

**logs**
ERROR: Peers => Connect Peer Error: {"name":"StatusCodeError","statusCode":500,"message":"500 - {\"error\":\"need: lnc pubkeyhash@hostname\",\"code\":2,\"message\":\"need: lnc pubkeyhash@hostname\",\"details\":[]}","error":{"error":"need: lnc pubkeyhash@hostname","code":2,"message":"need: lnc pubkeyhash@hostname","details":[]},"options":{"url":"https://localhost:8080/v1/peers","rejectUnauthorized":false,"json":true,"headers":{},"method":"POST","qs":{},"form":"{\"perm\":false}","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":500,"body":{"error":"need: lnc pubkeyhash@hostname","code":2,"message":"need: lnc pubkeyhash@hostname","details":[]},"headers":{"content-type":"application/json","trailer":"Grpc-Trailer-Content-Type","date":"Wed, 01 Sep 2021 16:43:06 GMT","connection":"close","transfer-encoding":"chunked"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"localhost:8080","port":"8080","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/v1/peers","path":"/v1/peers","href":"https://localhost:8080/v1/peers"},"method":"POST","headers":{"content-type":"application/x-www-form-urlencoded","accept":"application/json","content-length":14}}}}

**Comment by benjamin-wilson** [comment]
Downgrading to 10.1-beta resolves this issue.

**Comment by ShahanaFarooqui** [comment]
@benjamin-wilson Thanks for raising the issue. It was a bug which has been fixed with PR #785 and will be released with 0.11.2.

**Comment by ShahanaFarooqui** [comment]
@benjamin-wilson the bug fix has been released with Release0.11.2-beta. Please feel free to upgrade the version.
