### ISSUE TITLE
Adding any peer ends with "Need: lnc pubkeyhash@hostname"

### ISSUE THREAD

**Issue by agd-media** [Ride-The-Lightning/RTL#788]
**Describe the bug**
Despite using pubkeyhash@hostname there is this failure with every peer I try to add.

**To Reproduce**
1. Add peer 03f2f3b5ac54d7b4fbecc0978888b66fe318af6595b6344ba7a2368e61075ffc98@hcbl56od7rwbcxjmhwrk3stikpc7t7dnsekimfyy7dqlr4si3r3n2rid.onion:9735 (or any other)
2. Result is "Need: lnc pubkeyhash@hostname"

**Your environment**
RTL 0.11.1
LND 0.13.1-beta
BTC v0.21.0

**Comment by saubyk** [comment]
Hi @agd-media 
This issue has been fixed with the hotfix release v0.11.2. please update your RTL version.
https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.11.2

Thanks
