### ISSUE TITLE
Problems such as not being able to add peers, not being able to transfer funds after receiving them, etc.

### ISSUE THREAD

**Issue by zuizuibase** [Ride-The-Lightning/RTL#789]
I have built a BTCPay server on Raspberry Pi 4 as per the following page

https://docs.btcpayserver.org/RPi4/

After the synchronization was completed, I used RTL, but when I tried to add a peer, I got an error like the one in the image and could not add a peer.

![E-CLwl1VQAAsErO](https://user-images.githubusercontent.com/77468356/132128393-350b5dbd-01da-4f0d-ad52-d25014252d31.jpg)

This problem was solved by linking the node to Joule and adding a peer on the Joule side (not yet possible on the RTL side).

We also succeeded in adding a peer by connecting to the Raspberry Pi via SSH and entering commands in lncli.
I then opened a channel with LNBig and secured the inbound capacity.

I then created an invoice on the Raspberry Pi node and successfully transferred 100 Sats from the mobile wallet!
However, when I try to transfer 10Sats to my mobile wallet, it says the balance is insufficient.

![insu](https://user-images.githubusercontent.com/77468356/132128764-4e58d330-cdb8-41a4-b2f0-0d27907c6701.png)

My outband capacity should be enough, but I can't transfer money even with Joule and lncli commands.
I have tried restarting lnd and rebuilding on raspberry pi many times, but the same problem occurs.

I also contacted the BTCPay server, but they said it was a problem on the lnd side...
I don't have any technical knowledge, but I'm sure there's a reason for the problem, because I've tried to build it again and again according to the Docs.

If this problem is solved, people can have a free payment system including lightning for only $200, which is great.

Sorry for my English in translation software, but please help me!

Device: Raspberry Pi 4 8GB
LND version:0.11.1-beta
Implementation:LND0.13.1-beta commit=basedon-v0.13.1-beta-withloop-fix-fresh-btcpay

![conf](https://user-images.githubusercontent.com/77468356/132129040-a8ebc753-5b05-4d11-b999-dde9c7eb6fb7.png)

**Comment by saubyk** [comment]
Hi @zuizuibase 
The issue related to connecting with a peer has been addressed with a hot fix release v0.11.2. Please update your RTL version to address it.
https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.11.2

Regarding your inability to make a payment, I see from the screenshot, that you have unusually low channel balance on your outgoing side (1010 sats), which might not be sufficient to accommodate other associated operations with payments like updating reserve balances etc.

You should be able to make payments if you open channels with more capacity on your side. Closing this issue now.

Thanks
