### ISSUE TITLE
Offers - Basic One time Payments

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#795]
Paying an offer
- User clicks on the `Send Payment` button under the Payments tab
- User is presented with 3 options to choose from Invoice/Keysend/Offer
- If the user selects `Offer`, user is asked to enter the bolt12 offer string
- Decode the offer with C-Lightning-REST API: `/utility/decode`
- Fetch the invoice with C-Lightning-REST API: `/offers/fetchInvoice`
- Confirm with user, the intention to pay the amount on the invoice.
- If the user confirms, make the payment with the C-Lightning-REST API: `/pay`

**Comment by ShahanaFarooqui** [comment]
@violet360 Thanks for the contribution. Closing with PR #886.
