### ISSUE TITLE
Offers - Offers page and Create Offer

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#803]
Under the `Lightning/Transactions` menu, create a new tab for `Offers`
- On the Offers tab
  - There should be a button `Create Offer` to enable setting up of a new offer
  - There should be a list displaying existing offers already setup
  - On each row of the list of offers, there should be an actions menu with the options of `View Info`/`Disable Offer`/`Print QR code`

List Columns
    - Offer ID e.g. 8c0684d82076f3497691b4a76cbc6...
    - Active (True/False)
    - Single Use (True False)
    - Used (True/False)

When the user clicks on `View Info`, the modal with the QR code of Bolt12 string along with other details of the offer should be displayed.
E.g. Bolt12 Offer string: lno1qgsyxjtl6luzd9t3pr62xr7eemp6awnejusgf6gw45q75vcfqqqqqqqgqvqcdgq2zafh26r9vgnhxgp3xqczqumpwss8qcted4jkuaq7yqvyf043d0udmrrmcvzc3wxr0vmwv2m3cm5p96dkm9mvpft7z5d79uzqfgn82s5e5rn7vlp7k9d96tsv8kmg69fwa4d243706hra2glm22qduch5jy7w923s65mcljdxktsmkk24w2ra963vstd5m3xu5qyl6pg

- Create offer
  - C-Lightning-REST API: `/offers/offer`
  - Required parameters: Amount (`any` or specific sats), Description.
  - Suggested optional params: Recurrence flag, Recurrence frequency (mins, hours, days, weeks, months years)
  - The modal should display the `bolt12` string as QR code, upon successful creation of the offer

**Comment by ShahanaFarooqui** [comment]
Created a new issue to handle recurrence in future releases. Issue #896
