### ISSUE TITLE
[CLT] routing peers show msats instead of sats

### ISSUE THREAD

**Issue by LightningHelper** [Ride-The-Lightning/RTL#804]
**Describe the bug**
![image](https://user-images.githubusercontent.com/35897350/132950103-eae86a4e-3e9e-488d-b01f-212df981103c.png)

I've run a seperate analysis using python and I can clearly see that althogh the number are very similar, the data shown in RTL is with mSats:

![image](https://user-images.githubusercontent.com/35897350/132950163-1b3ed447-a38d-4550-8287-8cd98e287d88.png)

**Your environment**
RTL - 0.11.2
c-lightning 0.10.1

**Comment by ShahanaFarooqui** [comment]
@LightningHelper Thank you for opening the issue. The bug has been fixed for Amount & Fee both columns and will be released with v0.12.
