### ISSUE TITLE
C-Lightning Liquidity ads support (Leasing funds)

### ISSUE THREAD

**Issue by TheeHandwoven** [Ride-The-Lightning/RTL#819]
With the version 10 release of c-lightning, a feature for advertising that node operators can provide liquidity for channels with a cost is introduced. This allows purchasing of inbound liquidity, and it also allows for creating balanced channels at creation because both the liquidity provider and the channel open initiator may provide funds to the channel.

Lisa Neigut from Blockstream has written a nice blog post on how it works [on medium](https://medium.com/blockstream/setting-up-liquidity-ads-in-c-lightning-54e4c59c091d).

It is still experimental, but it would be great to have this functionality in RTL.

**Comment by ShahanaFarooqui** [comment]
Closing with v0.13.0 release.
