### ISSUE TITLE
Download CSV of Transactions returns "Decoding Payments Failed!"

### ISSUE THREAD

**Issue by Jestopher-BTC** [Ride-The-Lightning/RTL#826]
**Describe the bug**
When attempting to download the history of payments from RTL using the Download CSV dialog, I get an error that states:
### Error Code
413
### API URL
./api/lnd/payreq

**To Reproduce**
Download CSV of Transactions from Payments History

**Additional context**
Given that the transaction level data is shown, this tells me that this is simply a bug with the Download CSV function and not a result of the macaroons.

**Comment by ShahanaFarooqui** [comment]
@Jestopher-BTC Thanks for opening the issue. The fix will be released with v0.12.
