### ISSUE TITLE
Update Fee Policy poorly specifies channel for the user

### ISSUE THREAD

**Issue by dscotese** [Ride-The-Lightning/RTL#829]
**Is your feature request related to a problem? Please describe.**
Choosing "Update Fee Policy" from the "Actions" dropdown in the Open tab of the Peers/Channels page opens a modal dialog which identifies the node chosen using the channelID.  The channelID doesn't appear on the Open tab of the Peers/Channels page, and even if it did, the modal might cover it up.  This makes it difficult to verify that the "Update Fee Policy" option from the intended channel is the one that was selected.

What went through my head was "Lemme check out the fees for LNBIG.com[lnd-39]" (the alias of the peer) but that alias isn't in the "Update Fee Policy" (modal) box that shows up, so I don't know if I chose the right Actions dropdown.

**Describe the solution you'd like**
Since the two most obvious identifiers in the Peers/Channels page are the other node's alias and the short-channel-id, I'd like the "Update Fee Policy" box to have one or both of those identifiers displayed inside of it so it's clear which channel's fees we are changing.

**Describe alternatives you've considered**
The channel whose Actions dropdown was used could be highlighted somehow, but that might not be obvious enough to the user.

**Comment by ShahanaFarooqui** [comment]
@dscotese Thank you for opening the issue and the suggestion. 

We updated the application to show channel alias and short channel id instead of channel ID. 

Also note that, we extended the same feature to `View Remote Fee` and `Close channel` modals too. 

These updates will be available from the next release (0.12.0). Closing the issue now.
