### ISSUE TITLE
504/403 errors on RTL in BTCPAYSERVER

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#845]
updating channel fees gives 504 error

![2021-10-23 18_36_53-RTL](https://user-images.githubusercontent.com/60074674/139531367-66d4dab6-2efe-4686-bf65-5ff47e7d9423.png)

lightning -> routing or feereport gives 403 error:

![2021-10-30 13_30_31-RTL](https://user-images.githubusercontent.com/60074674/139531388-14bcb47d-c0fd-43fe-ac79-e0341517f6ab.png)

some things still work (paying an invoice with RTL) but lots of things are kinda fucky

any ideas whats causing this?

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin Sorry to hear that you are getting these many errors. Can you please confirm if you are still getting these? If yes, which RTL version are you on?

**Comment by sendbitcoin** [comment]
after updating btcpayserver (and thus also RTL) everything seems to be fine. I have not got these weird errors anymore.
