### ISSUE TITLE
Running 11.2 has broken the balances dashboard

### ISSUE THREAD

**Issue by martinatime** [Ride-The-Lightning/RTL#846]
**Describe the bug**
Just upgraded to 11.2 and the balances on the dashboard is showing up like this
![image](https://user-images.githubusercontent.com/258678/139557559-3a62509a-e6d5-4104-bd22-5a25e9d001d4.png)

**To Reproduce**
1. Install 11.2 using the git pull and install
2. Log in to RTL

**Screenshots**
See above

**Your environment**
* Version of `RTL` - 11.2
* Version of `lnd` - 13.3
* Version of `btcd`, `bitcoind`, or other backend - 22.0
* Browser & browser version - Firefox 93.0 (64bit) Windiws
* Operating system (`uname -a` on *Nix) - LND on Debian buster
* any other relevant environment details

**Additional context**

**Comment by martinatime** [comment]
I reverted to v11.0 for the time being

**Comment by saubyk** [comment]
Hi @martinatime please update to the latest version of RTL (v0.12.0) and your issue should be addressed. If it isn't, please feel free to re-open the issue. Thanks.
