### ISSUE TITLE
RTL stuck after install

### ISSUE THREAD

**Issue by johnkeong** [Ride-The-Lightning/RTL#862]
Hi, I'm currently running Umbrel on Dell Latitude E6440 Ubuntu 20.04.3 LTS (Focal Fossa). It's stuck a with "starting" icon after installing RTL.

I'm not too sure how to get about to view log (if any) available as I'm still new to Linux environment.
How do I go about to resolve this issue?

![Screenshot 2021-11-21 232241](https://user-images.githubusercontent.com/55941790/142768121-e7bdc86d-5ac8-4295-a8aa-d02fc3bc446b.jpg)

Log file: [umbrel-1637512413836-debug.log](https://github.com/Ride-The-Lightning/RTL/files/7576626/umbrel-1637512413836-debug.log)

**Comment by saubyk** [comment]
hi @johnkeong this issue is best addressed by the Umbrel team. Suggest opening an issue with them.

**Comment by johnkeong** [comment]
> hi @johnkeong this issue is best addressed by the Umbrel team. Suggest opening an issue with them.

Hi saubyk, thanks for replying. I'll get in touch with them soon.

**Comment by johnkeong** [comment]
Post have be relocated to Umbrel Community: https://community.getumbrel.com/t/rtl-stuck-after-install/4821?u=johnkeong
