### ISSUE TITLE
Open channel with max channel size button

### ISSUE THREAD

**Issue by bitbandi** [Ride-The-Lightning/RTL#863]
**Is your feature request related to a problem? Please describe.**
I want to open channel with max fund

**Describe the solution you'd like**
Add a "Max" button to Open Channel dialog, after Amount field. Pressing the button sets the amount field to the possible max value: the the available balance is less the the configured max channel size, put the available balance. if it is more than maxchannelsize, puts maxchannelsize value:  min(networkinfo.max_channel_size, totalBalance - fundingAmount)

**Additional context**
Something like this:
![kép](https://user-images.githubusercontent.com/7190678/142776910-da6c3797-75c6-4b31-add9-42facf2ee7c3.png)

**Comment by djkazic** [comment]
You'd probably also want to factor in anchor channel outputs consuming a portion of the available balance (10k sats per channel or 100k sats total IIRC)

Otherwise, you'll get an error.

**Comment by saubyk** [comment]
Hi @bitbandi this requirement is best handled by LND providing support via the API. Once the API supports the feature, we can include that in the UI.

Refer to this PR:
https://github.com/lightningnetwork/lnd/pull/4029

You can leave a comment on the PR to prioritize this work with them.

**Comment by bitbandi** [comment]
it doesn't have to be that complicated, getnetworkinfo returns the max_channel_size field, just use (`min(x,y)`) with current displayed remaining balance.

**Comment by djkazic** [comment]
@bitbandi not quite. That does not take into account the reserved UTXOs for anchor channels.

**Comment by ShahanaFarooqui** [comment]
Closing this issue as it is not possible to implement in the UI.
