### ISSUE TITLE
Error message when paying invoice without setting a fee limit

### ISSUE THREAD

**Issue by bitcoinheiro** [Ride-The-Lightning/RTL#867]
**Describe the bug**
Error message when paying invoice without setting a fee limit

**To Reproduce**
Try to pay a invoice within RTL.
See error

**Screenshots**
![image](https://user-images.githubusercontent.com/50273260/143056590-74dfe00a-ed8e-4112-acef-97c41df6dcac.png)

**Your environment**
Latest BTCPayServer running on VPS
Other user from Umbrel reported same problem

**Comment by ShahanaFarooqui** [comment]
Due to LND update to 0.14

**Comment by acantril** [comment]
confirmed, same issue lnd 0.14

**Comment by jaonoctus** [comment]
+1, had the same issue

**Comment by bitbandi** [comment]
already reported the issue: #866

**Comment by ShahanaFarooqui** [comment]
Closing with PR #880.
