### ISSUE TITLE
Do not throw error when already connected peer

### ISSUE THREAD

**Issue by bitbandi** [Ride-The-Lightning/RTL#884]
**Is your feature request related to a problem? Please describe.**
If i try to connect to a new peer, but my node already connected, i got an error. there is a retry button, but in this situation it is useless :)

**Describe the solution you'd like**
Step next to openchannel panel.

![kép](https://user-images.githubusercontent.com/7190678/144310008-eb459a32-7dd4-4d8e-be29-eff0065f7783.png)

**Comment by saiy2k** [comment]
I thought of fixing this and make a PR. But it seems, this is already resolved (in v0.12.0)

**Comment by ShahanaFarooqui** [comment]
@saiy2k sometimes if I find any bug while working on something else, I fix that too without realizing that an issue is open about that. Thank you for the information, I will confirm once again and close the issue asap.

**Comment by ShahanaFarooqui** [comment]
@bitbandi & @saiy2k, We decided to not to work on this one. We do not want to block our users from any valid operation. We trust the user's intelligence to decide if they want to keep trying to connect with already connected peer :).
