### ISSUE TITLE
Can't start server "Something went wrong while configuring the node server: "

### ISSUE THREAD

**Issue by VajraOfIndra** [Ride-The-Lightning/RTL#889]
**Describe the bug**

When I try to run RTL after installing it and creating the conf file, I get the following error message:

> Something went wrong while configuring the node server: 
> SyntaxError: Unexpected string in JSON at position 420
> /home/rtl/RTL/routes/connect.js:580
>     throw new Error(err);
>     ^
> 
> Error: SyntaxError: Unexpected string in JSON at position 420
>     at Object.connect.setServerConfiguration (/home/rtl/RTL/routes/connect.js:580:11)
>     at Object.<anonymous> (/home/rtl/RTL/rtl.js:6:43)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
>     at internal/main/run_main_module.js:17:47

I tried to look for similar issues in the repo but couldn't find the same issue. Any idea what am I doing wrong here? Thanks!

**To Reproduce**

Follow install guide provided here: [https://raspibolt.org/rtl.html](https://raspibolt.org/rtl.html) up to the point of testing RTL.

**Screenshots**

**Your environment**
* RTL v0.11.2
* lnd v0.14.1-betq
* bitcoind v22.0
* Firefox v94.0 (not relevant)
* RasPiOS Lite (64-bit)

**Additional context**

Content of `/home/rtl/RTL/RTL-Config.json` (format not preserved in output below)

>   "multiPass": "mypassword",
>   "port": "3000",
>   "defaultNodeIndex": 1,
>   "SSO": {
>     "rtlSSO": 0,
>     "rtlCookiePath": "",
>     "logoutRedirectLink": ""
>   },
>   "nodes": [
>     {
>       "index": 1,
>       "lnNode": "Node 1",
>       "lnImplementation": "LND",
>       "Authentication": {
>         "macaroonPath": "/home/rtl",
>         "configPath": "/data/lnd/lnd.conf"
>         "swapMacaroonPath": "C:\\Users\\xyz\\AppData\\Local\\Loop\\mainnet",
>         "boltzMacaroonPath": "C:\\Users\\xyz\\AppData\\Boltz\\mainnet"
>       },
>       "Settings": {
>         "userPersona": "MERCHANT",
>         "themeMode": "DAY",
>         "themeColor": "PURPLE",
>         "channelBackupPath": "C:\\Users\\xyz\\backup\\node-1",
>         "logLevel": "ERROR",
>         "lnServerUrl": "https://localhost:8080",
>         "swapServerUrl": "https://localhost:8081",
>         "boltzServerUrl": "https://localhost:9003",
>         "fiatConversion": false
>       }
>     }
>   ]
> }

**Comment by ShahanaFarooqui** [comment]
The json file is invalid.  

1) Please add `,` at the last of `configPath`.
2) Use `\\` instead of `\` for `swapMacaroonPath`, `boltzMacaroonPath` & `channelBackupPath` for windows OS setup. 

Like below:
```
{
	"multiPass": "mypassword",
	"port": "3000",
	"defaultNodeIndex": 1,
	"SSO": {
		"rtlSSO": 0,
		"rtlCookiePath": "",
		"logoutRedirectLink": ""
	},
	"nodes": [
		{
			"index": 1,
			"lnNode": "Node 1",
			"lnImplementation": "LND",
			"Authentication": {
				"macaroonPath": "/home/rtl",
				"configPath": "/data/lnd/lnd.conf",
				"swapMacaroonPath": "C:\\Users\\xyz\\AppData\\Local\\Loop\\mainnet",
				"boltzMacaroonPath": "C:\\Users\\xyz\\AppData\\Boltz\\mainnet"
			},
			"Settings": {
				"userPersona": "MERCHANT",
				"themeMode": "DAY",
				"themeColor": "PURPLE",
				"channelBackupPath": "C:\\Users\\xyz\\backup\\node-1",
				"logLevel": "ERROR",
				"lnServerUrl": "https://localhost:8080",
				"swapServerUrl": "https://localhost:8081",
				"boltzServerUrl": "https://localhost:9003",
				"fiatConversion": false
			}
		}
	]
}
```

**Comment by VajraOfIndra** [comment]
Yes, it's working fine now. I forgot to close the issue sorry.
Thanks a lot for your help
