### ISSUE TITLE
Upon successful configuration of 2FA the enable 2fa button should update

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#906]
Upon successful configuration of 2FA one of the below two things should happen:

Use should be logged out of the application automatically and made to login again.
or
The `Enable 2FA` button should be change state to `Disable 2FA`

And vice versa, similar behavior on disabling the 2FA.

**Comment by ShahanaFarooqui** [comment]
Clising with commit `9ce43c861f89281aff27573531493f58e2e82f0a`.
