### ISSUE TITLE
unknown field "none"

### ISSUE THREAD

**Issue by webdiverblue** [Ride-The-Lightning/RTL#908]
Permanent failure when paying invoices with RTL since update to version 0.11.02

copied invoices e.g. from BTCPay Server or other payment requests give this error

I properly proofed for spaces or copy mistakes by myself

**Screenshots**

![image](https://user-images.githubusercontent.com/64732472/146414692-2a5df097-9dc2-45cb-9db0-0d97151c38ed.png)

**Your environment**
* Version of `RTL` 0.11.02
* Version of `lnd` v.14.1
* Version of `core'  v0.14.1
* Firefox

**Comment by ShahanaFarooqui** [comment]
Duplicate #867, fixed with PR #880.
