### ISSUE TITLE
Feature Request: Download to CSV more invoices/payments at once

### ISSUE THREAD

**Issue by ablekirby** [Ride-The-Lightning/RTL#914]
I need to export the invoice/payment records to CSV, but I can only save as many as are displayed on the page (100 max). This means I have to export about 12 pages separately and merge them to make a period report. As you might imagine, it's frustrating.

Allowing more transactions per page would be a great quick fix. Exporting a custom number of invoices/payments would be better. Top solution would be setting a custom date range to export, as period data is what businesses usually expect.

**Comment by saubyk** [comment]
This issue will be covered with this https://github.com/Ride-The-Lightning/RTL/issues/1090

**Comment by ShahanaFarooqui** [comment]
@ablekirby Thank you for the suggestion.

I will work on these suggestions with issue #1090. Closing this issue now.
