### ISSUE TITLE
Sending onchain from RTL didnt arrive?

### ISSUE THREAD

**Issue by Shadovv007** [Ride-The-Lightning/RTL#915]
**Describe the bug**
Yesterday I've installed Samurai wallet phone app and connected it to my Umbrel Samurai Dojo. I tried to send test tx and I did generate BTC address from my phone Samurai wallet. I did use Umbrel's RTL for sending test tx, but nothing arrived although on blockexplorer shows that the tx went thru and the deposit address has received the deposit.
I also installed Whirlpool GUI on my pc, successfully connected Whirlpool to my Umbrel and phone wallet. I generated deposit adress on this desktop GUI, I sent another test BTC tx from RTL and same story: on blockexplorer is everything fine but nothing arrived to my wallet.
Both txs are already confirmed in blockchain explorer and both contain the deposited BTC but both phone wallet and Whirlpool GUI shows zero balance. 
When I put "deposit address" from my GUI into blockchain explorer, it shows the sent tx with proper balance, but my both GUI and samurai wallet shows zero balance and no txs.
Any ideas?
Later I found out, that the problems seems to be with RTL, because I tried to send another test tx but directly from Umbrel home screen, and it appeared on both Samurai phone app and desktop Whirlpool GUI.
Still: Why sending from RTL doesnt work with Samurai even though on blockchain all looks valid?
Thanks!

I use latest Umbrel v 0.4.10 with 
Version of `RTL` : 0.11.2
For browser I use Tor Browser 11.0.3

Edit: I also tried test tx from ThunderHub and its working

**Comment by saubyk** [comment]
Hi @Shadovv007 which version of LND are you on?

**Comment by Shadovv007** [comment]
Hi @saubyk , where/how do I find it in my Umbrel? I can find, that in Umbrel version 0.4.9 there is LND 0.14.1
In latest Umbrel version 0.4.10 - the one I use , there is nothing written about LND version/update
Thank you!

**Comment by saubyk** [comment]
Hey @Shadovv007 this issue should get resolved, when Umbrel updates with the latest RTL release.

It's due to a few API changes made by LND with their latest release, which broke RTL's UI.

**Comment by saubyk** [comment]
Closing this right now. Feel free to open, if it doesn't get addressed after Umbrel's update. Thanks.
