### ISSUE TITLE
Wrong year in date of invoice

### ISSUE THREAD

**Issue by empewoow** [Ride-The-Lightning/RTL#918]
**Describe the bug**
I've just sent an invoice through Stekking (it uses LNPay.co) at 12:28 local Dutch time. Except my RTL shows the date (year) wrong; 01/Jan/2021 12:28. Of course that should be 2022.

**To Reproduce**
Not sure exactly, I cannot do any more Stekking withdrawals at this time.

**Screenshots**
![image](https://user-images.githubusercontent.com/23315837/147849939-43ff8629-f460-4184-9679-29bc1f4405e4.png)

![image](https://user-images.githubusercontent.com/23315837/147849722-7339ddaf-4684-4186-a885-6f9c62389408.png)

**Your environment**
Umbrel version 0.4.10
RTL version 0.11.2-beta
Chrome version 96.0.4664.110

**Additional context**
Now that I'm thinking about it, is this an issue for RTL or for LNPay.co?

**Comment by ShahanaFarooqui** [comment]
RTL is just showing the date/time provided to it. Please contact the party who created the invoice.

**Comment by empewoow** [comment]
Will do, thanks.

**Comment by tkijewski** [comment]
I checked the invoice and it seems to have the correct date

<img width="1103" alt="Decoder for Lightning Payment Requests 2022-01-02 16-33-01" src="https://user-images.githubusercontent.com/3043754/147890051-4fb2a848-af29-4cad-84f9-331dbb0d4b72.png">

**Comment by ShahanaFarooqui** [comment]
Can you check RTL logs for the same? The data with 10 invoices should be logged with `Invoice => Invoices List Received: ` and the creation date should be in Epoch format (example date `"creation_date":"1637986440"`).

**Comment by empewoow** [comment]
Hi Shahana, can you tell me which log file you are referring to? I found `~/umbrel/app-data/ride-the-lightning/rtl/logs/RTL-Node-1.log` and it mentions `[2021-12-30T11:43:28.178Z] INFO: Invoice => Invoices List Received.` but nothing more, I don't see any creation dates like you mention.

**Comment by ShahanaFarooqui** [comment]
You are checking the correct file but the `logLevel` in the RTL-Config.json is set to 'INFO'. 

- Either It needs to be changed to `DEBUG` to be able to see the data in the log file. Don't forget to restart RTL server after the change. 

- Or the easier option in your situation is to go to the browser > click F12/right click and inspect > Go to network tab and look for `invoices` API call data > Check the "creation_date" value for your invoice, like below:

![image](https://user-images.githubusercontent.com/23240721/147989562-661b2a70-88b1-42b2-9d07-a1a58c35c2a2.png)

**Comment by empewoow** [comment]
Found it. Great explanation and nice to learn how this works as well :)!

![image](https://user-images.githubusercontent.com/23315837/148119444-cc4db3b0-8a45-4ce0-b3da-bc64975dae6d.png)

So it is `1641036527` which translates to my local time as 1 January 2022 12:28:47. This is also the date/time that I expected.

Looks like the bug is in the RTL interface then?

**Comment by ShahanaFarooqui** [comment]
Yeah it is a bug in RTL. Will check and fix it soon. Thanks for raising the issue and helping us in debugging it as well.

**Comment by ShahanaFarooqui** [comment]
It was due to Angular Date pipe bug, changing the date pipe format from `dd/MMM/YYYY HH:mm` to `dd/MMM/y HH:mm` fixed the issue. Closing the issue with PR #920 and fix will be released with v0.12.1.
