### ISSUE TITLE
v0.12.0 broke the HTLC viewing feature for lnd

### ISSUE THREAD

**Issue by hazrulnizam** [Ride-The-Lightning/RTL#924]
**Describe the bug**
Unable to view a majority of successful and failed HTLCs on the Payment History page.

**To Reproduce**
1. Go to 'Lightning -> Transactions' to go the Payment History page.
2. Click on 'View Info' for single-attempt payments or click on 'Show' -> 'View n' where n is the HTLC number for a multiple-attempt payment.
4. For a few HTLCs, it works and HTLC details popped up, but for a majority of them, nothing happens.

**Your environment**
* `RTL 0.12.0-beta`
* `lnd 0.14.1-beta`
* `bitcoind 22.0`,
* Google Chrome Version 97.0.4692.71 (Official Build) (64-bit)
* RTL running on Linux `4.18.0-305.19.1.el8_4.x86_64`

**Additional context**
Downgraded back to `RTL 0.11.0-beta` to confirm the old page works, and it's not an `lnd` issue.

**Comment by ShahanaFarooqui** [comment]
@hazrulnizam Thanks for raising the issue. It is fixed with PR #930 and will be released with v0.12.1.

**Comment by hazrulnizam** [comment]
Thanks for the quick fix. I tested v0.12.1 and can verify the problem is no longer there.
