### ISSUE TITLE
Color setting in LND config not appearing in the UI

### ISSUE THREAD

**Issue by verbiricha** [Ride-The-Lightning/RTL#925]
First of all thanks for RTL, is a really great UI for managing Lightning node. I did a small modification to the LND config and saw that the UI doesn't display it correctly, here is my problem:

**Describe the bug**
The config parameters for LND that start with `#` aren't displayed on the Node Config UI.

**To Reproduce**
1. Add custom `color` parameter to LND config
2. Go to Node Config
3. Click on 'LND Config'
4. Scroll down to 'Application Options'
5. See that the `color` value is not displayed (perhaps interpreted as a comment)

**Screenshots**
<img width="1035" alt="Screenshot 2022-01-10 at 08 38 12" src="https://user-images.githubusercontent.com/92299987/148731743-b85f28ab-ce97-48f9-a53e-74f61fd6c2b3.png">

**Your environment**
* Version of `RTL` 0.11.2-beta
* Version of `lnd` LND 0.14.1-beta commit=v0.14.1-beta
* Bitcoin core v22.0.0
* Browser: Firefox latest
* Operating system: Darwin Kernel Version 21.0.1 (Macbook Pro M1 Apple)

**Comment by ShahanaFarooqui** [comment]
Fixed with commit `3d9c0b60cec4479ce46b002c96ebff3f4b32f625`.
