### ISSUE TITLE
Question: Why was the circular rebalance fee/hop estimation removed?

### ISSUE THREAD

**Issue by martinatime** [Ride-The-Lightning/RTL#934]
Just curious about the question in the title. I have used RTL for a bit and I rebuilt my node a couple of weeks ago and noticed that the new version of RTL didn't do the estimation of the fees/hops for circular rebalancing.

**Comment by saubyk** [comment]
Hi @martinatime this feature was not useful for the users as the estimates were almost always wrong. Users were getting frustrated, when the estimated fee would never work. Hence we decided to remove it.

**Comment by martinatime** [comment]
@saubyk Thanks for the answer. It's too bad that the network doesn't provide a better or more accurate estimation on fees and hops.
