### ISSUE TITLE
Change fee rate unit in circular rebalance from percentage to ppm

### ISSUE THREAD

**Issue by davotoula** [Ride-The-Lightning/RTL#935]
**Is your feature request related to a problem? Please describe.**
Currently the circular rebalance feature support a fee rate given in percentage. It allows integer only meaning lowest rate avaibale is 1%. This translate to a fee rate of 1,000 ppm. 

Channel fees are usually between 10 and 500ppm so a minimal rate of 1,000 ppm is unpractical. 

**Describe the solution you'd like**
Change the rebalance rate input field to ppm. Keep the integer validation requirement. 

**Describe alternatives you've considered**
Change the input field validation to accept float (?) so we can enter parts of a percentage. For example 0.01% for a ppm fee of 100.

**Comment by saubyk** [comment]
Hi @davotoula this feature can only be added, if LND Apis support passing fraction for percentages. Including it for the next release. Will close if API support is not available. Thanks

**Comment by davotoula** [comment]
Thank you for the consideration.

On of your competitor's ui supports fee rate in ppm so I assumed LND API supports it!

Looking forward to it.

**Comment by ShahanaFarooqui** [comment]
@saubyk Blocking it on you. Need more information.

**Comment by saubyk** [comment]
@ShahanaFarooqui as discussed, we need to investigate with if `fee_limit_percent value` parameter in the LND API, can accept fractional values. Thanks.

**Comment by ShahanaFarooqui** [comment]
@davotoula Thanks for the issue and the reference link. RTL will not accept the floating percentage and change it into max absolute fixed value. The PR #962 is merged into release 0.12.2 branch.
