### ISSUE TITLE
Wrong architecture on docker arm32v7 image

### ISSUE THREAD

**Issue by bota87** [Ride-The-Lightning/RTL#940]
**Describe the bug**
The image 0.12.1-arm32v7 hosted on [Docker Hub](https://hub.docker.com/layers/shahanafarooqui/rtl/0.12.1-arm32v7/images/sha256-2eb0a379a2fed06b28d391cb76e9c8c475e05b6850abc91eaa33e2edbd30d315?context=explore) have the wrong architecture

**To Reproduce**
Start the container on a arm7 system (like Raspberry OS) and you get this warning

> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

**Screenshots**
![image](https://user-images.githubusercontent.com/52842374/152688445-aa0454ef-a51a-4c89-96f2-bae5b58118cb.png)

**Comment by ShahanaFarooqui** [comment]
@bota87 As suggested [here ](https://github.com/docker/for-linux/issues/1170#issuecomment-750311549), you can use `--platform=linux/arm/v7` flag with docker run to ignore the warning for now.

@saubyk Blocking the issue on you :). RTL's CircleCI and docker compose setup scripts are too old and should to be updated soon.

CircleCI and docket compose both can be removed while adding docker actions directly thorough github actions and buildx. Before moving forward, I want to discuss the solution with you to understand its effects on BTCPayServer and Umbrel.

Reference links for me:
https://www.docker.com/blog/multi-arch-images/
https://docs.docker.com/desktop/multi-arch/
https://github.com/docker/build-push-action#multi-platform-image
https://github.com/docker/buildx/blob/master/docs/reference/buildx_bake.md
https://github.com/docker/for-linux/issues/1170
https://medium.com/@artur.klauser/building-multi-architecture-docker-images-with-buildx-27d80f7e2408
https://github.com/pi-hole/docker-pi-hole/issues/735
https://github.com/multiarch/qemu-user-static

**Comment by saubyk** [comment]
This is fixed release 13 onwards
