### ISSUE TITLE
Navigate to Inactive Channels from the Operator dashboard - LND

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#942]
The 'Channels' panel on the operator dashboard has a drop down menu, which can be expanded to include options for easy navigation to channel searches on LND nodes.

To navigate to Inactive channels, a menu option `Go to Inactive Channels` can be added, which should land the user on the channels page with the search filter populated with the "Inactive" string, which will enable the user to easily view all the inactive channels, without having to search for it.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/39208279/152694233-e0f2c3ee-0b20-4ee6-99a9-3fcdc363d99a.png">

**Comment by ShahanaFarooqui** [comment]
Closing with PR #949.
