### ISSUE TITLE
RTL keeps spamming boltz.exchange swap.lightning.today 

### ISSUE THREAD

**Issue by EZ0010** [Ride-The-Lightning/RTL#945]
**Describe the bug**
I have RTL installed on umbrel node, and for some reason I keep seeing `boltz.exchange` `swap.lightning.today` domains on pihole log.
it is heavily spamming these two domains like 4 requests every 2-5 seconds. once I uninstalled RTL these requests they are gone from pihole log.
I tried to uninstall RTL and reinstall it and got the same results.

**To Reproduce**
1. install RTL on umbrel node
2. install pihole
3. watch pihole log under (Tools -> Tail pihole.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/75021359/152881515-2826230c-cf06-47e0-95ad-3db713e780eb.png)

![image](https://user-images.githubusercontent.com/75021359/152880820-5f897de2-08d0-46e2-a9dd-71f736f5c8fe.png)

**Your environment**
* Version: 0.11.2-beta

**Comment by saubyk** [comment]
Hi @EZ0010 
I installed pihole on my Umbrel node and tailed the log via the app's dashboard. I was not able to observe any spamming behavior. Not clear, why it's happening in your case, have you tried restarting your node?

<img width="635" alt="image" src="https://user-images.githubusercontent.com/39208279/153730106-3a90c97a-96ff-42b1-ba70-41c1b872c206.png">

**Comment by EZ0010** [comment]
yes I restarted my node several times, I remember I tried to exchange LN to on-chain (or the reverse) using the exchange service on RTL with Bolts but it didn't go through, but I assume these information and local configurations should be deleted once I uninstall RTL from umbrel and reinstall it?
I will try to make another test today and update the results.

**Comment by EZ0010** [comment]
Yes I still see it
also when I open RTL -> Services -> Boltz
I see this popup I think it is what is causing the issue.

![image](https://user-images.githubusercontent.com/75021359/154083363-161fa28a-dea7-4591-83c2-e0b2ca312b6c.png)

**Comment by EZ0010** [comment]
I'm not sure how to debug this but it shows these domains:
`swap.lightning.today`
`boltz.exchange`
`nautilus.prod.lightningcluster.com`
these had more than 100 requests each in 5 minutes

pihole shows `NODATA-IPv6` not sure what that means, I know it is some DNS issue but still worth fixing IMO
![image](https://user-images.githubusercontent.com/75021359/154092795-8123f78d-4465-41c7-8b88-5e0b81967b26.png)
