### ISSUE TITLE
RTL 502 Bad Gateway

### ISSUE THREAD

**Issue by Casper0113** [Ride-The-Lightning/RTL#956]
I recently purchased a NODL DOJO and am unable to open RTL.  I continue to get a 502 Bad Gateway error.  I have tried stopping and starting the service, and refreshing to no avail.  I also tried accessing via the IP address instead of the default local address. 

LND and Bitcoin Core are running, and I have no issues with getting to the Lightning Terminal.  Any ideas?  I'm new to working with computers, so sorry for not providing additional information.  Any help is appreciated.

**Comment by ShahanaFarooqui** [comment]
@Casper0113 can you please share the RTL-Config.json file after removing password. The file must be in RTL’s root folder.

**Comment by Casper0113** [comment]
Dumb question, but can I access the json file from my laptop, or do I need to hook a monitor and keyboard up to the NODL?   I was able to hook up a monitor, but I only have a wireless keyboard and the NODL was not recognizing the keyboard, so I am unable to troubleshoot directly from the node.  

Sorry, I know it's like trying to explain physics to a monkey.  I assume the root folder is stored on the NODL hard drives since everything came pre-installed.  

NODL's software shows Ride The Lightning as "Running", but when I click the Open RTL button I get this error, no other data is on the screen. 

502 Bad Gateway
nginx/1.14.0 (Ubuntu)

Thanks for your help!
