### ISSUE TITLE
Filter non-routing peers for LND on Routing page

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL#960]
Objective: Identify channels with no routing history and enable channel management for them.

On the Routing page:
1. Add a new tab called `Non-Routing Peers`
2. On this tab, list all the channels with 0 Sats Sent and 0 Sats Received
3. The list should include the fields Channel ID, Alias, Sats Sent, Sats Received, Local Balance, Remote Balance
4. Each row will also have a button labeled `Manage`
5. Upon hitting the Manage button, the user should be navigated to the Channels page with the Channel ID in the filter, so that user can manage that specific channel on that page.

**Comment by ShahanaFarooqui** [comment]
Closing with PR #963.
