### ISSUE TITLE
C-Lightning RegTest login impossible

### ISSUE THREAD

**Issue by PatrickGeyer** [Ride-The-Lightning/RTL#974]
**Describe the bug**
When I try to run a c-lightning node in regtest mode, the RTL frontend logs me out automatically after fetching the node info and seeng the chain "network" key is not = "bitcoin"
**To Reproduce**
Run the environments below and log in. You will successfully be logged in, it will fetch nodeinfo, and then inmmediately trigger a logout.
**Screenshots**
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/5664617/157148226-f2c04044-9696-445e-ba4c-ab7a1cc7172b.png">
**Your environment**
* shahanafarooqui/rtl:0.12.1
* elementsproject/lightningd:latest
* saubyk/c-lightning-rest:0.6.1
* ruimarinho/bitcoin-core:0.17
* Chrome
* Mac

**Comment by PatrickGeyer** [comment]
Anyone able to reproduce this error?

**Comment by wellenreiter01** [comment]
I have a similar error on Linux 
environment:
shahanafarooqui/rtl:0.12.1
elementsproject/lightnind : v0.10.2-465-g5697521 
saubyk/c-lightning-rest:0.6.1
feathercoin-core: 0.19.1
After login RTL requests the Rest-api, gets information and the user is logged out.
A kind of workaround is to stop lightningd, login to RTL and start lightningd.
RTL comes up with empty forms, but after connecting a peer, all peers connected to the local node are shown and the same is true for the channels.
off chain data, like list of traansactions and repors can be retrieved then, but onchain data is not accessible.



[log.txt](https://github.com/Ride-The-Lightning/RTL/files/8371009/log.txt)

**Comment by wellenreiter01** [comment]
I think, I found the problem cause, and I must say, that I'm not happy about it:

in  src/app/clightning/store/cl.effects.ts  line 96 and following it is checked, if the chainname starts with 'bitcoin' and if NO all 
dialogs are closed:

-------------------------
 this.store.dispatch(closeAllDialogs());
              this.store.dispatch(openAlert({
                payload: {
                  data: {
                    type: AlertTypeEnum.ERROR,
                    alertTitle: 'Shitcoin Found',
--------------
besides the fact that I'm happy I found a possible cause of my problem , I'm not happy, that a monitoring tool defines anything but bitcoin as Shitcoin.
Thats simply arrogant

**Comment by ShahanaFarooqui** [comment]
@saubyk I am unable to fix it before local RegTest installation.

**Comment by PatrickGeyer** [comment]
Yeah it's just those lines of code, I disabled them and built a new RTL image which I use for my node now and works fine.

**Comment by PatrickGeyer** [comment]
Is this still blocked?

**Comment by ShahanaFarooqui** [comment]
I am planning to work on CLN regtest installation today. We should be able to fix it within 2-3 days.

**Comment by ShahanaFarooqui** [comment]
@PatrickGeyer Thank you for opening the issue. Closing with PR #1043, the fix will be released with v0.12.4.
