### ISSUE TITLE
AMP (keysend) payments

### ISSUE THREAD

**Issue by benjamin-wilson** [Ride-The-Lightning/RTL#981]
**Is your feature request related to a problem? Please describe.**
Keysend is a common and easy way to send sats around without an invoice. Currently RTL supports keysend payments (c-lightning only?) but not the successor, AMP payments. accept-amp=1 but no keysend is default for raspiblitz installations. 

**Describe the solution you'd like**
Option to send payment via AMP, similar to the current keysend

**Comment by ShahanaFarooqui** [comment]
@benjamin-wilson Thanks for the issue. It has been added with Release 0.13.2. Closing the issue now.
