### ISSUE TITLE
CLT channel filter on alias is not working 

### ISSUE THREAD

**Issue by ShahanaFarooqui** [Ride-The-Lightning/RTL#982]
Reference issue #632.

**Comment by dscotese** [comment]
@ShahanaFarooqui your title is not accurate.  It filters on short channel ID excellently.  The problem is that it is displaying the node alias instead of the short channel ID (for some channels), and it does NOT filter on the node aliases.

**Comment by ShahanaFarooqui** [comment]
@dscotese thank you for bringing it to my attention. I updated the title now.

**Comment by ShahanaFarooqui** [comment]
Closing with PR #996.
