### ISSUE TITLE
Cannot open channel (Button does nothing and gives no errors)

### ISSUE THREAD

**Issue by empewoow** [Ride-The-Lightning/RTL#986]
I'm using Umbrel. When I try to open a private channel through RTL and press the button "Open Channel", it just doesn't do anything. The browser console also doesn't show any details. Am I doing something wrong or is this a bug?

**Screenshot and video**
![image](https://user-images.githubusercontent.com/23315837/161420267-15336acb-b25a-4849-b9d8-880a227e4152.png)

https://user-images.githubusercontent.com/23315837/161421193-9e6d2a55-86bc-4106-92b7-0c86f8bb5ffb.mp4

**My environment**
* Umbrel version: 0.4.16
* RTL version: 0.12.1-beta
* Chrome 99.0.4844.84 (64 bit)
* Windows 10

**Comment by saubyk** [comment]
Hi @empewoow I tried this on my Umbrel and it went through without any issues.

Can you please confirm, if this is still an issue for you? Thanks.

**Comment by empewoow** [comment]
Hey @saubyk I recently opened the (private) channel that I wanted to open with Zeus, it worked perfectly. Now I don't want to open any private channels anymore, so I cannot test it again...

Is there anything else I can do to test it again? Because there is no way to cancel it, once I try to open one and it goes through right? (Newb question maybe, sorry.)

If the only way to test it, is to actually open another channel, I will figure out with whom I want to connect with next.

**Comment by ShahanaFarooqui** [comment]
@empewoow We tried to reproduce the issue with multiple private channel opening attempts and they all were successful. I am closing the issue as you can also open the channel now. Please comment on the same thread if it reoccurs, preferably with console error message.

**Comment by empewoow** [comment]
Hi @ShahanaFarooqui I can open private channels with Zeus app, but not with RTL. today I tried to open another (private) channel with RTL and it still doesn't work. I have the same behavior as in the video above. Also I don't get any console messages. By the way, opening a public channel also doesn't work. Again, no console messages. Please let me know how to debug the problem.

**Comment by ShahanaFarooqui** [comment]
@empewoow I again tried to reproduce the error at my end with multiple attempts and every attempt was successful. I tried them all on RTL v0.12.1 and still worked. It is impossible to fix the issue without getting knowing the error. Please try to check your browser's console for errors, something like below:

![image](https://user-images.githubusercontent.com/23240721/165127963-604a3e71-9ea8-49f9-b538-594f1feddfef.png)

Or upgrading to v0.12.3 (latest) might help.

**Comment by empewoow** [comment]
Hey @ShahanaFarooqui thanks, but as mentioned before I don't get any console messages when pressing the "Open Channel" button (the one to press the second time, after filling in the details of the channel).

But, when I press the first "Open Channel" button (the one to press before filling in the details):

![image](https://user-images.githubusercontent.com/23315837/166113787-7d8187e5-ad4e-4d5c-a0f4-5685d687a614.png)

I do get this message in my browser console:

![image](https://user-images.githubusercontent.com/23315837/166113818-560e5a95-a8be-47d7-8c8d-4fb3046d7224.png)

`Autofocus processing was blocked because a document already has a focused element.`

I Googled it, but I'm not sure if this might break the functionality of the form?

Regarding your second message, I did not run `npm audit fix`, or any related command, because I am using Umbrel and installed RTL using Umbrel, so almost never use SSH or run custom commands.

I hope this helps...

**Comment by ShahanaFarooqui** [comment]
@empewoow Thanks for the information. I forgot that you were using it on Umbrel, apologies or the inconvenience. Let me try to reproduce that on my local Umbrel setup and get back to you.

**Comment by empewoow** [comment]
Hi @ShahanaFarooqui, any news?

**Comment by ShahanaFarooqui** [comment]
I tried to reproduce it on Umbrel also but with no luck. It is almost impossible to debug with no error message or locally generated error. Keeping it open until Umbrel's next release.

**Comment by saubyk** [comment]
Closing this issue, as it's not reproduceable at our end.

**Comment by snieders** [comment]
I see this issue is closed. Just wanted to let you know that I encounter the same error as described above. 
I disabled all chrome plugins and tried different browsers, no luck. In dev tools I see this:

```
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
open:1 Autofocus processing was blocked because a document already has a focused element.
```

Umbrel Version 0.5.1

**Comment by empewoow** [comment]
Interesting! I tried it again with my setup today and I still cannot open channels through RTL... Whenever I push the button I don't see any message in the developer tools console.
