### ISSUE TITLE
When base fee=0 cannot change the fee rate

### ISSUE THREAD

**Issue by BTCBellyButton** [Ride-The-Lightning/RTL#987]
**Describe the bug**
When the base **fee=0** I cannot change the fee rate. 
I have to first make the base fee >0, change the rate fee, update and then change the base fee back to 0, update

**To Reproduce**
1. Go to "Actions" on a channel with a **0** as base fee.
2. Click on "Update fee policy"
3. change rate fee and save
4. no message. rate fee not updated

**Your environment**
* Version of `RTL` 0.12.0
* Version of C-Lightning v0.10.2
* Version of ``bitcoind`, 22.0.0
* Browser & browser version: Brave [Version 1.37.109 Chromium: 100.0.4896.60 (Official Build) (64-bit)](https://brave.com/latest/)
* Operating system 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ShahanaFarooqui** [comment]
@BTCBellyButton Thank you for raising the issue. It has been fixed in the feature branch and will be released in v0.12.3. Closing with PR #1004.

**Comment by BTCBellyButton** [comment]
Great! Looking forward to it!
