### ISSUE TITLE
[CLN] does not show multiple channels to same peer

### ISSUE THREAD

**Issue by svewa** [Ride-The-Lightning/RTL#988]
CLN now also supports multiple channels between peers, but RTL does not show this. The channel is neither under pending while it's opening, nor in open channels afterwards.

**Comment by saubyk** [comment]
Hi @svewa please note that the feature that you are referring to is not in the release, but may be on CLN's master. We do not build or support any features unless it's officially tagged and released on a version.

Once the latest release with this feature is published, we will work on supporting it. Thanks.

**Comment by theword3** [comment]
[v0.11.0.1 released this 27 Apr 2022](https://github.com/ElementsProject/lightning/releases/tag/v0.11.0.1) and later:

> We now finally support multiple live channels to the same peer!

**Comment by theword3** [comment]
Any updates?

**Comment by mrbitcoiner** [comment]
Having the same issue here.

**Comment by devastgh** [comment]
This should really need to be fixed asap. I don't understand why peerswap ui has higher priority.

**Comment by ShahanaFarooqui** [comment]
@svewa, @theword3, @mrbitcoiner  Thank you for opening and updating about the issue. 

This issue needs update from API `listchannels`. The change will be available from c-lightning-REST v0.9.0 onwards. RTL upgrade is not required but highly recommended for other features.

References:
PR => https://github.com/Ride-The-Lightning/c-lightning-REST/pull/134
Issue => https://github.com/Ride-The-Lightning/c-lightning-REST/issues/139

Closing with PR #1077.
